export declare type RadarAxis = $.kd.bos.form.chart.radar.RadarAxis;
export declare const RadarAxis: $.kd.bos.form.chart.radar.RadarAxis_C;
export declare type RadarChart = $.kd.bos.form.chart.radar.RadarChart;
export declare const RadarChart: $.kd.bos.form.chart.radar.RadarChart_C;
export declare type RadarChartData = $.kd.bos.form.chart.radar.RadarChartData;
export declare const RadarChartData: $.kd.bos.form.chart.radar.RadarChartData_C;
export declare type RadarData = $.kd.bos.form.chart.radar.RadarData;
export declare const RadarData: $.kd.bos.form.chart.radar.RadarData_C;
export declare type RadarIndicator = $.kd.bos.form.chart.radar.RadarIndicator;
export declare const RadarIndicator: $.kd.bos.form.chart.radar.RadarIndicator_C;
export declare type RadarSeries = $.kd.bos.form.chart.radar.RadarSeries;
export declare const RadarSeries: $.kd.bos.form.chart.radar.RadarSeries_C;
