export declare type CellStyleRule = $.kd.bos.report.events.CellStyleRule;
export declare const CellStyleRule: $.kd.bos.report.events.CellStyleRule_C;
export declare type CreateColumnEvent = $.kd.bos.report.events.CreateColumnEvent;
export declare const CreateColumnEvent: $.kd.bos.report.events.CreateColumnEvent_C;
export declare type CreateFilterInfoEvent = $.kd.bos.report.events.CreateFilterInfoEvent;
export declare const CreateFilterInfoEvent: $.kd.bos.report.events.CreateFilterInfoEvent_C;
export declare type FlexEvent = $.kd.bos.report.events.FlexEvent;
export declare const FlexEvent: $.kd.bos.report.events.FlexEvent_C;
export declare type FormatShowFilterEvent = $.kd.bos.report.events.FormatShowFilterEvent;
export declare const FormatShowFilterEvent: $.kd.bos.report.events.FormatShowFilterEvent_C;
export declare type MergeColumnRule = $.kd.bos.report.events.MergeColumnRule;
export declare const MergeColumnRule: $.kd.bos.report.events.MergeColumnRule_C;
export declare type QueryEvent = $.kd.bos.report.events.QueryEvent;
export declare const QueryEvent: $.kd.bos.report.events.QueryEvent_C;
export declare type ReportExportInitializeEvent = $.kd.bos.report.events.ReportExportInitializeEvent;
export declare const ReportExportInitializeEvent: $.kd.bos.report.events.ReportExportInitializeEvent_C;
export declare type SearchEvent = $.kd.bos.report.events.SearchEvent;
export declare const SearchEvent: $.kd.bos.report.events.SearchEvent_C;
export declare type SortAndFilterEvent = $.kd.bos.report.events.SortAndFilterEvent;
export declare const SortAndFilterEvent: $.kd.bos.report.events.SortAndFilterEvent_C;
export declare type SummaryEvent = $.kd.bos.report.events.SummaryEvent;
export declare const SummaryEvent: $.kd.bos.report.events.SummaryEvent_C;
export declare type TreeReportListEvent = $.kd.bos.report.events.TreeReportListEvent;
export declare const TreeReportListEvent: $.kd.bos.report.events.TreeReportListEvent_C;
