export declare type AuxQtyAndUnitHelper = $.kd.sdk.scmc.im.acct.AuxQtyAndUnitHelper;
export declare const AuxQtyAndUnitHelper: $.kd.sdk.scmc.im.acct.AuxQtyAndUnitHelper_C;
export declare type BillQtyAndUnitHelper = $.kd.sdk.scmc.im.acct.BillQtyAndUnitHelper;
export declare const BillQtyAndUnitHelper: $.kd.sdk.scmc.im.acct.BillQtyAndUnitHelper_C;
export declare type BillUnitAndQtytHelper = $.kd.sdk.scmc.im.acct.BillUnitAndQtytHelper;
export declare const BillUnitAndQtytHelper: $.kd.sdk.scmc.im.acct.BillUnitAndQtytHelper_C;
export declare type DateHelper = $.kd.sdk.scmc.im.acct.DateHelper;
export declare const DateHelper: $.kd.sdk.scmc.im.acct.DateHelper_C;
export declare type InvBillCalcHelper = $.kd.sdk.scmc.im.acct.InvBillCalcHelper;
export declare const InvBillCalcHelper: $.kd.sdk.scmc.im.acct.InvBillCalcHelper_C;
export declare type InvSchemeHelper = $.kd.sdk.scmc.im.acct.InvSchemeHelper;
export declare const InvSchemeHelper: $.kd.sdk.scmc.im.acct.InvSchemeHelper_C;
export declare type InverseBillHelper = $.kd.sdk.scmc.im.acct.InverseBillHelper;
export declare const InverseBillHelper: $.kd.sdk.scmc.im.acct.InverseBillHelper_C;
export declare type SdkAppParameterHelper = $.kd.sdk.scmc.im.acct.SdkAppParameterHelper;
export declare const SdkAppParameterHelper: $.kd.sdk.scmc.im.acct.SdkAppParameterHelper_C;
export declare type SettleBillHelper = $.kd.sdk.scmc.im.acct.SettleBillHelper;
export declare const SettleBillHelper: $.kd.sdk.scmc.im.acct.SettleBillHelper_C;
