export declare type CtAfterBuildDrawFilterEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterBuildDrawFilterEventArgs;
export declare const CtAfterBuildDrawFilterEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterBuildDrawFilterEventArgs_C;
export declare type CtAfterBuildQueryParemeterEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterBuildQueryParemeterEventArgs;
export declare const CtAfterBuildQueryParemeterEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterBuildQueryParemeterEventArgs_C;
export declare type CtAfterBuildRowConditionEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterBuildRowConditionEventArgs;
export declare const CtAfterBuildRowConditionEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterBuildRowConditionEventArgs_C;
export declare type CtAfterBuildSourceBillIdsEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterBuildSourceBillIdsEventArgs;
export declare const CtAfterBuildSourceBillIdsEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterBuildSourceBillIdsEventArgs_C;
export declare type CtAfterCalcWriteValueEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterCalcWriteValueEventArgs;
export declare const CtAfterCalcWriteValueEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterCalcWriteValueEventArgs_C;
export declare type CtAfterCloseRowEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterCloseRowEventArgs;
export declare const CtAfterCloseRowEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterCloseRowEventArgs_C;
export declare type CtAfterCommitAmountEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterCommitAmountEventArgs;
export declare const CtAfterCommitAmountEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterCommitAmountEventArgs_C;
export declare type CtAfterCreateLinkEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterCreateLinkEventArgs;
export declare const CtAfterCreateLinkEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterCreateLinkEventArgs_C;
export declare type CtAfterCreateTargetEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterCreateTargetEventArgs;
export declare const CtAfterCreateTargetEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterCreateTargetEventArgs_C;
export declare type CtAfterCtConvertEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterCtConvertEventArgs;
export declare const CtAfterCtConvertEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterCtConvertEventArgs_C;
export declare type CtAfterExcessCheckEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterExcessCheckEventArgs;
export declare const CtAfterExcessCheckEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterExcessCheckEventArgs_C;
export declare type CtAfterFieldMappingEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterFieldMappingEventArgs;
export declare const CtAfterFieldMappingEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterFieldMappingEventArgs_C;
export declare type CtAfterGetSourceDataEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterGetSourceDataEventArgs;
export declare const CtAfterGetSourceDataEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterGetSourceDataEventArgs_C;
export declare type CtAfterReadSourceBillEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterReadSourceBillEventArgs;
export declare const CtAfterReadSourceBillEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterReadSourceBillEventArgs_C;
export declare type CtAfterSaveSourceBillEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterSaveSourceBillEventArgs;
export declare const CtAfterSaveSourceBillEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtAfterSaveSourceBillEventArgs_C;
export declare type CtBeforeBuildGroupModeEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeBuildGroupModeEventArgs;
export declare const CtBeforeBuildGroupModeEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeBuildGroupModeEventArgs_C;
export declare type CtBeforeBuildRowConditionEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeBuildRowConditionEventArgs;
export declare const CtBeforeBuildRowConditionEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeBuildRowConditionEventArgs_C;
export declare type CtBeforeCloseRowEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeCloseRowEventArgs;
export declare const CtBeforeCloseRowEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeCloseRowEventArgs_C;
export declare type CtBeforeCreateArticulationRowEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeCreateArticulationRowEventArgs;
export declare const CtBeforeCreateArticulationRowEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeCreateArticulationRowEventArgs_C;
export declare type CtBeforeCreateLinkEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeCreateLinkEventArgs;
export declare const CtBeforeCreateLinkEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeCreateLinkEventArgs_C;
export declare type CtBeforeCreateTargetEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeCreateTargetEventArgs;
export declare const CtBeforeCreateTargetEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeCreateTargetEventArgs_C;
export declare type CtBeforeExcessCheckEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeExcessCheckEventArgs;
export declare const CtBeforeExcessCheckEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeExcessCheckEventArgs_C;
export declare type CtBeforeExecWriteBackRuleEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeExecWriteBackRuleEventArgs;
export declare const CtBeforeExecWriteBackRuleEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeExecWriteBackRuleEventArgs_C;
export declare type CtBeforeGetSourceDataEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeGetSourceDataEventArgs;
export declare const CtBeforeGetSourceDataEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeGetSourceDataEventArgs_C;
export declare type CtBeforeReadSourceBillEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeReadSourceBillEventArgs;
export declare const CtBeforeReadSourceBillEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeReadSourceBillEventArgs_C;
export declare type CtBeforeSaveSourceBillEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeSaveSourceBillEventArgs;
export declare const CtBeforeSaveSourceBillEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeSaveSourceBillEventArgs_C;
export declare type CtBeforeSaveTransEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeSaveTransEventArgs;
export declare const CtBeforeSaveTransEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeSaveTransEventArgs_C;
export declare type CtBeforeTrackEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeTrackEventArgs;
export declare const CtBeforeTrackEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtBeforeTrackEventArgs_C;
export declare type CtConvertPluginEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtConvertPluginEventArgs;
export declare const CtConvertPluginEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtConvertPluginEventArgs_C;
export declare type CtFinishWriteBackEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtFinishWriteBackEventArgs;
export declare const CtFinishWriteBackEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtFinishWriteBackEventArgs_C;
export declare type CtInitVariableEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtInitVariableEventArgs;
export declare const CtInitVariableEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtInitVariableEventArgs_C;
export declare type CtPreparePropertysEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtPreparePropertysEventArgs;
export declare const CtPreparePropertysEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtPreparePropertysEventArgs_C;
export declare type CtRollbackSaveEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtRollbackSaveEventArgs;
export declare const CtRollbackSaveEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtRollbackSaveEventArgs_C;
export declare type CtWriteBackEventArgs = $.kd.bos.entity.ctbotp.plugin.tracker.args.CtWriteBackEventArgs;
export declare const CtWriteBackEventArgs: $.kd.bos.entity.ctbotp.plugin.tracker.args.CtWriteBackEventArgs_C;
