export declare type IPrintEventBo = $.kd.bos.print.core.plugin.event.bo.IPrintEventBo;
export declare const IPrintEventBo: $.kd.bos.print.core.plugin.event.bo.IPrintEventBo;
export declare type PWGridBo = $.kd.bos.print.core.plugin.event.bo.PWGridBo;
export declare const PWGridBo: $.kd.bos.print.core.plugin.event.bo.PWGridBo_C;
export declare type PWGridCellBo = $.kd.bos.print.core.plugin.event.bo.PWGridCellBo;
export declare const PWGridCellBo: $.kd.bos.print.core.plugin.event.bo.PWGridCellBo_C;
export declare type PWGridColumnBo = $.kd.bos.print.core.plugin.event.bo.PWGridColumnBo;
export declare const PWGridColumnBo: $.kd.bos.print.core.plugin.event.bo.PWGridColumnBo_C;
export declare type PWGridRowBo = $.kd.bos.print.core.plugin.event.bo.PWGridRowBo;
export declare const PWGridRowBo: $.kd.bos.print.core.plugin.event.bo.PWGridRowBo_C;
export declare type PWTextBo = $.kd.bos.print.core.plugin.event.bo.PWTextBo;
export declare const PWTextBo: $.kd.bos.print.core.plugin.event.bo.PWTextBo_C;
export declare type PluginDataVisitorBo = $.kd.bos.print.core.plugin.event.bo.PluginDataVisitorBo;
export declare const PluginDataVisitorBo: $.kd.bos.print.core.plugin.event.bo.PluginDataVisitorBo_C;
