export declare type IBankCardService = $.kd.sdk.hr.hom.business.personinfo.IBankCardService;
export declare const IBankCardService: $.kd.sdk.hr.hom.business.personinfo.IBankCardService;
export declare type IBaseInfoService = $.kd.sdk.hr.hom.business.personinfo.IBaseInfoService;
export declare const IBaseInfoService: $.kd.sdk.hr.hom.business.personinfo.IBaseInfoService;
export declare type ICanFamilyService = $.kd.sdk.hr.hom.business.personinfo.ICanFamilyService;
export declare const ICanFamilyService: $.kd.sdk.hr.hom.business.personinfo.ICanFamilyService;
export declare type ICancontactService = $.kd.sdk.hr.hom.business.personinfo.ICancontactService;
export declare const ICancontactService: $.kd.sdk.hr.hom.business.personinfo.ICancontactService;
export declare type ICertificateInfoService = $.kd.sdk.hr.hom.business.personinfo.ICertificateInfoService;
export declare const ICertificateInfoService: $.kd.sdk.hr.hom.business.personinfo.ICertificateInfoService;
export declare type IContactInfoService = $.kd.sdk.hr.hom.business.personinfo.IContactInfoService;
export declare const IContactInfoService: $.kd.sdk.hr.hom.business.personinfo.IContactInfoService;
export declare type IEducationExpService = $.kd.sdk.hr.hom.business.personinfo.IEducationExpService;
export declare const IEducationExpService: $.kd.sdk.hr.hom.business.personinfo.IEducationExpService;
export declare type ILanguageSkillService = $.kd.sdk.hr.hom.business.personinfo.ILanguageSkillService;
export declare const ILanguageSkillService: $.kd.sdk.hr.hom.business.personinfo.ILanguageSkillService;
export declare type IPreviousWorkExpService = $.kd.sdk.hr.hom.business.personinfo.IPreviousWorkExpService;
export declare const IPreviousWorkExpService: $.kd.sdk.hr.hom.business.personinfo.IPreviousWorkExpService;
export declare type IRsmpatinvService = $.kd.sdk.hr.hom.business.personinfo.IRsmpatinvService;
export declare const IRsmpatinvService: $.kd.sdk.hr.hom.business.personinfo.IRsmpatinvService;
