/// <reference types="../../index" />
export declare type Attr = $.org.w3c.dom.Attr;
export declare const Attr: $.org.w3c.dom.Attr;
export declare type CDATASection = $.org.w3c.dom.CDATASection;
export declare const CDATASection: $.org.w3c.dom.CDATASection;
export declare type CharacterData = $.org.w3c.dom.CharacterData;
export declare const CharacterData: $.org.w3c.dom.CharacterData;
export declare type Comment = $.org.w3c.dom.Comment;
export declare const Comment: $.org.w3c.dom.Comment;
export declare type DOMConfiguration = $.org.w3c.dom.DOMConfiguration;
export declare const DOMConfiguration: $.org.w3c.dom.DOMConfiguration;
export declare type DOMImplementation = $.org.w3c.dom.DOMImplementation;
export declare const DOMImplementation: $.org.w3c.dom.DOMImplementation;
export declare type DOMStringList = $.org.w3c.dom.DOMStringList;
export declare const DOMStringList: $.org.w3c.dom.DOMStringList;
export declare type Document = $.org.w3c.dom.Document;
export declare const Document: $.org.w3c.dom.Document;
export declare type DocumentFragment = $.org.w3c.dom.DocumentFragment;
export declare const DocumentFragment: $.org.w3c.dom.DocumentFragment;
export declare type DocumentType = $.org.w3c.dom.DocumentType;
export declare const DocumentType: $.org.w3c.dom.DocumentType;
export declare type Element = $.org.w3c.dom.Element;
export declare const Element: $.org.w3c.dom.Element;
export declare type EntityReference = $.org.w3c.dom.EntityReference;
export declare const EntityReference: $.org.w3c.dom.EntityReference;
export declare type NamedNodeMap = $.org.w3c.dom.NamedNodeMap;
export declare const NamedNodeMap: $.org.w3c.dom.NamedNodeMap;
export declare type Node = $.org.w3c.dom.Node;
export declare const Node: $.org.w3c.dom.Node;
export declare type NodeList = $.org.w3c.dom.NodeList;
export declare const NodeList: $.org.w3c.dom.NodeList;
export declare type ProcessingInstruction = $.org.w3c.dom.ProcessingInstruction;
export declare const ProcessingInstruction: $.org.w3c.dom.ProcessingInstruction;
export declare type Text = $.org.w3c.dom.Text;
export declare const Text: $.org.w3c.dom.Text;
export declare type TypeInfo = $.org.w3c.dom.TypeInfo;
export declare const TypeInfo: $.org.w3c.dom.TypeInfo;
export declare type UserDataHandler = $.org.w3c.dom.UserDataHandler;
export declare const UserDataHandler: $.org.w3c.dom.UserDataHandler;
