export declare type OrgRelationConfig = $.kd.bos.entity.property.org.OrgRelationConfig;
export declare const OrgRelationConfig: $.kd.bos.entity.property.org.OrgRelationConfig_C;
export declare type OrgRelationItem = $.kd.bos.entity.property.org.OrgRelationItem;
export declare const OrgRelationItem: $.kd.bos.entity.property.org.OrgRelationItem_C;
export declare type OrgRelationItemDirect = $.kd.bos.entity.property.org.OrgRelationItemDirect;
export declare const OrgRelationItemDirect: $.kd.bos.entity.property.org.OrgRelationItemDirect_C;
export declare type OrgRelationItemOrg = $.kd.bos.entity.property.org.OrgRelationItemOrg;
export declare const OrgRelationItemOrg: $.kd.bos.entity.property.org.OrgRelationItemOrg_C;
export declare type OrgRelationItemType = $.kd.bos.entity.property.org.OrgRelationItemType;
export declare const OrgRelationItemType: $.kd.bos.entity.property.org.OrgRelationItemType_C;
export declare type OrgViewSchemeProp = $.kd.bos.entity.property.org.OrgViewSchemeProp;
export declare const OrgViewSchemeProp: $.kd.bos.entity.property.org.OrgViewSchemeProp_C;
