export declare type MacroItem = $.kd.bos.workflow.api.model.MacroItem;
export declare const MacroItem: $.kd.bos.workflow.api.model.MacroItem_C;
export declare type NodeMacro = $.kd.bos.workflow.api.model.NodeMacro;
export declare const NodeMacro: $.kd.bos.workflow.api.model.NodeMacro_C;
export declare type NodeProperty = $.kd.bos.workflow.api.model.NodeProperty;
export declare const NodeProperty: $.kd.bos.workflow.api.model.NodeProperty_C;
export declare type ProcPublishResult = $.kd.bos.workflow.api.model.ProcPublishResult;
export declare const ProcPublishResult: $.kd.bos.workflow.api.model.ProcPublishResult_C;
export declare type ProcessDefinitionInfo = $.kd.bos.workflow.api.model.ProcessDefinitionInfo;
export declare const ProcessDefinitionInfo: $.kd.bos.workflow.api.model.ProcessDefinitionInfo_C;
export declare type ProcessInitiator = $.kd.bos.workflow.api.model.ProcessInitiator;
export declare const ProcessInitiator: $.kd.bos.workflow.api.model.ProcessInitiator_C;
export declare type ProcessModel = $.kd.bos.workflow.api.model.ProcessModel;
export declare const ProcessModel: $.kd.bos.workflow.api.model.ProcessModel_C;
export declare type ProcessNode = $.kd.bos.workflow.api.model.ProcessNode;
export declare const ProcessNode: $.kd.bos.workflow.api.model.ProcessNode_C;
export declare type ProcessTemplate = $.kd.bos.workflow.api.model.ProcessTemplate;
export declare const ProcessTemplate: $.kd.bos.workflow.api.model.ProcessTemplate_C;
export declare type ValidateResultItem = $.kd.bos.workflow.api.model.ValidateResultItem;
export declare const ValidateResultItem: $.kd.bos.workflow.api.model.ValidateResultItem_C;
