export declare type AfterLoadDataEvent = $.kd.bos.print.core.plugin.event.AfterLoadDataEvent;
export declare const AfterLoadDataEvent: $.kd.bos.print.core.plugin.event.AfterLoadDataEvent_C;
export declare type AfterOutputGridEvent = $.kd.bos.print.core.plugin.event.AfterOutputGridEvent;
export declare const AfterOutputGridEvent: $.kd.bos.print.core.plugin.event.AfterOutputGridEvent_C;
export declare type AfterOutputRowEvent = $.kd.bos.print.core.plugin.event.AfterOutputRowEvent;
export declare const AfterOutputRowEvent: $.kd.bos.print.core.plugin.event.AfterOutputRowEvent_C;
export declare type AfterOutputWidgetEvent = $.kd.bos.print.core.plugin.event.AfterOutputWidgetEvent;
export declare const AfterOutputWidgetEvent: $.kd.bos.print.core.plugin.event.AfterOutputWidgetEvent_C;
export declare type BeforeExportEvent = $.kd.bos.print.core.plugin.event.BeforeExportEvent;
export declare const BeforeExportEvent: $.kd.bos.print.core.plugin.event.BeforeExportEvent_C;
export declare type BeforeInitWidgetEvent = $.kd.bos.print.core.plugin.event.BeforeInitWidgetEvent;
export declare const BeforeInitWidgetEvent: $.kd.bos.print.core.plugin.event.BeforeInitWidgetEvent_C;
export declare type BeforeLoadDataEvent = $.kd.bos.print.core.plugin.event.BeforeLoadDataEvent;
export declare const BeforeLoadDataEvent: $.kd.bos.print.core.plugin.event.BeforeLoadDataEvent_C;
export declare type BeforeOutputGridEvent = $.kd.bos.print.core.plugin.event.BeforeOutputGridEvent;
export declare const BeforeOutputGridEvent: $.kd.bos.print.core.plugin.event.BeforeOutputGridEvent_C;
export declare type BeforeOutputRowEvent = $.kd.bos.print.core.plugin.event.BeforeOutputRowEvent;
export declare const BeforeOutputRowEvent: $.kd.bos.print.core.plugin.event.BeforeOutputRowEvent_C;
export declare type BeforeOutputTextEvent = $.kd.bos.print.core.plugin.event.BeforeOutputTextEvent;
export declare const BeforeOutputTextEvent: $.kd.bos.print.core.plugin.event.BeforeOutputTextEvent_C;
export declare type BeforeOutputWidgetEvent = $.kd.bos.print.core.plugin.event.BeforeOutputWidgetEvent;
export declare const BeforeOutputWidgetEvent: $.kd.bos.print.core.plugin.event.BeforeOutputWidgetEvent_C;
export declare type CustomDataLoadEvent = $.kd.bos.print.core.plugin.event.CustomDataLoadEvent;
export declare const CustomDataLoadEvent: $.kd.bos.print.core.plugin.event.CustomDataLoadEvent_C;
export declare type EndExportEvent = $.kd.bos.print.core.plugin.event.EndExportEvent;
export declare const EndExportEvent: $.kd.bos.print.core.plugin.event.EndExportEvent_C;
export declare type ExpFileEvent = $.kd.bos.print.core.plugin.event.ExpFileEvent;
export declare const ExpFileEvent: $.kd.bos.print.core.plugin.event.ExpFileEvent_C;
export declare type LineWrapEvent = $.kd.bos.print.core.plugin.event.LineWrapEvent;
export declare const LineWrapEvent: $.kd.bos.print.core.plugin.event.LineWrapEvent_C;
export declare type ParseRichImgEvent = $.kd.bos.print.core.plugin.event.ParseRichImgEvent;
export declare const ParseRichImgEvent: $.kd.bos.print.core.plugin.event.ParseRichImgEvent_C;
