export declare type ComboSearchValue = $.kd.bos.list.column.ComboSearchValue;
export declare const ComboSearchValue: $.kd.bos.list.column.ComboSearchValue_C;
export declare type CompareSearchValue = $.kd.bos.list.column.CompareSearchValue;
export declare const CompareSearchValue: $.kd.bos.list.column.CompareSearchValue_C;
export declare type ListColumnComboItem = $.kd.bos.list.column.ListColumnComboItem;
export declare const ListColumnComboItem: $.kd.bos.list.column.ListColumnComboItem_C;
export declare type ListColumnCompare = $.kd.bos.list.column.ListColumnCompare;
export declare const ListColumnCompare: $.kd.bos.list.column.ListColumnCompare_C;
export declare type ListColumnCompareService = $.kd.bos.list.column.ListColumnCompareService;
export declare const ListColumnCompareService: $.kd.bos.list.column.ListColumnCompareService;
export declare type ListColumnCompares = $.kd.bos.list.column.ListColumnCompares;
export declare const ListColumnCompares: $.kd.bos.list.column.ListColumnCompares_C;
export declare type ListOperationColumnDesc = $.kd.bos.list.column.ListOperationColumnDesc;
export declare const ListOperationColumnDesc: $.kd.bos.list.column.ListOperationColumnDesc_C;
export declare type TemplateTextItem = $.kd.bos.list.column.TemplateTextItem;
export declare const TemplateTextItem: $.kd.bos.list.column.TemplateTextItem_C;
