export declare type BackPressedEvent = $.kd.bos.list.events.BackPressedEvent;
export declare const BackPressedEvent: $.kd.bos.list.events.BackPressedEvent_C;
export declare type BeforeShowBillFormEvent = $.kd.bos.list.events.BeforeShowBillFormEvent;
export declare const BeforeShowBillFormEvent: $.kd.bos.list.events.BeforeShowBillFormEvent_C;
export declare type BillClosedCallBackEvent = $.kd.bos.list.events.BillClosedCallBackEvent;
export declare const BillClosedCallBackEvent: $.kd.bos.list.events.BillClosedCallBackEvent_C;
export declare type BillListGetEntityTypeListener = $.kd.bos.list.events.BillListGetEntityTypeListener;
export declare const BillListGetEntityTypeListener: $.kd.bos.list.events.BillListGetEntityTypeListener;
export declare type BuildTreeListFilterEvent = $.kd.bos.list.events.BuildTreeListFilterEvent;
export declare const BuildTreeListFilterEvent: $.kd.bos.list.events.BuildTreeListFilterEvent_C;
export declare type ChatEvent = $.kd.bos.list.events.ChatEvent;
export declare const ChatEvent: $.kd.bos.list.events.ChatEvent_C;
export declare type CreateListColumnsListener = $.kd.bos.list.events.CreateListColumnsListener;
export declare const CreateListColumnsListener: $.kd.bos.list.events.CreateListColumnsListener;
export declare type CreateListDataProviderListener = $.kd.bos.list.events.CreateListDataProviderListener;
export declare const CreateListDataProviderListener: $.kd.bos.list.events.CreateListDataProviderListener;
export declare type CreateTreeListViewEvent = $.kd.bos.list.events.CreateTreeListViewEvent;
export declare const CreateTreeListViewEvent: $.kd.bos.list.events.CreateTreeListViewEvent_C;
export declare type F7SelectedListRemoveEvent = $.kd.bos.list.events.F7SelectedListRemoveEvent;
export declare const F7SelectedListRemoveEvent: $.kd.bos.list.events.F7SelectedListRemoveEvent_C;
export declare type F7SelectedListRemoveListener = $.kd.bos.list.events.F7SelectedListRemoveListener;
export declare const F7SelectedListRemoveListener: $.kd.bos.list.events.F7SelectedListRemoveListener;
export declare type F7SelectedListSortEvent = $.kd.bos.list.events.F7SelectedListSortEvent;
export declare const F7SelectedListSortEvent: $.kd.bos.list.events.F7SelectedListSortEvent_C;
export declare type F7SelectedListSortListener = $.kd.bos.list.events.F7SelectedListSortListener;
export declare const F7SelectedListSortListener: $.kd.bos.list.events.F7SelectedListSortListener;
export declare type IndexModeSetEvent = $.kd.bos.list.events.IndexModeSetEvent;
export declare const IndexModeSetEvent: $.kd.bos.list.events.IndexModeSetEvent_C;
export declare type ItemSelectEvent = $.kd.bos.list.events.ItemSelectEvent;
export declare const ItemSelectEvent: $.kd.bos.list.events.ItemSelectEvent_C;
export declare type ListBeforeBindDataEvent = $.kd.bos.list.events.ListBeforeBindDataEvent;
export declare const ListBeforeBindDataEvent: $.kd.bos.list.events.ListBeforeBindDataEvent_C;
export declare type ListColumnFilter = $.kd.bos.list.events.ListColumnFilter;
export declare const ListColumnFilter: $.kd.bos.list.events.ListColumnFilter_C;
export declare type ListColumnFilterCollection = $.kd.bos.list.events.ListColumnFilterCollection;
export declare const ListColumnFilterCollection: $.kd.bos.list.events.ListColumnFilterCollection_C;
export declare type ListHyperLinkClickEvent = $.kd.bos.list.events.ListHyperLinkClickEvent;
export declare const ListHyperLinkClickEvent: $.kd.bos.list.events.ListHyperLinkClickEvent_C;
export declare type ListHyperLinkClickListener = $.kd.bos.list.events.ListHyperLinkClickListener;
export declare const ListHyperLinkClickListener: $.kd.bos.list.events.ListHyperLinkClickListener;
export declare type ListRowClickEvent = $.kd.bos.list.events.ListRowClickEvent;
export declare const ListRowClickEvent: $.kd.bos.list.events.ListRowClickEvent_C;
export declare type ListRowClickListener = $.kd.bos.list.events.ListRowClickListener;
export declare const ListRowClickListener: $.kd.bos.list.events.ListRowClickListener;
export declare type ListRowDetailShowEvent = $.kd.bos.list.events.ListRowDetailShowEvent;
export declare const ListRowDetailShowEvent: $.kd.bos.list.events.ListRowDetailShowEvent_C;
export declare type ListRowFilterEvent = $.kd.bos.list.events.ListRowFilterEvent;
export declare const ListRowFilterEvent: $.kd.bos.list.events.ListRowFilterEvent_C;
export declare type ListSelectedListener = $.kd.bos.list.events.ListSelectedListener;
export declare const ListSelectedListener: $.kd.bos.list.events.ListSelectedListener;
export declare type MultiFieldsSortEvent = $.kd.bos.list.events.MultiFieldsSortEvent;
export declare const MultiFieldsSortEvent: $.kd.bos.list.events.MultiFieldsSortEvent_C;
export declare type QueryBillDataCountEvent = $.kd.bos.list.events.QueryBillDataCountEvent;
export declare const QueryBillDataCountEvent: $.kd.bos.list.events.QueryBillDataCountEvent_C;
export declare type QueryBillDataCountListener = $.kd.bos.list.events.QueryBillDataCountListener;
export declare const QueryBillDataCountListener: $.kd.bos.list.events.QueryBillDataCountListener;
export declare type QueryExceedMaxCountEvent = $.kd.bos.list.events.QueryExceedMaxCountEvent;
export declare const QueryExceedMaxCountEvent: $.kd.bos.list.events.QueryExceedMaxCountEvent_C;
export declare type QueryExceedMaxCountListener = $.kd.bos.list.events.QueryExceedMaxCountListener;
export declare const QueryExceedMaxCountListener: $.kd.bos.list.events.QueryExceedMaxCountListener;
export declare type QueryListEvent = $.kd.bos.list.events.QueryListEvent;
export declare const QueryListEvent: $.kd.bos.list.events.QueryListEvent_C;
export declare type QueryRealCountEvent = $.kd.bos.list.events.QueryRealCountEvent;
export declare const QueryRealCountEvent: $.kd.bos.list.events.QueryRealCountEvent_C;
export declare type QueryRealCountListener = $.kd.bos.list.events.QueryRealCountListener;
export declare const QueryRealCountListener: $.kd.bos.list.events.QueryRealCountListener;
export declare type QuerySumDataEvent = $.kd.bos.list.events.QuerySumDataEvent;
export declare const QuerySumDataEvent: $.kd.bos.list.events.QuerySumDataEvent_C;
export declare type QuerySumDataListener = $.kd.bos.list.events.QuerySumDataListener;
export declare const QuerySumDataListener: $.kd.bos.list.events.QuerySumDataListener;
export declare type SelectEvent = $.kd.bos.list.events.SelectEvent;
export declare const SelectEvent: $.kd.bos.list.events.SelectEvent_C;
export declare type SetCellFieldValueArgs = $.kd.bos.list.events.SetCellFieldValueArgs;
export declare const SetCellFieldValueArgs: $.kd.bos.list.events.SetCellFieldValueArgs_C;
export declare type SetCellFieldValueEvent = $.kd.bos.list.events.SetCellFieldValueEvent;
export declare const SetCellFieldValueEvent: $.kd.bos.list.events.SetCellFieldValueEvent_C;
export declare type SetCellFieldValueListener = $.kd.bos.list.events.SetCellFieldValueListener;
export declare const SetCellFieldValueListener: $.kd.bos.list.events.SetCellFieldValueListener;
export declare type DataSelectEvent = $.kd.bos.list.events.DataSelectEvent;
export declare const DataSelectEvent: $.kd.bos.list.events.DataSelectEvent_C;
export declare type EndSelectEvent = $.kd.bos.list.events.EndSelectEvent;
export declare const EndSelectEvent: $.kd.bos.list.events.EndSelectEvent_C;
