export declare type AbstractListPlugin = $.kd.bos.list.plugin.AbstractListPlugin;
export declare const AbstractListPlugin: $.kd.bos.list.plugin.AbstractListPlugin_C;
export declare type AbstractListViewPluginProxy = $.kd.bos.list.plugin.AbstractListViewPluginProxy;
export declare const AbstractListViewPluginProxy: $.kd.bos.list.plugin.AbstractListViewPluginProxy_C;
export declare type AbstractMobListPlugin = $.kd.bos.list.plugin.AbstractMobListPlugin;
export declare const AbstractMobListPlugin: $.kd.bos.list.plugin.AbstractMobListPlugin_C;
export declare type AbstractTreeListPlugin = $.kd.bos.list.plugin.AbstractTreeListPlugin;
export declare const AbstractTreeListPlugin: $.kd.bos.list.plugin.AbstractTreeListPlugin_C;
export declare type IListPlugin = $.kd.bos.list.plugin.IListPlugin;
export declare const IListPlugin: $.kd.bos.list.plugin.IListPlugin;
export declare type IMobListPlugin = $.kd.bos.list.plugin.IMobListPlugin;
export declare const IMobListPlugin: $.kd.bos.list.plugin.IMobListPlugin;
export declare type IPCListPlugin = $.kd.bos.list.plugin.IPCListPlugin;
export declare const IPCListPlugin: $.kd.bos.list.plugin.IPCListPlugin;
export declare type ITreeListPlugin = $.kd.bos.list.plugin.ITreeListPlugin;
export declare const ITreeListPlugin: $.kd.bos.list.plugin.ITreeListPlugin;
export declare type ListViewPluginProxy = $.kd.bos.list.plugin.ListViewPluginProxy;
export declare const ListViewPluginProxy: $.kd.bos.list.plugin.ListViewPluginProxy_C;
export declare type StandardTreeListPlugin = $.kd.bos.list.plugin.StandardTreeListPlugin;
export declare const StandardTreeListPlugin: $.kd.bos.list.plugin.StandardTreeListPlugin_C;
