export declare type AfterQteGenQTEvent = $.kd.sdk.wtc.wtes.business.qte.executor.AfterQteGenQTEvent;
export declare const AfterQteGenQTEvent: $.kd.sdk.wtc.wtes.business.qte.executor.AfterQteGenQTEvent_C;
export declare type QteGenQTExtPlugin = $.kd.sdk.wtc.wtes.business.qte.executor.QteGenQTExtPlugin;
export declare const QteGenQTExtPlugin: $.kd.sdk.wtc.wtes.business.qte.executor.QteGenQTExtPlugin;
export declare type QuotaDetail = $.kd.sdk.wtc.wtes.business.qte.executor.QuotaDetail;
export declare const QuotaDetail: $.kd.sdk.wtc.wtes.business.qte.executor.QuotaDetail_C;
export declare type QuotaDetailInOut = $.kd.sdk.wtc.wtes.business.qte.executor.QuotaDetailInOut;
export declare const QuotaDetailInOut: $.kd.sdk.wtc.wtes.business.qte.executor.QuotaDetailInOut_C;
export declare type QuotaDetailOverdraw = $.kd.sdk.wtc.wtes.business.qte.executor.QuotaDetailOverdraw;
export declare const QuotaDetailOverdraw: $.kd.sdk.wtc.wtes.business.qte.executor.QuotaDetailOverdraw_C;
export declare type QuotaDetailOverdrawQl = $.kd.sdk.wtc.wtes.business.qte.executor.QuotaDetailOverdrawQl;
export declare const QuotaDetailOverdrawQl: $.kd.sdk.wtc.wtes.business.qte.executor.QuotaDetailOverdrawQl_C;
export declare type QuotaDetailQualification = $.kd.sdk.wtc.wtes.business.qte.executor.QuotaDetailQualification;
export declare const QuotaDetailQualification: $.kd.sdk.wtc.wtes.business.qte.executor.QuotaDetailQualification_C;
export declare type QuotaDetailStandard = $.kd.sdk.wtc.wtes.business.qte.executor.QuotaDetailStandard;
export declare const QuotaDetailStandard: $.kd.sdk.wtc.wtes.business.qte.executor.QuotaDetailStandard_C;
export declare type QuotaDetailUse = $.kd.sdk.wtc.wtes.business.qte.executor.QuotaDetailUse;
export declare const QuotaDetailUse: $.kd.sdk.wtc.wtes.business.qte.executor.QuotaDetailUse_C;
export declare type QuotaDetailUseQualification = $.kd.sdk.wtc.wtes.business.qte.executor.QuotaDetailUseQualification;
export declare const QuotaDetailUseQualification: $.kd.sdk.wtc.wtes.business.qte.executor.QuotaDetailUseQualification_C;
