export declare type HPRIPerBankCardServiceHelper = $.kd.hr.hbp.business.openservicehelper.hrpi.HPRIPerBankCardServiceHelper;
export declare const HPRIPerBankCardServiceHelper: $.kd.hr.hbp.business.openservicehelper.hrpi.HPRIPerBankCardServiceHelper_C;
export declare type HRPIApplyServiceHelper = $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIApplyServiceHelper;
export declare const HRPIApplyServiceHelper: $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIApplyServiceHelper_C;
export declare type HRPIChargePersonServiceHelper = $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIChargePersonServiceHelper;
export declare const HRPIChargePersonServiceHelper: $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIChargePersonServiceHelper_C;
export declare type HRPICmpempServiceHelper = $.kd.hr.hbp.business.openservicehelper.hrpi.HRPICmpempServiceHelper;
export declare const HRPICmpempServiceHelper: $.kd.hr.hbp.business.openservicehelper.hrpi.HRPICmpempServiceHelper_C;
export declare type HRPIDepempServiceHelper = $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIDepempServiceHelper;
export declare const HRPIDepempServiceHelper: $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIDepempServiceHelper_C;
export declare type HRPIEmployeeServiceHelper = $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIEmployeeServiceHelper;
export declare const HRPIEmployeeServiceHelper: $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIEmployeeServiceHelper_C;
export declare type HRPIModule = $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIModule;
export declare const HRPIModule: $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIModule_C;
export declare type HRPIOrgWorkFlowServiceHelper = $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIOrgWorkFlowServiceHelper;
export declare const HRPIOrgWorkFlowServiceHelper: $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIOrgWorkFlowServiceHelper_C;
export declare type HRPIPersonGenericServiceHelper = $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIPersonGenericServiceHelper;
export declare const HRPIPersonGenericServiceHelper: $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIPersonGenericServiceHelper_C;
export declare type HRPIPersonServiceHelper = $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIPersonServiceHelper;
export declare const HRPIPersonServiceHelper: $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIPersonServiceHelper_C;
export declare type HRPIWorkRoleServiceHelper = $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIWorkRoleServiceHelper;
export declare const HRPIWorkRoleServiceHelper: $.kd.hr.hbp.business.openservicehelper.hrpi.HRPIWorkRoleServiceHelper_C;
export declare type HRPTMMServiceHelper = $.kd.hr.hbp.business.openservicehelper.hrpi.HRPTMMServiceHelper;
export declare const HRPTMMServiceHelper: $.kd.hr.hbp.business.openservicehelper.hrpi.HRPTMMServiceHelper_C;
