export declare type Donothing = $.kd.bos.service.operation.Donothing;
export declare const Donothing: $.kd.bos.service.operation.Donothing_C;
export declare type EntityOperateService = $.kd.bos.service.operation.EntityOperateService;
export declare const EntityOperateService: $.kd.bos.service.operation.EntityOperateService_C;
export declare type OperationServiceImpl = $.kd.bos.service.operation.OperationServiceImpl;
export declare const OperationServiceImpl: $.kd.bos.service.operation.OperationServiceImpl_C;
export declare type Save = $.kd.bos.service.operation.Save;
export declare const Save: $.kd.bos.service.operation.Save_C;
export declare type StatusConvertOperateService = $.kd.bos.service.operation.StatusConvertOperateService;
export declare const StatusConvertOperateService: $.kd.bos.service.operation.StatusConvertOperateService_C;
export declare type OperationService = $.kd.bos.service.operation.OperationService;
export declare const OperationService: $.kd.bos.service.operation.OperationService;
