export declare type IReportColumnSetting = $.kd.sdk.fi.gl.extpoint.report.IReportColumnSetting;
export declare const IReportColumnSetting: $.kd.sdk.fi.gl.extpoint.report.IReportColumnSetting;
export declare type IReportQuery = $.kd.sdk.fi.gl.extpoint.report.IReportQuery;
export declare const IReportQuery: $.kd.sdk.fi.gl.extpoint.report.IReportQuery;
export declare type IReportRowHideSpi = $.kd.sdk.fi.gl.extpoint.report.IReportRowHideSpi;
export declare const IReportRowHideSpi: $.kd.sdk.fi.gl.extpoint.report.IReportRowHideSpi;
export declare type ReportParam = $.kd.sdk.fi.gl.extpoint.report.ReportParam;
export declare const ReportParam: $.kd.sdk.fi.gl.extpoint.report.ReportParam_C;
export declare type RowType = $.kd.sdk.fi.gl.extpoint.report.RowType;
export declare const RowType: typeof $.kd.sdk.fi.gl.extpoint.report.RowType;
