export declare type IAmountControl = $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IAmountControl;
export declare const IAmountControl: $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IAmountControl;
export declare type IAssetentryMustInput = $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IAssetentryMustInput;
export declare const IAssetentryMustInput: $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IAssetentryMustInput;
export declare type IChangeReceiveAmount = $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IChangeReceiveAmount;
export declare const IChangeReceiveAmount: $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IChangeReceiveAmount;
export declare type IEntryMustInput = $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IEntryMustInput;
export declare const IEntryMustInput: $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IEntryMustInput;
export declare type IInitBillInfo = $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IInitBillInfo;
export declare const IInitBillInfo: $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IInitBillInfo;
export declare type IPayAmountCal = $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IPayAmountCal;
export declare const IPayAmountCal: $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IPayAmountCal;
export declare type IReimburseAmount = $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IReimburseAmount;
export declare const IReimburseAmount: $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IReimburseAmount;
export declare type ISuperClosedCallBack = $.kd.sdk.fi.er.extpoint.dailyreimbursebill.ISuperClosedCallBack;
export declare const ISuperClosedCallBack: $.kd.sdk.fi.er.extpoint.dailyreimbursebill.ISuperClosedCallBack;
export declare type ITripStandardControl = $.kd.sdk.fi.er.extpoint.dailyreimbursebill.ITripStandardControl;
export declare const ITripStandardControl: $.kd.sdk.fi.er.extpoint.dailyreimbursebill.ITripStandardControl;
export declare type IWriteBackService = $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IWriteBackService;
export declare const IWriteBackService: $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IWriteBackService;
export declare type IWriteOffMoney = $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IWriteOffMoney;
export declare const IWriteOffMoney: $.kd.sdk.fi.er.extpoint.dailyreimbursebill.IWriteOffMoney;
