export declare type BaseDataColumnDependFieldSetEvent = $.kd.bos.form.control.events.BaseDataColumnDependFieldSetEvent;
export declare const BaseDataColumnDependFieldSetEvent: $.kd.bos.form.control.events.BaseDataColumnDependFieldSetEvent_C;
export declare type BaseDataColumnDependFieldSetListener = $.kd.bos.form.control.events.BaseDataColumnDependFieldSetListener;
export declare const BaseDataColumnDependFieldSetListener: $.kd.bos.form.control.events.BaseDataColumnDependFieldSetListener;
export declare type FilterContainerInitEvent = $.kd.bos.form.control.events.FilterContainerInitEvent;
export declare const FilterContainerInitEvent: $.kd.bos.form.control.events.FilterContainerInitEvent_C;
export declare type FilterContainerInitListener = $.kd.bos.form.control.events.FilterContainerInitListener;
export declare const FilterContainerInitListener: $.kd.bos.form.control.events.FilterContainerInitListener;
export declare type MobFilterSortInitEvent = $.kd.bos.form.control.events.MobFilterSortInitEvent;
export declare const MobFilterSortInitEvent: $.kd.bos.form.control.events.MobFilterSortInitEvent_C;
export declare type MobFilterSortInitListener = $.kd.bos.form.control.events.MobFilterSortInitListener;
export declare const MobFilterSortInitListener: $.kd.bos.form.control.events.MobFilterSortInitListener;
export declare type MobileSearchInitEvent = $.kd.bos.form.control.events.MobileSearchInitEvent;
export declare const MobileSearchInitEvent: $.kd.bos.form.control.events.MobileSearchInitEvent_C;
export declare type MobileSearchInitListener = $.kd.bos.form.control.events.MobileSearchInitListener;
export declare const MobileSearchInitListener: $.kd.bos.form.control.events.MobileSearchInitListener;
export declare type ActiveViewEvent = $.kd.bos.form.control.events.ActiveViewEvent;
export declare const ActiveViewEvent: $.kd.bos.form.control.events.ActiveViewEvent_C;
export declare type ActiveViewListener = $.kd.bos.form.control.events.ActiveViewListener;
export declare const ActiveViewListener: $.kd.bos.form.control.events.ActiveViewListener;
export declare type AfterSearchClickListener = $.kd.bos.form.control.events.AfterSearchClickListener;
export declare const AfterSearchClickListener: $.kd.bos.form.control.events.AfterSearchClickListener;
export declare type AfterShowTipsEvent = $.kd.bos.form.control.events.AfterShowTipsEvent;
export declare const AfterShowTipsEvent: $.kd.bos.form.control.events.AfterShowTipsEvent_C;
export declare type BeforeClickEvent = $.kd.bos.form.control.events.BeforeClickEvent;
export declare const BeforeClickEvent: $.kd.bos.form.control.events.BeforeClickEvent_C;
export declare type BeforeItemClickEvent = $.kd.bos.form.control.events.BeforeItemClickEvent;
export declare const BeforeItemClickEvent: $.kd.bos.form.control.events.BeforeItemClickEvent_C;
export declare type BeforeShowTipsEvent = $.kd.bos.form.control.events.BeforeShowTipsEvent;
export declare const BeforeShowTipsEvent: $.kd.bos.form.control.events.BeforeShowTipsEvent_C;
export declare type CellClickEvent = $.kd.bos.form.control.events.CellClickEvent;
export declare const CellClickEvent: $.kd.bos.form.control.events.CellClickEvent_C;
export declare type CellClickListener = $.kd.bos.form.control.events.CellClickListener;
export declare const CellClickListener: $.kd.bos.form.control.events.CellClickListener;
export declare type ChartClickEvent = $.kd.bos.form.control.events.ChartClickEvent;
export declare const ChartClickEvent: $.kd.bos.form.control.events.ChartClickEvent_C;
export declare type ClickEvent = $.kd.bos.form.control.events.ClickEvent;
export declare const ClickEvent: $.kd.bos.form.control.events.ClickEvent_C;
export declare type ClickListener = $.kd.bos.form.control.events.ClickListener;
export declare const ClickListener: $.kd.bos.form.control.events.ClickListener;
export declare type ContainerOnShowEvent = $.kd.bos.form.control.events.ContainerOnShowEvent;
export declare const ContainerOnShowEvent: $.kd.bos.form.control.events.ContainerOnShowEvent_C;
export declare type ContainerOnShowListener = $.kd.bos.form.control.events.ContainerOnShowListener;
export declare const ContainerOnShowListener: $.kd.bos.form.control.events.ContainerOnShowListener;
export declare type EnterKeyEvent = $.kd.bos.form.control.events.EnterKeyEvent;
export declare const EnterKeyEvent: $.kd.bos.form.control.events.EnterKeyEvent_C;
export declare type EnterKeyListener = $.kd.bos.form.control.events.EnterKeyListener;
export declare const EnterKeyListener: $.kd.bos.form.control.events.EnterKeyListener;
export declare type EntryFilterChangedEvent = $.kd.bos.form.control.events.EntryFilterChangedEvent;
export declare const EntryFilterChangedEvent: $.kd.bos.form.control.events.EntryFilterChangedEvent_C;
export declare type EntryFilterChangedListener = $.kd.bos.form.control.events.EntryFilterChangedListener;
export declare const EntryFilterChangedListener: $.kd.bos.form.control.events.EntryFilterChangedListener;
export declare type EntryGridBindDataEvent = $.kd.bos.form.control.events.EntryGridBindDataEvent;
export declare const EntryGridBindDataEvent: $.kd.bos.form.control.events.EntryGridBindDataEvent_C;
export declare type EntryGridBindDataListener = $.kd.bos.form.control.events.EntryGridBindDataListener;
export declare const EntryGridBindDataListener: $.kd.bos.form.control.events.EntryGridBindDataListener;
export declare type EntryGridColAllCheckedEvent = $.kd.bos.form.control.events.EntryGridColAllCheckedEvent;
export declare const EntryGridColAllCheckedEvent: $.kd.bos.form.control.events.EntryGridColAllCheckedEvent_C;
export declare type EntryGridColAllCheckedListener = $.kd.bos.form.control.events.EntryGridColAllCheckedListener;
export declare const EntryGridColAllCheckedListener: $.kd.bos.form.control.events.EntryGridColAllCheckedListener;
export declare type EntryGridFilterEntryEvent = $.kd.bos.form.control.events.EntryGridFilterEntryEvent;
export declare const EntryGridFilterEntryEvent: $.kd.bos.form.control.events.EntryGridFilterEntryEvent_C;
export declare type EntryGridFilterEntryListener = $.kd.bos.form.control.events.EntryGridFilterEntryListener;
export declare const EntryGridFilterEntryListener: $.kd.bos.form.control.events.EntryGridFilterEntryListener;
export declare type EntryGridSetRowDataEvent = $.kd.bos.form.control.events.EntryGridSetRowDataEvent;
export declare const EntryGridSetRowDataEvent: $.kd.bos.form.control.events.EntryGridSetRowDataEvent_C;
export declare type EntryGridSetRowDataListener = $.kd.bos.form.control.events.EntryGridSetRowDataListener;
export declare const EntryGridSetRowDataListener: $.kd.bos.form.control.events.EntryGridSetRowDataListener;
export declare type FilterGridF7ClickEvent = $.kd.bos.form.control.events.FilterGridF7ClickEvent;
export declare const FilterGridF7ClickEvent: $.kd.bos.form.control.events.FilterGridF7ClickEvent_C;
export declare type FilterGridF7ClickListener = $.kd.bos.form.control.events.FilterGridF7ClickListener;
export declare const FilterGridF7ClickListener: $.kd.bos.form.control.events.FilterGridF7ClickListener;
export declare type FilterGridF7CloseCallBackEvent = $.kd.bos.form.control.events.FilterGridF7CloseCallBackEvent;
export declare const FilterGridF7CloseCallBackEvent: $.kd.bos.form.control.events.FilterGridF7CloseCallBackEvent_C;
export declare type FilterGridF7CloseCallBackListener = $.kd.bos.form.control.events.FilterGridF7CloseCallBackListener;
export declare const FilterGridF7CloseCallBackListener: $.kd.bos.form.control.events.FilterGridF7CloseCallBackListener;
export declare type FireFocusEvent = $.kd.bos.form.control.events.FireFocusEvent;
export declare const FireFocusEvent: $.kd.bos.form.control.events.FireFocusEvent_C;
export declare type HeaderCellClickEvent = $.kd.bos.form.control.events.HeaderCellClickEvent;
export declare const HeaderCellClickEvent: $.kd.bos.form.control.events.HeaderCellClickEvent_C;
export declare type HeaderCellClickListener = $.kd.bos.form.control.events.HeaderCellClickListener;
export declare const HeaderCellClickListener: $.kd.bos.form.control.events.HeaderCellClickListener;
export declare type ISuportClick = $.kd.bos.form.control.events.ISuportClick;
export declare const ISuportClick: $.kd.bos.form.control.events.ISuportClick;
export declare type InputFocusListener = $.kd.bos.form.control.events.InputFocusListener;
export declare const InputFocusListener: $.kd.bos.form.control.events.InputFocusListener;
export declare type ItemClickEvent = $.kd.bos.form.control.events.ItemClickEvent;
export declare const ItemClickEvent: $.kd.bos.form.control.events.ItemClickEvent_C;
export declare type ItemClickListener = $.kd.bos.form.control.events.ItemClickListener;
export declare const ItemClickListener: $.kd.bos.form.control.events.ItemClickListener;
export declare type ListboxClickListener = $.kd.bos.form.control.events.ListboxClickListener;
export declare const ListboxClickListener: $.kd.bos.form.control.events.ListboxClickListener;
export declare type MobileSearchCancelListener = $.kd.bos.form.control.events.MobileSearchCancelListener;
export declare const MobileSearchCancelListener: $.kd.bos.form.control.events.MobileSearchCancelListener;
export declare type MobileSearchFocusListener = $.kd.bos.form.control.events.MobileSearchFocusListener;
export declare const MobileSearchFocusListener: $.kd.bos.form.control.events.MobileSearchFocusListener;
export declare type MobileSearchTextChangeEvent = $.kd.bos.form.control.events.MobileSearchTextChangeEvent;
export declare const MobileSearchTextChangeEvent: $.kd.bos.form.control.events.MobileSearchTextChangeEvent_C;
export declare type MobileSearchTextChangeListener = $.kd.bos.form.control.events.MobileSearchTextChangeListener;
export declare const MobileSearchTextChangeListener: $.kd.bos.form.control.events.MobileSearchTextChangeListener;
export declare type OCREvent = $.kd.bos.form.control.events.OCREvent;
export declare const OCREvent: $.kd.bos.form.control.events.OCREvent_C;
export declare type OCRListener = $.kd.bos.form.control.events.OCRListener;
export declare const OCRListener: $.kd.bos.form.control.events.OCRListener;
export declare type ProgressEvent = $.kd.bos.form.control.events.ProgressEvent;
export declare const ProgressEvent: $.kd.bos.form.control.events.ProgressEvent_C;
export declare type ProgresssListener = $.kd.bos.form.control.events.ProgresssListener;
export declare const ProgresssListener: $.kd.bos.form.control.events.ProgresssListener;
export declare type PullRefreshEvent = $.kd.bos.form.control.events.PullRefreshEvent;
export declare const PullRefreshEvent: $.kd.bos.form.control.events.PullRefreshEvent_C;
export declare type PullRefreshListener = $.kd.bos.form.control.events.PullRefreshListener;
export declare const PullRefreshListener: $.kd.bos.form.control.events.PullRefreshListener;
export declare type RateEvent = $.kd.bos.form.control.events.RateEvent;
export declare const RateEvent: $.kd.bos.form.control.events.RateEvent_C;
export declare type RateListener = $.kd.bos.form.control.events.RateListener;
export declare const RateListener: $.kd.bos.form.control.events.RateListener;
export declare type RefreshNodeEvent = $.kd.bos.form.control.events.RefreshNodeEvent;
export declare const RefreshNodeEvent: $.kd.bos.form.control.events.RefreshNodeEvent_C;
export declare type ResponseEvent = $.kd.bos.form.control.events.ResponseEvent;
export declare const ResponseEvent: $.kd.bos.form.control.events.ResponseEvent_C;
export declare type ResponseListener = $.kd.bos.form.control.events.ResponseListener;
export declare const ResponseListener: $.kd.bos.form.control.events.ResponseListener;
export declare type RowClickEvent = $.kd.bos.form.control.events.RowClickEvent;
export declare const RowClickEvent: $.kd.bos.form.control.events.RowClickEvent_C;
export declare type RowClickEventListener = $.kd.bos.form.control.events.RowClickEventListener;
export declare const RowClickEventListener: $.kd.bos.form.control.events.RowClickEventListener;
export declare type SearchClickEvent = $.kd.bos.form.control.events.SearchClickEvent;
export declare const SearchClickEvent: $.kd.bos.form.control.events.SearchClickEvent_C;
export declare type SearchClickListener = $.kd.bos.form.control.events.SearchClickListener;
export declare const SearchClickListener: $.kd.bos.form.control.events.SearchClickListener;
export declare type SearchEnterEvent = $.kd.bos.form.control.events.SearchEnterEvent;
export declare const SearchEnterEvent: $.kd.bos.form.control.events.SearchEnterEvent_C;
export declare type SearchEnterListener = $.kd.bos.form.control.events.SearchEnterListener;
export declare const SearchEnterListener: $.kd.bos.form.control.events.SearchEnterListener;
export declare type SegmentedControlSelectEvent = $.kd.bos.form.control.events.SegmentedControlSelectEvent;
export declare const SegmentedControlSelectEvent: $.kd.bos.form.control.events.SegmentedControlSelectEvent_C;
export declare type SegmentedControlSelectListener = $.kd.bos.form.control.events.SegmentedControlSelectListener;
export declare const SegmentedControlSelectListener: $.kd.bos.form.control.events.SegmentedControlSelectListener;
export declare type SelectRowsEvent = $.kd.bos.form.control.events.SelectRowsEvent;
export declare const SelectRowsEvent: $.kd.bos.form.control.events.SelectRowsEvent_C;
export declare type SelectRowsEventListener = $.kd.bos.form.control.events.SelectRowsEventListener;
export declare const SelectRowsEventListener: $.kd.bos.form.control.events.SelectRowsEventListener;
export declare type SliderEvent = $.kd.bos.form.control.events.SliderEvent;
export declare const SliderEvent: $.kd.bos.form.control.events.SliderEvent_C;
export declare type SliderListener = $.kd.bos.form.control.events.SliderListener;
export declare const SliderListener: $.kd.bos.form.control.events.SliderListener;
export declare type StepEvent = $.kd.bos.form.control.events.StepEvent;
export declare const StepEvent: $.kd.bos.form.control.events.StepEvent_C;
export declare type TabBatchCloseEvent = $.kd.bos.form.control.events.TabBatchCloseEvent;
export declare const TabBatchCloseEvent: $.kd.bos.form.control.events.TabBatchCloseEvent_C;
export declare type TabBatchCloseListener = $.kd.bos.form.control.events.TabBatchCloseListener;
export declare const TabBatchCloseListener: $.kd.bos.form.control.events.TabBatchCloseListener;
export declare type TabCloseListener = $.kd.bos.form.control.events.TabCloseListener;
export declare const TabCloseListener: $.kd.bos.form.control.events.TabCloseListener;
export declare type TabOperationEvent = $.kd.bos.form.control.events.TabOperationEvent;
export declare const TabOperationEvent: $.kd.bos.form.control.events.TabOperationEvent_C;
export declare type TabOperationListener = $.kd.bos.form.control.events.TabOperationListener;
export declare const TabOperationListener: $.kd.bos.form.control.events.TabOperationListener;
export declare type TabSelectEvent = $.kd.bos.form.control.events.TabSelectEvent;
export declare const TabSelectEvent: $.kd.bos.form.control.events.TabSelectEvent_C;
export declare type TabSelectListener = $.kd.bos.form.control.events.TabSelectListener;
export declare const TabSelectListener: $.kd.bos.form.control.events.TabSelectListener;
export declare type TimelineEvent = $.kd.bos.form.control.events.TimelineEvent;
export declare const TimelineEvent: $.kd.bos.form.control.events.TimelineEvent_C;
export declare type TimelineListener = $.kd.bos.form.control.events.TimelineListener;
export declare const TimelineListener: $.kd.bos.form.control.events.TimelineListener;
export declare type TipsListener = $.kd.bos.form.control.events.TipsListener;
export declare const TipsListener: $.kd.bos.form.control.events.TipsListener;
export declare type TreeMenuAddNodesEvent = $.kd.bos.form.control.events.TreeMenuAddNodesEvent;
export declare const TreeMenuAddNodesEvent: $.kd.bos.form.control.events.TreeMenuAddNodesEvent_C;
export declare type TreeMenuClickListener = $.kd.bos.form.control.events.TreeMenuClickListener;
export declare const TreeMenuClickListener: $.kd.bos.form.control.events.TreeMenuClickListener;
export declare type TreeNodeCheckEvent = $.kd.bos.form.control.events.TreeNodeCheckEvent;
export declare const TreeNodeCheckEvent: $.kd.bos.form.control.events.TreeNodeCheckEvent_C;
export declare type TreeNodeCheckListener = $.kd.bos.form.control.events.TreeNodeCheckListener;
export declare const TreeNodeCheckListener: $.kd.bos.form.control.events.TreeNodeCheckListener;
export declare type TreeNodeClickListener = $.kd.bos.form.control.events.TreeNodeClickListener;
export declare const TreeNodeClickListener: $.kd.bos.form.control.events.TreeNodeClickListener;
export declare type TreeNodeDragEvent = $.kd.bos.form.control.events.TreeNodeDragEvent;
export declare const TreeNodeDragEvent: $.kd.bos.form.control.events.TreeNodeDragEvent_C;
export declare type TreeNodeDragListener = $.kd.bos.form.control.events.TreeNodeDragListener;
export declare const TreeNodeDragListener: $.kd.bos.form.control.events.TreeNodeDragListener;
export declare type TreeNodeEvent = $.kd.bos.form.control.events.TreeNodeEvent;
export declare const TreeNodeEvent: $.kd.bos.form.control.events.TreeNodeEvent_C;
export declare type TreeNodeQueryListener = $.kd.bos.form.control.events.TreeNodeQueryListener;
export declare const TreeNodeQueryListener: $.kd.bos.form.control.events.TreeNodeQueryListener;
export declare type TreeViewListener = $.kd.bos.form.control.events.TreeViewListener;
export declare const TreeViewListener: $.kd.bos.form.control.events.TreeViewListener;
export declare type WizardStepsListener = $.kd.bos.form.control.events.WizardStepsListener;
export declare const WizardStepsListener: $.kd.bos.form.control.events.WizardStepsListener;
export declare type BeforeUploadEvent = $.kd.bos.form.control.events.BeforeUploadEvent;
export declare const BeforeUploadEvent: $.kd.bos.form.control.events.BeforeUploadEvent_C;
export declare type UploadEvent = $.kd.bos.form.control.events.UploadEvent;
export declare const UploadEvent: $.kd.bos.form.control.events.UploadEvent_C;
export declare type UploadListener = $.kd.bos.form.control.events.UploadListener;
export declare const UploadListener: $.kd.bos.form.control.events.UploadListener;
export declare type AttachmentDownLoadEvent = $.kd.bos.form.control.events.AttachmentDownLoadEvent;
export declare const AttachmentDownLoadEvent: $.kd.bos.form.control.events.AttachmentDownLoadEvent_C;
export declare type AttachmentDownloadListener = $.kd.bos.form.control.events.AttachmentDownloadListener;
export declare const AttachmentDownloadListener: $.kd.bos.form.control.events.AttachmentDownloadListener;
export declare type UploadResultEvent = $.kd.bos.form.control.events.UploadResultEvent;
export declare const UploadResultEvent: $.kd.bos.form.control.events.UploadResultEvent_C;
