export declare type CandContrastPropLoadEvent = $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.CandContrastPropLoadEvent;
export declare const CandContrastPropLoadEvent: $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.CandContrastPropLoadEvent_C;
export declare type ContrastPropLoadEvent = $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.ContrastPropLoadEvent;
export declare const ContrastPropLoadEvent: $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.ContrastPropLoadEvent_C;
export declare type OnGetCustomerQFilterEvent = $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetCustomerQFilterEvent;
export declare const OnGetCustomerQFilterEvent: $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetCustomerQFilterEvent_C;
export declare type OnGetDefaultDisplayParamEvent = $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetDefaultDisplayParamEvent;
export declare const OnGetDefaultDisplayParamEvent: $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetDefaultDisplayParamEvent_C;
export declare type OnGetFieldColumnWidthEvent = $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetFieldColumnWidthEvent;
export declare const OnGetFieldColumnWidthEvent: $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetFieldColumnWidthEvent_C;
export declare type OnGetFieldLockStatusEvent = $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetFieldLockStatusEvent;
export declare const OnGetFieldLockStatusEvent: $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetFieldLockStatusEvent_C;
export declare type OnGetFieldParamEvent = $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetFieldParamEvent;
export declare const OnGetFieldParamEvent: $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetFieldParamEvent_C;
export declare type OnGetIntervalPropEvent = $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetIntervalPropEvent;
export declare const OnGetIntervalPropEvent: $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetIntervalPropEvent_C;
export declare type OnGetItemRankEvent = $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetItemRankEvent;
export declare const OnGetItemRankEvent: $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetItemRankEvent_C;
export declare type OnGetItemTipsEvent = $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetItemTipsEvent;
export declare const OnGetItemTipsEvent: $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetItemTipsEvent_C;
export declare type OnGetNumberConstraintEvent = $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetNumberConstraintEvent;
export declare const OnGetNumberConstraintEvent: $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetNumberConstraintEvent_C;
export declare type OnGetOnlySalaryCountEvent = $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetOnlySalaryCountEvent;
export declare const OnGetOnlySalaryCountEvent: $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetOnlySalaryCountEvent_C;
export declare type OnGetPreviewStyleEvent = $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetPreviewStyleEvent;
export declare const OnGetPreviewStyleEvent: $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetPreviewStyleEvent_C;
export declare type OnGetSpecialRankEvent = $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetSpecialRankEvent;
export declare const OnGetSpecialRankEvent: $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetSpecialRankEvent_C;
export declare type OnGetVarPredictItemEvent = $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetVarPredictItemEvent;
export declare const OnGetVarPredictItemEvent: $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.OnGetVarPredictItemEvent_C;
export declare type StdTableCalculateEvent = $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.StdTableCalculateEvent;
export declare const StdTableCalculateEvent: $.kd.sdk.swc.hcdm.business.extpoint.salarystd.event.StdTableCalculateEvent_C;
