export declare type AddFuzzySearchEvent = $.kd.bos.form.field.events.AddFuzzySearchEvent;
export declare const AddFuzzySearchEvent: $.kd.bos.form.field.events.AddFuzzySearchEvent_C;
export declare type AfterBindingDataEvent = $.kd.bos.form.field.events.AfterBindingDataEvent;
export declare const AfterBindingDataEvent: $.kd.bos.form.field.events.AfterBindingDataEvent_C;
export declare type AfterChangeMainOrgEventArgs = $.kd.bos.form.field.events.AfterChangeMainOrgEventArgs;
export declare const AfterChangeMainOrgEventArgs: $.kd.bos.form.field.events.AfterChangeMainOrgEventArgs_C;
export declare type AfterF7SelectEvent = $.kd.bos.form.field.events.AfterF7SelectEvent;
export declare const AfterF7SelectEvent: $.kd.bos.form.field.events.AfterF7SelectEvent_C;
export declare type AfterF7SelectListener = $.kd.bos.form.field.events.AfterF7SelectListener;
export declare const AfterF7SelectListener: $.kd.bos.form.field.events.AfterF7SelectListener;
export declare type BaseDataCustomControllerEvent = $.kd.bos.form.field.events.BaseDataCustomControllerEvent;
export declare const BaseDataCustomControllerEvent: $.kd.bos.form.field.events.BaseDataCustomControllerEvent_C;
export declare type BasedataControllerSourceEnum = $.kd.bos.form.field.events.BasedataControllerSourceEnum;
export declare const BasedataControllerSourceEnum: typeof $.kd.bos.form.field.events.BasedataControllerSourceEnum;
export declare type BasedataEditListener = $.kd.bos.form.field.events.BasedataEditListener;
export declare const BasedataEditListener: $.kd.bos.form.field.events.BasedataEditListener;
export declare type BasedataFuzzySearchEvent = $.kd.bos.form.field.events.BasedataFuzzySearchEvent;
export declare const BasedataFuzzySearchEvent: $.kd.bos.form.field.events.BasedataFuzzySearchEvent_C;
export declare type BasedataFuzzySearchListener = $.kd.bos.form.field.events.BasedataFuzzySearchListener;
export declare const BasedataFuzzySearchListener: $.kd.bos.form.field.events.BasedataFuzzySearchListener;
export declare type BeforeBasedataSetValueListener = $.kd.bos.form.field.events.BeforeBasedataSetValueListener;
export declare const BeforeBasedataSetValueListener: $.kd.bos.form.field.events.BeforeBasedataSetValueListener;
export declare type BeforeChangeMainOrgEventArgs = $.kd.bos.form.field.events.BeforeChangeMainOrgEventArgs;
export declare const BeforeChangeMainOrgEventArgs: $.kd.bos.form.field.events.BeforeChangeMainOrgEventArgs_C;
export declare type BeforeF7SelectEvent = $.kd.bos.form.field.events.BeforeF7SelectEvent;
export declare const BeforeF7SelectEvent: $.kd.bos.form.field.events.BeforeF7SelectEvent_C;
export declare type BeforeF7SelectListener = $.kd.bos.form.field.events.BeforeF7SelectListener;
export declare const BeforeF7SelectListener: $.kd.bos.form.field.events.BeforeF7SelectListener;
export declare type BeforeF7ViewDetailEvent = $.kd.bos.form.field.events.BeforeF7ViewDetailEvent;
export declare const BeforeF7ViewDetailEvent: $.kd.bos.form.field.events.BeforeF7ViewDetailEvent_C;
export declare type BeforeFilterF7SelectEvent = $.kd.bos.form.field.events.BeforeFilterF7SelectEvent;
export declare const BeforeFilterF7SelectEvent: $.kd.bos.form.field.events.BeforeFilterF7SelectEvent_C;
export declare type BeforeFilterF7SelectListener = $.kd.bos.form.field.events.BeforeFilterF7SelectListener;
export declare const BeforeFilterF7SelectListener: $.kd.bos.form.field.events.BeforeFilterF7SelectListener;
export declare type BeforeQuickAddNewEvent = $.kd.bos.form.field.events.BeforeQuickAddNewEvent;
export declare const BeforeQuickAddNewEvent: $.kd.bos.form.field.events.BeforeQuickAddNewEvent_C;
export declare type BeforeQuickAddNewListener = $.kd.bos.form.field.events.BeforeQuickAddNewListener;
export declare const BeforeQuickAddNewListener: $.kd.bos.form.field.events.BeforeQuickAddNewListener;
export declare type CellTipsClickEvent = $.kd.bos.form.field.events.CellTipsClickEvent;
export declare const CellTipsClickEvent: $.kd.bos.form.field.events.CellTipsClickEvent_C;
export declare type CellTipsClickListener = $.kd.bos.form.field.events.CellTipsClickListener;
export declare const CellTipsClickListener: $.kd.bos.form.field.events.CellTipsClickListener;
export declare type DateClickListener = $.kd.bos.form.field.events.DateClickListener;
export declare const DateClickListener: $.kd.bos.form.field.events.DateClickListener;
export declare type FlexControlMetaPreRenderListener = $.kd.bos.form.field.events.FlexControlMetaPreRenderListener;
export declare const FlexControlMetaPreRenderListener: $.kd.bos.form.field.events.FlexControlMetaPreRenderListener;
export declare type ListExpandEvent = $.kd.bos.form.field.events.ListExpandEvent;
export declare const ListExpandEvent: $.kd.bos.form.field.events.ListExpandEvent_C;
export declare type ListExpandListener = $.kd.bos.form.field.events.ListExpandListener;
export declare const ListExpandListener: $.kd.bos.form.field.events.ListExpandListener;
export declare type MainOrgChangeListener = $.kd.bos.form.field.events.MainOrgChangeListener;
export declare const MainOrgChangeListener: $.kd.bos.form.field.events.MainOrgChangeListener;
export declare type ResetDateFilterEvent = $.kd.bos.form.field.events.ResetDateFilterEvent;
export declare const ResetDateFilterEvent: $.kd.bos.form.field.events.ResetDateFilterEvent_C;
export declare type ShowFlexEditEvent = $.kd.bos.form.field.events.ShowFlexEditEvent;
export declare const ShowFlexEditEvent: $.kd.bos.form.field.events.ShowFlexEditEvent_C;
export declare type ShowFlexEditListener = $.kd.bos.form.field.events.ShowFlexEditListener;
export declare const ShowFlexEditListener: $.kd.bos.form.field.events.ShowFlexEditListener;
