export declare type AdminGroupReq = $.kd.bos.permission.model.perm.req.AdminGroupReq;
export declare const AdminGroupReq: $.kd.bos.permission.model.perm.req.AdminGroupReq_C;
export declare type CheckPermissionReq = $.kd.bos.permission.model.perm.req.CheckPermissionReq;
export declare const CheckPermissionReq: $.kd.bos.permission.model.perm.req.CheckPermissionReq_C;
export declare type DimFuncPermReq = $.kd.bos.permission.model.perm.req.DimFuncPermReq;
export declare const DimFuncPermReq: $.kd.bos.permission.model.perm.req.DimFuncPermReq_C;
export declare type DimRoleReq = $.kd.bos.permission.model.perm.req.DimRoleReq;
export declare const DimRoleReq: $.kd.bos.permission.model.perm.req.DimRoleReq_C;
export declare type GetPermLevelHashReq = $.kd.bos.permission.model.perm.req.GetPermLevelHashReq;
export declare const GetPermLevelHashReq: $.kd.bos.permission.model.perm.req.GetPermLevelHashReq_C;
export declare type PermLogReq = $.kd.bos.permission.model.perm.req.PermLogReq;
export declare const PermLogReq: $.kd.bos.permission.model.perm.req.PermLogReq_C;
export declare type RoleAssignUserDimReq = $.kd.bos.permission.model.perm.req.RoleAssignUserDimReq;
export declare const RoleAssignUserDimReq: $.kd.bos.permission.model.perm.req.RoleAssignUserDimReq_C;
export declare type UserAssignDimRoleReq = $.kd.bos.permission.model.perm.req.UserAssignDimRoleReq;
export declare const UserAssignDimRoleReq: $.kd.bos.permission.model.perm.req.UserAssignDimRoleReq_C;
export declare type UserAssignUserGroupReq = $.kd.bos.permission.model.perm.req.UserAssignUserGroupReq;
export declare const UserAssignUserGroupReq: $.kd.bos.permission.model.perm.req.UserAssignUserGroupReq_C;
export declare type UserDimReq = $.kd.bos.permission.model.perm.req.UserDimReq;
export declare const UserDimReq: $.kd.bos.permission.model.perm.req.UserDimReq_C;
export declare type UserGroupAssignUserReq = $.kd.bos.permission.model.perm.req.UserGroupAssignUserReq;
export declare const UserGroupAssignUserReq: $.kd.bos.permission.model.perm.req.UserGroupAssignUserReq_C;
