export declare type PermUser = $.kd.bos.permission.model.perm.user.PermUser;
export declare const PermUser: $.kd.bos.permission.model.perm.user.PermUser_C;
export declare type UserDrDim = $.kd.bos.permission.model.perm.user.UserDrDim;
export declare const UserDrDim: $.kd.bos.permission.model.perm.user.UserDrDim_C;
export declare type UserDrPrDim = $.kd.bos.permission.model.perm.user.UserDrPrDim;
export declare const UserDrPrDim: $.kd.bos.permission.model.perm.user.UserDrPrDim_C;
export declare type UserFieldPermDim = $.kd.bos.permission.model.perm.user.UserFieldPermDim;
export declare const UserFieldPermDim: $.kd.bos.permission.model.perm.user.UserFieldPermDim_C;
export declare type UserFuncDim = $.kd.bos.permission.model.perm.user.UserFuncDim;
export declare const UserFuncDim: $.kd.bos.permission.model.perm.user.UserFuncDim_C;
