/// <reference types="../../index" />
export declare type DragGestureEvent = $.java.awt.dnd.DragGestureEvent;
export declare const DragGestureEvent: $.java.awt.dnd.DragGestureEvent_C;
export declare type DragGestureListener = $.java.awt.dnd.DragGestureListener;
export declare const DragGestureListener: $.java.awt.dnd.DragGestureListener;
export declare type DragGestureRecognizer = $.java.awt.dnd.DragGestureRecognizer;
export declare const DragGestureRecognizer: $.java.awt.dnd.DragGestureRecognizer_C;
export declare type DragSource = $.java.awt.dnd.DragSource;
export declare const DragSource: $.java.awt.dnd.DragSource_C;
export declare type DragSourceContext = $.java.awt.dnd.DragSourceContext;
export declare const DragSourceContext: $.java.awt.dnd.DragSourceContext_C;
export declare type DragSourceDragEvent = $.java.awt.dnd.DragSourceDragEvent;
export declare const DragSourceDragEvent: $.java.awt.dnd.DragSourceDragEvent_C;
export declare type DragSourceDropEvent = $.java.awt.dnd.DragSourceDropEvent;
export declare const DragSourceDropEvent: $.java.awt.dnd.DragSourceDropEvent_C;
export declare type DragSourceEvent = $.java.awt.dnd.DragSourceEvent;
export declare const DragSourceEvent: $.java.awt.dnd.DragSourceEvent_C;
export declare type DragSourceListener = $.java.awt.dnd.DragSourceListener;
export declare const DragSourceListener: $.java.awt.dnd.DragSourceListener;
export declare type DragSourceMotionListener = $.java.awt.dnd.DragSourceMotionListener;
export declare const DragSourceMotionListener: $.java.awt.dnd.DragSourceMotionListener;
export declare type DropTarget = $.java.awt.dnd.DropTarget;
export declare const DropTarget: $.java.awt.dnd.DropTarget_C;
export declare type DropTargetContext = $.java.awt.dnd.DropTargetContext;
export declare const DropTargetContext: $.java.awt.dnd.DropTargetContext_C;
export declare type DropTargetDragEvent = $.java.awt.dnd.DropTargetDragEvent;
export declare const DropTargetDragEvent: $.java.awt.dnd.DropTargetDragEvent_C;
export declare type DropTargetDropEvent = $.java.awt.dnd.DropTargetDropEvent;
export declare const DropTargetDropEvent: $.java.awt.dnd.DropTargetDropEvent_C;
export declare type DropTargetEvent = $.java.awt.dnd.DropTargetEvent;
export declare const DropTargetEvent: $.java.awt.dnd.DropTargetEvent_C;
export declare type DropTargetListener = $.java.awt.dnd.DropTargetListener;
export declare const DropTargetListener: $.java.awt.dnd.DropTargetListener;
