/// <reference types="../../index" />
export declare type AWTEventListener = $.java.awt.event.AWTEventListener;
export declare const AWTEventListener: $.java.awt.event.AWTEventListener;
export declare type ActionEvent = $.java.awt.event.ActionEvent;
export declare const ActionEvent: $.java.awt.event.ActionEvent_C;
export declare type ActionListener = $.java.awt.event.ActionListener;
export declare const ActionListener: $.java.awt.event.ActionListener;
export declare type ComponentEvent = $.java.awt.event.ComponentEvent;
export declare const ComponentEvent: $.java.awt.event.ComponentEvent_C;
export declare type ComponentListener = $.java.awt.event.ComponentListener;
export declare const ComponentListener: $.java.awt.event.ComponentListener;
export declare type ContainerEvent = $.java.awt.event.ContainerEvent;
export declare const ContainerEvent: $.java.awt.event.ContainerEvent_C;
export declare type ContainerListener = $.java.awt.event.ContainerListener;
export declare const ContainerListener: $.java.awt.event.ContainerListener;
export declare type FocusEvent = $.java.awt.event.FocusEvent;
export declare const FocusEvent: $.java.awt.event.FocusEvent_C;
export declare type FocusListener = $.java.awt.event.FocusListener;
export declare const FocusListener: $.java.awt.event.FocusListener;
export declare type HierarchyBoundsListener = $.java.awt.event.HierarchyBoundsListener;
export declare const HierarchyBoundsListener: $.java.awt.event.HierarchyBoundsListener;
export declare type HierarchyEvent = $.java.awt.event.HierarchyEvent;
export declare const HierarchyEvent: $.java.awt.event.HierarchyEvent_C;
export declare type HierarchyListener = $.java.awt.event.HierarchyListener;
export declare const HierarchyListener: $.java.awt.event.HierarchyListener;
export declare type InputEvent = $.java.awt.event.InputEvent;
export declare const InputEvent: $.java.awt.event.InputEvent_C;
export declare type InputMethodEvent = $.java.awt.event.InputMethodEvent;
export declare const InputMethodEvent: $.java.awt.event.InputMethodEvent_C;
export declare type InputMethodListener = $.java.awt.event.InputMethodListener;
export declare const InputMethodListener: $.java.awt.event.InputMethodListener;
export declare type KeyEvent = $.java.awt.event.KeyEvent;
export declare const KeyEvent: $.java.awt.event.KeyEvent_C;
export declare type KeyListener = $.java.awt.event.KeyListener;
export declare const KeyListener: $.java.awt.event.KeyListener;
export declare type MouseEvent = $.java.awt.event.MouseEvent;
export declare const MouseEvent: $.java.awt.event.MouseEvent_C;
export declare type MouseListener = $.java.awt.event.MouseListener;
export declare const MouseListener: $.java.awt.event.MouseListener;
export declare type MouseMotionListener = $.java.awt.event.MouseMotionListener;
export declare const MouseMotionListener: $.java.awt.event.MouseMotionListener;
export declare type MouseWheelEvent = $.java.awt.event.MouseWheelEvent;
export declare const MouseWheelEvent: $.java.awt.event.MouseWheelEvent_C;
export declare type MouseWheelListener = $.java.awt.event.MouseWheelListener;
export declare const MouseWheelListener: $.java.awt.event.MouseWheelListener;
export declare type PaintEvent = $.java.awt.event.PaintEvent;
export declare const PaintEvent: $.java.awt.event.PaintEvent_C;
export declare type WindowEvent = $.java.awt.event.WindowEvent;
export declare const WindowEvent: $.java.awt.event.WindowEvent_C;
export declare type WindowFocusListener = $.java.awt.event.WindowFocusListener;
export declare const WindowFocusListener: $.java.awt.event.WindowFocusListener;
export declare type WindowListener = $.java.awt.event.WindowListener;
export declare const WindowListener: $.java.awt.event.WindowListener;
export declare type WindowStateListener = $.java.awt.event.WindowStateListener;
export declare const WindowStateListener: $.java.awt.event.WindowStateListener;
