/// <reference types="../../index" />
export declare type BufferStrategy = $.java.awt.image.BufferStrategy;
export declare const BufferStrategy: $.java.awt.image.BufferStrategy_C;
export declare type BufferedImage = $.java.awt.image.BufferedImage;
export declare const BufferedImage: $.java.awt.image.BufferedImage_C;
export declare type BufferedImageOp = $.java.awt.image.BufferedImageOp;
export declare const BufferedImageOp: $.java.awt.image.BufferedImageOp;
export declare type ColorModel = $.java.awt.image.ColorModel;
export declare const ColorModel: $.java.awt.image.ColorModel_C;
export declare type DataBuffer = $.java.awt.image.DataBuffer;
export declare const DataBuffer: $.java.awt.image.DataBuffer_C;
export declare type ImageConsumer = $.java.awt.image.ImageConsumer;
export declare const ImageConsumer: $.java.awt.image.ImageConsumer;
export declare type ImageObserver = $.java.awt.image.ImageObserver;
export declare const ImageObserver: $.java.awt.image.ImageObserver;
export declare type ImageProducer = $.java.awt.image.ImageProducer;
export declare const ImageProducer: $.java.awt.image.ImageProducer;
export declare type IndexColorModel = $.java.awt.image.IndexColorModel;
export declare const IndexColorModel: $.java.awt.image.IndexColorModel_C;
export declare type Raster = $.java.awt.image.Raster;
export declare const Raster: $.java.awt.image.Raster_C;
export declare type RenderedImage = $.java.awt.image.RenderedImage;
export declare const RenderedImage: $.java.awt.image.RenderedImage;
export declare type SampleModel = $.java.awt.image.SampleModel;
export declare const SampleModel: $.java.awt.image.SampleModel_C;
export declare type TileObserver = $.java.awt.image.TileObserver;
export declare const TileObserver: $.java.awt.image.TileObserver;
export declare type VolatileImage = $.java.awt.image.VolatileImage;
export declare const VolatileImage: $.java.awt.image.VolatileImage_C;
export declare type WritableRaster = $.java.awt.image.WritableRaster;
export declare const WritableRaster: $.java.awt.image.WritableRaster_C;
export declare type WritableRenderedImage = $.java.awt.image.WritableRenderedImage;
export declare const WritableRenderedImage: $.java.awt.image.WritableRenderedImage;
