export declare type WFAuditTask = $.kd.bos.workflow.engine.dynprocess.freeflow.WFAuditTask;
export declare const WFAuditTask: $.kd.bos.workflow.engine.dynprocess.freeflow.WFAuditTask_C;
export declare type WFAutoTask = $.kd.bos.workflow.engine.dynprocess.freeflow.WFAutoTask;
export declare const WFAutoTask: $.kd.bos.workflow.engine.dynprocess.freeflow.WFAutoTask_C;
export declare type WFAutoTaskExtItf = $.kd.bos.workflow.engine.dynprocess.freeflow.WFAutoTaskExtItf;
export declare const WFAutoTaskExtItf: $.kd.bos.workflow.engine.dynprocess.freeflow.WFAutoTaskExtItf_C;
export declare type WFBillSetting = $.kd.bos.workflow.engine.dynprocess.freeflow.WFBillSetting;
export declare const WFBillSetting: $.kd.bos.workflow.engine.dynprocess.freeflow.WFBillSetting_C;
export declare type WFCustomParam = $.kd.bos.workflow.engine.dynprocess.freeflow.WFCustomParam;
export declare const WFCustomParam: $.kd.bos.workflow.engine.dynprocess.freeflow.WFCustomParam_C;
export declare type WFDecisionOption = $.kd.bos.workflow.engine.dynprocess.freeflow.WFDecisionOption;
export declare const WFDecisionOption: $.kd.bos.workflow.engine.dynprocess.freeflow.WFDecisionOption_C;
export declare type WFFlowElement = $.kd.bos.workflow.engine.dynprocess.freeflow.WFFlowElement;
export declare const WFFlowElement: $.kd.bos.workflow.engine.dynprocess.freeflow.WFFlowElement_C;
export declare type WFFlowNode = $.kd.bos.workflow.engine.dynprocess.freeflow.WFFlowNode;
export declare const WFFlowNode: $.kd.bos.workflow.engine.dynprocess.freeflow.WFFlowNode_C;
export declare type WFJointAuditTask = $.kd.bos.workflow.engine.dynprocess.freeflow.WFJointAuditTask;
export declare const WFJointAuditTask: $.kd.bos.workflow.engine.dynprocess.freeflow.WFJointAuditTask_C;
export declare type WFParticipantEntity = $.kd.bos.workflow.engine.dynprocess.freeflow.WFParticipantEntity;
export declare const WFParticipantEntity: $.kd.bos.workflow.engine.dynprocess.freeflow.WFParticipantEntity_C;
export declare type WFParticipantModel = $.kd.bos.workflow.engine.dynprocess.freeflow.WFParticipantModel;
export declare const WFParticipantModel: $.kd.bos.workflow.engine.dynprocess.freeflow.WFParticipantModel_C;
export declare type WFProcess = $.kd.bos.workflow.engine.dynprocess.freeflow.WFProcess;
export declare const WFProcess: $.kd.bos.workflow.engine.dynprocess.freeflow.WFProcess_C;
export declare type WFRejectNodesModel = $.kd.bos.workflow.engine.dynprocess.freeflow.WFRejectNodesModel;
export declare const WFRejectNodesModel: $.kd.bos.workflow.engine.dynprocess.freeflow.WFRejectNodesModel_C;
export declare type WFUserTask = $.kd.bos.workflow.engine.dynprocess.freeflow.WFUserTask;
export declare const WFUserTask: $.kd.bos.workflow.engine.dynprocess.freeflow.WFUserTask_C;
