export declare type Distinctable = $.kd.bos.orm.query.Distinctable;
export declare const Distinctable: $.kd.bos.orm.query.Distinctable;
export declare type EntityNotExistsException = $.kd.bos.orm.query.EntityNotExistsException;
export declare const EntityNotExistsException: $.kd.bos.orm.query.EntityNotExistsException_C;
export declare type NoSuchPropertyException = $.kd.bos.orm.query.NoSuchPropertyException;
export declare const NoSuchPropertyException: $.kd.bos.orm.query.NoSuchPropertyException_C;
export declare type ORMException = $.kd.bos.orm.query.ORMException;
export declare const ORMException: $.kd.bos.orm.query.ORMException_C;
export declare type QCP = $.kd.bos.orm.query.QCP;
export declare const QCP: $.kd.bos.orm.query.QCP;
export declare type QFilter = $.kd.bos.orm.query.QFilter;
export declare const QFilter: $.kd.bos.orm.query.QFilter_C;
export declare type QFilter$QFilterNest = $.kd.bos.orm.query.QFilter$QFilterNest;
export declare const QFilter$QFilterNest: $.kd.bos.orm.query.QFilter$QFilterNest_C;
export declare type QFilterEvaluator = $.kd.bos.orm.query.QFilterEvaluator;
export declare const QFilterEvaluator: $.kd.bos.orm.query.QFilterEvaluator;
export declare type QFilterHint = $.kd.bos.orm.query.QFilterHint;
export declare const QFilterHint: $.kd.bos.orm.query.QFilterHint;
export declare type WithEntityEntryDistinctable = $.kd.bos.orm.query.WithEntityEntryDistinctable;
export declare const WithEntityEntryDistinctable: $.kd.bos.orm.query.WithEntityEntryDistinctable_C;
