export declare type CopyEntryRow = $.kd.bos.form.operate.formop.CopyEntryRow;
export declare const CopyEntryRow: $.kd.bos.form.operate.formop.CopyEntryRow_C;
export declare type DeleteEntry = $.kd.bos.form.operate.formop.DeleteEntry;
export declare const DeleteEntry: $.kd.bos.form.operate.formop.DeleteEntry_C;
export declare type NewEntry = $.kd.bos.form.operate.formop.NewEntry;
export declare const NewEntry: $.kd.bos.form.operate.formop.NewEntry_C;
export declare type OpenForm = $.kd.bos.form.operate.formop.OpenForm;
export declare const OpenForm: $.kd.bos.form.operate.formop.OpenForm_C;
export declare type Refresh = $.kd.bos.form.operate.formop.Refresh;
export declare const Refresh: $.kd.bos.form.operate.formop.Refresh_C;
