/// <reference types="../../index" />
export declare type BiConsumer = $.java.util.function_.BiConsumer;
export declare const BiConsumer: $.java.util.function_.BiConsumer;
export declare type BiFunction = $.java.util.function_.BiFunction;
export declare const BiFunction: $.java.util.function_.BiFunction;
export declare type BinaryOperator = $.java.util.function_.BinaryOperator;
export declare const BinaryOperator: $.java.util.function_.BinaryOperator;
export declare type Consumer = $.java.util.function_.Consumer;
export declare const Consumer: $.java.util.function_.Consumer;
export declare type DoubleBinaryOperator = $.java.util.function_.DoubleBinaryOperator;
export declare const DoubleBinaryOperator: $.java.util.function_.DoubleBinaryOperator;
export declare type DoubleConsumer = $.java.util.function_.DoubleConsumer;
export declare const DoubleConsumer: $.java.util.function_.DoubleConsumer;
export declare type DoubleFunction = $.java.util.function_.DoubleFunction;
export declare const DoubleFunction: $.java.util.function_.DoubleFunction;
export declare type DoublePredicate = $.java.util.function_.DoublePredicate;
export declare const DoublePredicate: $.java.util.function_.DoublePredicate;
export declare type DoubleSupplier = $.java.util.function_.DoubleSupplier;
export declare const DoubleSupplier: $.java.util.function_.DoubleSupplier;
export declare type DoubleToIntFunction = $.java.util.function_.DoubleToIntFunction;
export declare const DoubleToIntFunction: $.java.util.function_.DoubleToIntFunction;
export declare type DoubleToLongFunction = $.java.util.function_.DoubleToLongFunction;
export declare const DoubleToLongFunction: $.java.util.function_.DoubleToLongFunction;
export declare type DoubleUnaryOperator = $.java.util.function_.DoubleUnaryOperator;
export declare const DoubleUnaryOperator: $.java.util.function_.DoubleUnaryOperator;
export declare type Function = $.java.util.function_.Function;
export declare const Function: $.java.util.function_.Function;
export declare type IntBinaryOperator = $.java.util.function_.IntBinaryOperator;
export declare const IntBinaryOperator: $.java.util.function_.IntBinaryOperator;
export declare type IntConsumer = $.java.util.function_.IntConsumer;
export declare const IntConsumer: $.java.util.function_.IntConsumer;
export declare type IntFunction = $.java.util.function_.IntFunction;
export declare const IntFunction: $.java.util.function_.IntFunction;
export declare type IntPredicate = $.java.util.function_.IntPredicate;
export declare const IntPredicate: $.java.util.function_.IntPredicate;
export declare type IntSupplier = $.java.util.function_.IntSupplier;
export declare const IntSupplier: $.java.util.function_.IntSupplier;
export declare type IntToDoubleFunction = $.java.util.function_.IntToDoubleFunction;
export declare const IntToDoubleFunction: $.java.util.function_.IntToDoubleFunction;
export declare type IntToLongFunction = $.java.util.function_.IntToLongFunction;
export declare const IntToLongFunction: $.java.util.function_.IntToLongFunction;
export declare type IntUnaryOperator = $.java.util.function_.IntUnaryOperator;
export declare const IntUnaryOperator: $.java.util.function_.IntUnaryOperator;
export declare type LongBinaryOperator = $.java.util.function_.LongBinaryOperator;
export declare const LongBinaryOperator: $.java.util.function_.LongBinaryOperator;
export declare type LongConsumer = $.java.util.function_.LongConsumer;
export declare const LongConsumer: $.java.util.function_.LongConsumer;
export declare type LongFunction = $.java.util.function_.LongFunction;
export declare const LongFunction: $.java.util.function_.LongFunction;
export declare type LongPredicate = $.java.util.function_.LongPredicate;
export declare const LongPredicate: $.java.util.function_.LongPredicate;
export declare type LongSupplier = $.java.util.function_.LongSupplier;
export declare const LongSupplier: $.java.util.function_.LongSupplier;
export declare type LongToDoubleFunction = $.java.util.function_.LongToDoubleFunction;
export declare const LongToDoubleFunction: $.java.util.function_.LongToDoubleFunction;
export declare type LongToIntFunction = $.java.util.function_.LongToIntFunction;
export declare const LongToIntFunction: $.java.util.function_.LongToIntFunction;
export declare type LongUnaryOperator = $.java.util.function_.LongUnaryOperator;
export declare const LongUnaryOperator: $.java.util.function_.LongUnaryOperator;
export declare type ObjDoubleConsumer = $.java.util.function_.ObjDoubleConsumer;
export declare const ObjDoubleConsumer: $.java.util.function_.ObjDoubleConsumer;
export declare type ObjIntConsumer = $.java.util.function_.ObjIntConsumer;
export declare const ObjIntConsumer: $.java.util.function_.ObjIntConsumer;
export declare type ObjLongConsumer = $.java.util.function_.ObjLongConsumer;
export declare const ObjLongConsumer: $.java.util.function_.ObjLongConsumer;
export declare type Predicate = $.java.util.function_.Predicate;
export declare const Predicate: $.java.util.function_.Predicate;
export declare type Supplier = $.java.util.function_.Supplier;
export declare const Supplier: $.java.util.function_.Supplier;
export declare type ToDoubleBiFunction = $.java.util.function_.ToDoubleBiFunction;
export declare const ToDoubleBiFunction: $.java.util.function_.ToDoubleBiFunction;
export declare type ToDoubleFunction = $.java.util.function_.ToDoubleFunction;
export declare const ToDoubleFunction: $.java.util.function_.ToDoubleFunction;
export declare type ToIntBiFunction = $.java.util.function_.ToIntBiFunction;
export declare const ToIntBiFunction: $.java.util.function_.ToIntBiFunction;
export declare type ToIntFunction = $.java.util.function_.ToIntFunction;
export declare const ToIntFunction: $.java.util.function_.ToIntFunction;
export declare type ToLongBiFunction = $.java.util.function_.ToLongBiFunction;
export declare const ToLongBiFunction: $.java.util.function_.ToLongBiFunction;
export declare type ToLongFunction = $.java.util.function_.ToLongFunction;
export declare const ToLongFunction: $.java.util.function_.ToLongFunction;
export declare type UnaryOperator = $.java.util.function_.UnaryOperator;
export declare const UnaryOperator: $.java.util.function_.UnaryOperator;
