export declare type AbstractMetadataReader = $.kd.bos.metadata.dao.AbstractMetadataReader;
export declare const AbstractMetadataReader: $.kd.bos.metadata.dao.AbstractMetadataReader_C;
export declare type AbstractMetadataWriter = $.kd.bos.metadata.dao.AbstractMetadataWriter;
export declare const AbstractMetadataWriter: $.kd.bos.metadata.dao.AbstractMetadataWriter_C;
export declare type EntityMetadataUtil = $.kd.bos.metadata.dao.EntityMetadataUtil;
export declare const EntityMetadataUtil: $.kd.bos.metadata.dao.EntityMetadataUtil_C;
export declare type IMetadataDaoPlugIn = $.kd.bos.metadata.dao.IMetadataDaoPlugIn;
export declare const IMetadataDaoPlugIn: $.kd.bos.metadata.dao.IMetadataDaoPlugIn;
export declare type MetaCacheUtils = $.kd.bos.metadata.dao.MetaCacheUtils;
export declare const MetaCacheUtils: $.kd.bos.metadata.dao.MetaCacheUtils_C;
export declare type MetaCategory = $.kd.bos.metadata.dao.MetaCategory;
export declare const MetaCategory: typeof $.kd.bos.metadata.dao.MetaCategory;
export declare type MetaLogType = $.kd.bos.metadata.dao.MetaLogType;
export declare const MetaLogType: typeof $.kd.bos.metadata.dao.MetaLogType;
export declare type MetaType = $.kd.bos.metadata.dao.MetaType;
export declare const MetaType: typeof $.kd.bos.metadata.dao.MetaType;
export declare type MetadataDao = $.kd.bos.metadata.dao.MetadataDao;
export declare const MetadataDao: $.kd.bos.metadata.dao.MetadataDao_C;
export declare type MetadataExtends = $.kd.bos.metadata.dao.MetadataExtends;
export declare const MetadataExtends: $.kd.bos.metadata.dao.MetadataExtends_C;
export declare type MetadataReader = $.kd.bos.metadata.dao.MetadataReader;
export declare const MetadataReader: $.kd.bos.metadata.dao.MetadataReader_C;
export declare type MetadataWriter = $.kd.bos.metadata.dao.MetadataWriter;
export declare const MetadataWriter: $.kd.bos.metadata.dao.MetadataWriter_C;
