export declare type BaseEntity = $.kd.bos.metadata.entity.BaseEntity;
export declare const BaseEntity: $.kd.bos.metadata.entity.BaseEntity_C;
export declare type BillEntity = $.kd.bos.metadata.entity.BillEntity;
export declare const BillEntity: $.kd.bos.metadata.entity.BillEntity_C;
export declare type BusinessControl = $.kd.bos.metadata.entity.BusinessControl;
export declare const BusinessControl: $.kd.bos.metadata.entity.BusinessControl_C;
export declare type Entity = $.kd.bos.metadata.entity.Entity;
export declare const Entity: $.kd.bos.metadata.entity.Entity_C;
export declare type EntityItem = $.kd.bos.metadata.entity.EntityItem;
export declare const EntityItem: $.kd.bos.metadata.entity.EntityItem_C;
export declare type EntityMetadata = $.kd.bos.metadata.entity.EntityMetadata;
export declare const EntityMetadata: $.kd.bos.metadata.entity.EntityMetadata_C;
export declare type EntryEntity = $.kd.bos.metadata.entity.EntryEntity;
export declare const EntryEntity: $.kd.bos.metadata.entity.EntryEntity_C;
export declare type IChildElement = $.kd.bos.metadata.entity.IChildElement;
export declare const IChildElement: $.kd.bos.metadata.entity.IChildElement;
export declare type ITreeEntryEntity = $.kd.bos.metadata.entity.ITreeEntryEntity;
export declare const ITreeEntryEntity: $.kd.bos.metadata.entity.ITreeEntryEntity;
export declare type JsonSubEntryEntity = $.kd.bos.metadata.entity.JsonSubEntryEntity;
export declare const JsonSubEntryEntity: $.kd.bos.metadata.entity.JsonSubEntryEntity_C;
export declare type LinkEntryEntity = $.kd.bos.metadata.entity.LinkEntryEntity;
export declare const LinkEntryEntity: $.kd.bos.metadata.entity.LinkEntryEntity_C;
export declare type LinkSet = $.kd.bos.metadata.entity.LinkSet;
export declare const LinkSet: $.kd.bos.metadata.entity.LinkSet_C;
export declare type LinkSetItem = $.kd.bos.metadata.entity.LinkSetItem;
export declare const LinkSetItem: $.kd.bos.metadata.entity.LinkSetItem_C;
export declare type LogBillEntity = $.kd.bos.metadata.entity.LogBillEntity;
export declare const LogBillEntity: $.kd.bos.metadata.entity.LogBillEntity_C;
export declare type MainEntity = $.kd.bos.metadata.entity.MainEntity;
export declare const MainEntity: $.kd.bos.metadata.entity.MainEntity_C;
export declare type NameVersionEntryEntity = $.kd.bos.metadata.entity.NameVersionEntryEntity;
export declare const NameVersionEntryEntity: $.kd.bos.metadata.entity.NameVersionEntryEntity_C;
export declare type QueryEntity = $.kd.bos.metadata.entity.QueryEntity;
export declare const QueryEntity: $.kd.bos.metadata.entity.QueryEntity_C;
export declare type SplitTable = $.kd.bos.metadata.entity.SplitTable;
export declare const SplitTable: $.kd.bos.metadata.entity.SplitTable_C;
export declare type SubEntryEntity = $.kd.bos.metadata.entity.SubEntryEntity;
export declare const SubEntryEntity: $.kd.bos.metadata.entity.SubEntryEntity_C;
export declare type TreeEntryEntity = $.kd.bos.metadata.entity.TreeEntryEntity;
export declare const TreeEntryEntity: $.kd.bos.metadata.entity.TreeEntryEntity_C;
export declare type TreeSubEntryEntity = $.kd.bos.metadata.entity.TreeSubEntryEntity;
export declare const TreeSubEntryEntity: $.kd.bos.metadata.entity.TreeSubEntryEntity_C;
