export declare type CommonApproverFilterColumnAp = $.kd.bos.metadata.filter.CommonApproverFilterColumnAp;
export declare const CommonApproverFilterColumnAp: $.kd.bos.metadata.filter.CommonApproverFilterColumnAp_C;
export declare type CommonBaseDataFilterColumnAp = $.kd.bos.metadata.filter.CommonBaseDataFilterColumnAp;
export declare const CommonBaseDataFilterColumnAp: $.kd.bos.metadata.filter.CommonBaseDataFilterColumnAp_C;
export declare type CommonCheckBoxFilterColumnAp = $.kd.bos.metadata.filter.CommonCheckBoxFilterColumnAp;
export declare const CommonCheckBoxFilterColumnAp: $.kd.bos.metadata.filter.CommonCheckBoxFilterColumnAp_C;
export declare type CommonCheckBoxGroupFilterColumnAp = $.kd.bos.metadata.filter.CommonCheckBoxGroupFilterColumnAp;
export declare const CommonCheckBoxGroupFilterColumnAp: $.kd.bos.metadata.filter.CommonCheckBoxGroupFilterColumnAp_C;
export declare type CommonDateFilterColumnAp = $.kd.bos.metadata.filter.CommonDateFilterColumnAp;
export declare const CommonDateFilterColumnAp: $.kd.bos.metadata.filter.CommonDateFilterColumnAp_C;
export declare type CommonFilterColumnAp = $.kd.bos.metadata.filter.CommonFilterColumnAp;
export declare const CommonFilterColumnAp: $.kd.bos.metadata.filter.CommonFilterColumnAp_C;
export declare type FastSearchGridViewAp = $.kd.bos.metadata.filter.FastSearchGridViewAp;
export declare const FastSearchGridViewAp: $.kd.bos.metadata.filter.FastSearchGridViewAp_C;
export declare type FilterColumnAp = $.kd.bos.metadata.filter.FilterColumnAp;
export declare const FilterColumnAp: $.kd.bos.metadata.filter.FilterColumnAp_C;
export declare type FilterContainerAp = $.kd.bos.metadata.filter.FilterContainerAp;
export declare const FilterContainerAp: $.kd.bos.metadata.filter.FilterContainerAp_C;
export declare type FilterGridViewAp = $.kd.bos.metadata.filter.FilterGridViewAp;
export declare const FilterGridViewAp: $.kd.bos.metadata.filter.FilterGridViewAp_C;
export declare type SchemeApproverFilterColumnAp = $.kd.bos.metadata.filter.SchemeApproverFilterColumnAp;
export declare const SchemeApproverFilterColumnAp: $.kd.bos.metadata.filter.SchemeApproverFilterColumnAp_C;
export declare type SchemeBaseDataFilterColumnAp = $.kd.bos.metadata.filter.SchemeBaseDataFilterColumnAp;
export declare const SchemeBaseDataFilterColumnAp: $.kd.bos.metadata.filter.SchemeBaseDataFilterColumnAp_C;
export declare type SchemeComboFilterColumnAp = $.kd.bos.metadata.filter.SchemeComboFilterColumnAp;
export declare const SchemeComboFilterColumnAp: $.kd.bos.metadata.filter.SchemeComboFilterColumnAp_C;
export declare type SchemeFilterColumnAp = $.kd.bos.metadata.filter.SchemeFilterColumnAp;
export declare const SchemeFilterColumnAp: $.kd.bos.metadata.filter.SchemeFilterColumnAp_C;
export declare type SchemeFilterViewAp = $.kd.bos.metadata.filter.SchemeFilterViewAp;
export declare const SchemeFilterViewAp: $.kd.bos.metadata.filter.SchemeFilterViewAp_C;
export declare type SchemeVoucherFilterColumnAp = $.kd.bos.metadata.filter.SchemeVoucherFilterColumnAp;
export declare const SchemeVoucherFilterColumnAp: $.kd.bos.metadata.filter.SchemeVoucherFilterColumnAp_C;
