export declare type AbstractStyle = $.kd.bos.metadata.form.AbstractStyle;
export declare const AbstractStyle: $.kd.bos.metadata.form.AbstractStyle_C;
export declare type Border = $.kd.bos.metadata.form.Border;
export declare const Border: $.kd.bos.metadata.form.Border_C;
export declare type Margin = $.kd.bos.metadata.form.Margin;
export declare const Margin: $.kd.bos.metadata.form.Margin_C;
export declare type Padding = $.kd.bos.metadata.form.Padding;
export declare const Padding: $.kd.bos.metadata.form.Padding_C;
export declare type Style = $.kd.bos.metadata.form.Style;
export declare const Style: $.kd.bos.metadata.form.Style_C;
export declare type BasedataFormAp = $.kd.bos.metadata.form.BasedataFormAp;
export declare const BasedataFormAp: $.kd.bos.metadata.form.BasedataFormAp_C;
export declare type BillFormAp = $.kd.bos.metadata.form.BillFormAp;
export declare const BillFormAp: $.kd.bos.metadata.form.BillFormAp_C;
export declare type CardAp = $.kd.bos.metadata.form.CardAp;
export declare const CardAp: $.kd.bos.metadata.form.CardAp_C;
export declare type ContainerAp = $.kd.bos.metadata.form.ContainerAp;
export declare const ContainerAp: $.kd.bos.metadata.form.ContainerAp_C;
export declare type ControlAp = $.kd.bos.metadata.form.ControlAp;
export declare const ControlAp: $.kd.bos.metadata.form.ControlAp_C;
export declare type FormAp = $.kd.bos.metadata.form.FormAp;
export declare const FormAp: $.kd.bos.metadata.form.FormAp_C;
export declare type FormMetadata = $.kd.bos.metadata.form.FormMetadata;
export declare const FormMetadata: $.kd.bos.metadata.form.FormMetadata_C;
export declare type IBillListAp = $.kd.bos.metadata.form.IBillListAp;
export declare const IBillListAp: $.kd.bos.metadata.form.IBillListAp;
export declare type ICardRowPanelAp = $.kd.bos.metadata.form.ICardRowPanelAp;
export declare const ICardRowPanelAp: $.kd.bos.metadata.form.ICardRowPanelAp;
export declare type IListGridViewAp = $.kd.bos.metadata.form.IListGridViewAp;
export declare const IListGridViewAp: $.kd.bos.metadata.form.IListGridViewAp;
export declare type LogBillFormAp = $.kd.bos.metadata.form.LogBillFormAp;
export declare const LogBillFormAp: $.kd.bos.metadata.form.LogBillFormAp_C;
export declare type MenuItem = $.kd.bos.metadata.form.MenuItem;
export declare const MenuItem: $.kd.bos.metadata.form.MenuItem_C;
export declare type MobileBillFormAp = $.kd.bos.metadata.form.MobileBillFormAp;
export declare const MobileBillFormAp: $.kd.bos.metadata.form.MobileBillFormAp_C;
export declare type MobileFormAp = $.kd.bos.metadata.form.MobileFormAp;
export declare const MobileFormAp: $.kd.bos.metadata.form.MobileFormAp_C;
export declare type MobileUserGuideFormAp = $.kd.bos.metadata.form.MobileUserGuideFormAp;
export declare const MobileUserGuideFormAp: $.kd.bos.metadata.form.MobileUserGuideFormAp_C;
export declare type ParameterFormAp = $.kd.bos.metadata.form.ParameterFormAp;
export declare const ParameterFormAp: $.kd.bos.metadata.form.ParameterFormAp_C;
export declare type PrintFormAp = $.kd.bos.metadata.form.PrintFormAp;
export declare const PrintFormAp: $.kd.bos.metadata.form.PrintFormAp_C;
export declare type PrintMetadata = $.kd.bos.metadata.form.PrintMetadata;
export declare const PrintMetadata: $.kd.bos.metadata.form.PrintMetadata_C;
export declare type WidgetFormAp = $.kd.bos.metadata.form.WidgetFormAp;
export declare const WidgetFormAp: $.kd.bos.metadata.form.WidgetFormAp_C;
