export declare type ApproverListColumnAp = $.kd.bos.metadata.list.ApproverListColumnAp;
export declare const ApproverListColumnAp: $.kd.bos.metadata.list.ApproverListColumnAp_C;
export declare type BillListAp = $.kd.bos.metadata.list.BillListAp;
export declare const BillListAp: $.kd.bos.metadata.list.BillListAp_C;
export declare type CardCheckBoxListColumnAp = $.kd.bos.metadata.list.CardCheckBoxListColumnAp;
export declare const CardCheckBoxListColumnAp: $.kd.bos.metadata.list.CardCheckBoxListColumnAp_C;
export declare type CardComboListColumnAp = $.kd.bos.metadata.list.CardComboListColumnAp;
export declare const CardComboListColumnAp: $.kd.bos.metadata.list.CardComboListColumnAp_C;
export declare type CardDateListColumnAp = $.kd.bos.metadata.list.CardDateListColumnAp;
export declare const CardDateListColumnAp: $.kd.bos.metadata.list.CardDateListColumnAp_C;
export declare type CardDecimalListColumnAp = $.kd.bos.metadata.list.CardDecimalListColumnAp;
export declare const CardDecimalListColumnAp: $.kd.bos.metadata.list.CardDecimalListColumnAp_C;
export declare type CardFlexListColumnAp = $.kd.bos.metadata.list.CardFlexListColumnAp;
export declare const CardFlexListColumnAp: $.kd.bos.metadata.list.CardFlexListColumnAp_C;
export declare type CardFlexPanelAp = $.kd.bos.metadata.list.CardFlexPanelAp;
export declare const CardFlexPanelAp: $.kd.bos.metadata.list.CardFlexPanelAp_C;
export declare type CardListColumnAp = $.kd.bos.metadata.list.CardListColumnAp;
export declare const CardListColumnAp: $.kd.bos.metadata.list.CardListColumnAp_C;
export declare type CardMulComboListColumnAp = $.kd.bos.metadata.list.CardMulComboListColumnAp;
export declare const CardMulComboListColumnAp: $.kd.bos.metadata.list.CardMulComboListColumnAp_C;
export declare type CardRowPanelAp = $.kd.bos.metadata.list.CardRowPanelAp;
export declare const CardRowPanelAp: $.kd.bos.metadata.list.CardRowPanelAp_C;
export declare type CardTimeListColumnAp = $.kd.bos.metadata.list.CardTimeListColumnAp;
export declare const CardTimeListColumnAp: $.kd.bos.metadata.list.CardTimeListColumnAp_C;
export declare type CardVoucherNoListColumnAp = $.kd.bos.metadata.list.CardVoucherNoListColumnAp;
export declare const CardVoucherNoListColumnAp: $.kd.bos.metadata.list.CardVoucherNoListColumnAp_C;
export declare type CheckBoxListColumnAp = $.kd.bos.metadata.list.CheckBoxListColumnAp;
export declare const CheckBoxListColumnAp: $.kd.bos.metadata.list.CheckBoxListColumnAp_C;
export declare type CityListAp = $.kd.bos.metadata.list.CityListAp;
export declare const CityListAp: $.kd.bos.metadata.list.CityListAp_C;
export declare type ComboListColumnAp = $.kd.bos.metadata.list.ComboListColumnAp;
export declare const ComboListColumnAp: $.kd.bos.metadata.list.ComboListColumnAp_C;
export declare type DateListColumnAp = $.kd.bos.metadata.list.DateListColumnAp;
export declare const DateListColumnAp: $.kd.bos.metadata.list.DateListColumnAp_C;
export declare type DecimalListColumnAp = $.kd.bos.metadata.list.DecimalListColumnAp;
export declare const DecimalListColumnAp: $.kd.bos.metadata.list.DecimalListColumnAp_C;
export declare type DynamicTextListColumnAp = $.kd.bos.metadata.list.DynamicTextListColumnAp;
export declare const DynamicTextListColumnAp: $.kd.bos.metadata.list.DynamicTextListColumnAp_C;
export declare type F7SelectedListAp = $.kd.bos.metadata.list.F7SelectedListAp;
export declare const F7SelectedListAp: $.kd.bos.metadata.list.F7SelectedListAp_C;
export declare type FlexListColumnAp = $.kd.bos.metadata.list.FlexListColumnAp;
export declare const FlexListColumnAp: $.kd.bos.metadata.list.FlexListColumnAp_C;
export declare type ListCardViewAp = $.kd.bos.metadata.list.ListCardViewAp;
export declare const ListCardViewAp: $.kd.bos.metadata.list.ListCardViewAp_C;
export declare type ListColumnAp = $.kd.bos.metadata.list.ListColumnAp;
export declare const ListColumnAp: $.kd.bos.metadata.list.ListColumnAp_C;
export declare type ListColumnGroupAp = $.kd.bos.metadata.list.ListColumnGroupAp;
export declare const ListColumnGroupAp: $.kd.bos.metadata.list.ListColumnGroupAp_C;
export declare type ListFormAp = $.kd.bos.metadata.list.ListFormAp;
export declare const ListFormAp: $.kd.bos.metadata.list.ListFormAp_C;
export declare type ListGridViewAp = $.kd.bos.metadata.list.ListGridViewAp;
export declare const ListGridViewAp: $.kd.bos.metadata.list.ListGridViewAp_C;
export declare type ListOperationColumnAp = $.kd.bos.metadata.list.ListOperationColumnAp;
export declare const ListOperationColumnAp: $.kd.bos.metadata.list.ListOperationColumnAp_C;
export declare type MergeListColumnAp = $.kd.bos.metadata.list.MergeListColumnAp;
export declare const MergeListColumnAp: $.kd.bos.metadata.list.MergeListColumnAp_C;
export declare type MobF7SelectedListAp = $.kd.bos.metadata.list.MobF7SelectedListAp;
export declare const MobF7SelectedListAp: $.kd.bos.metadata.list.MobF7SelectedListAp_C;
export declare type MobileListAp = $.kd.bos.metadata.list.MobileListAp;
export declare const MobileListAp: $.kd.bos.metadata.list.MobileListAp_C;
export declare type MobileListFormAp = $.kd.bos.metadata.list.MobileListFormAp;
export declare const MobileListFormAp: $.kd.bos.metadata.list.MobileListFormAp_C;
export declare type MulComboListColumnAp = $.kd.bos.metadata.list.MulComboListColumnAp;
export declare const MulComboListColumnAp: $.kd.bos.metadata.list.MulComboListColumnAp_C;
export declare type OrgListAp = $.kd.bos.metadata.list.OrgListAp;
export declare const OrgListAp: $.kd.bos.metadata.list.OrgListAp_C;
export declare type QingViewAp = $.kd.bos.metadata.list.QingViewAp;
export declare const QingViewAp: $.kd.bos.metadata.list.QingViewAp_C;
export declare type TimeListColumnAp = $.kd.bos.metadata.list.TimeListColumnAp;
export declare const TimeListColumnAp: $.kd.bos.metadata.list.TimeListColumnAp_C;
export declare type UserListAp = $.kd.bos.metadata.list.UserListAp;
export declare const UserListAp: $.kd.bos.metadata.list.UserListAp_C;
export declare type VoucherNoListColumnAp = $.kd.bos.metadata.list.VoucherNoListColumnAp;
export declare const VoucherNoListColumnAp: $.kd.bos.metadata.list.VoucherNoListColumnAp_C;
