export declare type BuildOption = $.kd.bos.metadata.treebuilder.BuildOption;
export declare const BuildOption: $.kd.bos.metadata.treebuilder.BuildOption_C;
export declare type ControlsTreeBuildOption = $.kd.bos.metadata.treebuilder.ControlsTreeBuildOption;
export declare const ControlsTreeBuildOption: $.kd.bos.metadata.treebuilder.ControlsTreeBuildOption_C;
export declare type EntityFieldTreeBuildOption = $.kd.bos.metadata.treebuilder.EntityFieldTreeBuildOption;
export declare const EntityFieldTreeBuildOption: $.kd.bos.metadata.treebuilder.EntityFieldTreeBuildOption_C;
export declare type ExpressionEditHelper = $.kd.bos.metadata.treebuilder.ExpressionEditHelper;
export declare const ExpressionEditHelper: $.kd.bos.metadata.treebuilder.ExpressionEditHelper_C;
export declare type FieldTreeShowHelper = $.kd.bos.metadata.treebuilder.FieldTreeShowHelper;
export declare const FieldTreeShowHelper: $.kd.bos.metadata.treebuilder.FieldTreeShowHelper_C;
export declare type FilterEditHelper = $.kd.bos.metadata.treebuilder.FilterEditHelper;
export declare const FilterEditHelper: $.kd.bos.metadata.treebuilder.FilterEditHelper_C;
export declare type FilterFieldBuildOption = $.kd.bos.metadata.treebuilder.FilterFieldBuildOption;
export declare const FilterFieldBuildOption: $.kd.bos.metadata.treebuilder.FilterFieldBuildOption_C;
export declare type FormFieldTreeBuildOption = $.kd.bos.metadata.treebuilder.FormFieldTreeBuildOption;
export declare const FormFieldTreeBuildOption: $.kd.bos.metadata.treebuilder.FormFieldTreeBuildOption_C;
export declare type FormTreeBuilder = $.kd.bos.metadata.treebuilder.FormTreeBuilder;
export declare const FormTreeBuilder: $.kd.bos.metadata.treebuilder.FormTreeBuilder_C;
export declare type PropTreeBuildOption = $.kd.bos.metadata.treebuilder.PropTreeBuildOption;
export declare const PropTreeBuildOption: $.kd.bos.metadata.treebuilder.PropTreeBuildOption_C;
