export declare type ModelType = $.kd.bos.designer.query.ModelType;
export declare const ModelType: typeof $.kd.bos.designer.query.ModelType;
export declare type QueryConditionSelectFieldList = $.kd.bos.designer.query.QueryConditionSelectFieldList;
export declare const QueryConditionSelectFieldList: $.kd.bos.designer.query.QueryConditionSelectFieldList_C;
export declare type QueryDynSourcePlugIn = $.kd.bos.designer.query.QueryDynSourcePlugIn;
export declare const QueryDynSourcePlugIn: $.kd.bos.designer.query.QueryDynSourcePlugIn_C;
export declare type QueryDynSourceValid = $.kd.bos.designer.query.QueryDynSourceValid;
export declare const QueryDynSourceValid: $.kd.bos.designer.query.QueryDynSourceValid_C;
export declare type QueryEntityParseHelper = $.kd.bos.designer.query.QueryEntityParseHelper;
export declare const QueryEntityParseHelper: $.kd.bos.designer.query.QueryEntityParseHelper_C;
export declare type QueryEntityTreeBuildParameter = $.kd.bos.designer.query.QueryEntityTreeBuildParameter;
export declare const QueryEntityTreeBuildParameter: $.kd.bos.designer.query.QueryEntityTreeBuildParameter_C;
export declare type QueryEntityTreeNode = $.kd.bos.designer.query.QueryEntityTreeNode;
export declare const QueryEntityTreeNode: $.kd.bos.designer.query.QueryEntityTreeNode_C;
export declare type QueryMetadataHelper = $.kd.bos.designer.query.QueryMetadataHelper;
export declare const QueryMetadataHelper: $.kd.bos.designer.query.QueryMetadataHelper_C;
export declare type QuerySelectFieldList = $.kd.bos.designer.query.QuerySelectFieldList;
export declare const QuerySelectFieldList: $.kd.bos.designer.query.QuerySelectFieldList_C;
export declare type QueryTreeListPlugin = $.kd.bos.designer.query.QueryTreeListPlugin;
export declare const QueryTreeListPlugin: $.kd.bos.designer.query.QueryTreeListPlugin_C;
export declare type ReportComboItemPlugin = $.kd.bos.designer.query.ReportComboItemPlugin;
export declare const ReportComboItemPlugin: $.kd.bos.designer.query.ReportComboItemPlugin_C;
