export declare type BeforeChooseApplyTypeEvent = $.kd.sdk.wtc.wtss.business.homepage.BeforeChooseApplyTypeEvent;
export declare const BeforeChooseApplyTypeEvent: $.kd.sdk.wtc.wtss.business.homepage.BeforeChooseApplyTypeEvent_C;
export declare type BeforeShowApplyPageEvent = $.kd.sdk.wtc.wtss.business.homepage.BeforeShowApplyPageEvent;
export declare const BeforeShowApplyPageEvent: $.kd.sdk.wtc.wtss.business.homepage.BeforeShowApplyPageEvent_C;
export declare type BeforeShowDetailPageEvent = $.kd.sdk.wtc.wtss.business.homepage.BeforeShowDetailPageEvent;
export declare const BeforeShowDetailPageEvent: $.kd.sdk.wtc.wtss.business.homepage.BeforeShowDetailPageEvent_C;
export declare type BillReplaceExtPlugin = $.kd.sdk.wtc.wtss.business.homepage.BillReplaceExtPlugin;
export declare const BillReplaceExtPlugin: $.kd.sdk.wtc.wtss.business.homepage.BillReplaceExtPlugin;
export declare type ISignAddressReplacePlugin = $.kd.sdk.wtc.wtss.business.homepage.ISignAddressReplacePlugin;
export declare const ISignAddressReplacePlugin: $.kd.sdk.wtc.wtss.business.homepage.ISignAddressReplacePlugin;
export declare type MobileBillListDto = $.kd.sdk.wtc.wtss.business.homepage.MobileBillListDto;
export declare const MobileBillListDto: $.kd.sdk.wtc.wtss.business.homepage.MobileBillListDto_C;
export declare type OnFilterMobileBillListEvent = $.kd.sdk.wtc.wtss.business.homepage.OnFilterMobileBillListEvent;
export declare const OnFilterMobileBillListEvent: $.kd.sdk.wtc.wtss.business.homepage.OnFilterMobileBillListEvent_C;
export declare type OnQueryMobileBillListEvent = $.kd.sdk.wtc.wtss.business.homepage.OnQueryMobileBillListEvent;
export declare const OnQueryMobileBillListEvent: $.kd.sdk.wtc.wtss.business.homepage.OnQueryMobileBillListEvent_C;
export declare type SignAddressChooseEvent = $.kd.sdk.wtc.wtss.business.homepage.SignAddressChooseEvent;
export declare const SignAddressChooseEvent: $.kd.sdk.wtc.wtss.business.homepage.SignAddressChooseEvent_C;
export declare type WtssHomepageServiceHelper = $.kd.sdk.wtc.wtss.business.homepage.WtssHomepageServiceHelper;
export declare const WtssHomepageServiceHelper: $.kd.sdk.wtc.wtss.business.homepage.WtssHomepageServiceHelper_C;
