export declare type AfterInitAttStatisticAdminOrgEvent = $.kd.sdk.wtc.wtss.business.teamhome.AfterInitAttStatisticAdminOrgEvent;
export declare const AfterInitAttStatisticAdminOrgEvent: $.kd.sdk.wtc.wtss.business.teamhome.AfterInitAttStatisticAdminOrgEvent_C;
export declare type AttStatisticAdminOrgParam = $.kd.sdk.wtc.wtss.business.teamhome.AttStatisticAdminOrgParam;
export declare const AttStatisticAdminOrgParam: $.kd.sdk.wtc.wtss.business.teamhome.AttStatisticAdminOrgParam_C;
export declare type AttStatisticQueryExtPlugin = $.kd.sdk.wtc.wtss.business.teamhome.AttStatisticQueryExtPlugin;
export declare const AttStatisticQueryExtPlugin: $.kd.sdk.wtc.wtss.business.teamhome.AttStatisticQueryExtPlugin;
export declare type AttStatisticTargetQueryParam = $.kd.sdk.wtc.wtss.business.teamhome.AttStatisticTargetQueryParam;
export declare const AttStatisticTargetQueryParam: $.kd.sdk.wtc.wtss.business.teamhome.AttStatisticTargetQueryParam_C;
export declare type AttTargetQueryExpandService = $.kd.sdk.wtc.wtss.business.teamhome.AttTargetQueryExpandService;
export declare const AttTargetQueryExpandService: $.kd.sdk.wtc.wtss.business.teamhome.AttTargetQueryExpandService;
export declare type BeforeQueryAttStatisticEvent = $.kd.sdk.wtc.wtss.business.teamhome.BeforeQueryAttStatisticEvent;
export declare const BeforeQueryAttStatisticEvent: $.kd.sdk.wtc.wtss.business.teamhome.BeforeQueryAttStatisticEvent_C;
