export declare type AfterBizRuleEventArgs = $.kd.bos.entity.botp.plugin.args.AfterBizRuleEventArgs;
export declare const AfterBizRuleEventArgs: $.kd.bos.entity.botp.plugin.args.AfterBizRuleEventArgs_C;
export declare type AfterBuildDrawFilterEventArgs = $.kd.bos.entity.botp.plugin.args.AfterBuildDrawFilterEventArgs;
export declare const AfterBuildDrawFilterEventArgs: $.kd.bos.entity.botp.plugin.args.AfterBuildDrawFilterEventArgs_C;
export declare type AfterBuildQueryParemeterEventArgs = $.kd.bos.entity.botp.plugin.args.AfterBuildQueryParemeterEventArgs;
export declare const AfterBuildQueryParemeterEventArgs: $.kd.bos.entity.botp.plugin.args.AfterBuildQueryParemeterEventArgs_C;
export declare type AfterBuildRowConditionEventArgs = $.kd.bos.entity.botp.plugin.args.AfterBuildRowConditionEventArgs;
export declare const AfterBuildRowConditionEventArgs: $.kd.bos.entity.botp.plugin.args.AfterBuildRowConditionEventArgs_C;
export declare type AfterBuildSourceBillIdsEventArgs = $.kd.bos.entity.botp.plugin.args.AfterBuildSourceBillIdsEventArgs;
export declare const AfterBuildSourceBillIdsEventArgs: $.kd.bos.entity.botp.plugin.args.AfterBuildSourceBillIdsEventArgs_C;
export declare type AfterCalcWriteValueEventArgs = $.kd.bos.entity.botp.plugin.args.AfterCalcWriteValueEventArgs;
export declare const AfterCalcWriteValueEventArgs: $.kd.bos.entity.botp.plugin.args.AfterCalcWriteValueEventArgs_C;
export declare type AfterCloseRowEventArgs = $.kd.bos.entity.botp.plugin.args.AfterCloseRowEventArgs;
export declare const AfterCloseRowEventArgs: $.kd.bos.entity.botp.plugin.args.AfterCloseRowEventArgs_C;
export declare type AfterCommitAmountEventArgs = $.kd.bos.entity.botp.plugin.args.AfterCommitAmountEventArgs;
export declare const AfterCommitAmountEventArgs: $.kd.bos.entity.botp.plugin.args.AfterCommitAmountEventArgs_C;
export declare type AfterConvertEventArgs = $.kd.bos.entity.botp.plugin.args.AfterConvertEventArgs;
export declare const AfterConvertEventArgs: $.kd.bos.entity.botp.plugin.args.AfterConvertEventArgs_C;
export declare type AfterCreateLinkEventArgs = $.kd.bos.entity.botp.plugin.args.AfterCreateLinkEventArgs;
export declare const AfterCreateLinkEventArgs: $.kd.bos.entity.botp.plugin.args.AfterCreateLinkEventArgs_C;
export declare type AfterCreateTargetEventArgs = $.kd.bos.entity.botp.plugin.args.AfterCreateTargetEventArgs;
export declare const AfterCreateTargetEventArgs: $.kd.bos.entity.botp.plugin.args.AfterCreateTargetEventArgs_C;
export declare type AfterExcessCheckEventArgs = $.kd.bos.entity.botp.plugin.args.AfterExcessCheckEventArgs;
export declare const AfterExcessCheckEventArgs: $.kd.bos.entity.botp.plugin.args.AfterExcessCheckEventArgs_C;
export declare type AfterFieldMappingEventArgs = $.kd.bos.entity.botp.plugin.args.AfterFieldMappingEventArgs;
export declare const AfterFieldMappingEventArgs: $.kd.bos.entity.botp.plugin.args.AfterFieldMappingEventArgs_C;
export declare type AfterGetSourceDataEventArgs = $.kd.bos.entity.botp.plugin.args.AfterGetSourceDataEventArgs;
export declare const AfterGetSourceDataEventArgs: $.kd.bos.entity.botp.plugin.args.AfterGetSourceDataEventArgs_C;
export declare type AfterReadSourceBillEventArgs = $.kd.bos.entity.botp.plugin.args.AfterReadSourceBillEventArgs;
export declare const AfterReadSourceBillEventArgs: $.kd.bos.entity.botp.plugin.args.AfterReadSourceBillEventArgs_C;
export declare type AfterSaveSourceBillEventArgs = $.kd.bos.entity.botp.plugin.args.AfterSaveSourceBillEventArgs;
export declare const AfterSaveSourceBillEventArgs: $.kd.bos.entity.botp.plugin.args.AfterSaveSourceBillEventArgs_C;
export declare type BeforeBuildGroupModeEventArgs = $.kd.bos.entity.botp.plugin.args.BeforeBuildGroupModeEventArgs;
export declare const BeforeBuildGroupModeEventArgs: $.kd.bos.entity.botp.plugin.args.BeforeBuildGroupModeEventArgs_C;
export declare type BeforeBuildRowConditionEventArgs = $.kd.bos.entity.botp.plugin.args.BeforeBuildRowConditionEventArgs;
export declare const BeforeBuildRowConditionEventArgs: $.kd.bos.entity.botp.plugin.args.BeforeBuildRowConditionEventArgs_C;
export declare type BeforeCloseRowEventArgs = $.kd.bos.entity.botp.plugin.args.BeforeCloseRowEventArgs;
export declare const BeforeCloseRowEventArgs: $.kd.bos.entity.botp.plugin.args.BeforeCloseRowEventArgs_C;
export declare type BeforeCreateArticulationRowEventArgs = $.kd.bos.entity.botp.plugin.args.BeforeCreateArticulationRowEventArgs;
export declare const BeforeCreateArticulationRowEventArgs: $.kd.bos.entity.botp.plugin.args.BeforeCreateArticulationRowEventArgs_C;
export declare type BeforeCreateLinkEventArgs = $.kd.bos.entity.botp.plugin.args.BeforeCreateLinkEventArgs;
export declare const BeforeCreateLinkEventArgs: $.kd.bos.entity.botp.plugin.args.BeforeCreateLinkEventArgs_C;
export declare type BeforeCreateTargetEventArgs = $.kd.bos.entity.botp.plugin.args.BeforeCreateTargetEventArgs;
export declare const BeforeCreateTargetEventArgs: $.kd.bos.entity.botp.plugin.args.BeforeCreateTargetEventArgs_C;
export declare type BeforeExcessCheckEventArgs = $.kd.bos.entity.botp.plugin.args.BeforeExcessCheckEventArgs;
export declare const BeforeExcessCheckEventArgs: $.kd.bos.entity.botp.plugin.args.BeforeExcessCheckEventArgs_C;
export declare type BeforeExecWriteBackRuleEventArgs = $.kd.bos.entity.botp.plugin.args.BeforeExecWriteBackRuleEventArgs;
export declare const BeforeExecWriteBackRuleEventArgs: $.kd.bos.entity.botp.plugin.args.BeforeExecWriteBackRuleEventArgs_C;
export declare type BeforeGetSourceDataEventArgs = $.kd.bos.entity.botp.plugin.args.BeforeGetSourceDataEventArgs;
export declare const BeforeGetSourceDataEventArgs: $.kd.bos.entity.botp.plugin.args.BeforeGetSourceDataEventArgs_C;
export declare type BeforeReadSourceBillEventArgs = $.kd.bos.entity.botp.plugin.args.BeforeReadSourceBillEventArgs;
export declare const BeforeReadSourceBillEventArgs: $.kd.bos.entity.botp.plugin.args.BeforeReadSourceBillEventArgs_C;
export declare type BeforeSaveSourceBillEventArgs = $.kd.bos.entity.botp.plugin.args.BeforeSaveSourceBillEventArgs;
export declare const BeforeSaveSourceBillEventArgs: $.kd.bos.entity.botp.plugin.args.BeforeSaveSourceBillEventArgs_C;
export declare type BeforeSaveTransEventArgs = $.kd.bos.entity.botp.plugin.args.BeforeSaveTransEventArgs;
export declare const BeforeSaveTransEventArgs: $.kd.bos.entity.botp.plugin.args.BeforeSaveTransEventArgs_C;
export declare type BeforeTrackEventArgs = $.kd.bos.entity.botp.plugin.args.BeforeTrackEventArgs;
export declare const BeforeTrackEventArgs: $.kd.bos.entity.botp.plugin.args.BeforeTrackEventArgs_C;
export declare type ConvertPluginEventArgs = $.kd.bos.entity.botp.plugin.args.ConvertPluginEventArgs;
export declare const ConvertPluginEventArgs: $.kd.bos.entity.botp.plugin.args.ConvertPluginEventArgs_C;
export declare type FinishWriteBackEventArgs = $.kd.bos.entity.botp.plugin.args.FinishWriteBackEventArgs;
export declare const FinishWriteBackEventArgs: $.kd.bos.entity.botp.plugin.args.FinishWriteBackEventArgs_C;
export declare type InitVariableEventArgs = $.kd.bos.entity.botp.plugin.args.InitVariableEventArgs;
export declare const InitVariableEventArgs: $.kd.bos.entity.botp.plugin.args.InitVariableEventArgs_C;
export declare type PreparePropertysEventArgs = $.kd.bos.entity.botp.plugin.args.PreparePropertysEventArgs;
export declare const PreparePropertysEventArgs: $.kd.bos.entity.botp.plugin.args.PreparePropertysEventArgs_C;
export declare type RollbackSaveEventArgs = $.kd.bos.entity.botp.plugin.args.RollbackSaveEventArgs;
export declare const RollbackSaveEventArgs: $.kd.bos.entity.botp.plugin.args.RollbackSaveEventArgs_C;
export declare type WriteBackEventArgs = $.kd.bos.entity.botp.plugin.args.WriteBackEventArgs;
export declare const WriteBackEventArgs: $.kd.bos.entity.botp.plugin.args.WriteBackEventArgs_C;
