export declare type AgentExecution = $.kd.bos.workflow.api.AgentExecution;
export declare const AgentExecution: $.kd.bos.workflow.api.AgentExecution;
export declare type AgentTask = $.kd.bos.workflow.api.AgentTask;
export declare const AgentTask: $.kd.bos.workflow.api.AgentTask;
export declare type BizProcessStatus = $.kd.bos.workflow.api.BizProcessStatus;
export declare const BizProcessStatus: $.kd.bos.workflow.api.BizProcessStatus_C;
export declare type ExecutionListener = $.kd.bos.workflow.api.ExecutionListener;
export declare const ExecutionListener: $.kd.bos.workflow.api.ExecutionListener;
export declare type IConditionalRuleParser = $.kd.bos.workflow.api.IConditionalRuleParser;
export declare const IConditionalRuleParser: $.kd.bos.workflow.api.IConditionalRuleParser;
export declare type IRelationService = $.kd.bos.workflow.api.IRelationService;
export declare const IRelationService: $.kd.bos.workflow.api.IRelationService;
export declare type IWorkflowService = $.kd.bos.workflow.api.IWorkflowService;
export declare const IWorkflowService: $.kd.bos.workflow.api.IWorkflowService;
export declare type MessageRequestInfo = $.kd.bos.workflow.api.MessageRequestInfo;
export declare const MessageRequestInfo: $.kd.bos.workflow.api.MessageRequestInfo_C;
export declare type NodeTemplate = $.kd.bos.workflow.api.NodeTemplate;
export declare const NodeTemplate: $.kd.bos.workflow.api.NodeTemplate_C;
export declare type WorkflowElement = $.kd.bos.workflow.api.WorkflowElement;
export declare const WorkflowElement: $.kd.bos.workflow.api.WorkflowElement;
