export declare type Axis = $.kd.bos.form.chart.Axis;
export declare const Axis: $.kd.bos.form.chart.Axis_C;
export declare type AxisType = $.kd.bos.form.chart.AxisType;
export declare const AxisType: typeof $.kd.bos.form.chart.AxisType;
export declare type BarChart = $.kd.bos.form.chart.BarChart;
export declare const BarChart: $.kd.bos.form.chart.BarChart_C;
export declare type BarSeries = $.kd.bos.form.chart.BarSeries;
export declare const BarSeries: $.kd.bos.form.chart.BarSeries_C;
export declare type BaseGraphicStyle = $.kd.bos.form.chart.BaseGraphicStyle;
export declare const BaseGraphicStyle: $.kd.bos.form.chart.BaseGraphicStyle_C;
export declare type BaseGraphicType = $.kd.bos.form.chart.BaseGraphicType;
export declare const BaseGraphicType: $.kd.bos.form.chart.BaseGraphicType_C;
export declare type Chart = $.kd.bos.form.chart.Chart;
export declare const Chart: $.kd.bos.form.chart.Chart_C;
export declare type ChartData = $.kd.bos.form.chart.ChartData;
export declare const ChartData: $.kd.bos.form.chart.ChartData_C;
export declare type ChartType = $.kd.bos.form.chart.ChartType;
export declare const ChartType: typeof $.kd.bos.form.chart.ChartType;
export declare type CustomChart = $.kd.bos.form.chart.CustomChart;
export declare const CustomChart: $.kd.bos.form.chart.CustomChart_C;
export declare type GaugeChart = $.kd.bos.form.chart.GaugeChart;
export declare const GaugeChart: $.kd.bos.form.chart.GaugeChart_C;
export declare type GaugeSeries = $.kd.bos.form.chart.GaugeSeries;
export declare const GaugeSeries: $.kd.bos.form.chart.GaugeSeries_C;
export declare type GradientItem = $.kd.bos.form.chart.GradientItem;
export declare const GradientItem: $.kd.bos.form.chart.GradientItem_C;
export declare type HistogramChart = $.kd.bos.form.chart.HistogramChart;
export declare const HistogramChart: $.kd.bos.form.chart.HistogramChart_C;
export declare type ItemValue = $.kd.bos.form.chart.ItemValue;
export declare const ItemValue: $.kd.bos.form.chart.ItemValue_C;
export declare type Label = $.kd.bos.form.chart.Label;
export declare const Label: $.kd.bos.form.chart.Label_C;
export declare type LineSeries = $.kd.bos.form.chart.LineSeries;
export declare const LineSeries: $.kd.bos.form.chart.LineSeries_C;
export declare type PieChart = $.kd.bos.form.chart.PieChart;
export declare const PieChart: $.kd.bos.form.chart.PieChart_C;
export declare type PieSeries = $.kd.bos.form.chart.PieSeries;
export declare const PieSeries: $.kd.bos.form.chart.PieSeries_C;
export declare type PointLineChart = $.kd.bos.form.chart.PointLineChart;
export declare const PointLineChart: $.kd.bos.form.chart.PointLineChart_C;
export declare type PolygonGraphicShape = $.kd.bos.form.chart.PolygonGraphicShape;
export declare const PolygonGraphicShape: $.kd.bos.form.chart.PolygonGraphicShape_C;
export declare type PolygonGraphicStyle = $.kd.bos.form.chart.PolygonGraphicStyle;
export declare const PolygonGraphicStyle: $.kd.bos.form.chart.PolygonGraphicStyle_C;
export declare type PolygonGraphicType = $.kd.bos.form.chart.PolygonGraphicType;
export declare const PolygonGraphicType: $.kd.bos.form.chart.PolygonGraphicType_C;
export declare type Position = $.kd.bos.form.chart.Position;
export declare const Position: typeof $.kd.bos.form.chart.Position;
export declare type RoseType = $.kd.bos.form.chart.RoseType;
export declare const RoseType: typeof $.kd.bos.form.chart.RoseType;
export declare type Series = $.kd.bos.form.chart.Series;
export declare const Series: $.kd.bos.form.chart.Series_C;
export declare type TextGraphicStyle = $.kd.bos.form.chart.TextGraphicStyle;
export declare const TextGraphicStyle: $.kd.bos.form.chart.TextGraphicStyle_C;
export declare type TextGraphicType = $.kd.bos.form.chart.TextGraphicType;
export declare const TextGraphicType: $.kd.bos.form.chart.TextGraphicType_C;
export declare type XAlign = $.kd.bos.form.chart.XAlign;
export declare const XAlign: typeof $.kd.bos.form.chart.XAlign;
export declare type YAlign = $.kd.bos.form.chart.YAlign;
export declare const YAlign: typeof $.kd.bos.form.chart.YAlign;
