export declare type QingAnalysis = $.kd.bos.form.control.QingAnalysis;
export declare const QingAnalysis: $.kd.bos.form.control.QingAnalysis_C;
export declare type AbstractGrid = $.kd.bos.form.control.AbstractGrid;
export declare const AbstractGrid: $.kd.bos.form.control.AbstractGrid_C;
export declare type Button = $.kd.bos.form.control.Button;
export declare const Button: $.kd.bos.form.control.Button_C;
export declare type CarouselFigure = $.kd.bos.form.control.CarouselFigure;
export declare const CarouselFigure: $.kd.bos.form.control.CarouselFigure_C;
export declare type ClientAjax = $.kd.bos.form.control.ClientAjax;
export declare const ClientAjax: $.kd.bos.form.control.ClientAjax_C;
export declare type ClientAjaxOption = $.kd.bos.form.control.ClientAjaxOption;
export declare const ClientAjaxOption: $.kd.bos.form.control.ClientAjaxOption_C;
export declare type CodeEdit = $.kd.bos.form.control.CodeEdit;
export declare const CodeEdit: $.kd.bos.form.control.CodeEdit_C;
export declare type Control = $.kd.bos.form.control.Control;
export declare const Control: $.kd.bos.form.control.Control_C;
export declare type CustomView = $.kd.bos.form.control.CustomView;
export declare const CustomView: $.kd.bos.form.control.CustomView_C;
export declare type EntryData = $.kd.bos.form.control.EntryData;
export declare const EntryData: $.kd.bos.form.control.EntryData_C;
export declare type EntryFieldContainer = $.kd.bos.form.control.EntryFieldContainer;
export declare const EntryFieldContainer: $.kd.bos.form.control.EntryFieldContainer_C;
export declare type EntryGrid = $.kd.bos.form.control.EntryGrid;
export declare const EntryGrid: $.kd.bos.form.control.EntryGrid_C;
export declare type EntryGridSetRowDataConfig = $.kd.bos.form.control.EntryGridSetRowDataConfig;
export declare const EntryGridSetRowDataConfig: $.kd.bos.form.control.EntryGridSetRowDataConfig_C;
export declare type EntryViewType = $.kd.bos.form.control.EntryViewType;
export declare const EntryViewType: typeof $.kd.bos.form.control.EntryViewType;
export declare type FilterGrid = $.kd.bos.form.control.FilterGrid;
export declare const FilterGrid: $.kd.bos.form.control.FilterGrid_C;
export declare type FloatMenu = $.kd.bos.form.control.FloatMenu;
export declare const FloatMenu: $.kd.bos.form.control.FloatMenu_C;
export declare type Html = $.kd.bos.form.control.Html;
export declare const Html: $.kd.bos.form.control.Html_C;
export declare type Hyperlink = $.kd.bos.form.control.Hyperlink;
export declare const Hyperlink: $.kd.bos.form.control.Hyperlink_C;
export declare type IFrame = $.kd.bos.form.control.IFrame;
export declare const IFrame: $.kd.bos.form.control.IFrame_C;
export declare type KingScriptEdit = $.kd.bos.form.control.KingScriptEdit;
export declare const KingScriptEdit: $.kd.bos.form.control.KingScriptEdit_C;
export declare type Label = $.kd.bos.form.control.Label;
export declare const Label: $.kd.bos.form.control.Label_C;
export declare type MenuItem = $.kd.bos.form.control.MenuItem;
export declare const MenuItem: $.kd.bos.form.control.MenuItem_C;
export declare type OCR = $.kd.bos.form.control.OCR;
export declare const OCR: $.kd.bos.form.control.OCR_C;
export declare type OperationColumn = $.kd.bos.form.control.OperationColumn;
export declare const OperationColumn: $.kd.bos.form.control.OperationColumn_C;
export declare type ProgressBar = $.kd.bos.form.control.ProgressBar;
export declare const ProgressBar: $.kd.bos.form.control.ProgressBar_C;
export declare type QRCode = $.kd.bos.form.control.QRCode;
export declare const QRCode: $.kd.bos.form.control.QRCode_C;
export declare type Rate = $.kd.bos.form.control.Rate;
export declare const Rate: $.kd.bos.form.control.Rate_C;
export declare type RichTextEditor = $.kd.bos.form.control.RichTextEditor;
export declare const RichTextEditor: $.kd.bos.form.control.RichTextEditor_C;
export declare type Search = $.kd.bos.form.control.Search;
export declare const Search: $.kd.bos.form.control.Search_C;
export declare type SegmentedControl = $.kd.bos.form.control.SegmentedControl;
export declare const SegmentedControl: $.kd.bos.form.control.SegmentedControl_C;
export declare type Slider = $.kd.bos.form.control.Slider;
export declare const Slider: $.kd.bos.form.control.Slider_C;
export declare type SplitContainer = $.kd.bos.form.control.SplitContainer;
export declare const SplitContainer: $.kd.bos.form.control.SplitContainer_C;
export declare type SplitDirection = $.kd.bos.form.control.SplitDirection;
export declare const SplitDirection: typeof $.kd.bos.form.control.SplitDirection;
export declare type Steps = $.kd.bos.form.control.Steps;
export declare const Steps: $.kd.bos.form.control.Steps_C;
export declare type StepsOption = $.kd.bos.form.control.StepsOption;
export declare const StepsOption: $.kd.bos.form.control.StepsOption_C;
export declare type SubEntryGrid = $.kd.bos.form.control.SubEntryGrid;
export declare const SubEntryGrid: $.kd.bos.form.control.SubEntryGrid_C;
export declare type TaskNotice = $.kd.bos.form.control.TaskNotice;
export declare const TaskNotice: $.kd.bos.form.control.TaskNotice_C;
export declare type TimeLineStyle = $.kd.bos.form.control.TimeLineStyle;
export declare const TimeLineStyle: $.kd.bos.form.control.TimeLineStyle_C;
export declare type Timeline = $.kd.bos.form.control.Timeline;
export declare const Timeline: $.kd.bos.form.control.Timeline_C;
export declare type TimelineClickArgs = $.kd.bos.form.control.TimelineClickArgs;
export declare const TimelineClickArgs: $.kd.bos.form.control.TimelineClickArgs_C;
export declare type TimelineContentOption = $.kd.bos.form.control.TimelineContentOption;
export declare const TimelineContentOption: $.kd.bos.form.control.TimelineContentOption_C;
export declare type TimelineLabelOption = $.kd.bos.form.control.TimelineLabelOption;
export declare const TimelineLabelOption: $.kd.bos.form.control.TimelineLabelOption_C;
export declare type TimelineOption = $.kd.bos.form.control.TimelineOption;
export declare const TimelineOption: $.kd.bos.form.control.TimelineOption_C;
export declare type TimelineOptionClickArg = $.kd.bos.form.control.TimelineOptionClickArg;
export declare const TimelineOptionClickArg: $.kd.bos.form.control.TimelineOptionClickArg_C;
export declare type TimelineOptionKey = $.kd.bos.form.control.TimelineOptionKey;
export declare const TimelineOptionKey: $.kd.bos.form.control.TimelineOptionKey_C;
export declare type TimelineText = $.kd.bos.form.control.TimelineText;
export declare const TimelineText: $.kd.bos.form.control.TimelineText_C;
export declare type Toolbar = $.kd.bos.form.control.Toolbar;
export declare const Toolbar: $.kd.bos.form.control.Toolbar_C;
export declare type TransferContainer = $.kd.bos.form.control.TransferContainer;
export declare const TransferContainer: $.kd.bos.form.control.TransferContainer_C;
export declare type TreeEntryGrid = $.kd.bos.form.control.TreeEntryGrid;
export declare const TreeEntryGrid: $.kd.bos.form.control.TreeEntryGrid_C;
export declare type TreeMenu = $.kd.bos.form.control.TreeMenu;
export declare const TreeMenu: $.kd.bos.form.control.TreeMenu_C;
export declare type TreeView = $.kd.bos.form.control.TreeView;
export declare const TreeView: $.kd.bos.form.control.TreeView_C;
export declare type TreeView$TreeState = $.kd.bos.form.control.TreeView$TreeState;
export declare const TreeView$TreeState: $.kd.bos.form.control.TreeView$TreeState_C;
export declare type UrlUtil = $.kd.bos.form.control.UrlUtil;
export declare const UrlUtil: $.kd.bos.form.control.UrlUtil_C;
export declare type Vector = $.kd.bos.form.control.Vector;
export declare const Vector: $.kd.bos.form.control.Vector_C;
export declare type VectorList = $.kd.bos.form.control.VectorList;
export declare const VectorList: $.kd.bos.form.control.VectorList_C;
export declare type WorkCalendar = $.kd.bos.form.control.WorkCalendar;
export declare const WorkCalendar: $.kd.bos.form.control.WorkCalendar_C;
export declare type WorkCalendarData = $.kd.bos.form.control.WorkCalendarData;
export declare const WorkCalendarData: $.kd.bos.form.control.WorkCalendarData_C;
export declare type AttachmentPanel = $.kd.bos.form.control.AttachmentPanel;
export declare const AttachmentPanel: $.kd.bos.form.control.AttachmentPanel_C;
export declare type Image = $.kd.bos.form.control.Image;
export declare const Image: $.kd.bos.form.control.Image_C;
export declare type ImageList = $.kd.bos.form.control.ImageList;
export declare const ImageList: $.kd.bos.form.control.ImageList_C;
export declare type WebOffice = $.kd.bos.form.control.WebOffice;
export declare const WebOffice: $.kd.bos.form.control.WebOffice_C;
