export declare type BeforeCreateListColumnsArgs = $.kd.bos.form.events.BeforeCreateListColumnsArgs;
export declare const BeforeCreateListColumnsArgs: $.kd.bos.form.events.BeforeCreateListColumnsArgs_C;
export declare type FilterColumnSetFilterEvent = $.kd.bos.form.events.FilterColumnSetFilterEvent;
export declare const FilterColumnSetFilterEvent: $.kd.bos.form.events.FilterColumnSetFilterEvent_C;
export declare type FilterContainerInitArgs = $.kd.bos.form.events.FilterContainerInitArgs;
export declare const FilterContainerInitArgs: $.kd.bos.form.events.FilterContainerInitArgs_C;
export declare type MobFilterSortInitArgs = $.kd.bos.form.events.MobFilterSortInitArgs;
export declare const MobFilterSortInitArgs: $.kd.bos.form.events.MobFilterSortInitArgs_C;
export declare type SetFilterEvent = $.kd.bos.form.events.SetFilterEvent;
export declare const SetFilterEvent: $.kd.bos.form.events.SetFilterEvent_C;
export declare type SetFilterListener = $.kd.bos.form.events.SetFilterListener;
export declare const SetFilterListener: $.kd.bos.form.events.SetFilterListener;
export declare type AddCustomViewEvent = $.kd.bos.form.events.AddCustomViewEvent;
export declare const AddCustomViewEvent: $.kd.bos.form.events.AddCustomViewEvent_C;
export declare type AfterBindDataEvent = $.kd.bos.form.events.AfterBindDataEvent;
export declare const AfterBindDataEvent: $.kd.bos.form.events.AfterBindDataEvent_C;
export declare type AfterBindDataListener = $.kd.bos.form.events.AfterBindDataListener;
export declare const AfterBindDataListener: $.kd.bos.form.events.AfterBindDataListener;
export declare type AfterDoOperationEventArgs = $.kd.bos.form.events.AfterDoOperationEventArgs;
export declare const AfterDoOperationEventArgs: $.kd.bos.form.events.AfterDoOperationEventArgs_C;
export declare type AfterMobileListPushDownRefreshEvent = $.kd.bos.form.events.AfterMobileListPushDownRefreshEvent;
export declare const AfterMobileListPushDownRefreshEvent: $.kd.bos.form.events.AfterMobileListPushDownRefreshEvent_C;
export declare type AfterMobileListPushDownRefreshListener = $.kd.bos.form.events.AfterMobileListPushDownRefreshListener;
export declare const AfterMobileListPushDownRefreshListener: $.kd.bos.form.events.AfterMobileListPushDownRefreshListener;
export declare type AfterQueryOfExportEvent = $.kd.bos.form.events.AfterQueryOfExportEvent;
export declare const AfterQueryOfExportEvent: $.kd.bos.form.events.AfterQueryOfExportEvent_C;
export declare type BeforeBindDataEvent = $.kd.bos.form.events.BeforeBindDataEvent;
export declare const BeforeBindDataEvent: $.kd.bos.form.events.BeforeBindDataEvent_C;
export declare type BeforeBindDataListener = $.kd.bos.form.events.BeforeBindDataListener;
export declare const BeforeBindDataListener: $.kd.bos.form.events.BeforeBindDataListener;
export declare type BeforeBuildTreeNodeEvent = $.kd.bos.form.events.BeforeBuildTreeNodeEvent;
export declare const BeforeBuildTreeNodeEvent: $.kd.bos.form.events.BeforeBuildTreeNodeEvent_C;
export declare type BeforeClosedEvent = $.kd.bos.form.events.BeforeClosedEvent;
export declare const BeforeClosedEvent: $.kd.bos.form.events.BeforeClosedEvent_C;
export declare type BeforeCreateListDataProviderArgs = $.kd.bos.form.events.BeforeCreateListDataProviderArgs;
export declare const BeforeCreateListDataProviderArgs: $.kd.bos.form.events.BeforeCreateListDataProviderArgs_C;
export declare type BeforeDoCheckDataPermissionArgs = $.kd.bos.form.events.BeforeDoCheckDataPermissionArgs;
export declare const BeforeDoCheckDataPermissionArgs: $.kd.bos.form.events.BeforeDoCheckDataPermissionArgs_C;
export declare type BeforeDoOperationEventArgs = $.kd.bos.form.events.BeforeDoOperationEventArgs;
export declare const BeforeDoOperationEventArgs: $.kd.bos.form.events.BeforeDoOperationEventArgs_C;
export declare type BeforeExportFileEvent = $.kd.bos.form.events.BeforeExportFileEvent;
export declare const BeforeExportFileEvent: $.kd.bos.form.events.BeforeExportFileEvent_C;
export declare type BeforeFieldPostBackEvent = $.kd.bos.form.events.BeforeFieldPostBackEvent;
export declare const BeforeFieldPostBackEvent: $.kd.bos.form.events.BeforeFieldPostBackEvent_C;
export declare type BeforeQueryOfExportEvent = $.kd.bos.form.events.BeforeQueryOfExportEvent;
export declare const BeforeQueryOfExportEvent: $.kd.bos.form.events.BeforeQueryOfExportEvent_C;
export declare type BeforeTreeNodeClickEvent = $.kd.bos.form.events.BeforeTreeNodeClickEvent;
export declare const BeforeTreeNodeClickEvent: $.kd.bos.form.events.BeforeTreeNodeClickEvent_C;
export declare type BillListHyperLinkClickEvent = $.kd.bos.form.events.BillListHyperLinkClickEvent;
export declare const BillListHyperLinkClickEvent: $.kd.bos.form.events.BillListHyperLinkClickEvent_C;
export declare type ClientCallBackEvent = $.kd.bos.form.events.ClientCallBackEvent;
export declare const ClientCallBackEvent: $.kd.bos.form.events.ClientCallBackEvent_C;
export declare type ClosedCallBackEvent = $.kd.bos.form.events.ClosedCallBackEvent;
export declare const ClosedCallBackEvent: $.kd.bos.form.events.ClosedCallBackEvent_C;
export declare type ContextMenuClickEvent = $.kd.bos.form.events.ContextMenuClickEvent;
export declare const ContextMenuClickEvent: $.kd.bos.form.events.ContextMenuClickEvent_C;
export declare type CustomEventArgs = $.kd.bos.form.events.CustomEventArgs;
export declare const CustomEventArgs: $.kd.bos.form.events.CustomEventArgs_C;
export declare type EntryHyperLinkClickListener = $.kd.bos.form.events.EntryHyperLinkClickListener;
export declare const EntryHyperLinkClickListener: $.kd.bos.form.events.EntryHyperLinkClickListener;
export declare type ExportFileEvent = $.kd.bos.form.events.ExportFileEvent;
export declare const ExportFileEvent: $.kd.bos.form.events.ExportFileEvent_C;
export declare type FilterContainerSearchClickArgs = $.kd.bos.form.events.FilterContainerSearchClickArgs;
export declare const FilterContainerSearchClickArgs: $.kd.bos.form.events.FilterContainerSearchClickArgs_C;
export declare type FlexBeforeClosedEvent = $.kd.bos.form.events.FlexBeforeClosedEvent;
export declare const FlexBeforeClosedEvent: $.kd.bos.form.events.FlexBeforeClosedEvent_C;
export declare type HyperLinkClickArgs = $.kd.bos.form.events.HyperLinkClickArgs;
export declare const HyperLinkClickArgs: $.kd.bos.form.events.HyperLinkClickArgs_C;
export declare type HyperLinkClickEvent = $.kd.bos.form.events.HyperLinkClickEvent;
export declare const HyperLinkClickEvent: $.kd.bos.form.events.HyperLinkClickEvent_C;
export declare type HyperLinkClickListener = $.kd.bos.form.events.HyperLinkClickListener;
export declare const HyperLinkClickListener: $.kd.bos.form.events.HyperLinkClickListener;
export declare type ListColumnCompareTypesSetEvent = $.kd.bos.form.events.ListColumnCompareTypesSetEvent;
export declare const ListColumnCompareTypesSetEvent: $.kd.bos.form.events.ListColumnCompareTypesSetEvent_C;
export declare type ListColumnCompareTypesSetListener = $.kd.bos.form.events.ListColumnCompareTypesSetListener;
export declare const ListColumnCompareTypesSetListener: $.kd.bos.form.events.ListColumnCompareTypesSetListener;
export declare type LoadCustomControlMetasArgs = $.kd.bos.form.events.LoadCustomControlMetasArgs;
export declare const LoadCustomControlMetasArgs: $.kd.bos.form.events.LoadCustomControlMetasArgs_C;
export declare type MessageBoxClosedEvent = $.kd.bos.form.events.MessageBoxClosedEvent;
export declare const MessageBoxClosedEvent: $.kd.bos.form.events.MessageBoxClosedEvent_C;
export declare type MobFilterSortSearchClickArgs = $.kd.bos.form.events.MobFilterSortSearchClickArgs;
export declare const MobFilterSortSearchClickArgs: $.kd.bos.form.events.MobFilterSortSearchClickArgs_C;
export declare type OnCreateDynamicUIMetasArgs = $.kd.bos.form.events.OnCreateDynamicUIMetasArgs;
export declare const OnCreateDynamicUIMetasArgs: $.kd.bos.form.events.OnCreateDynamicUIMetasArgs_C;
export declare type OnGetControlArgs = $.kd.bos.form.events.OnGetControlArgs;
export declare const OnGetControlArgs: $.kd.bos.form.events.OnGetControlArgs_C;
export declare type PagerClickEvent = $.kd.bos.form.events.PagerClickEvent;
export declare const PagerClickEvent: $.kd.bos.form.events.PagerClickEvent_C;
export declare type PagerClickListener = $.kd.bos.form.events.PagerClickListener;
export declare const PagerClickListener: $.kd.bos.form.events.PagerClickListener;
export declare type PreOpenFormEventArgs = $.kd.bos.form.events.PreOpenFormEventArgs;
export declare const PreOpenFormEventArgs: $.kd.bos.form.events.PreOpenFormEventArgs_C;
export declare type SumDataLoadOnFirstSetEvent = $.kd.bos.form.events.SumDataLoadOnFirstSetEvent;
export declare const SumDataLoadOnFirstSetEvent: $.kd.bos.form.events.SumDataLoadOnFirstSetEvent_C;
export declare type TimeZoneLocationEvent = $.kd.bos.form.events.TimeZoneLocationEvent;
export declare const TimeZoneLocationEvent: $.kd.bos.form.events.TimeZoneLocationEvent_C;
export declare type TimerElapsedArgs = $.kd.bos.form.events.TimerElapsedArgs;
export declare const TimerElapsedArgs: $.kd.bos.form.events.TimerElapsedArgs_C;
