export declare type AddressEdit = $.kd.bos.form.field.AddressEdit;
export declare const AddressEdit: $.kd.bos.form.field.AddressEdit_C;
export declare type AdminDivisionEdit = $.kd.bos.form.field.AdminDivisionEdit;
export declare const AdminDivisionEdit: $.kd.bos.form.field.AdminDivisionEdit_C;
export declare type AmountEdit = $.kd.bos.form.field.AmountEdit;
export declare const AmountEdit: $.kd.bos.form.field.AmountEdit_C;
export declare type AssistantEdit = $.kd.bos.form.field.AssistantEdit;
export declare const AssistantEdit: $.kd.bos.form.field.AssistantEdit_C;
export declare type AssistantFlexEdit = $.kd.bos.form.field.AssistantFlexEdit;
export declare const AssistantFlexEdit: $.kd.bos.form.field.AssistantFlexEdit_C;
export declare type BasedataEdit = $.kd.bos.form.field.BasedataEdit;
export declare const BasedataEdit: $.kd.bos.form.field.BasedataEdit_C;
export declare type BasedataFlexEdit = $.kd.bos.form.field.BasedataFlexEdit;
export declare const BasedataFlexEdit: $.kd.bos.form.field.BasedataFlexEdit_C;
export declare type BasedataPropEdit = $.kd.bos.form.field.BasedataPropEdit;
export declare const BasedataPropEdit: $.kd.bos.form.field.BasedataPropEdit_C;
export declare type BillStatusEdit = $.kd.bos.form.field.BillStatusEdit;
export declare const BillStatusEdit: $.kd.bos.form.field.BillStatusEdit_C;
export declare type BillTypeEdit = $.kd.bos.form.field.BillTypeEdit;
export declare const BillTypeEdit: $.kd.bos.form.field.BillTypeEdit_C;
export declare type BizBasedataEdit = $.kd.bos.form.field.BizBasedataEdit;
export declare const BizBasedataEdit: $.kd.bos.form.field.BizBasedataEdit_C;
export declare type CityEdit = $.kd.bos.form.field.CityEdit;
export declare const CityEdit: $.kd.bos.form.field.CityEdit_C;
export declare type CityEditUtil = $.kd.bos.form.field.CityEditUtil;
export declare const CityEditUtil: $.kd.bos.form.field.CityEditUtil_C;
export declare type ComboEdit = $.kd.bos.form.field.ComboEdit;
export declare const ComboEdit: $.kd.bos.form.field.ComboEdit_C;
export declare type ComboItem = $.kd.bos.form.field.ComboItem;
export declare const ComboItem: $.kd.bos.form.field.ComboItem_C;
export declare type DateEdit = $.kd.bos.form.field.DateEdit;
export declare const DateEdit: $.kd.bos.form.field.DateEdit_C;
export declare type DateRangeEdit = $.kd.bos.form.field.DateRangeEdit;
export declare const DateRangeEdit: $.kd.bos.form.field.DateRangeEdit_C;
export declare type DateTimeEdit = $.kd.bos.form.field.DateTimeEdit;
export declare const DateTimeEdit: $.kd.bos.form.field.DateTimeEdit_C;
export declare type DecimalEdit = $.kd.bos.form.field.DecimalEdit;
export declare const DecimalEdit: $.kd.bos.form.field.DecimalEdit_C;
export declare type DecimalFlexEdit = $.kd.bos.form.field.DecimalFlexEdit;
export declare const DecimalFlexEdit: $.kd.bos.form.field.DecimalFlexEdit_C;
export declare type EmailEdit = $.kd.bos.form.field.EmailEdit;
export declare const EmailEdit: $.kd.bos.form.field.EmailEdit_C;
export declare type ExchangeRateEdit = $.kd.bos.form.field.ExchangeRateEdit;
export declare const ExchangeRateEdit: $.kd.bos.form.field.ExchangeRateEdit_C;
export declare type FieldEdit = $.kd.bos.form.field.FieldEdit;
export declare const FieldEdit: $.kd.bos.form.field.FieldEdit_C;
export declare type FlexEdit = $.kd.bos.form.field.FlexEdit;
export declare const FlexEdit: $.kd.bos.form.field.FlexEdit_C;
export declare type GeoPointEdit = $.kd.bos.form.field.GeoPointEdit;
export declare const GeoPointEdit: $.kd.bos.form.field.GeoPointEdit_C;
export declare type GroupEdit = $.kd.bos.form.field.GroupEdit;
export declare const GroupEdit: $.kd.bos.form.field.GroupEdit_C;
export declare type IntegerEdit = $.kd.bos.form.field.IntegerEdit;
export declare const IntegerEdit: $.kd.bos.form.field.IntegerEdit_C;
export declare type ItemClassEdit = $.kd.bos.form.field.ItemClassEdit;
export declare const ItemClassEdit: $.kd.bos.form.field.ItemClassEdit_C;
export declare type ItemClassTypeEdit = $.kd.bos.form.field.ItemClassTypeEdit;
export declare const ItemClassTypeEdit: $.kd.bos.form.field.ItemClassTypeEdit_C;
export declare type LargeTextEdit = $.kd.bos.form.field.LargeTextEdit;
export declare const LargeTextEdit: $.kd.bos.form.field.LargeTextEdit_C;
export declare type LargeTextOtherEdit = $.kd.bos.form.field.LargeTextOtherEdit;
export declare const LargeTextOtherEdit: $.kd.bos.form.field.LargeTextOtherEdit_C;
export declare type MainOrgEdit = $.kd.bos.form.field.MainOrgEdit;
export declare const MainOrgEdit: $.kd.bos.form.field.MainOrgEdit_C;
export declare type MasterBasedataEdit = $.kd.bos.form.field.MasterBasedataEdit;
export declare const MasterBasedataEdit: $.kd.bos.form.field.MasterBasedataEdit_C;
export declare type MaterielEdit = $.kd.bos.form.field.MaterielEdit;
export declare const MaterielEdit: $.kd.bos.form.field.MaterielEdit_C;
export declare type MobBasedataEdit = $.kd.bos.form.field.MobBasedataEdit;
export declare const MobBasedataEdit: $.kd.bos.form.field.MobBasedataEdit_C;
export declare type MulBasedataEdit = $.kd.bos.form.field.MulBasedataEdit;
export declare const MulBasedataEdit: $.kd.bos.form.field.MulBasedataEdit_C;
export declare type MulComboEdit = $.kd.bos.form.field.MulComboEdit;
export declare const MulComboEdit: $.kd.bos.form.field.MulComboEdit_C;
export declare type OrgEdit = $.kd.bos.form.field.OrgEdit;
export declare const OrgEdit: $.kd.bos.form.field.OrgEdit_C;
export declare type OrgFlexEdit = $.kd.bos.form.field.OrgFlexEdit;
export declare const OrgFlexEdit: $.kd.bos.form.field.OrgFlexEdit_C;
export declare type ParentBasedataEdit = $.kd.bos.form.field.ParentBasedataEdit;
export declare const ParentBasedataEdit: $.kd.bos.form.field.ParentBasedataEdit_C;
export declare type PriceEdit = $.kd.bos.form.field.PriceEdit;
export declare const PriceEdit: $.kd.bos.form.field.PriceEdit_C;
export declare type QtyEdit = $.kd.bos.form.field.QtyEdit;
export declare const QtyEdit: $.kd.bos.form.field.QtyEdit_C;
export declare type RadioEdit = $.kd.bos.form.field.RadioEdit;
export declare const RadioEdit: $.kd.bos.form.field.RadioEdit_C;
export declare type RefBillEdit = $.kd.bos.form.field.RefBillEdit;
export declare const RefBillEdit: $.kd.bos.form.field.RefBillEdit_C;
export declare type RichEdit = $.kd.bos.form.field.RichEdit;
export declare const RichEdit: $.kd.bos.form.field.RichEdit_C;
export declare type StepperEdit = $.kd.bos.form.field.StepperEdit;
export declare const StepperEdit: $.kd.bos.form.field.StepperEdit_C;
export declare type TelephoneEdit = $.kd.bos.form.field.TelephoneEdit;
export declare const TelephoneEdit: $.kd.bos.form.field.TelephoneEdit_C;
export declare type TextAreaEdit = $.kd.bos.form.field.TextAreaEdit;
export declare const TextAreaEdit: $.kd.bos.form.field.TextAreaEdit_C;
export declare type TextEdit = $.kd.bos.form.field.TextEdit;
export declare const TextEdit: $.kd.bos.form.field.TextEdit_C;
export declare type TextFlexEdit = $.kd.bos.form.field.TextFlexEdit;
export declare const TextFlexEdit: $.kd.bos.form.field.TextFlexEdit_C;
export declare type TimeEdit = $.kd.bos.form.field.TimeEdit;
export declare const TimeEdit: $.kd.bos.form.field.TimeEdit_C;
export declare type TimeRangeEdit = $.kd.bos.form.field.TimeRangeEdit;
export declare const TimeRangeEdit: $.kd.bos.form.field.TimeRangeEdit_C;
export declare type UnitEdit = $.kd.bos.form.field.UnitEdit;
export declare const UnitEdit: $.kd.bos.form.field.UnitEdit_C;
export declare type UserAvatarEdit = $.kd.bos.form.field.UserAvatarEdit;
export declare const UserAvatarEdit: $.kd.bos.form.field.UserAvatarEdit_C;
export declare type UserEdit = $.kd.bos.form.field.UserEdit;
export declare const UserEdit: $.kd.bos.form.field.UserEdit_C;
export declare type AttachmentEdit = $.kd.bos.form.field.AttachmentEdit;
export declare const AttachmentEdit: $.kd.bos.form.field.AttachmentEdit_C;
