export declare type Copy = $.kd.bos.form.operate.Copy;
export declare const Copy: $.kd.bos.form.operate.Copy_C;
export declare type DefaultDynamicFormOperate = $.kd.bos.form.operate.DefaultDynamicFormOperate;
export declare const DefaultDynamicFormOperate: $.kd.bos.form.operate.DefaultDynamicFormOperate_C;
export declare type Modify = $.kd.bos.form.operate.Modify;
export declare const Modify: $.kd.bos.form.operate.Modify_C;
export declare type MoveEntryDown = $.kd.bos.form.operate.MoveEntryDown;
export declare const MoveEntryDown: $.kd.bos.form.operate.MoveEntryDown_C;
export declare type MoveEntryUp = $.kd.bos.form.operate.MoveEntryUp;
export declare const MoveEntryUp: $.kd.bos.form.operate.MoveEntryUp_C;
export declare type New = $.kd.bos.form.operate.New;
export declare const New: $.kd.bos.form.operate.New_C;
export declare type SetEntryBottom = $.kd.bos.form.operate.SetEntryBottom;
export declare const SetEntryBottom: $.kd.bos.form.operate.SetEntryBottom_C;
export declare type SetEntryTop = $.kd.bos.form.operate.SetEntryTop;
export declare const SetEntryTop: $.kd.bos.form.operate.SetEntryTop_C;
export declare type View = $.kd.bos.form.operate.View;
export declare const View: $.kd.bos.form.operate.View_C;
export declare type EntityOperate = $.kd.bos.form.operate.EntityOperate;
export declare const EntityOperate: $.kd.bos.form.operate.EntityOperate_C;
export declare type MutexHelper = $.kd.bos.form.operate.MutexHelper;
export declare const MutexHelper: $.kd.bos.form.operate.MutexHelper_C;
export declare type AbstractOperate = $.kd.bos.form.operate.AbstractOperate;
export declare const AbstractOperate: $.kd.bos.form.operate.AbstractOperate_C;
export declare type CoreMutexHelper = $.kd.bos.form.operate.CoreMutexHelper;
export declare const CoreMutexHelper: $.kd.bos.form.operate.CoreMutexHelper_C;
export declare type FormOperate = $.kd.bos.form.operate.FormOperate;
export declare const FormOperate: $.kd.bos.form.operate.FormOperate_C;
export declare type IFormMutexService = $.kd.bos.form.operate.IFormMutexService;
export declare const IFormMutexService: $.kd.bos.form.operate.IFormMutexService;
export declare type IFormOperate = $.kd.bos.form.operate.IFormOperate;
export declare const IFormOperate: $.kd.bos.form.operate.IFormOperate;
export declare type OpFieldValueReader = $.kd.bos.form.operate.OpFieldValueReader;
export declare const OpFieldValueReader: $.kd.bos.form.operate.OpFieldValueReader;
