export declare type AfterExportEntryEvent = $.kd.bos.form.plugin.AfterExportEntryEvent;
export declare const AfterExportEntryEvent: $.kd.bos.form.plugin.AfterExportEntryEvent_C;
export declare type BeforeDownloadImportTemplateEvent = $.kd.bos.form.plugin.BeforeDownloadImportTemplateEvent;
export declare const BeforeDownloadImportTemplateEvent: $.kd.bos.form.plugin.BeforeDownloadImportTemplateEvent_C;
export declare type BeforeExportEntryEvent = $.kd.bos.form.plugin.BeforeExportEntryEvent;
export declare const BeforeExportEntryEvent: $.kd.bos.form.plugin.BeforeExportEntryEvent_C;
export declare type ImportTemplateListener = $.kd.bos.form.plugin.ImportTemplateListener;
export declare const ImportTemplateListener: $.kd.bos.form.plugin.ImportTemplateListener;
export declare type OperationResultPlugin = $.kd.bos.form.plugin.OperationResultPlugin;
export declare const OperationResultPlugin: $.kd.bos.form.plugin.OperationResultPlugin_C;
export declare type TemplateGroupBaseDataPlugin = $.kd.bos.form.plugin.TemplateGroupBaseDataPlugin;
export declare const TemplateGroupBaseDataPlugin: $.kd.bos.form.plugin.TemplateGroupBaseDataPlugin_C;
export declare type TemplateTreeBaseDataPlugin = $.kd.bos.form.plugin.TemplateTreeBaseDataPlugin;
export declare const TemplateTreeBaseDataPlugin: $.kd.bos.form.plugin.TemplateTreeBaseDataPlugin_C;
export declare type TemplateTreePlugin = $.kd.bos.form.plugin.TemplateTreePlugin;
export declare const TemplateTreePlugin: $.kd.bos.form.plugin.TemplateTreePlugin_C;
export declare type TreeListBizAppsPlugin = $.kd.bos.form.plugin.TreeListBizAppsPlugin;
export declare const TreeListBizAppsPlugin: $.kd.bos.form.plugin.TreeListBizAppsPlugin_C;
export declare type MobileTreeListPlugin = $.kd.bos.form.plugin.MobileTreeListPlugin;
export declare const MobileTreeListPlugin: $.kd.bos.form.plugin.MobileTreeListPlugin_C;
export declare type YzjContextMenuClickPlugin = $.kd.bos.form.plugin.YzjContextMenuClickPlugin;
export declare const YzjContextMenuClickPlugin: $.kd.bos.form.plugin.YzjContextMenuClickPlugin_C;
export declare type AbstractFormPlugin = $.kd.bos.form.plugin.AbstractFormPlugin;
export declare const AbstractFormPlugin: $.kd.bos.form.plugin.AbstractFormPlugin_C;
export declare type AbstractMobFormPlugin = $.kd.bos.form.plugin.AbstractMobFormPlugin;
export declare const AbstractMobFormPlugin: $.kd.bos.form.plugin.AbstractMobFormPlugin_C;
export declare type FormViewPluginProxy = $.kd.bos.form.plugin.FormViewPluginProxy;
export declare const FormViewPluginProxy: $.kd.bos.form.plugin.FormViewPluginProxy_C;
export declare type IFormPlugin = $.kd.bos.form.plugin.IFormPlugin;
export declare const IFormPlugin: $.kd.bos.form.plugin.IFormPlugin;
export declare type IMobFormPlugin = $.kd.bos.form.plugin.IMobFormPlugin;
export declare const IMobFormPlugin: $.kd.bos.form.plugin.IMobFormPlugin;
export declare type IWaterMarkPlugin = $.kd.bos.form.plugin.IWaterMarkPlugin;
export declare const IWaterMarkPlugin: $.kd.bos.form.plugin.IWaterMarkPlugin;
