/// <reference path="../index.d.ts" />
export declare type AWTEvent = $.java.awt.AWTEvent;
export declare const AWTEvent: $.java.awt.AWTEvent_C;
export declare type BufferCapabilities = $.java.awt.BufferCapabilities;
export declare const BufferCapabilities: $.java.awt.BufferCapabilities_C;
export declare type BufferCapabilities$FlipContents = $.java.awt.BufferCapabilities$FlipContents;
export declare const BufferCapabilities$FlipContents: $.java.awt.BufferCapabilities$FlipContents_C;
export declare type Color = $.java.awt.Color;
export declare const Color: $.java.awt.Color_C;
export declare type Component = $.java.awt.Component;
export declare const Component: $.java.awt.Component_C;
export declare type Component$BaselineResizeBehavior = $.java.awt.Component$BaselineResizeBehavior;
export declare const Component$BaselineResizeBehavior: typeof $.java.awt.Component$BaselineResizeBehavior;
export declare type ComponentOrientation = $.java.awt.ComponentOrientation;
export declare const ComponentOrientation: $.java.awt.ComponentOrientation_C;
export declare type Composite = $.java.awt.Composite;
export declare const Composite: $.java.awt.Composite;
export declare type CompositeContext = $.java.awt.CompositeContext;
export declare const CompositeContext: $.java.awt.CompositeContext;
export declare type Container = $.java.awt.Container;
export declare const Container: $.java.awt.Container_C;
export declare type Cursor = $.java.awt.Cursor;
export declare const Cursor: $.java.awt.Cursor_C;
export declare type Dialog$ModalExclusionType = $.java.awt.Dialog$ModalExclusionType;
export declare const Dialog$ModalExclusionType: typeof $.java.awt.Dialog$ModalExclusionType;
export declare type Dialog$ModalityType = $.java.awt.Dialog$ModalityType;
export declare const Dialog$ModalityType: typeof $.java.awt.Dialog$ModalityType;
export declare type Dimension = $.java.awt.Dimension;
export declare const Dimension: $.java.awt.Dimension_C;
export declare type DisplayMode = $.java.awt.DisplayMode;
export declare const DisplayMode: $.java.awt.DisplayMode_C;
export declare type Event = $.java.awt.Event;
export declare const Event: $.java.awt.Event_C;
export declare type EventQueue = $.java.awt.EventQueue;
export declare const EventQueue: $.java.awt.EventQueue_C;
export declare type FocusTraversalPolicy = $.java.awt.FocusTraversalPolicy;
export declare const FocusTraversalPolicy: $.java.awt.FocusTraversalPolicy_C;
export declare type Font = $.java.awt.Font;
export declare const Font: $.java.awt.Font_C;
export declare type FontMetrics = $.java.awt.FontMetrics;
export declare const FontMetrics: $.java.awt.FontMetrics_C;
export declare type Frame = $.java.awt.Frame;
export declare const Frame: $.java.awt.Frame_C;
export declare type Graphics = $.java.awt.Graphics;
export declare const Graphics: $.java.awt.Graphics_C;
export declare type Graphics2D = $.java.awt.Graphics2D;
export declare const Graphics2D: $.java.awt.Graphics2D_C;
export declare type GraphicsConfigTemplate = $.java.awt.GraphicsConfigTemplate;
export declare const GraphicsConfigTemplate: $.java.awt.GraphicsConfigTemplate_C;
export declare type GraphicsConfiguration = $.java.awt.GraphicsConfiguration;
export declare const GraphicsConfiguration: $.java.awt.GraphicsConfiguration_C;
export declare type GraphicsDevice = $.java.awt.GraphicsDevice;
export declare const GraphicsDevice: $.java.awt.GraphicsDevice_C;
export declare type GraphicsDevice$WindowTranslucency = $.java.awt.GraphicsDevice$WindowTranslucency;
export declare const GraphicsDevice$WindowTranslucency: typeof $.java.awt.GraphicsDevice$WindowTranslucency;
export declare type Image = $.java.awt.Image;
export declare const Image: $.java.awt.Image_C;
export declare type ImageCapabilities = $.java.awt.ImageCapabilities;
export declare const ImageCapabilities: $.java.awt.ImageCapabilities_C;
export declare type Insets = $.java.awt.Insets;
export declare const Insets: $.java.awt.Insets_C;
export declare type JobAttributes = $.java.awt.JobAttributes;
export declare const JobAttributes: $.java.awt.JobAttributes_C;
export declare type JobAttributes$DefaultSelectionType = $.java.awt.JobAttributes$DefaultSelectionType;
export declare const JobAttributes$DefaultSelectionType: $.java.awt.JobAttributes$DefaultSelectionType_C;
export declare type JobAttributes$DestinationType = $.java.awt.JobAttributes$DestinationType;
export declare const JobAttributes$DestinationType: $.java.awt.JobAttributes$DestinationType_C;
export declare type JobAttributes$DialogType = $.java.awt.JobAttributes$DialogType;
export declare const JobAttributes$DialogType: $.java.awt.JobAttributes$DialogType_C;
export declare type JobAttributes$MultipleDocumentHandlingType = $.java.awt.JobAttributes$MultipleDocumentHandlingType;
export declare const JobAttributes$MultipleDocumentHandlingType: $.java.awt.JobAttributes$MultipleDocumentHandlingType_C;
export declare type JobAttributes$SidesType = $.java.awt.JobAttributes$SidesType;
export declare const JobAttributes$SidesType: $.java.awt.JobAttributes$SidesType_C;
export declare type LayoutManager = $.java.awt.LayoutManager;
export declare const LayoutManager: $.java.awt.LayoutManager;
export declare type Menu = $.java.awt.Menu;
export declare const Menu: $.java.awt.Menu_C;
export declare type MenuBar = $.java.awt.MenuBar;
export declare const MenuBar: $.java.awt.MenuBar_C;
export declare type MenuComponent = $.java.awt.MenuComponent;
export declare const MenuComponent: $.java.awt.MenuComponent_C;
export declare type MenuContainer = $.java.awt.MenuContainer;
export declare const MenuContainer: $.java.awt.MenuContainer;
export declare type MenuItem = $.java.awt.MenuItem;
export declare const MenuItem: $.java.awt.MenuItem_C;
export declare type MenuShortcut = $.java.awt.MenuShortcut;
export declare const MenuShortcut: $.java.awt.MenuShortcut_C;
export declare type PageAttributes = $.java.awt.PageAttributes;
export declare const PageAttributes: $.java.awt.PageAttributes_C;
export declare type PageAttributes$ColorType = $.java.awt.PageAttributes$ColorType;
export declare const PageAttributes$ColorType: $.java.awt.PageAttributes$ColorType_C;
export declare type PageAttributes$MediaType = $.java.awt.PageAttributes$MediaType;
export declare const PageAttributes$MediaType: $.java.awt.PageAttributes$MediaType_C;
export declare type PageAttributes$OrientationRequestedType = $.java.awt.PageAttributes$OrientationRequestedType;
export declare const PageAttributes$OrientationRequestedType: $.java.awt.PageAttributes$OrientationRequestedType_C;
export declare type PageAttributes$OriginType = $.java.awt.PageAttributes$OriginType;
export declare const PageAttributes$OriginType: $.java.awt.PageAttributes$OriginType_C;
export declare type PageAttributes$PrintQualityType = $.java.awt.PageAttributes$PrintQualityType;
export declare const PageAttributes$PrintQualityType: $.java.awt.PageAttributes$PrintQualityType_C;
export declare type Paint = $.java.awt.Paint;
export declare const Paint: $.java.awt.Paint;
export declare type PaintContext = $.java.awt.PaintContext;
export declare const PaintContext: $.java.awt.PaintContext;
export declare type Point = $.java.awt.Point;
export declare const Point: $.java.awt.Point_C;
export declare type Polygon = $.java.awt.Polygon;
export declare const Polygon: $.java.awt.Polygon_C;
export declare type PopupMenu = $.java.awt.PopupMenu;
export declare const PopupMenu: $.java.awt.PopupMenu_C;
export declare type PrintJob = $.java.awt.PrintJob;
export declare const PrintJob: $.java.awt.PrintJob_C;
export declare type Rectangle = $.java.awt.Rectangle;
export declare const Rectangle: $.java.awt.Rectangle_C;
export declare type RenderingHints = $.java.awt.RenderingHints;
export declare const RenderingHints: $.java.awt.RenderingHints_C;
export declare type RenderingHints$Key = $.java.awt.RenderingHints$Key;
export declare const RenderingHints$Key: $.java.awt.RenderingHints$Key_C;
export declare type SecondaryLoop = $.java.awt.SecondaryLoop;
export declare const SecondaryLoop: $.java.awt.SecondaryLoop;
export declare type Shape = $.java.awt.Shape;
export declare const Shape: $.java.awt.Shape;
export declare type Stroke = $.java.awt.Stroke;
export declare const Stroke: $.java.awt.Stroke;
export declare type Toolkit = $.java.awt.Toolkit;
export declare const Toolkit: $.java.awt.Toolkit_C;
export declare type Transparency = $.java.awt.Transparency;
export declare const Transparency: $.java.awt.Transparency;
export declare type Window = $.java.awt.Window;
export declare const Window: $.java.awt.Window_C;
export declare type Window$Type = $.java.awt.Window$Type;
export declare const Window$Type: typeof $.java.awt.Window$Type;
