/// <reference path="../index.d.ts" />
export declare type Appendable = $.java.lang.Appendable;
export declare const Appendable: $.java.lang.Appendable;
export declare type AutoCloseable = $.java.lang.AutoCloseable;
export declare const AutoCloseable: $.java.lang.AutoCloseable;
export declare type CharSequence = $.java.lang.CharSequence;
export declare const CharSequence: $.java.lang.CharSequence;
export declare type Character$Subset = $.java.lang.Character$Subset;
export declare const Character$Subset: $.java.lang.Character$Subset_C;
export declare type Cloneable = $.java.lang.Cloneable;
export declare const Cloneable: $.java.lang.Cloneable;
export declare type Comparable = $.java.lang.Comparable;
export declare const Comparable: $.java.lang.Comparable;
export declare type Enum = $.java.lang.Enum;
export declare const Enum: $.java.lang.Enum_C;
export declare type Exception = $.java.lang.Exception;
export declare const Exception: $.java.lang.Exception_C;
export declare type Iterable = $.java.lang.Iterable;
export declare const Iterable: $.java.lang.Iterable;
export declare type Long = $.java.lang.Long;
export declare const Long: $.java.lang.Long_C;
export declare type Package = $.java.lang.Package;
export declare const Package: $.java.lang.Package_C;
export declare type Readable = $.java.lang.Readable;
export declare const Readable: $.java.lang.Readable;
export declare type Runnable = $.java.lang.Runnable;
export declare const Runnable: $.java.lang.Runnable;
export declare type StackTraceElement = $.java.lang.StackTraceElement;
export declare const StackTraceElement: $.java.lang.StackTraceElement_C;
export declare type StringBuffer = $.java.lang.StringBuffer;
export declare const StringBuffer: $.java.lang.StringBuffer_C;
export declare type StringBuilder = $.java.lang.StringBuilder;
export declare const StringBuilder: $.java.lang.StringBuilder_C;
export declare type Throwable = $.java.lang.Throwable;
export declare const Throwable: $.java.lang.Throwable_C;
