/// <reference path="../index.d.ts" />
export declare type ContentHandler = $.java.net.ContentHandler;
export declare const ContentHandler: $.java.net.ContentHandler_C;
export declare type ContentHandlerFactory = $.java.net.ContentHandlerFactory;
export declare const ContentHandlerFactory: $.java.net.ContentHandlerFactory;
export declare type FileNameMap = $.java.net.FileNameMap;
export declare const FileNameMap: $.java.net.FileNameMap;
export declare type Proxy = $.java.net.Proxy;
export declare const Proxy: $.java.net.Proxy_C;
export declare type Proxy$Type = $.java.net.Proxy$Type;
export declare const Proxy$Type: typeof $.java.net.Proxy$Type;
export declare type URI = $.java.net.URI;
export declare const URI: $.java.net.URI_C;
export declare type URL = $.java.net.URL;
export declare const URL: $.java.net.URL_C;
export declare type URLConnection = $.java.net.URLConnection;
export declare const URLConnection: $.java.net.URLConnection_C;
export declare type URLStreamHandler = $.java.net.URLStreamHandler;
export declare const URLStreamHandler: $.java.net.URLStreamHandler_C;
export declare type URLStreamHandlerFactory = $.java.net.URLStreamHandlerFactory;
export declare const URLStreamHandlerFactory: $.java.net.URLStreamHandlerFactory;
