/// <reference path="../index.d.ts" />
export declare type AccessControlContext = $.java.security.AccessControlContext;
export declare const AccessControlContext: $.java.security.AccessControlContext_C;
export declare type AlgorithmParameters = $.java.security.AlgorithmParameters;
export declare const AlgorithmParameters: $.java.security.AlgorithmParameters_C;
export declare type CodeSigner = $.java.security.CodeSigner;
export declare const CodeSigner: $.java.security.CodeSigner_C;
export declare type CodeSource = $.java.security.CodeSource;
export declare const CodeSource: $.java.security.CodeSource_C;
export declare type DomainCombiner = $.java.security.DomainCombiner;
export declare const DomainCombiner: $.java.security.DomainCombiner;
export declare type Guard = $.java.security.Guard;
export declare const Guard: $.java.security.Guard;
export declare type Key = $.java.security.Key;
export declare const Key: $.java.security.Key;
export declare type Permission = $.java.security.Permission;
export declare const Permission: $.java.security.Permission_C;
export declare type PermissionCollection = $.java.security.PermissionCollection;
export declare const PermissionCollection: $.java.security.PermissionCollection_C;
export declare type Principal = $.java.security.Principal;
export declare const Principal: $.java.security.Principal;
export declare type PrivilegedAction = $.java.security.PrivilegedAction;
export declare const PrivilegedAction: $.java.security.PrivilegedAction;
export declare type PrivilegedExceptionAction = $.java.security.PrivilegedExceptionAction;
export declare const PrivilegedExceptionAction: $.java.security.PrivilegedExceptionAction;
export declare type ProtectionDomain = $.java.security.ProtectionDomain;
export declare const ProtectionDomain: $.java.security.ProtectionDomain_C;
export declare type Provider = $.java.security.Provider;
export declare const Provider: $.java.security.Provider_C;
export declare type Provider$Service = $.java.security.Provider$Service;
export declare const Provider$Service: $.java.security.Provider$Service_C;
export declare type PublicKey = $.java.security.PublicKey;
export declare const PublicKey: $.java.security.PublicKey;
export declare type SecureRandom = $.java.security.SecureRandom;
export declare const SecureRandom: $.java.security.SecureRandom_C;
export declare type Timestamp = $.java.security.Timestamp;
export declare const Timestamp: $.java.security.Timestamp_C;
