/// <reference path="../index.d.ts" />
export declare type Array = $.java.sql.Array;
export declare const Array: $.java.sql.Array;
export declare type Blob = $.java.sql.Blob;
export declare const Blob: $.java.sql.Blob;
export declare type CallableStatement = $.java.sql.CallableStatement;
export declare const CallableStatement: $.java.sql.CallableStatement;
export declare type Clob = $.java.sql.Clob;
export declare const Clob: $.java.sql.Clob;
export declare type Connection = $.java.sql.Connection;
export declare const Connection: $.java.sql.Connection;
export declare type DatabaseMetaData = $.java.sql.DatabaseMetaData;
export declare const DatabaseMetaData: $.java.sql.DatabaseMetaData;
export declare type NClob = $.java.sql.NClob;
export declare const NClob: $.java.sql.NClob;
export declare type ParameterMetaData = $.java.sql.ParameterMetaData;
export declare const ParameterMetaData: $.java.sql.ParameterMetaData;
export declare type PreparedStatement = $.java.sql.PreparedStatement;
export declare const PreparedStatement: $.java.sql.PreparedStatement;
export declare type Ref = $.java.sql.Ref;
export declare const Ref: $.java.sql.Ref;
export declare type ResultSet = $.java.sql.ResultSet;
export declare const ResultSet: $.java.sql.ResultSet;
export declare type ResultSetMetaData = $.java.sql.ResultSetMetaData;
export declare const ResultSetMetaData: $.java.sql.ResultSetMetaData;
export declare type RowId = $.java.sql.RowId;
export declare const RowId: $.java.sql.RowId;
export declare type RowIdLifetime = $.java.sql.RowIdLifetime;
export declare const RowIdLifetime: typeof $.java.sql.RowIdLifetime;
export declare type SQLException = $.java.sql.SQLException;
export declare const SQLException: $.java.sql.SQLException_C;
export declare type SQLType = $.java.sql.SQLType;
export declare const SQLType: $.java.sql.SQLType;
export declare type SQLWarning = $.java.sql.SQLWarning;
export declare const SQLWarning: $.java.sql.SQLWarning_C;
export declare type SQLXML = $.java.sql.SQLXML;
export declare const SQLXML: $.java.sql.SQLXML;
export declare type Savepoint = $.java.sql.Savepoint;
export declare const Savepoint: $.java.sql.Savepoint;
export declare type Statement = $.java.sql.Statement;
export declare const Statement: $.java.sql.Statement;
export declare type Struct = $.java.sql.Struct;
export declare const Struct: $.java.sql.Struct;
export declare type Wrapper = $.java.sql.Wrapper;
export declare const Wrapper: $.java.sql.Wrapper;
