/// <reference path="../index.d.ts" />
export declare type Clock = $.java.time.Clock;
export declare const Clock: $.java.time.Clock_C;
export declare type DayOfWeek = $.java.time.DayOfWeek;
export declare const DayOfWeek: typeof $.java.time.DayOfWeek;
export declare type Duration = $.java.time.Duration;
export declare const Duration: $.java.time.Duration_C;
export declare type Instant = $.java.time.Instant;
export declare const Instant: $.java.time.Instant_C;
export declare type LocalDate = $.java.time.LocalDate;
export declare const LocalDate: $.java.time.LocalDate_C;
export declare type LocalDateTime = $.java.time.LocalDateTime;
export declare const LocalDateTime: $.java.time.LocalDateTime_C;
export declare type LocalTime = $.java.time.LocalTime;
export declare const LocalTime: $.java.time.LocalTime_C;
export declare type Month = $.java.time.Month;
export declare const Month: typeof $.java.time.Month;
export declare type OffsetDateTime = $.java.time.OffsetDateTime;
export declare const OffsetDateTime: $.java.time.OffsetDateTime_C;
export declare type OffsetTime = $.java.time.OffsetTime;
export declare const OffsetTime: $.java.time.OffsetTime_C;
export declare type Period = $.java.time.Period;
export declare const Period: $.java.time.Period_C;
export declare type ZoneId = $.java.time.ZoneId;
export declare const ZoneId: $.java.time.ZoneId_C;
export declare type ZoneOffset = $.java.time.ZoneOffset;
export declare const ZoneOffset: $.java.time.ZoneOffset_C;
export declare type ZonedDateTime = $.java.time.ZonedDateTime;
export declare const ZonedDateTime: $.java.time.ZonedDateTime_C;
