/// <reference path="../index.d.ts" />
export declare type AbstractCollection = $.java.util.AbstractCollection;
export declare const AbstractCollection: $.java.util.AbstractCollection_C;
export declare type AbstractList = $.java.util.AbstractList;
export declare const AbstractList: $.java.util.AbstractList_C;
export declare type AbstractMap = $.java.util.AbstractMap;
export declare const AbstractMap: $.java.util.AbstractMap_C;
export declare type AbstractSequentialList = $.java.util.AbstractSequentialList;
export declare const AbstractSequentialList: $.java.util.AbstractSequentialList_C;
export declare type AbstractSet = $.java.util.AbstractSet;
export declare const AbstractSet: $.java.util.AbstractSet_C;
export declare type ArrayList = $.java.util.ArrayList;
export declare const ArrayList: $.java.util.ArrayList_C;
export declare type BitSet = $.java.util.BitSet;
export declare const BitSet: $.java.util.BitSet_C;
export declare type Calendar = $.java.util.Calendar;
export declare const Calendar: $.java.util.Calendar_C;
export declare type Collection = $.java.util.Collection;
export declare const Collection: $.java.util.Collection;
export declare type Comparator = $.java.util.Comparator;
export declare const Comparator: $.java.util.Comparator;
export declare type Currency = $.java.util.Currency;
export declare const Currency: $.java.util.Currency_C;
export declare type Deque = $.java.util.Deque;
export declare const Deque: $.java.util.Deque;
export declare type Dictionary = $.java.util.Dictionary;
export declare const Dictionary: $.java.util.Dictionary_C;
export declare type DoubleSummaryStatistics = $.java.util.DoubleSummaryStatistics;
export declare const DoubleSummaryStatistics: $.java.util.DoubleSummaryStatistics_C;
export declare type EnumMap = $.java.util.EnumMap;
export declare const EnumMap: $.java.util.EnumMap_C;
export declare type EnumSet = $.java.util.EnumSet;
export declare const EnumSet: $.java.util.EnumSet_C;
export declare type Enumeration = $.java.util.Enumeration;
export declare const Enumeration: $.java.util.Enumeration;
export declare type EventListener = $.java.util.EventListener;
export declare const EventListener: $.java.util.EventListener;
export declare type EventObject = $.java.util.EventObject;
export declare const EventObject: $.java.util.EventObject_C;
export declare type GregorianCalendar = $.java.util.GregorianCalendar;
export declare const GregorianCalendar: $.java.util.GregorianCalendar_C;
export declare type HashMap = $.java.util.HashMap;
export declare const HashMap: $.java.util.HashMap_C;
export declare type HashSet = $.java.util.HashSet;
export declare const HashSet: $.java.util.HashSet_C;
export declare type Hashtable = $.java.util.Hashtable;
export declare const Hashtable: $.java.util.Hashtable_C;
export declare type IntSummaryStatistics = $.java.util.IntSummaryStatistics;
export declare const IntSummaryStatistics: $.java.util.IntSummaryStatistics_C;
export declare type Iterator = $.java.util.Iterator;
export declare const Iterator: $.java.util.Iterator;
export declare type LinkedHashMap = $.java.util.LinkedHashMap;
export declare const LinkedHashMap: $.java.util.LinkedHashMap_C;
export declare type LinkedList = $.java.util.LinkedList;
export declare const LinkedList: $.java.util.LinkedList_C;
export declare type List = $.java.util.List;
export declare const List: $.java.util.List;
export declare type ListIterator = $.java.util.ListIterator;
export declare const ListIterator: $.java.util.ListIterator;
export declare type Locale = $.java.util.Locale;
export declare const Locale: $.java.util.Locale_C;
export declare type Locale$Category = $.java.util.Locale$Category;
export declare const Locale$Category: typeof $.java.util.Locale$Category;
export declare type Locale$FilteringMode = $.java.util.Locale$FilteringMode;
export declare const Locale$FilteringMode: typeof $.java.util.Locale$FilteringMode;
export declare type LongSummaryStatistics = $.java.util.LongSummaryStatistics;
export declare const LongSummaryStatistics: $.java.util.LongSummaryStatistics_C;
export declare type Map = $.java.util.Map;
export declare const Map: $.java.util.Map;
export declare type Map$Entry = $.java.util.Map$Entry;
export declare const Map$Entry: $.java.util.Map$Entry;
export declare type NavigableMap = $.java.util.NavigableMap;
export declare const NavigableMap: $.java.util.NavigableMap;
export declare type NavigableSet = $.java.util.NavigableSet;
export declare const NavigableSet: $.java.util.NavigableSet;
export declare type Optional = $.java.util.Optional;
export declare const Optional: $.java.util.Optional_C;
export declare type OptionalDouble = $.java.util.OptionalDouble;
export declare const OptionalDouble: $.java.util.OptionalDouble_C;
export declare type OptionalInt = $.java.util.OptionalInt;
export declare const OptionalInt: $.java.util.OptionalInt_C;
export declare type OptionalLong = $.java.util.OptionalLong;
export declare const OptionalLong: $.java.util.OptionalLong_C;
export declare type PrimitiveIterator = $.java.util.PrimitiveIterator;
export declare const PrimitiveIterator: $.java.util.PrimitiveIterator;
export declare type PrimitiveIterator$OfDouble = $.java.util.PrimitiveIterator$OfDouble;
export declare const PrimitiveIterator$OfDouble: $.java.util.PrimitiveIterator$OfDouble;
export declare type PrimitiveIterator$OfInt = $.java.util.PrimitiveIterator$OfInt;
export declare const PrimitiveIterator$OfInt: $.java.util.PrimitiveIterator$OfInt;
export declare type PrimitiveIterator$OfLong = $.java.util.PrimitiveIterator$OfLong;
export declare const PrimitiveIterator$OfLong: $.java.util.PrimitiveIterator$OfLong;
export declare type Properties = $.java.util.Properties;
export declare const Properties: $.java.util.Properties_C;
export declare type Queue = $.java.util.Queue;
export declare const Queue: $.java.util.Queue;
export declare type Random = $.java.util.Random;
export declare const Random: $.java.util.Random_C;
export declare type RandomAccess = $.java.util.RandomAccess;
export declare const RandomAccess: $.java.util.RandomAccess;
export declare type Set = $.java.util.Set;
export declare const Set: $.java.util.Set;
export declare type SortedMap = $.java.util.SortedMap;
export declare const SortedMap: $.java.util.SortedMap;
export declare type SortedSet = $.java.util.SortedSet;
export declare const SortedSet: $.java.util.SortedSet;
export declare type Spliterator = $.java.util.Spliterator;
export declare const Spliterator: $.java.util.Spliterator;
export declare type Spliterator$OfDouble = $.java.util.Spliterator$OfDouble;
export declare const Spliterator$OfDouble: $.java.util.Spliterator$OfDouble;
export declare type Spliterator$OfInt = $.java.util.Spliterator$OfInt;
export declare const Spliterator$OfInt: $.java.util.Spliterator$OfInt;
export declare type Spliterator$OfLong = $.java.util.Spliterator$OfLong;
export declare const Spliterator$OfLong: $.java.util.Spliterator$OfLong;
export declare type Spliterator$OfPrimitive = $.java.util.Spliterator$OfPrimitive;
export declare const Spliterator$OfPrimitive: $.java.util.Spliterator$OfPrimitive;
export declare type TimeZone = $.java.util.TimeZone;
export declare const TimeZone: $.java.util.TimeZone_C;
export declare type TreeMap = $.java.util.TreeMap;
export declare const TreeMap: $.java.util.TreeMap_C;
export declare type TreeSet = $.java.util.TreeSet;
export declare const TreeSet: $.java.util.TreeSet_C;
export declare type UUID = $.java.util.UUID;
export declare const UUID: $.java.util.UUID_C;
export declare type Vector = $.java.util.Vector;
export declare const Vector: $.java.util.Vector_C;
