export declare type AnchorControl = $.kd.bos.ext.form.control.AnchorControl;
export declare const AnchorControl: $.kd.bos.ext.form.control.AnchorControl_C;
export declare type AppStarted = $.kd.bos.ext.form.control.AppStarted;
export declare const AppStarted: $.kd.bos.ext.form.control.AppStarted_C;
export declare type Audio = $.kd.bos.ext.form.control.Audio;
export declare const Audio: $.kd.bos.ext.form.control.Audio_C;
export declare type CommonFunctionControl = $.kd.bos.ext.form.control.CommonFunctionControl;
export declare const CommonFunctionControl: $.kd.bos.ext.form.control.CommonFunctionControl_C;
export declare type CountDown = $.kd.bos.ext.form.control.CountDown;
export declare const CountDown: $.kd.bos.ext.form.control.CountDown_C;
export declare type CustomControl = $.kd.bos.ext.form.control.CustomControl;
export declare const CustomControl: $.kd.bos.ext.form.control.CustomControl_C;
export declare type HelpCenter = $.kd.bos.ext.form.control.HelpCenter;
export declare const HelpCenter: $.kd.bos.ext.form.control.HelpCenter_C;
export declare type Listbox = $.kd.bos.ext.form.control.Listbox;
export declare const Listbox: $.kd.bos.ext.form.control.Listbox_C;
export declare type LittleK = $.kd.bos.ext.form.control.LittleK;
export declare const LittleK: $.kd.bos.ext.form.control.LittleK_C;
export declare type MapControl = $.kd.bos.ext.form.control.MapControl;
export declare const MapControl: $.kd.bos.ext.form.control.MapControl_C;
export declare type Markdown = $.kd.bos.ext.form.control.Markdown;
export declare const Markdown: $.kd.bos.ext.form.control.Markdown_C;
export declare type Media = $.kd.bos.ext.form.control.Media;
export declare const Media: $.kd.bos.ext.form.control.Media_C;
export declare type SuspendButton = $.kd.bos.ext.form.control.SuspendButton;
export declare const SuspendButton: $.kd.bos.ext.form.control.SuspendButton_C;
export declare type TilePanel = $.kd.bos.ext.form.control.TilePanel;
export declare const TilePanel: $.kd.bos.ext.form.control.TilePanel_C;
export declare type Video = $.kd.bos.ext.form.control.Video;
export declare const Video: $.kd.bos.ext.form.control.Video_C;
