export declare type AfterAddRowEventArgs = $.kd.bos.entity.datamodel.events.AfterAddRowEventArgs;
export declare const AfterAddRowEventArgs: $.kd.bos.entity.datamodel.events.AfterAddRowEventArgs_C;
export declare type AfterDeleteEntryEventArgs = $.kd.bos.entity.datamodel.events.AfterDeleteEntryEventArgs;
export declare const AfterDeleteEntryEventArgs: $.kd.bos.entity.datamodel.events.AfterDeleteEntryEventArgs_C;
export declare type AfterDeleteRowEventArgs = $.kd.bos.entity.datamodel.events.AfterDeleteRowEventArgs;
export declare const AfterDeleteRowEventArgs: $.kd.bos.entity.datamodel.events.AfterDeleteRowEventArgs_C;
export declare type AfterMoveEntryEventArgs = $.kd.bos.entity.datamodel.events.AfterMoveEntryEventArgs;
export declare const AfterMoveEntryEventArgs: $.kd.bos.entity.datamodel.events.AfterMoveEntryEventArgs_C;
export declare type AfterTogetherMoveEntryRowEventArgs = $.kd.bos.entity.datamodel.events.AfterTogetherMoveEntryRowEventArgs;
export declare const AfterTogetherMoveEntryRowEventArgs: $.kd.bos.entity.datamodel.events.AfterTogetherMoveEntryRowEventArgs_C;
export declare type BeforeAddRowEventArgs = $.kd.bos.entity.datamodel.events.BeforeAddRowEventArgs;
export declare const BeforeAddRowEventArgs: $.kd.bos.entity.datamodel.events.BeforeAddRowEventArgs_C;
export declare type BeforeDeleteEntryEventArgs = $.kd.bos.entity.datamodel.events.BeforeDeleteEntryEventArgs;
export declare const BeforeDeleteEntryEventArgs: $.kd.bos.entity.datamodel.events.BeforeDeleteEntryEventArgs_C;
export declare type BeforeDeleteRowEventArgs = $.kd.bos.entity.datamodel.events.BeforeDeleteRowEventArgs;
export declare const BeforeDeleteRowEventArgs: $.kd.bos.entity.datamodel.events.BeforeDeleteRowEventArgs_C;
export declare type BeforeImportDataEventArgs = $.kd.bos.entity.datamodel.events.BeforeImportDataEventArgs;
export declare const BeforeImportDataEventArgs: $.kd.bos.entity.datamodel.events.BeforeImportDataEventArgs_C;
export declare type BeforeImportEntryEventArgs = $.kd.bos.entity.datamodel.events.BeforeImportEntryEventArgs;
export declare const BeforeImportEntryEventArgs: $.kd.bos.entity.datamodel.events.BeforeImportEntryEventArgs_C;
export declare type BeforePackageDataEvent = $.kd.bos.entity.datamodel.events.BeforePackageDataEvent;
export declare const BeforePackageDataEvent: $.kd.bos.entity.datamodel.events.BeforePackageDataEvent_C;
export declare type BeforeSetItemValueEventArgs = $.kd.bos.entity.datamodel.events.BeforeSetItemValueEventArgs;
export declare const BeforeSetItemValueEventArgs: $.kd.bos.entity.datamodel.events.BeforeSetItemValueEventArgs_C;
export declare type BeforeTogetherMoveEntryRowEventArgs = $.kd.bos.entity.datamodel.events.BeforeTogetherMoveEntryRowEventArgs;
export declare const BeforeTogetherMoveEntryRowEventArgs: $.kd.bos.entity.datamodel.events.BeforeTogetherMoveEntryRowEventArgs_C;
export declare type BizDataEventArgs = $.kd.bos.entity.datamodel.events.BizDataEventArgs;
export declare const BizDataEventArgs: $.kd.bos.entity.datamodel.events.BizDataEventArgs_C;
export declare type ChangeData = $.kd.bos.entity.datamodel.events.ChangeData;
export declare const ChangeData: $.kd.bos.entity.datamodel.events.ChangeData_C;
export declare type GetEntityTypeEventArgs = $.kd.bos.entity.datamodel.events.GetEntityTypeEventArgs;
export declare const GetEntityTypeEventArgs: $.kd.bos.entity.datamodel.events.GetEntityTypeEventArgs_C;
export declare type IDataModelChangeListener = $.kd.bos.entity.datamodel.events.IDataModelChangeListener;
export declare const IDataModelChangeListener: $.kd.bos.entity.datamodel.events.IDataModelChangeListener;
export declare type IDataModelListener = $.kd.bos.entity.datamodel.events.IDataModelListener;
export declare const IDataModelListener: $.kd.bos.entity.datamodel.events.IDataModelListener;
export declare type ImportDataEventArgs = $.kd.bos.entity.datamodel.events.ImportDataEventArgs;
export declare const ImportDataEventArgs: $.kd.bos.entity.datamodel.events.ImportDataEventArgs_C;
export declare type InitImportDataEventArgs = $.kd.bos.entity.datamodel.events.InitImportDataEventArgs;
export declare const InitImportDataEventArgs: $.kd.bos.entity.datamodel.events.InitImportDataEventArgs_C;
export declare type LoadDataEventArgs = $.kd.bos.entity.datamodel.events.LoadDataEventArgs;
export declare const LoadDataEventArgs: $.kd.bos.entity.datamodel.events.LoadDataEventArgs_C;
export declare type PackageDataEvent = $.kd.bos.entity.datamodel.events.PackageDataEvent;
export declare const PackageDataEvent: $.kd.bos.entity.datamodel.events.PackageDataEvent_C;
export declare type PropertyChangedArgs = $.kd.bos.entity.datamodel.events.PropertyChangedArgs;
export declare const PropertyChangedArgs: $.kd.bos.entity.datamodel.events.PropertyChangedArgs_C;
export declare type QueryImportBasedataEventArgs = $.kd.bos.entity.datamodel.events.QueryImportBasedataEventArgs;
export declare const QueryImportBasedataEventArgs: $.kd.bos.entity.datamodel.events.QueryImportBasedataEventArgs_C;
