export declare type PoolRejectedExecutionHandler = $.kd.bos.unifiedthreadpool.api.PoolRejectedExecutionHandler;
export declare const PoolRejectedExecutionHandler: $.kd.bos.unifiedthreadpool.api.PoolRejectedExecutionHandler;
export declare type ThreadExecutorService = $.kd.bos.unifiedthreadpool.api.ThreadExecutorService;
export declare const ThreadExecutorService: $.kd.bos.unifiedthreadpool.api.ThreadExecutorService;
export declare type ThreadPoolFactory = $.kd.bos.unifiedthreadpool.api.ThreadPoolFactory;
export declare const ThreadPoolFactory: $.kd.bos.unifiedthreadpool.api.ThreadPoolFactory_C;
export declare type ThreadPoolStrategy = $.kd.bos.unifiedthreadpool.api.ThreadPoolStrategy;
export declare const ThreadPoolStrategy: $.kd.bos.unifiedthreadpool.api.ThreadPoolStrategy;
export declare type ThreadPoolStrategyFactory = $.kd.bos.unifiedthreadpool.api.ThreadPoolStrategyFactory;
export declare const ThreadPoolStrategyFactory: $.kd.bos.unifiedthreadpool.api.ThreadPoolStrategyFactory_C;
