export declare type HasPermDimObjResult = $.kd.bos.permission.api.HasPermDimObjResult;
export declare const HasPermDimObjResult: $.kd.bos.permission.api.HasPermDimObjResult;
export declare type HasPermOrgResult = $.kd.bos.permission.api.HasPermOrgResult;
export declare const HasPermOrgResult: $.kd.bos.permission.api.HasPermOrgResult;
export declare type AdminAppResult = $.kd.bos.permission.api.AdminAppResult;
export declare const AdminAppResult: $.kd.bos.permission.api.AdminAppResult_C;
export declare type BizRoleInfo = $.kd.bos.permission.api.BizRoleInfo;
export declare const BizRoleInfo: $.kd.bos.permission.api.BizRoleInfo_C;
export declare type BizRoleInfo$BizRoleDisPerm = $.kd.bos.permission.api.BizRoleInfo$BizRoleDisPerm;
export declare const BizRoleInfo$BizRoleDisPerm: $.kd.bos.permission.api.BizRoleInfo$BizRoleDisPerm_C;
export declare type BizRoleInfo$BizRoleOrg = $.kd.bos.permission.api.BizRoleInfo$BizRoleOrg;
export declare const BizRoleInfo$BizRoleOrg: $.kd.bos.permission.api.BizRoleInfo$BizRoleOrg_C;
export declare type BizRoleInfo$BizRolePerm = $.kd.bos.permission.api.BizRoleInfo$BizRolePerm;
export declare const BizRoleInfo$BizRolePerm: $.kd.bos.permission.api.BizRoleInfo$BizRolePerm_C;
export declare type BizRoleInfo$CommonRole = $.kd.bos.permission.api.BizRoleInfo$CommonRole;
export declare const BizRoleInfo$CommonRole: $.kd.bos.permission.api.BizRoleInfo$CommonRole_C;
export declare type DimensionPermOrgResult = $.kd.bos.permission.api.DimensionPermOrgResult;
export declare const DimensionPermOrgResult: $.kd.bos.permission.api.DimensionPermOrgResult_C;
export declare type FieldControlRule = $.kd.bos.permission.api.FieldControlRule;
export declare const FieldControlRule: $.kd.bos.permission.api.FieldControlRule_C;
export declare type FieldControlRuleDto = $.kd.bos.permission.api.FieldControlRuleDto;
export declare const FieldControlRuleDto: $.kd.bos.permission.api.FieldControlRuleDto_C;
export declare type FieldControlRules = $.kd.bos.permission.api.FieldControlRules;
export declare const FieldControlRules: $.kd.bos.permission.api.FieldControlRules_C;
export declare type RoleInfo = $.kd.bos.permission.api.RoleInfo;
export declare const RoleInfo: $.kd.bos.permission.api.RoleInfo_C;
export declare type UserScopeResult = $.kd.bos.permission.api.UserScopeResult;
export declare const UserScopeResult: $.kd.bos.permission.api.UserScopeResult;
