export declare type AdminType = $.kd.bos.permission.model.AdminType;
export declare const AdminType: typeof $.kd.bos.permission.model.AdminType;
export declare type DataRuleInfo = $.kd.bos.permission.model.DataRuleInfo;
export declare const DataRuleInfo: $.kd.bos.permission.model.DataRuleInfo_C;
export declare type DataRulesInfo = $.kd.bos.permission.model.DataRulesInfo;
export declare const DataRulesInfo: $.kd.bos.permission.model.DataRulesInfo_C;
export declare type EntDataRuleInfo = $.kd.bos.permission.model.EntDataRuleInfo;
export declare const EntDataRuleInfo: $.kd.bos.permission.model.EntDataRuleInfo_C;
export declare type EntDataRuleInfo$BdPropsDataRule = $.kd.bos.permission.model.EntDataRuleInfo$BdPropsDataRule;
export declare const EntDataRuleInfo$BdPropsDataRule: $.kd.bos.permission.model.EntDataRuleInfo$BdPropsDataRule_C;
export declare type EntDataRuleInfo$PermItemsDataRule = $.kd.bos.permission.model.EntDataRuleInfo$PermItemsDataRule;
export declare const EntDataRuleInfo$PermItemsDataRule: $.kd.bos.permission.model.EntDataRuleInfo$PermItemsDataRule_C;
export declare type PermRes = $.kd.bos.permission.model.PermRes;
export declare const PermRes: $.kd.bos.permission.model.PermRes_C;
export declare type PermResult = $.kd.bos.permission.model.PermResult;
export declare const PermResult: $.kd.bos.permission.model.PermResult_C;
export declare type PersonQueryParam = $.kd.bos.permission.model.PersonQueryParam;
export declare const PersonQueryParam: $.kd.bos.permission.model.PersonQueryParam_C;
export declare type PersonQueryType = $.kd.bos.permission.model.PersonQueryType;
export declare const PersonQueryType: typeof $.kd.bos.permission.model.PersonQueryType;
