export declare type AdmGroup = $.kd.bos.permission.model.perm.AdmGroup;
export declare const AdmGroup: $.kd.bos.permission.model.perm.AdmGroup_C;
export declare type App = $.kd.bos.permission.model.perm.App;
export declare const App: $.kd.bos.permission.model.perm.App_C;
export declare type Cloud = $.kd.bos.permission.model.perm.Cloud;
export declare const Cloud: $.kd.bos.permission.model.perm.Cloud_C;
export declare type ComRoleFieldPermScheme = $.kd.bos.permission.model.perm.ComRoleFieldPermScheme;
export declare const ComRoleFieldPermScheme: $.kd.bos.permission.model.perm.ComRoleFieldPermScheme_C;
export declare type ComRoleFieldPermSchemeDetail = $.kd.bos.permission.model.perm.ComRoleFieldPermSchemeDetail;
export declare const ComRoleFieldPermSchemeDetail: $.kd.bos.permission.model.perm.ComRoleFieldPermSchemeDetail_C;
export declare type ComRoleGroup = $.kd.bos.permission.model.perm.ComRoleGroup;
export declare const ComRoleGroup: $.kd.bos.permission.model.perm.ComRoleGroup_C;
export declare type DataChangeType = $.kd.bos.permission.model.perm.DataChangeType;
export declare const DataChangeType: $.kd.bos.permission.model.perm.DataChangeType_C;
export declare type Dim = $.kd.bos.permission.model.perm.Dim;
export declare const Dim: $.kd.bos.permission.model.perm.Dim_C;
export declare type DimFieldPerm = $.kd.bos.permission.model.perm.DimFieldPerm;
export declare const DimFieldPerm: $.kd.bos.permission.model.perm.DimFieldPerm_C;
export declare type Entity = $.kd.bos.permission.model.perm.Entity;
export declare const Entity: $.kd.bos.permission.model.perm.Entity_C;
export declare type FieldPerm = $.kd.bos.permission.model.perm.FieldPerm;
export declare const FieldPerm: $.kd.bos.permission.model.perm.FieldPerm_C;
export declare type FieldPermScheme = $.kd.bos.permission.model.perm.FieldPermScheme;
export declare const FieldPermScheme: $.kd.bos.permission.model.perm.FieldPermScheme_C;
export declare type FieldPermSchemeDetail = $.kd.bos.permission.model.perm.FieldPermSchemeDetail;
export declare const FieldPermSchemeDetail: $.kd.bos.permission.model.perm.FieldPermSchemeDetail_C;
export declare type LogDrInfo = $.kd.bos.permission.model.perm.LogDrInfo;
export declare const LogDrInfo: $.kd.bos.permission.model.perm.LogDrInfo_C;
export declare type PermCtrlType = $.kd.bos.permission.model.perm.PermCtrlType;
export declare const PermCtrlType: $.kd.bos.permission.model.perm.PermCtrlType_C;
export declare type PermItem = $.kd.bos.permission.model.perm.PermItem;
export declare const PermItem: $.kd.bos.permission.model.perm.PermItem_C;
export declare type PermLevelHash = $.kd.bos.permission.model.perm.PermLevelHash;
export declare const PermLevelHash: $.kd.bos.permission.model.perm.PermLevelHash_C;
export declare type UserDimFieldPerm = $.kd.bos.permission.model.perm.UserDimFieldPerm;
export declare const UserDimFieldPerm: $.kd.bos.permission.model.perm.UserDimFieldPerm_C;
export declare type UserFieldPermScheme = $.kd.bos.permission.model.perm.UserFieldPermScheme;
export declare const UserFieldPermScheme: $.kd.bos.permission.model.perm.UserFieldPermScheme_C;
export declare type UserFieldPermSchemeDetail = $.kd.bos.permission.model.perm.UserFieldPermSchemeDetail;
export declare const UserFieldPermSchemeDetail: $.kd.bos.permission.model.perm.UserFieldPermSchemeDetail_C;
