export declare type ApiController = $.kd.bos.openapi.common.custom.annotation.ApiController;
export declare const ApiController: $.kd.bos.openapi.common.custom.annotation.ApiController;
export declare type ApiErrorCode = $.kd.bos.openapi.common.custom.annotation.ApiErrorCode;
export declare const ApiErrorCode: $.kd.bos.openapi.common.custom.annotation.ApiErrorCode;
export declare type ApiErrorCodes = $.kd.bos.openapi.common.custom.annotation.ApiErrorCodes;
export declare const ApiErrorCodes: $.kd.bos.openapi.common.custom.annotation.ApiErrorCodes;
export declare type ApiGetMapping = $.kd.bos.openapi.common.custom.annotation.ApiGetMapping;
export declare const ApiGetMapping: $.kd.bos.openapi.common.custom.annotation.ApiGetMapping;
export declare type ApiHeader = $.kd.bos.openapi.common.custom.annotation.ApiHeader;
export declare const ApiHeader: $.kd.bos.openapi.common.custom.annotation.ApiHeader;
export declare type ApiHeaders = $.kd.bos.openapi.common.custom.annotation.ApiHeaders;
export declare const ApiHeaders: $.kd.bos.openapi.common.custom.annotation.ApiHeaders;
export declare type ApiMapping = $.kd.bos.openapi.common.custom.annotation.ApiMapping;
export declare const ApiMapping: $.kd.bos.openapi.common.custom.annotation.ApiMapping;
export declare type ApiModel = $.kd.bos.openapi.common.custom.annotation.ApiModel;
export declare const ApiModel: $.kd.bos.openapi.common.custom.annotation.ApiModel;
export declare type ApiParam = $.kd.bos.openapi.common.custom.annotation.ApiParam;
export declare const ApiParam: $.kd.bos.openapi.common.custom.annotation.ApiParam;
export declare type ApiPostMapping = $.kd.bos.openapi.common.custom.annotation.ApiPostMapping;
export declare const ApiPostMapping: $.kd.bos.openapi.common.custom.annotation.ApiPostMapping;
export declare type ApiRequestBody = $.kd.bos.openapi.common.custom.annotation.ApiRequestBody;
export declare const ApiRequestBody: $.kd.bos.openapi.common.custom.annotation.ApiRequestBody;
export declare type ApiResponseBody = $.kd.bos.openapi.common.custom.annotation.ApiResponseBody;
export declare const ApiResponseBody: $.kd.bos.openapi.common.custom.annotation.ApiResponseBody;
