export declare type AfterEmbedChildPageEvent = $.kd.sdk.swc.hsas.common.events.salaryfile.AfterEmbedChildPageEvent;
export declare const AfterEmbedChildPageEvent: $.kd.sdk.swc.hsas.common.events.salaryfile.AfterEmbedChildPageEvent_C;
export declare type InitEmbedChildPageEvent = $.kd.sdk.swc.hsas.common.events.salaryfile.InitEmbedChildPageEvent;
export declare const InitEmbedChildPageEvent: $.kd.sdk.swc.hsas.common.events.salaryfile.InitEmbedChildPageEvent_C;
export declare type SalaryFileBeforeValidateDepEmpDateEvent = $.kd.sdk.swc.hsas.common.events.salaryfile.SalaryFileBeforeValidateDepEmpDateEvent;
export declare const SalaryFileBeforeValidateDepEmpDateEvent: $.kd.sdk.swc.hsas.common.events.salaryfile.SalaryFileBeforeValidateDepEmpDateEvent_C;
export declare type SalaryFileExportEvent = $.kd.sdk.swc.hsas.common.events.salaryfile.SalaryFileExportEvent;
export declare const SalaryFileExportEvent: $.kd.sdk.swc.hsas.common.events.salaryfile.SalaryFileExportEvent_C;
export declare type SalaryFileImportEvent = $.kd.sdk.swc.hsas.common.events.salaryfile.SalaryFileImportEvent;
export declare const SalaryFileImportEvent: $.kd.sdk.swc.hsas.common.events.salaryfile.SalaryFileImportEvent_C;
