export declare type AttachmentPanelMapItem = $.kd.bos.entity.botp.AttachmentPanelMapItem;
export declare const AttachmentPanelMapItem: $.kd.bos.entity.botp.AttachmentPanelMapItem_C;
export declare type AttachmentPanelMapPolicy = $.kd.bos.entity.botp.AttachmentPanelMapPolicy;
export declare const AttachmentPanelMapPolicy: $.kd.bos.entity.botp.AttachmentPanelMapPolicy_C;
export declare type BillCloseType = $.kd.bos.entity.botp.BillCloseType;
export declare const BillCloseType: typeof $.kd.bos.entity.botp.BillCloseType;
export declare type BillTypeMapItem = $.kd.bos.entity.botp.BillTypeMapItem;
export declare const BillTypeMapItem: $.kd.bos.entity.botp.BillTypeMapItem_C;
export declare type BillTypeMapPolicy = $.kd.bos.entity.botp.BillTypeMapPolicy;
export declare const BillTypeMapPolicy: $.kd.bos.entity.botp.BillTypeMapPolicy_C;
export declare type BizRulePolicy = $.kd.bos.entity.botp.BizRulePolicy;
export declare const BizRulePolicy: $.kd.bos.entity.botp.BizRulePolicy_C;
export declare type BotpModule = $.kd.bos.entity.botp.BotpModule;
export declare const BotpModule: $.kd.bos.entity.botp.BotpModule_C;
export declare type CRBizRuleElement = $.kd.bos.entity.botp.CRBizRuleElement;
export declare const CRBizRuleElement: $.kd.bos.entity.botp.CRBizRuleElement_C;
export declare type CRCondition = $.kd.bos.entity.botp.CRCondition;
export declare const CRCondition: $.kd.bos.entity.botp.CRCondition_C;
export declare type CRValByCondition = $.kd.bos.entity.botp.CRValByCondition;
export declare const CRValByCondition: $.kd.bos.entity.botp.CRValByCondition_C;
export declare type CRValByConditionType = $.kd.bos.entity.botp.CRValByConditionType;
export declare const CRValByConditionType: typeof $.kd.bos.entity.botp.CRValByConditionType;
export declare type CRValByConditions = $.kd.bos.entity.botp.CRValByConditions;
export declare const CRValByConditions: $.kd.bos.entity.botp.CRValByConditions_C;
export declare type ConvertBill = $.kd.bos.entity.botp.ConvertBill;
export declare const ConvertBill: $.kd.bos.entity.botp.ConvertBill_C;
export declare type ConvertOpType = $.kd.bos.entity.botp.ConvertOpType;
export declare const ConvertOpType: typeof $.kd.bos.entity.botp.ConvertOpType;
export declare type ConvertPath = $.kd.bos.entity.botp.ConvertPath;
export declare const ConvertPath: $.kd.bos.entity.botp.ConvertPath_C;
export declare type ConvertRuleCache = $.kd.bos.entity.botp.ConvertRuleCache;
export declare const ConvertRuleCache: $.kd.bos.entity.botp.ConvertRuleCache_C;
export declare type ConvertRuleElement = $.kd.bos.entity.botp.ConvertRuleElement;
export declare const ConvertRuleElement: $.kd.bos.entity.botp.ConvertRuleElement_C;
export declare type DistributeType = $.kd.bos.entity.botp.DistributeType;
export declare const DistributeType: typeof $.kd.bos.entity.botp.DistributeType;
export declare type ExcessCheckType = $.kd.bos.entity.botp.ExcessCheckType;
export declare const ExcessCheckType: typeof $.kd.bos.entity.botp.ExcessCheckType;
export declare type FieldConvertType = $.kd.bos.entity.botp.FieldConvertType;
export declare const FieldConvertType: typeof $.kd.bos.entity.botp.FieldConvertType;
export declare type FieldMapItem = $.kd.bos.entity.botp.FieldMapItem;
export declare const FieldMapItem: $.kd.bos.entity.botp.FieldMapItem_C;
export declare type FieldMapPolicy = $.kd.bos.entity.botp.FieldMapPolicy;
export declare const FieldMapPolicy: $.kd.bos.entity.botp.FieldMapPolicy_C;
export declare type FieldSumType = $.kd.bos.entity.botp.FieldSumType;
export declare const FieldSumType: typeof $.kd.bos.entity.botp.FieldSumType;
export declare type FilterPolicy = $.kd.bos.entity.botp.FilterPolicy;
export declare const FilterPolicy: $.kd.bos.entity.botp.FilterPolicy_C;
export declare type GroupByMode = $.kd.bos.entity.botp.GroupByMode;
export declare const GroupByMode: typeof $.kd.bos.entity.botp.GroupByMode;
export declare type GroupByPolicy = $.kd.bos.entity.botp.GroupByPolicy;
export declare const GroupByPolicy: $.kd.bos.entity.botp.GroupByPolicy_C;
export declare type LinkEntityPolicy = $.kd.bos.entity.botp.LinkEntityPolicy;
export declare const LinkEntityPolicy: $.kd.bos.entity.botp.LinkEntityPolicy_C;
export declare type LinkRecordType = $.kd.bos.entity.botp.LinkRecordType;
export declare const LinkRecordType: typeof $.kd.bos.entity.botp.LinkRecordType;
export declare type OptionPolicy = $.kd.bos.entity.botp.OptionPolicy;
export declare const OptionPolicy: $.kd.bos.entity.botp.OptionPolicy_C;
export declare type PlugInPolicy = $.kd.bos.entity.botp.PlugInPolicy;
export declare const PlugInPolicy: $.kd.bos.entity.botp.PlugInPolicy_C;
export declare type WriteBackBizRule = $.kd.bos.entity.botp.WriteBackBizRule;
export declare const WriteBackBizRule: $.kd.bos.entity.botp.WriteBackBizRule_C;
export declare type WriteBackFormula = $.kd.bos.entity.botp.WriteBackFormula;
export declare const WriteBackFormula: $.kd.bos.entity.botp.WriteBackFormula_C;
export declare type WriteBackOpType = $.kd.bos.entity.botp.WriteBackOpType;
export declare const WriteBackOpType: typeof $.kd.bos.entity.botp.WriteBackOpType;
export declare type WriteBackRuleElement = $.kd.bos.entity.botp.WriteBackRuleElement;
export declare const WriteBackRuleElement: $.kd.bos.entity.botp.WriteBackRuleElement_C;
export declare type WriteBackType = $.kd.bos.entity.botp.WriteBackType;
export declare const WriteBackType: typeof $.kd.bos.entity.botp.WriteBackType;
export declare type CRFormula = $.kd.bos.entity.botp.CRFormula;
export declare const CRFormula: $.kd.bos.entity.botp.CRFormula_C;
export declare type CRPlugin = $.kd.bos.entity.botp.CRPlugin;
export declare const CRPlugin: $.kd.bos.entity.botp.CRPlugin_C;
export declare type CheckMessage = $.kd.bos.entity.botp.CheckMessage;
export declare const CheckMessage: $.kd.bos.entity.botp.CheckMessage_C;
export declare type CheckResult = $.kd.bos.entity.botp.CheckResult;
export declare const CheckResult: $.kd.bos.entity.botp.CheckResult_C;
