export declare type CtAttachmentPanelMapItem = $.kd.bos.entity.ctbotp.CtAttachmentPanelMapItem;
export declare const CtAttachmentPanelMapItem: $.kd.bos.entity.ctbotp.CtAttachmentPanelMapItem_C;
export declare type CtAttachmentPanelMapPolicy = $.kd.bos.entity.ctbotp.CtAttachmentPanelMapPolicy;
export declare const CtAttachmentPanelMapPolicy: $.kd.bos.entity.ctbotp.CtAttachmentPanelMapPolicy_C;
export declare type CtBillTypeMapItem = $.kd.bos.entity.ctbotp.CtBillTypeMapItem;
export declare const CtBillTypeMapItem: $.kd.bos.entity.ctbotp.CtBillTypeMapItem_C;
export declare type CtBillTypeMapPolicy = $.kd.bos.entity.ctbotp.CtBillTypeMapPolicy;
export declare const CtBillTypeMapPolicy: $.kd.bos.entity.ctbotp.CtBillTypeMapPolicy_C;
export declare type CtConvertBill = $.kd.bos.entity.ctbotp.CtConvertBill;
export declare const CtConvertBill: $.kd.bos.entity.ctbotp.CtConvertBill_C;
export declare type CtConvertOpType = $.kd.bos.entity.ctbotp.CtConvertOpType;
export declare const CtConvertOpType: typeof $.kd.bos.entity.ctbotp.CtConvertOpType;
export declare type CtConvertRuleElement = $.kd.bos.entity.ctbotp.CtConvertRuleElement;
export declare const CtConvertRuleElement: $.kd.bos.entity.ctbotp.CtConvertRuleElement_C;
export declare type CtExtendedDataEntity = $.kd.bos.entity.ctbotp.CtExtendedDataEntity;
export declare const CtExtendedDataEntity: $.kd.bos.entity.ctbotp.CtExtendedDataEntity_C;
export declare type CtExtendedDataEntitySet = $.kd.bos.entity.ctbotp.CtExtendedDataEntitySet;
export declare const CtExtendedDataEntitySet: $.kd.bos.entity.ctbotp.CtExtendedDataEntitySet_C;
export declare type CtFieldMapItem = $.kd.bos.entity.ctbotp.CtFieldMapItem;
export declare const CtFieldMapItem: $.kd.bos.entity.ctbotp.CtFieldMapItem_C;
export declare type CtFieldMapPolicy = $.kd.bos.entity.ctbotp.CtFieldMapPolicy;
export declare const CtFieldMapPolicy: $.kd.bos.entity.ctbotp.CtFieldMapPolicy_C;
export declare type CtFilterPolicy = $.kd.bos.entity.ctbotp.CtFilterPolicy;
export declare const CtFilterPolicy: $.kd.bos.entity.ctbotp.CtFilterPolicy_C;
export declare type CtGroupByMode = $.kd.bos.entity.ctbotp.CtGroupByMode;
export declare const CtGroupByMode: typeof $.kd.bos.entity.ctbotp.CtGroupByMode;
export declare type CtGroupByPolicy = $.kd.bos.entity.ctbotp.CtGroupByPolicy;
export declare const CtGroupByPolicy: $.kd.bos.entity.ctbotp.CtGroupByPolicy_C;
export declare type CtLinkEntityPolicy = $.kd.bos.entity.ctbotp.CtLinkEntityPolicy;
export declare const CtLinkEntityPolicy: $.kd.bos.entity.ctbotp.CtLinkEntityPolicy_C;
export declare type CtMirrorLinkEntity = $.kd.bos.entity.ctbotp.CtMirrorLinkEntity;
export declare const CtMirrorLinkEntity: $.kd.bos.entity.ctbotp.CtMirrorLinkEntity_C;
export declare type CtOptionPolicy = $.kd.bos.entity.ctbotp.CtOptionPolicy;
export declare const CtOptionPolicy: $.kd.bos.entity.ctbotp.CtOptionPolicy_C;
export declare type CtPlugInPolicy = $.kd.bos.entity.ctbotp.CtPlugInPolicy;
export declare const CtPlugInPolicy: $.kd.bos.entity.ctbotp.CtPlugInPolicy_C;
