export declare type AbstractFormDataModel = $.kd.bos.entity.datamodel.AbstractFormDataModel;
export declare const AbstractFormDataModel: $.kd.bos.entity.datamodel.AbstractFormDataModel_C;
export declare type IParameterModel = $.kd.bos.entity.datamodel.IParameterModel;
export declare const IParameterModel: $.kd.bos.entity.datamodel.IParameterModel;
export declare type TableValueSetter = $.kd.bos.entity.datamodel.TableValueSetter;
export declare const TableValueSetter: $.kd.bos.entity.datamodel.TableValueSetter_C;
export declare type ApproverListField = $.kd.bos.entity.datamodel.ApproverListField;
export declare const ApproverListField: $.kd.bos.entity.datamodel.ApproverListField_C;
export declare type BasedataItem = $.kd.bos.entity.datamodel.BasedataItem;
export declare const BasedataItem: $.kd.bos.entity.datamodel.BasedataItem_C;
export declare type DynamicTextListField = $.kd.bos.entity.datamodel.DynamicTextListField;
export declare const DynamicTextListField: $.kd.bos.entity.datamodel.DynamicTextListField_C;
export declare type FmtField = $.kd.bos.entity.datamodel.FmtField;
export declare const FmtField: $.kd.bos.entity.datamodel.FmtField_C;
export declare type FmtInfoUtils = $.kd.bos.entity.datamodel.FmtInfoUtils;
export declare const FmtInfoUtils: $.kd.bos.entity.datamodel.FmtInfoUtils_C;
export declare type IBillModel = $.kd.bos.entity.datamodel.IBillModel;
export declare const IBillModel: $.kd.bos.entity.datamodel.IBillModel;
export declare type IDataModel = $.kd.bos.entity.datamodel.IDataModel;
export declare const IDataModel: $.kd.bos.entity.datamodel.IDataModel;
export declare type IDefValueProvider = $.kd.bos.entity.datamodel.IDefValueProvider;
export declare const IDefValueProvider: $.kd.bos.entity.datamodel.IDefValueProvider;
export declare type IEntryFilter = $.kd.bos.entity.datamodel.IEntryFilter;
export declare const IEntryFilter: $.kd.bos.entity.datamodel.IEntryFilter;
export declare type IEntryOperate = $.kd.bos.entity.datamodel.IEntryOperate;
export declare const IEntryOperate: $.kd.bos.entity.datamodel.IEntryOperate;
export declare type IFilterModel = $.kd.bos.entity.datamodel.IFilterModel;
export declare const IFilterModel: $.kd.bos.entity.datamodel.IFilterModel;
export declare type IListModel = $.kd.bos.entity.datamodel.IListModel;
export declare const IListModel: $.kd.bos.entity.datamodel.IListModel;
export declare type IListModelContext = $.kd.bos.entity.datamodel.IListModelContext;
export declare const IListModelContext: $.kd.bos.entity.datamodel.IListModelContext;
export declare type IListModelListener = $.kd.bos.entity.datamodel.IListModelListener;
export declare const IListModelListener: $.kd.bos.entity.datamodel.IListModelListener;
export declare type IRefrencedataProvider = $.kd.bos.entity.datamodel.IRefrencedataProvider;
export declare const IRefrencedataProvider: $.kd.bos.entity.datamodel.IRefrencedataProvider;
export declare type ITreeModel = $.kd.bos.entity.datamodel.ITreeModel;
export declare const ITreeModel: $.kd.bos.entity.datamodel.ITreeModel;
export declare type ListField = $.kd.bos.entity.datamodel.ListField;
export declare const ListField: $.kd.bos.entity.datamodel.ListField_C;
export declare type ListSelectedRow = $.kd.bos.entity.datamodel.ListSelectedRow;
export declare const ListSelectedRow: $.kd.bos.entity.datamodel.ListSelectedRow_C;
export declare type ListSelectedRowCollection = $.kd.bos.entity.datamodel.ListSelectedRowCollection;
export declare const ListSelectedRowCollection: $.kd.bos.entity.datamodel.ListSelectedRowCollection_C;
export declare type NumberPrecision = $.kd.bos.entity.datamodel.NumberPrecision;
export declare const NumberPrecision: $.kd.bos.entity.datamodel.NumberPrecision_C;
export declare type ORMUtil = $.kd.bos.entity.datamodel.ORMUtil;
export declare const ORMUtil: $.kd.bos.entity.datamodel.ORMUtil_C;
export declare type RowDataEntity = $.kd.bos.entity.datamodel.RowDataEntity;
export declare const RowDataEntity: $.kd.bos.entity.datamodel.RowDataEntity_C;
export declare type VoucherNoListField = $.kd.bos.entity.datamodel.VoucherNoListField;
export declare const VoucherNoListField: $.kd.bos.entity.datamodel.VoucherNoListField_C;
