export declare type FilterCondition = $.kd.bos.entity.filter.FilterCondition;
export declare const FilterCondition: $.kd.bos.entity.filter.FilterCondition_C;
export declare type FilterValue = $.kd.bos.entity.filter.FilterValue;
export declare const FilterValue: $.kd.bos.entity.filter.FilterValue_C;
export declare type SimpleFilterRow = $.kd.bos.entity.filter.SimpleFilterRow;
export declare const SimpleFilterRow: $.kd.bos.entity.filter.SimpleFilterRow_C;
export declare type AbstractFilterContantParser = $.kd.bos.entity.filter.AbstractFilterContantParser;
export declare const AbstractFilterContantParser: $.kd.bos.entity.filter.AbstractFilterContantParser_C;
export declare type ColumnParam = $.kd.bos.entity.filter.ColumnParam;
export declare const ColumnParam: $.kd.bos.entity.filter.ColumnParam_C;
export declare type CompareCategory = $.kd.bos.entity.filter.CompareCategory;
export declare const CompareCategory: $.kd.bos.entity.filter.CompareCategory_C;
export declare type CompareInputType = $.kd.bos.entity.filter.CompareInputType;
export declare const CompareInputType: typeof $.kd.bos.entity.filter.CompareInputType;
export declare type CompareType = $.kd.bos.entity.filter.CompareType;
export declare const CompareType: $.kd.bos.entity.filter.CompareType_C;
export declare type CompareTypeDto = $.kd.bos.entity.filter.CompareTypeDto;
export declare const CompareTypeDto: $.kd.bos.entity.filter.CompareTypeDto_C;
export declare type CompareTypeEnum = $.kd.bos.entity.filter.CompareTypeEnum;
export declare const CompareTypeEnum: typeof $.kd.bos.entity.filter.CompareTypeEnum;
export declare type CompareTypeValue = $.kd.bos.entity.filter.CompareTypeValue;
export declare const CompareTypeValue: $.kd.bos.entity.filter.CompareTypeValue_C;
export declare type ConditionVariableContext = $.kd.bos.entity.filter.ConditionVariableContext;
export declare const ConditionVariableContext: $.kd.bos.entity.filter.ConditionVariableContext_C;
export declare type ControlFilter = $.kd.bos.entity.filter.ControlFilter;
export declare const ControlFilter: $.kd.bos.entity.filter.ControlFilter_C;
export declare type ControlFilters = $.kd.bos.entity.filter.ControlFilters;
export declare const ControlFilters: $.kd.bos.entity.filter.ControlFilters_C;
export declare type F7FilterParam = $.kd.bos.entity.filter.F7FilterParam;
export declare const F7FilterParam: $.kd.bos.entity.filter.F7FilterParam_C;
export declare type FilterBuilder = $.kd.bos.entity.filter.FilterBuilder;
export declare const FilterBuilder: $.kd.bos.entity.filter.FilterBuilder_C;
export declare type FilterBuilderParameter = $.kd.bos.entity.filter.FilterBuilderParameter;
export declare const FilterBuilderParameter: $.kd.bos.entity.filter.FilterBuilderParameter_C;
export declare type FilterContantParserArgs = $.kd.bos.entity.filter.FilterContantParserArgs;
export declare const FilterContantParserArgs: $.kd.bos.entity.filter.FilterContantParserArgs_C;
export declare type FilterField = $.kd.bos.entity.filter.FilterField;
export declare const FilterField: $.kd.bos.entity.filter.FilterField_C;
export declare type FilterKeyValue = $.kd.bos.entity.filter.FilterKeyValue;
export declare const FilterKeyValue: $.kd.bos.entity.filter.FilterKeyValue_C;
export declare type FilterKeyValueCollection = $.kd.bos.entity.filter.FilterKeyValueCollection;
export declare const FilterKeyValueCollection: $.kd.bos.entity.filter.FilterKeyValueCollection_C;
export declare type FilterKeyValueCollections = $.kd.bos.entity.filter.FilterKeyValueCollections;
export declare const FilterKeyValueCollections: $.kd.bos.entity.filter.FilterKeyValueCollections_C;
export declare type FilterMetadata = $.kd.bos.entity.filter.FilterMetadata;
export declare const FilterMetadata: $.kd.bos.entity.filter.FilterMetadata_C;
export declare type FilterObject = $.kd.bos.entity.filter.FilterObject;
export declare const FilterObject: $.kd.bos.entity.filter.FilterObject_C;
export declare type FilterParameter = $.kd.bos.entity.filter.FilterParameter;
export declare const FilterParameter: $.kd.bos.entity.filter.FilterParameter_C;
export declare type FilterResult = $.kd.bos.entity.filter.FilterResult;
export declare const FilterResult: $.kd.bos.entity.filter.FilterResult_C;
export declare type FilterRow = $.kd.bos.entity.filter.FilterRow;
export declare const FilterRow: $.kd.bos.entity.filter.FilterRow_C;
export declare type FilterScheme = $.kd.bos.entity.filter.FilterScheme;
export declare const FilterScheme: $.kd.bos.entity.filter.FilterScheme_C;
export declare type FilterScriptBuilder = $.kd.bos.entity.filter.FilterScriptBuilder;
export declare const FilterScriptBuilder: $.kd.bos.entity.filter.FilterScriptBuilder_C;
export declare type FilterUtil = $.kd.bos.entity.filter.FilterUtil;
export declare const FilterUtil: $.kd.bos.entity.filter.FilterUtil_C;
export declare type IConditionVariableAnalysis = $.kd.bos.entity.filter.IConditionVariableAnalysis;
export declare const IConditionVariableAnalysis: $.kd.bos.entity.filter.IConditionVariableAnalysis;
export declare type IFilterValueSetter = $.kd.bos.entity.filter.IFilterValueSetter;
export declare const IFilterValueSetter: $.kd.bos.entity.filter.IFilterValueSetter;
export declare type LogicOperate = $.kd.bos.entity.filter.LogicOperate;
export declare const LogicOperate: typeof $.kd.bos.entity.filter.LogicOperate;
export declare type PermissionFilterUtil = $.kd.bos.entity.filter.PermissionFilterUtil;
export declare const PermissionFilterUtil: $.kd.bos.entity.filter.PermissionFilterUtil_C;
export declare type SortType = $.kd.bos.entity.filter.SortType;
export declare const SortType: typeof $.kd.bos.entity.filter.SortType;
