export declare type AbstractFormat = $.kd.bos.entity.format.AbstractFormat;
export declare const AbstractFormat: $.kd.bos.entity.format.AbstractFormat_C;
export declare type CurrencyFormat = $.kd.bos.entity.format.CurrencyFormat;
export declare const CurrencyFormat: $.kd.bos.entity.format.CurrencyFormat_C;
export declare type CurrencyFormatObject = $.kd.bos.entity.format.CurrencyFormatObject;
export declare const CurrencyFormatObject: $.kd.bos.entity.format.CurrencyFormatObject_C;
export declare type CurrencyPrefixType = $.kd.bos.entity.format.CurrencyPrefixType;
export declare const CurrencyPrefixType: typeof $.kd.bos.entity.format.CurrencyPrefixType;
export declare type DateFormat = $.kd.bos.entity.format.DateFormat;
export declare const DateFormat: $.kd.bos.entity.format.DateFormat_C;
export declare type DateFormatObject = $.kd.bos.entity.format.DateFormatObject;
export declare const DateFormatObject: $.kd.bos.entity.format.DateFormatObject_C;
export declare type FormatFactory = $.kd.bos.entity.format.FormatFactory;
export declare const FormatFactory: $.kd.bos.entity.format.FormatFactory_C;
export declare type FormatObject = $.kd.bos.entity.format.FormatObject;
export declare const FormatObject: $.kd.bos.entity.format.FormatObject_C;
export declare type FormatTypes = $.kd.bos.entity.format.FormatTypes;
export declare const FormatTypes: typeof $.kd.bos.entity.format.FormatTypes;
export declare type IFormat = $.kd.bos.entity.format.IFormat;
export declare const IFormat: $.kd.bos.entity.format.IFormat;
export declare type NumberFormat = $.kd.bos.entity.format.NumberFormat;
export declare const NumberFormat: $.kd.bos.entity.format.NumberFormat_C;
export declare type NumberFormatObject = $.kd.bos.entity.format.NumberFormatObject;
export declare const NumberFormatObject: $.kd.bos.entity.format.NumberFormatObject_C;
export declare type TimeFormat = $.kd.bos.entity.format.TimeFormat;
export declare const TimeFormat: $.kd.bos.entity.format.TimeFormat_C;
export declare type TimeFormatObject = $.kd.bos.entity.format.TimeFormatObject;
export declare const TimeFormatObject: $.kd.bos.entity.format.TimeFormatObject_C;
