export declare type BOSBatchFunction = $.kd.bos.entity.function_.BOSBatchFunction;
export declare const BOSBatchFunction: $.kd.bos.entity.function_.BOSBatchFunction;
export declare type BOSUDFunction = $.kd.bos.entity.function_.BOSUDFunction;
export declare const BOSUDFunction: $.kd.bos.entity.function_.BOSUDFunction;
export declare type BatchFuncParser = $.kd.bos.entity.function_.BatchFuncParser;
export declare const BatchFuncParser: $.kd.bos.entity.function_.BatchFuncParser_C;
export declare type BatchFuncRunParam = $.kd.bos.entity.function_.BatchFuncRunParam;
export declare const BatchFuncRunParam: $.kd.bos.entity.function_.BatchFuncRunParam_C;
export declare type BillFuncTypesLoader = $.kd.bos.entity.function_.BillFuncTypesLoader;
export declare const BillFuncTypesLoader: $.kd.bos.entity.function_.BillFuncTypesLoader_C;
export declare type ExprFuncCreator = $.kd.bos.entity.function_.ExprFuncCreator;
export declare const ExprFuncCreator: $.kd.bos.entity.function_.ExprFuncCreator_C;
export declare type FunctionFeatures = $.kd.bos.entity.function_.FunctionFeatures;
export declare const FunctionFeatures: $.kd.bos.entity.function_.FunctionFeatures;
export declare type FunctionGroup = $.kd.bos.entity.function_.FunctionGroup;
export declare const FunctionGroup: $.kd.bos.entity.function_.FunctionGroup_C;
export declare type FunctionManage = $.kd.bos.entity.function_.FunctionManage;
export declare const FunctionManage: $.kd.bos.entity.function_.FunctionManage_C;
export declare type FunctionType = $.kd.bos.entity.function_.FunctionType;
export declare const FunctionType: $.kd.bos.entity.function_.FunctionType_C;
export declare type FunctionTypes = $.kd.bos.entity.function_.FunctionTypes;
export declare const FunctionTypes: $.kd.bos.entity.function_.FunctionTypes_C;
export declare type UDFunctionVisitor = $.kd.bos.entity.function_.UDFunctionVisitor;
export declare const UDFunctionVisitor: $.kd.bos.entity.function_.UDFunctionVisitor_C;
