export declare type AmountGroupInfo = $.kd.bos.entity.list.AmountGroupInfo;
export declare const AmountGroupInfo: $.kd.bos.entity.list.AmountGroupInfo_C;
export declare type AsyncSummaryEnum = $.kd.bos.entity.list.AsyncSummaryEnum;
export declare const AsyncSummaryEnum: typeof $.kd.bos.entity.list.AsyncSummaryEnum;
export declare type FormatFieldData = $.kd.bos.entity.list.FormatFieldData;
export declare const FormatFieldData: $.kd.bos.entity.list.FormatFieldData_C;
export declare type FormatRowData = $.kd.bos.entity.list.FormatRowData;
export declare const FormatRowData: $.kd.bos.entity.list.FormatRowData_C;
export declare type GroupByField = $.kd.bos.entity.list.GroupByField;
export declare const GroupByField: $.kd.bos.entity.list.GroupByField_C;
export declare type GroupBySummaryResult = $.kd.bos.entity.list.GroupBySummaryResult;
export declare const GroupBySummaryResult: $.kd.bos.entity.list.GroupBySummaryResult_C;
export declare type IListDataProvider = $.kd.bos.entity.list.IListDataProvider;
export declare const IListDataProvider: $.kd.bos.entity.list.IListDataProvider;
export declare type IListDataProviderContext = $.kd.bos.entity.list.IListDataProviderContext;
export declare const IListDataProviderContext: $.kd.bos.entity.list.IListDataProviderContext;
export declare type IQuery = $.kd.bos.entity.list.IQuery;
export declare const IQuery: $.kd.bos.entity.list.IQuery;
export declare type JoinEntity = $.kd.bos.entity.list.JoinEntity;
export declare const JoinEntity: $.kd.bos.entity.list.JoinEntity_C;
export declare type JoinProperty = $.kd.bos.entity.list.JoinProperty;
export declare const JoinProperty: $.kd.bos.entity.list.JoinProperty_C;
export declare type QueryBuilder = $.kd.bos.entity.list.QueryBuilder;
export declare const QueryBuilder: $.kd.bos.entity.list.QueryBuilder_C;
export declare type QueryResult = $.kd.bos.entity.list.QueryResult;
export declare const QueryResult: $.kd.bos.entity.list.QueryResult_C;
export declare type SummaryResult = $.kd.bos.entity.list.SummaryResult;
export declare const SummaryResult: $.kd.bos.entity.list.SummaryResult_C;
export declare type TimeoutSummaryResult = $.kd.bos.entity.list.TimeoutSummaryResult;
export declare const TimeoutSummaryResult: $.kd.bos.entity.list.TimeoutSummaryResult_C;
