export declare type AttachmentView = $.kd.bos.entity.operate.AttachmentView;
export declare const AttachmentView: $.kd.bos.entity.operate.AttachmentView_C;
export declare type DefaultEntityOperate = $.kd.bos.entity.operate.DefaultEntityOperate;
export declare const DefaultEntityOperate: $.kd.bos.entity.operate.DefaultEntityOperate_C;
export declare type Delete = $.kd.bos.entity.operate.Delete;
export declare const Delete: $.kd.bos.entity.operate.Delete_C;
export declare type Donothing = $.kd.bos.entity.operate.Donothing;
export declare const Donothing: $.kd.bos.entity.operate.Donothing_C;
export declare type Save = $.kd.bos.entity.operate.Save;
export declare const Save: $.kd.bos.entity.operate.Save_C;
export declare type SaveAndNew = $.kd.bos.entity.operate.SaveAndNew;
export declare const SaveAndNew: $.kd.bos.entity.operate.SaveAndNew_C;
export declare type StatusConvert = $.kd.bos.entity.operate.StatusConvert;
export declare const StatusConvert: $.kd.bos.entity.operate.StatusConvert_C;
export declare type Submit = $.kd.bos.entity.operate.Submit;
export declare const Submit: $.kd.bos.entity.operate.Submit_C;
export declare type SubmitAndNew = $.kd.bos.entity.operate.SubmitAndNew;
export declare const SubmitAndNew: $.kd.bos.entity.operate.SubmitAndNew_C;
export declare type EnumBillStatus = $.kd.bos.entity.operate.EnumBillStatus;
export declare const EnumBillStatus: typeof $.kd.bos.entity.operate.EnumBillStatus;
export declare type IEntityOperate = $.kd.bos.entity.operate.IEntityOperate;
export declare const IEntityOperate: $.kd.bos.entity.operate.IEntityOperate;
export declare type IOperationTask = $.kd.bos.entity.operate.IOperationTask;
export declare const IOperationTask: $.kd.bos.entity.operate.IOperationTask;
export declare type KDOpAsynExecutorException = $.kd.bos.entity.operate.KDOpAsynExecutorException;
export declare const KDOpAsynExecutorException: $.kd.bos.entity.operate.KDOpAsynExecutorException_C;
export declare type OperationException = $.kd.bos.entity.operate.OperationException;
export declare const OperationException: $.kd.bos.entity.operate.OperationException_C;
export declare type AbstractOperationResult = $.kd.bos.entity.operate.AbstractOperationResult;
export declare const AbstractOperationResult: $.kd.bos.entity.operate.AbstractOperationResult_C;
export declare type GridConfigurationRow = $.kd.bos.entity.operate.GridConfigurationRow;
export declare const GridConfigurationRow: $.kd.bos.entity.operate.GridConfigurationRow_C;
export declare type IOperationResult = $.kd.bos.entity.operate.IOperationResult;
export declare const IOperationResult: $.kd.bos.entity.operate.IOperationResult;
export declare type OperateOptionConst = $.kd.bos.entity.operate.OperateOptionConst;
export declare const OperateOptionConst: $.kd.bos.entity.operate.OperateOptionConst_C;
export declare type OperationContext = $.kd.bos.entity.operate.OperationContext;
export declare const OperationContext: $.kd.bos.entity.operate.OperationContext_C;
export declare type OperationParameterNames = $.kd.bos.entity.operate.OperationParameterNames;
export declare const OperationParameterNames: $.kd.bos.entity.operate.OperationParameterNames_C;
export declare type OperationTypeCache = $.kd.bos.entity.operate.OperationTypeCache;
export declare const OperationTypeCache: $.kd.bos.entity.operate.OperationTypeCache_C;
export declare type Operations = $.kd.bos.entity.operate.Operations;
export declare const Operations: $.kd.bos.entity.operate.Operations_C;
