export declare type AppCustomParam = $.kd.bos.entity.param.AppCustomParam;
export declare const AppCustomParam: $.kd.bos.entity.param.AppCustomParam_C;
export declare type AppParam = $.kd.bos.entity.param.AppParam;
export declare const AppParam: $.kd.bos.entity.param.AppParam_C;
export declare type BillParam = $.kd.bos.entity.param.BillParam;
export declare const BillParam: $.kd.bos.entity.param.BillParam_C;
export declare type CustomParam = $.kd.bos.entity.param.CustomParam;
export declare const CustomParam: $.kd.bos.entity.param.CustomParam_C;
export declare type FuzzySearch = $.kd.bos.entity.param.FuzzySearch;
export declare const FuzzySearch: $.kd.bos.entity.param.FuzzySearch_C;
export declare type MobileListF7Config = $.kd.bos.entity.param.MobileListF7Config;
export declare const MobileListF7Config: $.kd.bos.entity.param.MobileListF7Config_C;
export declare type OverallParam = $.kd.bos.entity.param.OverallParam;
export declare const OverallParam: $.kd.bos.entity.param.OverallParam_C;
export declare type ParamKey = $.kd.bos.entity.param.ParamKey;
export declare const ParamKey: $.kd.bos.entity.param.ParamKey_C;
export declare type ParamOperationResult = $.kd.bos.entity.param.ParamOperationResult;
export declare const ParamOperationResult: $.kd.bos.entity.param.ParamOperationResult_C;
export declare type ParamPublishObject = $.kd.bos.entity.param.ParamPublishObject;
export declare const ParamPublishObject: $.kd.bos.entity.param.ParamPublishObject_C;
export declare type ParamRow = $.kd.bos.entity.param.ParamRow;
export declare const ParamRow: $.kd.bos.entity.param.ParamRow_C;
export declare type ShowColumn = $.kd.bos.entity.param.ShowColumn;
export declare const ShowColumn: $.kd.bos.entity.param.ShowColumn_C;
