export declare type AbstractDataModelPlugin = $.kd.bos.entity.plugin.AbstractDataModelPlugin;
export declare const AbstractDataModelPlugin: $.kd.bos.entity.plugin.AbstractDataModelPlugin_C;
export declare type AbstractOperationServicePlugIn = $.kd.bos.entity.plugin.AbstractOperationServicePlugIn;
export declare const AbstractOperationServicePlugIn: $.kd.bos.entity.plugin.AbstractOperationServicePlugIn_C;
export declare type AddValidatorsEventArgs = $.kd.bos.entity.plugin.AddValidatorsEventArgs;
export declare const AddValidatorsEventArgs: $.kd.bos.entity.plugin.AddValidatorsEventArgs_C;
export declare type IOperationService = $.kd.bos.entity.plugin.IOperationService;
export declare const IOperationService: $.kd.bos.entity.plugin.IOperationService;
export declare type IOperationServicePlugIn = $.kd.bos.entity.plugin.IOperationServicePlugIn;
export declare const IOperationServicePlugIn: $.kd.bos.entity.plugin.IOperationServicePlugIn;
export declare type Plugin = $.kd.bos.entity.plugin.Plugin;
export declare const Plugin: $.kd.bos.entity.plugin.Plugin_C;
export declare type PreparePropertysEventArgs = $.kd.bos.entity.plugin.PreparePropertysEventArgs;
export declare const PreparePropertysEventArgs: $.kd.bos.entity.plugin.PreparePropertysEventArgs_C;
export declare type AbstractKsPrintServicePlugin = $.kd.bos.entity.plugin.AbstractKsPrintServicePlugin;
export declare const AbstractKsPrintServicePlugin: $.kd.bos.entity.plugin.AbstractKsPrintServicePlugin_C;
export declare type AbstractPrintServicePlugin = $.kd.bos.entity.plugin.AbstractPrintServicePlugin;
export declare const AbstractPrintServicePlugin: $.kd.bos.entity.plugin.AbstractPrintServicePlugin_C;
export declare type IPrintDataHelper = $.kd.bos.entity.plugin.IPrintDataHelper;
export declare const IPrintDataHelper: $.kd.bos.entity.plugin.IPrintDataHelper;
export declare type IPrintScriptable = $.kd.bos.entity.plugin.IPrintScriptable;
export declare const IPrintScriptable: $.kd.bos.entity.plugin.IPrintScriptable;
export declare type IPrintServicePlugin = $.kd.bos.entity.plugin.IPrintServicePlugin;
export declare const IPrintServicePlugin: $.kd.bos.entity.plugin.IPrintServicePlugin;
export declare type PrintServicePluginProxy = $.kd.bos.entity.plugin.PrintServicePluginProxy;
export declare const PrintServicePluginProxy: $.kd.bos.entity.plugin.PrintServicePluginProxy_C;
