export declare type AddressProp = $.kd.bos.entity.property.AddressProp;
export declare const AddressProp: $.kd.bos.entity.property.AddressProp_C;
export declare type AdminDivisionProp = $.kd.bos.entity.property.AdminDivisionProp;
export declare const AdminDivisionProp: $.kd.bos.entity.property.AdminDivisionProp_C;
export declare type AmountProp = $.kd.bos.entity.property.AmountProp;
export declare const AmountProp: $.kd.bos.entity.property.AmountProp_C;
export declare type AssistantProp = $.kd.bos.entity.property.AssistantProp;
export declare const AssistantProp: $.kd.bos.entity.property.AssistantProp_C;
export declare type BaseUnitqtyProp = $.kd.bos.entity.property.BaseUnitqtyProp;
export declare const BaseUnitqtyProp: $.kd.bos.entity.property.BaseUnitqtyProp_C;
export declare type BasedataProp = $.kd.bos.entity.property.BasedataProp;
export declare const BasedataProp: $.kd.bos.entity.property.BasedataProp_C;
export declare type BigIntProp = $.kd.bos.entity.property.BigIntProp;
export declare const BigIntProp: $.kd.bos.entity.property.BigIntProp_C;
export declare type BillStatusProp = $.kd.bos.entity.property.BillStatusProp;
export declare const BillStatusProp: $.kd.bos.entity.property.BillStatusProp_C;
export declare type BillTypeProp = $.kd.bos.entity.property.BillTypeProp;
export declare const BillTypeProp: $.kd.bos.entity.property.BillTypeProp_C;
export declare type BizBasedataProp = $.kd.bos.entity.property.BizBasedataProp;
export declare const BizBasedataProp: $.kd.bos.entity.property.BizBasedataProp_C;
export declare type BooleanProp = $.kd.bos.entity.property.BooleanProp;
export declare const BooleanProp: $.kd.bos.entity.property.BooleanProp_C;
export declare type CityProp = $.kd.bos.entity.property.CityProp;
export declare const CityProp: $.kd.bos.entity.property.CityProp_C;
export declare type ComboProp = $.kd.bos.entity.property.ComboProp;
export declare const ComboProp: $.kd.bos.entity.property.ComboProp_C;
export declare type CreateDateProp = $.kd.bos.entity.property.CreateDateProp;
export declare const CreateDateProp: $.kd.bos.entity.property.CreateDateProp_C;
export declare type CreatedByIdProp = $.kd.bos.entity.property.CreatedByIdProp;
export declare const CreatedByIdProp: $.kd.bos.entity.property.CreatedByIdProp_C;
export declare type CreaterProp = $.kd.bos.entity.property.CreaterProp;
export declare const CreaterProp: $.kd.bos.entity.property.CreaterProp_C;
export declare type CtLinkEntryProp = $.kd.bos.entity.property.CtLinkEntryProp;
export declare const CtLinkEntryProp: $.kd.bos.entity.property.CtLinkEntryProp_C;
export declare type CurrencyProp = $.kd.bos.entity.property.CurrencyProp;
export declare const CurrencyProp: $.kd.bos.entity.property.CurrencyProp_C;
export declare type DateProp = $.kd.bos.entity.property.DateProp;
export declare const DateProp: $.kd.bos.entity.property.DateProp_C;
export declare type DateTimeProp = $.kd.bos.entity.property.DateTimeProp;
export declare const DateTimeProp: $.kd.bos.entity.property.DateTimeProp_C;
export declare type DecimalProp = $.kd.bos.entity.property.DecimalProp;
export declare const DecimalProp: $.kd.bos.entity.property.DecimalProp_C;
export declare type EntryProp = $.kd.bos.entity.property.EntryProp;
export declare const EntryProp: $.kd.bos.entity.property.EntryProp_C;
export declare type ExchangeRateProp = $.kd.bos.entity.property.ExchangeRateProp;
export declare const ExchangeRateProp: $.kd.bos.entity.property.ExchangeRateProp_C;
export declare type FieldDefValue = $.kd.bos.entity.property.FieldDefValue;
export declare const FieldDefValue: $.kd.bos.entity.property.FieldDefValue_C;
export declare type FieldDefValueType = $.kd.bos.entity.property.FieldDefValueType;
export declare const FieldDefValueType: typeof $.kd.bos.entity.property.FieldDefValueType;
export declare type FieldProp = $.kd.bos.entity.property.FieldProp;
export declare const FieldProp: $.kd.bos.entity.property.FieldProp_C;
export declare type FlexProp = $.kd.bos.entity.property.FlexProp;
export declare const FlexProp: $.kd.bos.entity.property.FlexProp_C;
export declare type FormulaProp = $.kd.bos.entity.property.FormulaProp;
export declare const FormulaProp: $.kd.bos.entity.property.FormulaProp_C;
export declare type GeoPointProp = $.kd.bos.entity.property.GeoPointProp;
export declare const GeoPointProp: $.kd.bos.entity.property.GeoPointProp_C;
export declare type GroupProp = $.kd.bos.entity.property.GroupProp;
export declare const GroupProp: $.kd.bos.entity.property.GroupProp_C;
export declare type IBasedataField = $.kd.bos.entity.property.IBasedataField;
export declare const IBasedataField: $.kd.bos.entity.property.IBasedataField;
export declare type ICompareTypeConfig = $.kd.bos.entity.property.ICompareTypeConfig;
export declare const ICompareTypeConfig: $.kd.bos.entity.property.ICompareTypeConfig;
export declare type IFieldHandle = $.kd.bos.entity.property.IFieldHandle;
export declare const IFieldHandle: $.kd.bos.entity.property.IFieldHandle;
export declare type IntegerProp = $.kd.bos.entity.property.IntegerProp;
export declare const IntegerProp: $.kd.bos.entity.property.IntegerProp_C;
export declare type ItemClassProp = $.kd.bos.entity.property.ItemClassProp;
export declare const ItemClassProp: $.kd.bos.entity.property.ItemClassProp_C;
export declare type ItemClassTypeProp = $.kd.bos.entity.property.ItemClassTypeProp;
export declare const ItemClassTypeProp: $.kd.bos.entity.property.ItemClassTypeProp_C;
export declare type LargeTextProp = $.kd.bos.entity.property.LargeTextProp;
export declare const LargeTextProp: $.kd.bos.entity.property.LargeTextProp_C;
export declare type LinkEntryProp = $.kd.bos.entity.property.LinkEntryProp;
export declare const LinkEntryProp: $.kd.bos.entity.property.LinkEntryProp_C;
export declare type LongProp = $.kd.bos.entity.property.LongProp;
export declare const LongProp: $.kd.bos.entity.property.LongProp_C;
export declare type MainOrgProp = $.kd.bos.entity.property.MainOrgProp;
export declare const MainOrgProp: $.kd.bos.entity.property.MainOrgProp_C;
export declare type MasterBasedataProp = $.kd.bos.entity.property.MasterBasedataProp;
export declare const MasterBasedataProp: $.kd.bos.entity.property.MasterBasedataProp_C;
export declare type MaterielProp = $.kd.bos.entity.property.MaterielProp;
export declare const MaterielProp: $.kd.bos.entity.property.MaterielProp_C;
export declare type ModifierIdProp = $.kd.bos.entity.property.ModifierIdProp;
export declare const ModifierIdProp: $.kd.bos.entity.property.ModifierIdProp_C;
export declare type ModifierProp = $.kd.bos.entity.property.ModifierProp;
export declare const ModifierProp: $.kd.bos.entity.property.ModifierProp_C;
export declare type ModifyDateProp = $.kd.bos.entity.property.ModifyDateProp;
export declare const ModifyDateProp: $.kd.bos.entity.property.ModifyDateProp_C;
export declare type MulBasedataProp = $.kd.bos.entity.property.MulBasedataProp;
export declare const MulBasedataProp: $.kd.bos.entity.property.MulBasedataProp_C;
export declare type MulComboProp = $.kd.bos.entity.property.MulComboProp;
export declare const MulComboProp: $.kd.bos.entity.property.MulComboProp_C;
export declare type MuliLangTextProp = $.kd.bos.entity.property.MuliLangTextProp;
export declare const MuliLangTextProp: $.kd.bos.entity.property.MuliLangTextProp_C;
export declare type OrgProp = $.kd.bos.entity.property.OrgProp;
export declare const OrgProp: $.kd.bos.entity.property.OrgProp_C;
export declare type PKFieldProp = $.kd.bos.entity.property.PKFieldProp;
export declare const PKFieldProp: $.kd.bos.entity.property.PKFieldProp_C;
export declare type ParentBasedataProp = $.kd.bos.entity.property.ParentBasedataProp;
export declare const ParentBasedataProp: $.kd.bos.entity.property.ParentBasedataProp_C;
export declare type PeriodProp = $.kd.bos.entity.property.PeriodProp;
export declare const PeriodProp: $.kd.bos.entity.property.PeriodProp_C;
export declare type PriceProp = $.kd.bos.entity.property.PriceProp;
export declare const PriceProp: $.kd.bos.entity.property.PriceProp_C;
export declare type PrintCountProp = $.kd.bos.entity.property.PrintCountProp;
export declare const PrintCountProp: $.kd.bos.entity.property.PrintCountProp_C;
export declare type PrivacyProp = $.kd.bos.entity.property.PrivacyProp;
export declare const PrivacyProp: $.kd.bos.entity.property.PrivacyProp_C;
export declare type QtyProp = $.kd.bos.entity.property.QtyProp;
export declare const QtyProp: $.kd.bos.entity.property.QtyProp_C;
export declare type RefProp = $.kd.bos.entity.property.RefProp;
export declare const RefProp: $.kd.bos.entity.property.RefProp_C;
export declare type StepperProp = $.kd.bos.entity.property.StepperProp;
export declare const StepperProp: $.kd.bos.entity.property.StepperProp_C;
export declare type SubEntryProp = $.kd.bos.entity.property.SubEntryProp;
export declare const SubEntryProp: $.kd.bos.entity.property.SubEntryProp_C;
export declare type TextAreaProp = $.kd.bos.entity.property.TextAreaProp;
export declare const TextAreaProp: $.kd.bos.entity.property.TextAreaProp_C;
export declare type TextProp = $.kd.bos.entity.property.TextProp;
export declare const TextProp: $.kd.bos.entity.property.TextProp_C;
export declare type TimeProp = $.kd.bos.entity.property.TimeProp;
export declare const TimeProp: $.kd.bos.entity.property.TimeProp_C;
export declare type TreeEntryProp = $.kd.bos.entity.property.TreeEntryProp;
export declare const TreeEntryProp: $.kd.bos.entity.property.TreeEntryProp_C;
export declare type UnitProp = $.kd.bos.entity.property.UnitProp;
export declare const UnitProp: $.kd.bos.entity.property.UnitProp_C;
export declare type UserProp = $.kd.bos.entity.property.UserProp;
export declare const UserProp: $.kd.bos.entity.property.UserProp_C;
export declare type VarcharProp = $.kd.bos.entity.property.VarcharProp;
export declare const VarcharProp: $.kd.bos.entity.property.VarcharProp_C;
