export declare type AbstractReportListDataPlugin = $.kd.bos.entity.report.AbstractReportListDataPlugin;
export declare const AbstractReportListDataPlugin: $.kd.bos.entity.report.AbstractReportListDataPlugin_C;
export declare type AbstractReportListDataPluginExt = $.kd.bos.entity.report.AbstractReportListDataPluginExt;
export declare const AbstractReportListDataPluginExt: $.kd.bos.entity.report.AbstractReportListDataPluginExt_C;
export declare type AbstractReportTreeDataPlugin = $.kd.bos.entity.report.AbstractReportTreeDataPlugin;
export declare const AbstractReportTreeDataPlugin: $.kd.bos.entity.report.AbstractReportTreeDataPlugin_C;
export declare type DynamicReportColumnEvent = $.kd.bos.entity.report.DynamicReportColumnEvent;
export declare const DynamicReportColumnEvent: $.kd.bos.entity.report.DynamicReportColumnEvent_C;
export declare type IReportCache = $.kd.bos.entity.report.IReportCache;
export declare const IReportCache: $.kd.bos.entity.report.IReportCache;
export declare type IReportListDataPlugin = $.kd.bos.entity.report.IReportListDataPlugin;
export declare const IReportListDataPlugin: $.kd.bos.entity.report.IReportListDataPlugin;
export declare type IReportListDataServiceExt = $.kd.bos.entity.report.IReportListDataServiceExt;
export declare const IReportListDataServiceExt: $.kd.bos.entity.report.IReportListDataServiceExt;
export declare type IReportTreeModel = $.kd.bos.entity.report.IReportTreeModel;
export declare const IReportTreeModel: $.kd.bos.entity.report.IReportTreeModel;
export declare type ReportBatchLoadInfo = $.kd.bos.entity.report.ReportBatchLoadInfo;
export declare const ReportBatchLoadInfo: $.kd.bos.entity.report.ReportBatchLoadInfo_C;
export declare type ReportByBatchTaskResult = $.kd.bos.entity.report.ReportByBatchTaskResult;
export declare const ReportByBatchTaskResult: $.kd.bos.entity.report.ReportByBatchTaskResult_C;
export declare type ReportCacheManager = $.kd.bos.entity.report.ReportCacheManager;
export declare const ReportCacheManager: $.kd.bos.entity.report.ReportCacheManager_C;
export declare type ReportModule = $.kd.bos.entity.report.ReportModule;
export declare const ReportModule: $.kd.bos.entity.report.ReportModule_C;
export declare type ReportQueryBuilder = $.kd.bos.entity.report.ReportQueryBuilder;
export declare const ReportQueryBuilder: $.kd.bos.entity.report.ReportQueryBuilder_C;
export declare type ReportResultLimit = $.kd.bos.entity.report.ReportResultLimit;
export declare const ReportResultLimit: $.kd.bos.entity.report.ReportResultLimit_C;
export declare type ReportRowSet = $.kd.bos.entity.report.ReportRowSet;
export declare const ReportRowSet: $.kd.bos.entity.report.ReportRowSet_C;
export declare type ReportTaskParam = $.kd.bos.entity.report.ReportTaskParam;
export declare const ReportTaskParam: $.kd.bos.entity.report.ReportTaskParam_C;
export declare type ReportTaskResult = $.kd.bos.entity.report.ReportTaskResult;
export declare const ReportTaskResult: $.kd.bos.entity.report.ReportTaskResult_C;
export declare type TreeModel = $.kd.bos.entity.report.TreeModel;
export declare const TreeModel: $.kd.bos.entity.report.TreeModel_C;
export declare type AbstractReportColumn = $.kd.bos.entity.report.AbstractReportColumn;
export declare const AbstractReportColumn: $.kd.bos.entity.report.AbstractReportColumn_C;
export declare type CellStyle = $.kd.bos.entity.report.CellStyle;
export declare const CellStyle: $.kd.bos.entity.report.CellStyle_C;
export declare type ColumnStyle = $.kd.bos.entity.report.ColumnStyle;
export declare const ColumnStyle: $.kd.bos.entity.report.ColumnStyle_C;
export declare type ComboReportColumn = $.kd.bos.entity.report.ComboReportColumn;
export declare const ComboReportColumn: $.kd.bos.entity.report.ComboReportColumn_C;
export declare type DateEnum = $.kd.bos.entity.report.DateEnum;
export declare const DateEnum: typeof $.kd.bos.entity.report.DateEnum;
export declare type DateTimeReportColumn = $.kd.bos.entity.report.DateTimeReportColumn;
export declare const DateTimeReportColumn: $.kd.bos.entity.report.DateTimeReportColumn_C;
export declare type DecimalReportColumn = $.kd.bos.entity.report.DecimalReportColumn;
export declare const DecimalReportColumn: $.kd.bos.entity.report.DecimalReportColumn_C;
export declare type FastFilter = $.kd.bos.entity.report.FastFilter;
export declare const FastFilter: $.kd.bos.entity.report.FastFilter_C;
export declare type FilterInfo = $.kd.bos.entity.report.FilterInfo;
export declare const FilterInfo: $.kd.bos.entity.report.FilterInfo_C;
export declare type FilterItemInfo = $.kd.bos.entity.report.FilterItemInfo;
export declare const FilterItemInfo: $.kd.bos.entity.report.FilterItemInfo_C;
export declare type FlexReportColumn = $.kd.bos.entity.report.FlexReportColumn;
export declare const FlexReportColumn: $.kd.bos.entity.report.FlexReportColumn_C;
export declare type IReportBatchQueryInfo = $.kd.bos.entity.report.IReportBatchQueryInfo;
export declare const IReportBatchQueryInfo: $.kd.bos.entity.report.IReportBatchQueryInfo;
export declare type IReportListModel = $.kd.bos.entity.report.IReportListModel;
export declare const IReportListModel: $.kd.bos.entity.report.IReportListModel;
export declare type MulBasedataReportColumn = $.kd.bos.entity.report.MulBasedataReportColumn;
export declare const MulBasedataReportColumn: $.kd.bos.entity.report.MulBasedataReportColumn_C;
export declare type MulComboReportColumn = $.kd.bos.entity.report.MulComboReportColumn;
export declare const MulComboReportColumn: $.kd.bos.entity.report.MulComboReportColumn_C;
export declare type ReportBatchQueryInfo = $.kd.bos.entity.report.ReportBatchQueryInfo;
export declare const ReportBatchQueryInfo: $.kd.bos.entity.report.ReportBatchQueryInfo_C;
export declare type ReportColumn = $.kd.bos.entity.report.ReportColumn;
export declare const ReportColumn: $.kd.bos.entity.report.ReportColumn_C;
export declare type ReportColumnGroup = $.kd.bos.entity.report.ReportColumnGroup;
export declare const ReportColumnGroup: $.kd.bos.entity.report.ReportColumnGroup_C;
export declare type ReportFilterDefaultField = $.kd.bos.entity.report.ReportFilterDefaultField;
export declare const ReportFilterDefaultField: $.kd.bos.entity.report.ReportFilterDefaultField_C;
export declare type ReportQueryParam = $.kd.bos.entity.report.ReportQueryParam;
export declare const ReportQueryParam: $.kd.bos.entity.report.ReportQueryParam_C;
export declare type TextReportColumn = $.kd.bos.entity.report.TextReportColumn;
export declare const TextReportColumn: $.kd.bos.entity.report.TextReportColumn_C;
export declare type TimeReportColumn = $.kd.bos.entity.report.TimeReportColumn;
export declare const TimeReportColumn: $.kd.bos.entity.report.TimeReportColumn_C;
