export declare type AbstractValidator = $.kd.bos.entity.validate.AbstractValidator;
export declare const AbstractValidator: $.kd.bos.entity.validate.AbstractValidator_C;
export declare type BillStatus = $.kd.bos.entity.validate.BillStatus;
export declare const BillStatus: typeof $.kd.bos.entity.validate.BillStatus;
export declare type ErrorLevel = $.kd.bos.entity.validate.ErrorLevel;
export declare const ErrorLevel: typeof $.kd.bos.entity.validate.ErrorLevel;
export declare type GroupFieldsUniqueValidateResult = $.kd.bos.entity.validate.GroupFieldsUniqueValidateResult;
export declare const GroupFieldsUniqueValidateResult: $.kd.bos.entity.validate.GroupFieldsUniqueValidateResult_C;
export declare type IScopeCheck = $.kd.bos.entity.validate.IScopeCheck;
export declare const IScopeCheck: $.kd.bos.entity.validate.IScopeCheck;
export declare type IValidatorHanlder = $.kd.bos.entity.validate.IValidatorHanlder;
export declare const IValidatorHanlder: $.kd.bos.entity.validate.IValidatorHanlder;
export declare type RequiredValidator = $.kd.bos.entity.validate.RequiredValidator;
export declare const RequiredValidator: $.kd.bos.entity.validate.RequiredValidator_C;
export declare type ValidateContext = $.kd.bos.entity.validate.ValidateContext;
export declare const ValidateContext: $.kd.bos.entity.validate.ValidateContext_C;
export declare type ValidatePriority = $.kd.bos.entity.validate.ValidatePriority;
export declare const ValidatePriority: typeof $.kd.bos.entity.validate.ValidatePriority;
export declare type ValidateResult = $.kd.bos.entity.validate.ValidateResult;
export declare const ValidateResult: $.kd.bos.entity.validate.ValidateResult_C;
export declare type ValidateResultCollection = $.kd.bos.entity.validate.ValidateResultCollection;
export declare const ValidateResultCollection: $.kd.bos.entity.validate.ValidateResultCollection_C;
export declare type ValidationErrorInfo = $.kd.bos.entity.validate.ValidationErrorInfo;
export declare const ValidationErrorInfo: $.kd.bos.entity.validate.ValidationErrorInfo_C;
