export declare type ApiQueryOrderByModel = $.kd.bos.openapi.api.model.ApiQueryOrderByModel;
export declare const ApiQueryOrderByModel: $.kd.bos.openapi.api.model.ApiQueryOrderByModel_C;
export declare type ApiSerializerModel = $.kd.bos.openapi.api.model.ApiSerializerModel;
export declare const ApiSerializerModel: $.kd.bos.openapi.api.model.ApiSerializerModel_C;
export declare type ApiSerializerVersion = $.kd.bos.openapi.api.model.ApiSerializerVersion;
export declare const ApiSerializerVersion: typeof $.kd.bos.openapi.api.model.ApiSerializerVersion;
export declare type OpenApiRequest = $.kd.bos.openapi.api.model.OpenApiRequest;
export declare const OpenApiRequest: $.kd.bos.openapi.api.model.OpenApiRequest_C;
export declare type OpenApiResponse = $.kd.bos.openapi.api.model.OpenApiResponse;
export declare const OpenApiResponse: $.kd.bos.openapi.api.model.OpenApiResponse_C;
