export declare type ApiAppendEntryRowsPlugin = $.kd.bos.openapi.api.plugin.ApiAppendEntryRowsPlugin;
export declare const ApiAppendEntryRowsPlugin: $.kd.bos.openapi.api.plugin.ApiAppendEntryRowsPlugin;
export declare type ApiAuditPlugin = $.kd.bos.openapi.api.plugin.ApiAuditPlugin;
export declare const ApiAuditPlugin: $.kd.bos.openapi.api.plugin.ApiAuditPlugin;
export declare type ApiCommonPlugin = $.kd.bos.openapi.api.plugin.ApiCommonPlugin;
export declare const ApiCommonPlugin: $.kd.bos.openapi.api.plugin.ApiCommonPlugin;
export declare type ApiDeleteEntryRowsPlugin = $.kd.bos.openapi.api.plugin.ApiDeleteEntryRowsPlugin;
export declare const ApiDeleteEntryRowsPlugin: $.kd.bos.openapi.api.plugin.ApiDeleteEntryRowsPlugin;
export declare type ApiDeletePlugin = $.kd.bos.openapi.api.plugin.ApiDeletePlugin;
export declare const ApiDeletePlugin: $.kd.bos.openapi.api.plugin.ApiDeletePlugin;
export declare type ApiDeserializerPlugin = $.kd.bos.openapi.api.plugin.ApiDeserializerPlugin;
export declare const ApiDeserializerPlugin: $.kd.bos.openapi.api.plugin.ApiDeserializerPlugin;
export declare type ApiDisablePlugin = $.kd.bos.openapi.api.plugin.ApiDisablePlugin;
export declare const ApiDisablePlugin: $.kd.bos.openapi.api.plugin.ApiDisablePlugin;
export declare type ApiEnablePlugin = $.kd.bos.openapi.api.plugin.ApiEnablePlugin;
export declare const ApiEnablePlugin: $.kd.bos.openapi.api.plugin.ApiEnablePlugin;
export declare type ApiQueryPlugin = $.kd.bos.openapi.api.plugin.ApiQueryPlugin;
export declare const ApiQueryPlugin: $.kd.bos.openapi.api.plugin.ApiQueryPlugin;
export declare type ApiSavePlugin = $.kd.bos.openapi.api.plugin.ApiSavePlugin;
export declare const ApiSavePlugin: $.kd.bos.openapi.api.plugin.ApiSavePlugin;
export declare type ApiSerializerPlugin = $.kd.bos.openapi.api.plugin.ApiSerializerPlugin;
export declare const ApiSerializerPlugin: $.kd.bos.openapi.api.plugin.ApiSerializerPlugin;
export declare type ApiSubmitPlugin = $.kd.bos.openapi.api.plugin.ApiSubmitPlugin;
export declare const ApiSubmitPlugin: $.kd.bos.openapi.api.plugin.ApiSubmitPlugin;
export declare type ApiUnAuditPlugin = $.kd.bos.openapi.api.plugin.ApiUnAuditPlugin;
export declare const ApiUnAuditPlugin: $.kd.bos.openapi.api.plugin.ApiUnAuditPlugin;
export declare type ApiUnSubmitPlugin = $.kd.bos.openapi.api.plugin.ApiUnSubmitPlugin;
export declare const ApiUnSubmitPlugin: $.kd.bos.openapi.api.plugin.ApiUnSubmitPlugin;
export declare type SerializerResult = $.kd.bos.openapi.api.plugin.SerializerResult;
export declare const SerializerResult: $.kd.bos.openapi.api.plugin.SerializerResult_C;
