export declare type AfterCoordinationEvent = $.kd.sdk.wtc.wtp.business.coordination.AfterCoordinationEvent;
export declare const AfterCoordinationEvent: $.kd.sdk.wtc.wtp.business.coordination.AfterCoordinationEvent_C;
export declare type BeforeCoordinationEvent = $.kd.sdk.wtc.wtp.business.coordination.BeforeCoordinationEvent;
export declare const BeforeCoordinationEvent: $.kd.sdk.wtc.wtp.business.coordination.BeforeCoordinationEvent_C;
export declare type CoordinationExecuteExtPlugin = $.kd.sdk.wtc.wtp.business.coordination.CoordinationExecuteExtPlugin;
export declare const CoordinationExecuteExtPlugin: $.kd.sdk.wtc.wtp.business.coordination.CoordinationExecuteExtPlugin;
export declare type CoordinationExpandParam = $.kd.sdk.wtc.wtp.business.coordination.CoordinationExpandParam;
export declare const CoordinationExpandParam: $.kd.sdk.wtc.wtp.business.coordination.CoordinationExpandParam_C;
export declare type CoordinationExpandService = $.kd.sdk.wtc.wtp.business.coordination.CoordinationExpandService;
export declare const CoordinationExpandService: $.kd.sdk.wtc.wtp.business.coordination.CoordinationExpandService;
export declare type CoreCoordinationParam = $.kd.sdk.wtc.wtp.business.coordination.CoreCoordinationParam;
export declare const CoreCoordinationParam: $.kd.sdk.wtc.wtp.business.coordination.CoreCoordinationParam_C;
export declare type ExecutingCoordinationEvent = $.kd.sdk.wtc.wtp.business.coordination.ExecutingCoordinationEvent;
export declare const ExecutingCoordinationEvent: $.kd.sdk.wtc.wtp.business.coordination.ExecutingCoordinationEvent_C;
