/// <reference path="../index.d.ts" />
export declare type Accessible = $.javax.accessibility.Accessible;
export declare const Accessible: $.javax.accessibility.Accessible;
export declare type AccessibleAction = $.javax.accessibility.AccessibleAction;
export declare const AccessibleAction: $.javax.accessibility.AccessibleAction;
export declare type AccessibleBundle = $.javax.accessibility.AccessibleBundle;
export declare const AccessibleBundle: $.javax.accessibility.AccessibleBundle_C;
export declare type AccessibleComponent = $.javax.accessibility.AccessibleComponent;
export declare const AccessibleComponent: $.javax.accessibility.AccessibleComponent;
export declare type AccessibleContext = $.javax.accessibility.AccessibleContext;
export declare const AccessibleContext: $.javax.accessibility.AccessibleContext_C;
export declare type AccessibleEditableText = $.javax.accessibility.AccessibleEditableText;
export declare const AccessibleEditableText: $.javax.accessibility.AccessibleEditableText;
export declare type AccessibleIcon = $.javax.accessibility.AccessibleIcon;
export declare const AccessibleIcon: $.javax.accessibility.AccessibleIcon;
export declare type AccessibleRelation = $.javax.accessibility.AccessibleRelation;
export declare const AccessibleRelation: $.javax.accessibility.AccessibleRelation_C;
export declare type AccessibleRelationSet = $.javax.accessibility.AccessibleRelationSet;
export declare const AccessibleRelationSet: $.javax.accessibility.AccessibleRelationSet_C;
export declare type AccessibleRole = $.javax.accessibility.AccessibleRole;
export declare const AccessibleRole: $.javax.accessibility.AccessibleRole_C;
export declare type AccessibleSelection = $.javax.accessibility.AccessibleSelection;
export declare const AccessibleSelection: $.javax.accessibility.AccessibleSelection;
export declare type AccessibleState = $.javax.accessibility.AccessibleState;
export declare const AccessibleState: $.javax.accessibility.AccessibleState_C;
export declare type AccessibleStateSet = $.javax.accessibility.AccessibleStateSet;
export declare const AccessibleStateSet: $.javax.accessibility.AccessibleStateSet_C;
export declare type AccessibleTable = $.javax.accessibility.AccessibleTable;
export declare const AccessibleTable: $.javax.accessibility.AccessibleTable;
export declare type AccessibleText = $.javax.accessibility.AccessibleText;
export declare const AccessibleText: $.javax.accessibility.AccessibleText;
export declare type AccessibleValue = $.javax.accessibility.AccessibleValue;
export declare const AccessibleValue: $.javax.accessibility.AccessibleValue;
