export declare type AbstractConvertServiceArgs = $.kd.bos.entity.botp.runtime.AbstractConvertServiceArgs;
export declare const AbstractConvertServiceArgs: $.kd.bos.entity.botp.runtime.AbstractConvertServiceArgs_C;
export declare type BFRow = $.kd.bos.entity.botp.runtime.BFRow;
export declare const BFRow: $.kd.bos.entity.botp.runtime.BFRow_C;
export declare type BFRowId = $.kd.bos.entity.botp.runtime.BFRowId;
export declare const BFRowId: $.kd.bos.entity.botp.runtime.BFRowId_C;
export declare type BFRowLinkDownNode = $.kd.bos.entity.botp.runtime.BFRowLinkDownNode;
export declare const BFRowLinkDownNode: $.kd.bos.entity.botp.runtime.BFRowLinkDownNode_C;
export declare type BFRowLinkUpNode = $.kd.bos.entity.botp.runtime.BFRowLinkUpNode;
export declare const BFRowLinkUpNode: $.kd.bos.entity.botp.runtime.BFRowLinkUpNode_C;
export declare type BeforeDrawArgs = $.kd.bos.entity.botp.runtime.BeforeDrawArgs;
export declare const BeforeDrawArgs: $.kd.bos.entity.botp.runtime.BeforeDrawArgs_C;
export declare type BeforeDrawOpResult = $.kd.bos.entity.botp.runtime.BeforeDrawOpResult;
export declare const BeforeDrawOpResult: $.kd.bos.entity.botp.runtime.BeforeDrawOpResult_C;
export declare type ConvertConst = $.kd.bos.entity.botp.runtime.ConvertConst;
export declare const ConvertConst: $.kd.bos.entity.botp.runtime.ConvertConst_C;
export declare type ConvertOpRule = $.kd.bos.entity.botp.runtime.ConvertOpRule;
export declare const ConvertOpRule: $.kd.bos.entity.botp.runtime.ConvertOpRule_C;
export declare type ConvertOperationResult = $.kd.bos.entity.botp.runtime.ConvertOperationResult;
export declare const ConvertOperationResult: $.kd.bos.entity.botp.runtime.ConvertOperationResult_C;
export declare type DrawArgs = $.kd.bos.entity.botp.runtime.DrawArgs;
export declare const DrawArgs: $.kd.bos.entity.botp.runtime.DrawArgs_C;
export declare type GetTargetOptionalOrgsArgs = $.kd.bos.entity.botp.runtime.GetTargetOptionalOrgsArgs;
export declare const GetTargetOptionalOrgsArgs: $.kd.bos.entity.botp.runtime.GetTargetOptionalOrgsArgs_C;
export declare type GetTargetOptionalOrgsResult = $.kd.bos.entity.botp.runtime.GetTargetOptionalOrgsResult;
export declare const GetTargetOptionalOrgsResult: $.kd.bos.entity.botp.runtime.GetTargetOptionalOrgsResult_C;
export declare type PushArgs = $.kd.bos.entity.botp.runtime.PushArgs;
export declare const PushArgs: $.kd.bos.entity.botp.runtime.PushArgs_C;
export declare type SourceBillReport = $.kd.bos.entity.botp.runtime.SourceBillReport;
export declare const SourceBillReport: $.kd.bos.entity.botp.runtime.SourceBillReport_C;
export declare type SourceRowReport = $.kd.bos.entity.botp.runtime.SourceRowReport;
export declare const SourceRowReport: $.kd.bos.entity.botp.runtime.SourceRowReport_C;
export declare type TableDefine = $.kd.bos.entity.botp.runtime.TableDefine;
export declare const TableDefine: $.kd.bos.entity.botp.runtime.TableDefine_C;
