export declare type AbstractJobHandler = $.kd.bos.schedule.api.AbstractJobHandler;
export declare const AbstractJobHandler: $.kd.bos.schedule.api.AbstractJobHandler_C;
export declare type BroadcastTask = $.kd.bos.schedule.api.BroadcastTask;
export declare const BroadcastTask: $.kd.bos.schedule.api.BroadcastTask;
export declare type JobDao = $.kd.bos.schedule.api.JobDao;
export declare const JobDao: $.kd.bos.schedule.api.JobDao;
export declare type JobDispatcher = $.kd.bos.schedule.api.JobDispatcher;
export declare const JobDispatcher: $.kd.bos.schedule.api.JobDispatcher;
export declare type JobInfo = $.kd.bos.schedule.api.JobInfo;
export declare const JobInfo: $.kd.bos.schedule.api.JobInfo_C;
export declare type JobType = $.kd.bos.schedule.api.JobType;
export declare const JobType: typeof $.kd.bos.schedule.api.JobType;
export declare type MessageInfo = $.kd.bos.schedule.api.MessageInfo;
export declare const MessageInfo: $.kd.bos.schedule.api.MessageInfo_C;
export declare type ObjectFactory = $.kd.bos.schedule.api.ObjectFactory;
export declare const ObjectFactory: $.kd.bos.schedule.api.ObjectFactory;
export declare type PlanInfo = $.kd.bos.schedule.api.PlanInfo;
export declare const PlanInfo: $.kd.bos.schedule.api.PlanInfo_C;
export declare type ScheduleDao = $.kd.bos.schedule.api.ScheduleDao;
export declare const ScheduleDao: $.kd.bos.schedule.api.ScheduleDao;
export declare type ScheduleManager = $.kd.bos.schedule.api.ScheduleManager;
export declare const ScheduleManager: $.kd.bos.schedule.api.ScheduleManager;
export declare type ScheduleModule = $.kd.bos.schedule.api.ScheduleModule;
export declare const ScheduleModule: $.kd.bos.schedule.api.ScheduleModule_C;
export declare type ScheduleMsgInfo = $.kd.bos.schedule.api.ScheduleMsgInfo;
export declare const ScheduleMsgInfo: $.kd.bos.schedule.api.ScheduleMsgInfo_C;
export declare type ShardingParam = $.kd.bos.schedule.api.ShardingParam;
export declare const ShardingParam: $.kd.bos.schedule.api.ShardingParam_C;
export declare type ShardingTask = $.kd.bos.schedule.api.ShardingTask;
export declare const ShardingTask: $.kd.bos.schedule.api.ShardingTask;
export declare type StopTask = $.kd.bos.schedule.api.StopTask;
export declare const StopTask: $.kd.bos.schedule.api.StopTask;
export declare type TaskDao = $.kd.bos.schedule.api.TaskDao;
export declare const TaskDao: $.kd.bos.schedule.api.TaskDao;
export declare type TaskInfo = $.kd.bos.schedule.api.TaskInfo;
export declare const TaskInfo: $.kd.bos.schedule.api.TaskInfo_C;
export declare type TaskStatusConstant = $.kd.bos.schedule.api.TaskStatusConstant;
export declare const TaskStatusConstant: $.kd.bos.schedule.api.TaskStatusConstant_C;
