export declare type AbstractTaskClick = $.kd.bos.schedule.form.AbstractTaskClick;
export declare const AbstractTaskClick: $.kd.bos.schedule.form.AbstractTaskClick_C;
export declare type BackgroundTaskSubscriber = $.kd.bos.schedule.form.BackgroundTaskSubscriber;
export declare const BackgroundTaskSubscriber: $.kd.bos.schedule.form.BackgroundTaskSubscriber_C;
export declare type JobForm = $.kd.bos.schedule.form.JobForm;
export declare const JobForm: $.kd.bos.schedule.form.JobForm_C;
export declare type JobFormInfo = $.kd.bos.schedule.form.JobFormInfo;
export declare const JobFormInfo: $.kd.bos.schedule.form.JobFormInfo_C;
export declare type JobFromStatus = $.kd.bos.schedule.form.JobFromStatus;
export declare const JobFromStatus: typeof $.kd.bos.schedule.form.JobFromStatus;
export declare type TaskClick = $.kd.bos.schedule.form.TaskClick;
export declare const TaskClick: $.kd.bos.schedule.form.TaskClick;
export declare type TaskClickProxy = $.kd.bos.schedule.form.TaskClickProxy;
export declare const TaskClickProxy: $.kd.bos.schedule.form.TaskClickProxy_C;
export declare type TaskClientProxy = $.kd.bos.schedule.form.TaskClientProxy;
export declare const TaskClientProxy: $.kd.bos.schedule.form.TaskClientProxy_C;
