export declare type AbstractBasedataField = $.kd.bos.metadata.entity.businessfield.AbstractBasedataField;
export declare const AbstractBasedataField: $.kd.bos.metadata.entity.businessfield.AbstractBasedataField_C;
export declare type AbstractRefBillField = $.kd.bos.metadata.entity.businessfield.AbstractRefBillField;
export declare const AbstractRefBillField: $.kd.bos.metadata.entity.businessfield.AbstractRefBillField_C;
export declare type AddressField = $.kd.bos.metadata.entity.businessfield.AddressField;
export declare const AddressField: $.kd.bos.metadata.entity.businessfield.AddressField_C;
export declare type AmountField = $.kd.bos.metadata.entity.businessfield.AmountField;
export declare const AmountField: $.kd.bos.metadata.entity.businessfield.AmountField_C;
export declare type AssistantField = $.kd.bos.metadata.entity.businessfield.AssistantField;
export declare const AssistantField: $.kd.bos.metadata.entity.businessfield.AssistantField_C;
export declare type BaseUnitqtyField = $.kd.bos.metadata.entity.businessfield.BaseUnitqtyField;
export declare const BaseUnitqtyField: $.kd.bos.metadata.entity.businessfield.BaseUnitqtyField_C;
export declare type BasedataField = $.kd.bos.metadata.entity.businessfield.BasedataField;
export declare const BasedataField: $.kd.bos.metadata.entity.businessfield.BasedataField_C;
export declare type BasedataPropField = $.kd.bos.metadata.entity.businessfield.BasedataPropField;
export declare const BasedataPropField: $.kd.bos.metadata.entity.businessfield.BasedataPropField_C;
export declare type BillNoField = $.kd.bos.metadata.entity.businessfield.BillNoField;
export declare const BillNoField: $.kd.bos.metadata.entity.businessfield.BillNoField_C;
export declare type BillStatusField = $.kd.bos.metadata.entity.businessfield.BillStatusField;
export declare const BillStatusField: $.kd.bos.metadata.entity.businessfield.BillStatusField_C;
export declare type BillTypeField = $.kd.bos.metadata.entity.businessfield.BillTypeField;
export declare const BillTypeField: $.kd.bos.metadata.entity.businessfield.BillTypeField_C;
export declare type CityField = $.kd.bos.metadata.entity.businessfield.CityField;
export declare const CityField: $.kd.bos.metadata.entity.businessfield.CityField_C;
export declare type CreateDateField = $.kd.bos.metadata.entity.businessfield.CreateDateField;
export declare const CreateDateField: $.kd.bos.metadata.entity.businessfield.CreateDateField_C;
export declare type CreaterField = $.kd.bos.metadata.entity.businessfield.CreaterField;
export declare const CreaterField: $.kd.bos.metadata.entity.businessfield.CreaterField_C;
export declare type CurrencyField = $.kd.bos.metadata.entity.businessfield.CurrencyField;
export declare const CurrencyField: $.kd.bos.metadata.entity.businessfield.CurrencyField_C;
export declare type ExchangeRateField = $.kd.bos.metadata.entity.businessfield.ExchangeRateField;
export declare const ExchangeRateField: $.kd.bos.metadata.entity.businessfield.ExchangeRateField_C;
export declare type FlexField = $.kd.bos.metadata.entity.businessfield.FlexField;
export declare const FlexField: $.kd.bos.metadata.entity.businessfield.FlexField_C;
export declare type GroupField = $.kd.bos.metadata.entity.businessfield.GroupField;
export declare const GroupField: $.kd.bos.metadata.entity.businessfield.GroupField_C;
export declare type IBasedataField = $.kd.bos.metadata.entity.businessfield.IBasedataField;
export declare const IBasedataField: $.kd.bos.metadata.entity.businessfield.IBasedataField;
export declare type IRefBillField = $.kd.bos.metadata.entity.businessfield.IRefBillField;
export declare const IRefBillField: $.kd.bos.metadata.entity.businessfield.IRefBillField;
export declare type ItemClass = $.kd.bos.metadata.entity.businessfield.ItemClass;
export declare const ItemClass: $.kd.bos.metadata.entity.businessfield.ItemClass_C;
export declare type ItemClassField = $.kd.bos.metadata.entity.businessfield.ItemClassField;
export declare const ItemClassField: $.kd.bos.metadata.entity.businessfield.ItemClassField_C;
export declare type ItemClassTypeField = $.kd.bos.metadata.entity.businessfield.ItemClassTypeField;
export declare const ItemClassTypeField: $.kd.bos.metadata.entity.businessfield.ItemClassTypeField_C;
export declare type MasterIdField = $.kd.bos.metadata.entity.businessfield.MasterIdField;
export declare const MasterIdField: $.kd.bos.metadata.entity.businessfield.MasterIdField_C;
export declare type MaterielField = $.kd.bos.metadata.entity.businessfield.MaterielField;
export declare const MaterielField: $.kd.bos.metadata.entity.businessfield.MaterielField_C;
export declare type MobBasedataField = $.kd.bos.metadata.entity.businessfield.MobBasedataField;
export declare const MobBasedataField: $.kd.bos.metadata.entity.businessfield.MobBasedataField_C;
export declare type ModifierField = $.kd.bos.metadata.entity.businessfield.ModifierField;
export declare const ModifierField: $.kd.bos.metadata.entity.businessfield.ModifierField_C;
export declare type ModifyDateField = $.kd.bos.metadata.entity.businessfield.ModifyDateField;
export declare const ModifyDateField: $.kd.bos.metadata.entity.businessfield.ModifyDateField_C;
export declare type MulBasedataField = $.kd.bos.metadata.entity.businessfield.MulBasedataField;
export declare const MulBasedataField: $.kd.bos.metadata.entity.businessfield.MulBasedataField_C;
export declare type NameField = $.kd.bos.metadata.entity.businessfield.NameField;
export declare const NameField: $.kd.bos.metadata.entity.businessfield.NameField_C;
export declare type OrgField = $.kd.bos.metadata.entity.businessfield.OrgField;
export declare const OrgField: $.kd.bos.metadata.entity.businessfield.OrgField_C;
export declare type ParentBasedataField = $.kd.bos.metadata.entity.businessfield.ParentBasedataField;
export declare const ParentBasedataField: $.kd.bos.metadata.entity.businessfield.ParentBasedataField_C;
export declare type PriceField = $.kd.bos.metadata.entity.businessfield.PriceField;
export declare const PriceField: $.kd.bos.metadata.entity.businessfield.PriceField_C;
export declare type PrintCountField = $.kd.bos.metadata.entity.businessfield.PrintCountField;
export declare const PrintCountField: $.kd.bos.metadata.entity.businessfield.PrintCountField_C;
export declare type QtyField = $.kd.bos.metadata.entity.businessfield.QtyField;
export declare const QtyField: $.kd.bos.metadata.entity.businessfield.QtyField_C;
export declare type RefBasedata = $.kd.bos.metadata.entity.businessfield.RefBasedata;
export declare const RefBasedata: $.kd.bos.metadata.entity.businessfield.RefBasedata_C;
export declare type RefBillField = $.kd.bos.metadata.entity.businessfield.RefBillField;
export declare const RefBillField: $.kd.bos.metadata.entity.businessfield.RefBillField_C;
export declare type UnitField = $.kd.bos.metadata.entity.businessfield.UnitField;
export declare const UnitField: $.kd.bos.metadata.entity.businessfield.UnitField_C;
export declare type UserAvatarField = $.kd.bos.metadata.entity.businessfield.UserAvatarField;
export declare const UserAvatarField: $.kd.bos.metadata.entity.businessfield.UserAvatarField_C;
export declare type UserField = $.kd.bos.metadata.entity.businessfield.UserField;
export declare const UserField: $.kd.bos.metadata.entity.businessfield.UserField_C;
export declare type PrintTimeField = $.kd.bos.metadata.entity.businessfield.PrintTimeField;
export declare const PrintTimeField: $.kd.bos.metadata.entity.businessfield.PrintTimeField_C;
export declare type PrintUserField = $.kd.bos.metadata.entity.businessfield.PrintUserField;
export declare const PrintUserField: $.kd.bos.metadata.entity.businessfield.PrintUserField_C;
