export declare type AdminDivisionField = $.kd.bos.metadata.entity.commonfield.AdminDivisionField;
export declare const AdminDivisionField: $.kd.bos.metadata.entity.commonfield.AdminDivisionField_C;
export declare type BigIntField = $.kd.bos.metadata.entity.commonfield.BigIntField;
export declare const BigIntField: $.kd.bos.metadata.entity.commonfield.BigIntField_C;
export declare type CheckBoxField = $.kd.bos.metadata.entity.commonfield.CheckBoxField;
export declare const CheckBoxField: $.kd.bos.metadata.entity.commonfield.CheckBoxField_C;
export declare type ComboField = $.kd.bos.metadata.entity.commonfield.ComboField;
export declare const ComboField: $.kd.bos.metadata.entity.commonfield.ComboField_C;
export declare type ComboItem = $.kd.bos.metadata.entity.commonfield.ComboItem;
export declare const ComboItem: $.kd.bos.metadata.entity.commonfield.ComboItem_C;
export declare type DateField = $.kd.bos.metadata.entity.commonfield.DateField;
export declare const DateField: $.kd.bos.metadata.entity.commonfield.DateField_C;
export declare type DateRangeField = $.kd.bos.metadata.entity.commonfield.DateRangeField;
export declare const DateRangeField: $.kd.bos.metadata.entity.commonfield.DateRangeField_C;
export declare type DateTimeField = $.kd.bos.metadata.entity.commonfield.DateTimeField;
export declare const DateTimeField: $.kd.bos.metadata.entity.commonfield.DateTimeField_C;
export declare type DecimalField = $.kd.bos.metadata.entity.commonfield.DecimalField;
export declare const DecimalField: $.kd.bos.metadata.entity.commonfield.DecimalField_C;
export declare type DropdownItem = $.kd.bos.metadata.entity.commonfield.DropdownItem;
export declare const DropdownItem: $.kd.bos.metadata.entity.commonfield.DropdownItem_C;
export declare type EmailField = $.kd.bos.metadata.entity.commonfield.EmailField;
export declare const EmailField: $.kd.bos.metadata.entity.commonfield.EmailField_C;
export declare type Field = $.kd.bos.metadata.entity.commonfield.Field;
export declare const Field: $.kd.bos.metadata.entity.commonfield.Field_C;
export declare type FormulaField = $.kd.bos.metadata.entity.commonfield.FormulaField;
export declare const FormulaField: $.kd.bos.metadata.entity.commonfield.FormulaField_C;
export declare type GeoPointField = $.kd.bos.metadata.entity.commonfield.GeoPointField;
export declare const GeoPointField: $.kd.bos.metadata.entity.commonfield.GeoPointField_C;
export declare type IDBField = $.kd.bos.metadata.entity.commonfield.IDBField;
export declare const IDBField: $.kd.bos.metadata.entity.commonfield.IDBField;
export declare type IMultiDBField = $.kd.bos.metadata.entity.commonfield.IMultiDBField;
export declare const IMultiDBField: $.kd.bos.metadata.entity.commonfield.IMultiDBField;
export declare type IPrivacyField = $.kd.bos.metadata.entity.commonfield.IPrivacyField;
export declare const IPrivacyField: $.kd.bos.metadata.entity.commonfield.IPrivacyField;
export declare type IntegerField = $.kd.bos.metadata.entity.commonfield.IntegerField;
export declare const IntegerField: $.kd.bos.metadata.entity.commonfield.IntegerField_C;
export declare type LargeTextField = $.kd.bos.metadata.entity.commonfield.LargeTextField;
export declare const LargeTextField: $.kd.bos.metadata.entity.commonfield.LargeTextField_C;
export declare type LongPressItem = $.kd.bos.metadata.entity.commonfield.LongPressItem;
export declare const LongPressItem: $.kd.bos.metadata.entity.commonfield.LongPressItem_C;
export declare type MulComboField = $.kd.bos.metadata.entity.commonfield.MulComboField;
export declare const MulComboField: $.kd.bos.metadata.entity.commonfield.MulComboField_C;
export declare type MuliLangTextField = $.kd.bos.metadata.entity.commonfield.MuliLangTextField;
export declare const MuliLangTextField: $.kd.bos.metadata.entity.commonfield.MuliLangTextField_C;
export declare type RadioField = $.kd.bos.metadata.entity.commonfield.RadioField;
export declare const RadioField: $.kd.bos.metadata.entity.commonfield.RadioField_C;
export declare type RadioGroupField = $.kd.bos.metadata.entity.commonfield.RadioGroupField;
export declare const RadioGroupField: $.kd.bos.metadata.entity.commonfield.RadioGroupField_C;
export declare type RichTextField = $.kd.bos.metadata.entity.commonfield.RichTextField;
export declare const RichTextField: $.kd.bos.metadata.entity.commonfield.RichTextField_C;
export declare type SignatureField = $.kd.bos.metadata.entity.commonfield.SignatureField;
export declare const SignatureField: $.kd.bos.metadata.entity.commonfield.SignatureField_C;
export declare type StepperField = $.kd.bos.metadata.entity.commonfield.StepperField;
export declare const StepperField: $.kd.bos.metadata.entity.commonfield.StepperField_C;
export declare type TelephoneField = $.kd.bos.metadata.entity.commonfield.TelephoneField;
export declare const TelephoneField: $.kd.bos.metadata.entity.commonfield.TelephoneField_C;
export declare type TextAreaField = $.kd.bos.metadata.entity.commonfield.TextAreaField;
export declare const TextAreaField: $.kd.bos.metadata.entity.commonfield.TextAreaField_C;
export declare type TextField = $.kd.bos.metadata.entity.commonfield.TextField;
export declare const TextField: $.kd.bos.metadata.entity.commonfield.TextField_C;
export declare type TimeField = $.kd.bos.metadata.entity.commonfield.TimeField;
export declare const TimeField: $.kd.bos.metadata.entity.commonfield.TimeField_C;
export declare type TimeRangeField = $.kd.bos.metadata.entity.commonfield.TimeRangeField;
export declare const TimeRangeField: $.kd.bos.metadata.entity.commonfield.TimeRangeField_C;
export declare type AttachmentField = $.kd.bos.metadata.entity.commonfield.AttachmentField;
export declare const AttachmentField: $.kd.bos.metadata.entity.commonfield.AttachmentField_C;
