export declare type AbstractOpBizRuleParameterEdit = $.kd.bos.metadata.entity.operation.AbstractOpBizRuleParameterEdit;
export declare const AbstractOpBizRuleParameterEdit: $.kd.bos.metadata.entity.operation.AbstractOpBizRuleParameterEdit_C;
export declare type AbstractOpParameterPlugin = $.kd.bos.metadata.entity.operation.AbstractOpParameterPlugin;
export declare const AbstractOpParameterPlugin: $.kd.bos.metadata.entity.operation.AbstractOpParameterPlugin_C;
export declare type AuditParameter = $.kd.bos.metadata.entity.operation.AuditParameter;
export declare const AuditParameter: $.kd.bos.metadata.entity.operation.AuditParameter_C;
export declare type CallListParameter = $.kd.bos.metadata.entity.operation.CallListParameter;
export declare const CallListParameter: $.kd.bos.metadata.entity.operation.CallListParameter_C;
export declare type CopyEntryParameter = $.kd.bos.metadata.entity.operation.CopyEntryParameter;
export declare const CopyEntryParameter: $.kd.bos.metadata.entity.operation.CopyEntryParameter_C;
export declare type CopyParameter = $.kd.bos.metadata.entity.operation.CopyParameter;
export declare const CopyParameter: $.kd.bos.metadata.entity.operation.CopyParameter_C;
export declare type CustOpParameterPlugin = $.kd.bos.metadata.entity.operation.CustOpParameterPlugin;
export declare const CustOpParameterPlugin: $.kd.bos.metadata.entity.operation.CustOpParameterPlugin_C;
export declare type CustOperationParameter = $.kd.bos.metadata.entity.operation.CustOperationParameter;
export declare const CustOperationParameter: $.kd.bos.metadata.entity.operation.CustOperationParameter_C;
export declare type DelParameter = $.kd.bos.metadata.entity.operation.DelParameter;
export declare const DelParameter: $.kd.bos.metadata.entity.operation.DelParameter_C;
export declare type DeleteEntryParameter = $.kd.bos.metadata.entity.operation.DeleteEntryParameter;
export declare const DeleteEntryParameter: $.kd.bos.metadata.entity.operation.DeleteEntryParameter_C;
export declare type DoNothingParameter = $.kd.bos.metadata.entity.operation.DoNothingParameter;
export declare const DoNothingParameter: $.kd.bos.metadata.entity.operation.DoNothingParameter_C;
export declare type DrawParameter = $.kd.bos.metadata.entity.operation.DrawParameter;
export declare const DrawParameter: $.kd.bos.metadata.entity.operation.DrawParameter_C;
export declare type EntryOpParameter = $.kd.bos.metadata.entity.operation.EntryOpParameter;
export declare const EntryOpParameter: $.kd.bos.metadata.entity.operation.EntryOpParameter_C;
export declare type ExportParameter = $.kd.bos.metadata.entity.operation.ExportParameter;
export declare const ExportParameter: $.kd.bos.metadata.entity.operation.ExportParameter_C;
export declare type IOpBizRuleParameterEdit = $.kd.bos.metadata.entity.operation.IOpBizRuleParameterEdit;
export declare const IOpBizRuleParameterEdit: $.kd.bos.metadata.entity.operation.IOpBizRuleParameterEdit;
export declare type ImportParameter = $.kd.bos.metadata.entity.operation.ImportParameter;
export declare const ImportParameter: $.kd.bos.metadata.entity.operation.ImportParameter_C;
export declare type NewEntryParameter = $.kd.bos.metadata.entity.operation.NewEntryParameter;
export declare const NewEntryParameter: $.kd.bos.metadata.entity.operation.NewEntryParameter_C;
export declare type OpBizRuleElement = $.kd.bos.metadata.entity.operation.OpBizRuleElement;
export declare const OpBizRuleElement: $.kd.bos.metadata.entity.operation.OpBizRuleElement_C;
export declare type OpenQingViewParameter = $.kd.bos.metadata.entity.operation.OpenQingViewParameter;
export declare const OpenQingViewParameter: $.kd.bos.metadata.entity.operation.OpenQingViewParameter_C;
export declare type Operation = $.kd.bos.metadata.entity.operation.Operation;
export declare const Operation: $.kd.bos.metadata.entity.operation.Operation_C;
export declare type OperationParameter = $.kd.bos.metadata.entity.operation.OperationParameter;
export declare const OperationParameter: $.kd.bos.metadata.entity.operation.OperationParameter_C;
export declare type PushAndSaveParameter = $.kd.bos.metadata.entity.operation.PushAndSaveParameter;
export declare const PushAndSaveParameter: $.kd.bos.metadata.entity.operation.PushAndSaveParameter_C;
export declare type SaveParameter = $.kd.bos.metadata.entity.operation.SaveParameter;
export declare const SaveParameter: $.kd.bos.metadata.entity.operation.SaveParameter_C;
export declare type StatusConvertParameter = $.kd.bos.metadata.entity.operation.StatusConvertParameter;
export declare const StatusConvertParameter: $.kd.bos.metadata.entity.operation.StatusConvertParameter_C;
export declare type TrackDownParameter = $.kd.bos.metadata.entity.operation.TrackDownParameter;
export declare const TrackDownParameter: $.kd.bos.metadata.entity.operation.TrackDownParameter_C;
export declare type TrackUpParameter = $.kd.bos.metadata.entity.operation.TrackUpParameter;
export declare const TrackUpParameter: $.kd.bos.metadata.entity.operation.TrackUpParameter_C;
export declare type UnAuditParameter = $.kd.bos.metadata.entity.operation.UnAuditParameter;
export declare const UnAuditParameter: $.kd.bos.metadata.entity.operation.UnAuditParameter_C;
