export declare type AbstractValidationParamPlugin = $.kd.bos.metadata.entity.validation.AbstractValidationParamPlugin;
export declare const AbstractValidationParamPlugin: $.kd.bos.metadata.entity.validation.AbstractValidationParamPlugin_C;
export declare type ConditionValidation = $.kd.bos.metadata.entity.validation.ConditionValidation;
export declare const ConditionValidation: $.kd.bos.metadata.entity.validation.ConditionValidation_C;
export declare type CustValidation = $.kd.bos.metadata.entity.validation.CustValidation;
export declare const CustValidation: $.kd.bos.metadata.entity.validation.CustValidation_C;
export declare type CustValidationParamPlugin = $.kd.bos.metadata.entity.validation.CustValidationParamPlugin;
export declare const CustValidationParamPlugin: $.kd.bos.metadata.entity.validation.CustValidationParamPlugin_C;
export declare type DynamicValidation = $.kd.bos.metadata.entity.validation.DynamicValidation;
export declare const DynamicValidation: $.kd.bos.metadata.entity.validation.DynamicValidation_C;
export declare type GrpfieldsuniqueValidation = $.kd.bos.metadata.entity.validation.GrpfieldsuniqueValidation;
export declare const GrpfieldsuniqueValidation: $.kd.bos.metadata.entity.validation.GrpfieldsuniqueValidation_C;
export declare type MustInputValidation = $.kd.bos.metadata.entity.validation.MustInputValidation;
export declare const MustInputValidation: $.kd.bos.metadata.entity.validation.MustInputValidation_C;
export declare type PreCondition = $.kd.bos.metadata.entity.validation.PreCondition;
export declare const PreCondition: $.kd.bos.metadata.entity.validation.PreCondition_C;
export declare type Validation = $.kd.bos.metadata.entity.validation.Validation;
export declare const Validation: $.kd.bos.metadata.entity.validation.Validation_C;
export declare type ValidationType = $.kd.bos.metadata.entity.validation.ValidationType;
export declare const ValidationType: $.kd.bos.metadata.entity.validation.ValidationType_C;
export declare type ValidationTypeLoader = $.kd.bos.metadata.entity.validation.ValidationTypeLoader;
export declare const ValidationTypeLoader: $.kd.bos.metadata.entity.validation.ValidationTypeLoader_C;
export declare type ValidationTypes = $.kd.bos.metadata.entity.validation.ValidationTypes;
export declare const ValidationTypes: $.kd.bos.metadata.entity.validation.ValidationTypes_C;
