export declare type CardBindDataDTO = $.kd.sdk.hr.hspm.common.ext.file.CardBindDataDTO;
export declare const CardBindDataDTO: $.kd.sdk.hr.hspm.common.ext.file.CardBindDataDTO_C;
export declare type DialogBindDataDTO = $.kd.sdk.hr.hspm.common.ext.file.DialogBindDataDTO;
export declare const DialogBindDataDTO: $.kd.sdk.hr.hspm.common.ext.file.DialogBindDataDTO_C;
export declare type EmpReportExtCalculateDTO = $.kd.sdk.hr.hspm.common.ext.file.EmpReportExtCalculateDTO;
export declare const EmpReportExtCalculateDTO: $.kd.sdk.hr.hspm.common.ext.file.EmpReportExtCalculateDTO_C;
export declare type EmpReportExtColumnDTO = $.kd.sdk.hr.hspm.common.ext.file.EmpReportExtColumnDTO;
export declare const EmpReportExtColumnDTO: $.kd.sdk.hr.hspm.common.ext.file.EmpReportExtColumnDTO_C;
export declare type EmpReportExtQueryFieldsDTO = $.kd.sdk.hr.hspm.common.ext.file.EmpReportExtQueryFieldsDTO;
export declare const EmpReportExtQueryFieldsDTO: $.kd.sdk.hr.hspm.common.ext.file.EmpReportExtQueryFieldsDTO_C;
export declare type EmpReportExtQueryFilterDTO = $.kd.sdk.hr.hspm.common.ext.file.EmpReportExtQueryFilterDTO;
export declare const EmpReportExtQueryFilterDTO: $.kd.sdk.hr.hspm.common.ext.file.EmpReportExtQueryFilterDTO_C;
export declare type EmpReportExtReletionFilterDTO = $.kd.sdk.hr.hspm.common.ext.file.EmpReportExtReletionFilterDTO;
export declare const EmpReportExtReletionFilterDTO: $.kd.sdk.hr.hspm.common.ext.file.EmpReportExtReletionFilterDTO_C;
export declare type EmpSupRelDTO = $.kd.sdk.hr.hspm.common.ext.file.EmpSupRelDTO;
export declare const EmpSupRelDTO: $.kd.sdk.hr.hspm.common.ext.file.EmpSupRelDTO_C;
export declare type MobileHomeVectorDTO = $.kd.sdk.hr.hspm.common.ext.file.MobileHomeVectorDTO;
export declare const MobileHomeVectorDTO: $.kd.sdk.hr.hspm.common.ext.file.MobileHomeVectorDTO_C;
export declare type QuitEmpReportExtCalculateDTO = $.kd.sdk.hr.hspm.common.ext.file.QuitEmpReportExtCalculateDTO;
export declare const QuitEmpReportExtCalculateDTO: $.kd.sdk.hr.hspm.common.ext.file.QuitEmpReportExtCalculateDTO_C;
export declare type QuitEmpReportExtColumnDTO = $.kd.sdk.hr.hspm.common.ext.file.QuitEmpReportExtColumnDTO;
export declare const QuitEmpReportExtColumnDTO: $.kd.sdk.hr.hspm.common.ext.file.QuitEmpReportExtColumnDTO_C;
export declare type QuitEmpReportExtHisQueryDateDTO = $.kd.sdk.hr.hspm.common.ext.file.QuitEmpReportExtHisQueryDateDTO;
export declare const QuitEmpReportExtHisQueryDateDTO: $.kd.sdk.hr.hspm.common.ext.file.QuitEmpReportExtHisQueryDateDTO_C;
export declare type QuitEmpReportExtQueryFieldsDTO = $.kd.sdk.hr.hspm.common.ext.file.QuitEmpReportExtQueryFieldsDTO;
export declare const QuitEmpReportExtQueryFieldsDTO: $.kd.sdk.hr.hspm.common.ext.file.QuitEmpReportExtQueryFieldsDTO_C;
export declare type QuitEmpReportExtQueryFilterDTO = $.kd.sdk.hr.hspm.common.ext.file.QuitEmpReportExtQueryFilterDTO;
export declare const QuitEmpReportExtQueryFilterDTO: $.kd.sdk.hr.hspm.common.ext.file.QuitEmpReportExtQueryFilterDTO_C;
export declare type QuitEmpReportExtReletionFilterDTO = $.kd.sdk.hr.hspm.common.ext.file.QuitEmpReportExtReletionFilterDTO;
export declare const QuitEmpReportExtReletionFilterDTO: $.kd.sdk.hr.hspm.common.ext.file.QuitEmpReportExtReletionFilterDTO_C;
export declare type SideBarDataDTO = $.kd.sdk.hr.hspm.common.ext.file.SideBarDataDTO;
export declare const SideBarDataDTO: $.kd.sdk.hr.hspm.common.ext.file.SideBarDataDTO_C;
