export declare type AdvConAp = $.kd.bos.metadata.form.container.AdvConAp;
export declare const AdvConAp: $.kd.bos.metadata.form.container.AdvConAp_C;
export declare type AdvConBarItemAp = $.kd.bos.metadata.form.container.AdvConBarItemAp;
export declare const AdvConBarItemAp: $.kd.bos.metadata.form.container.AdvConBarItemAp_C;
export declare type AdvConChildPanelAp = $.kd.bos.metadata.form.container.AdvConChildPanelAp;
export declare const AdvConChildPanelAp: $.kd.bos.metadata.form.container.AdvConChildPanelAp_C;
export declare type AdvConSummaryPanelAp = $.kd.bos.metadata.form.container.AdvConSummaryPanelAp;
export declare const AdvConSummaryPanelAp: $.kd.bos.metadata.form.container.AdvConSummaryPanelAp_C;
export declare type AdvConToolbarAp = $.kd.bos.metadata.form.container.AdvConToolbarAp;
export declare const AdvConToolbarAp: $.kd.bos.metadata.form.container.AdvConToolbarAp_C;
export declare type ColumnAp = $.kd.bos.metadata.form.container.ColumnAp;
export declare const ColumnAp: $.kd.bos.metadata.form.container.ColumnAp_C;
export declare type ColumnPanelAp = $.kd.bos.metadata.form.container.ColumnPanelAp;
export declare const ColumnPanelAp: $.kd.bos.metadata.form.container.ColumnPanelAp_C;
export declare type FieldgroupPanelAp = $.kd.bos.metadata.form.container.FieldgroupPanelAp;
export declare const FieldgroupPanelAp: $.kd.bos.metadata.form.container.FieldgroupPanelAp_C;
export declare type FieldsetPanelAp = $.kd.bos.metadata.form.container.FieldsetPanelAp;
export declare const FieldsetPanelAp: $.kd.bos.metadata.form.container.FieldsetPanelAp_C;
export declare type FlexPanelAp = $.kd.bos.metadata.form.container.FlexPanelAp;
export declare const FlexPanelAp: $.kd.bos.metadata.form.container.FlexPanelAp_C;
export declare type GridFlatPanelAp = $.kd.bos.metadata.form.container.GridFlatPanelAp;
export declare const GridFlatPanelAp: $.kd.bos.metadata.form.container.GridFlatPanelAp_C;
export declare type HomePageTabAp = $.kd.bos.metadata.form.container.HomePageTabAp;
export declare const HomePageTabAp: $.kd.bos.metadata.form.container.HomePageTabAp_C;
export declare type HomePageTabItemAp = $.kd.bos.metadata.form.container.HomePageTabItemAp;
export declare const HomePageTabItemAp: $.kd.bos.metadata.form.container.HomePageTabItemAp_C;
export declare type LayoutFlexAp = $.kd.bos.metadata.form.container.LayoutFlexAp;
export declare const LayoutFlexAp: $.kd.bos.metadata.form.container.LayoutFlexAp_C;
export declare type SidePanelAp = $.kd.bos.metadata.form.container.SidePanelAp;
export declare const SidePanelAp: $.kd.bos.metadata.form.container.SidePanelAp_C;
export declare type SplitContainerAp = $.kd.bos.metadata.form.container.SplitContainerAp;
export declare const SplitContainerAp: $.kd.bos.metadata.form.container.SplitContainerAp_C;
export declare type SplitPanelAp = $.kd.bos.metadata.form.container.SplitPanelAp;
export declare const SplitPanelAp: $.kd.bos.metadata.form.container.SplitPanelAp_C;
export declare type TabAp = $.kd.bos.metadata.form.container.TabAp;
export declare const TabAp: $.kd.bos.metadata.form.container.TabAp_C;
export declare type TabPageAp = $.kd.bos.metadata.form.container.TabPageAp;
export declare const TabPageAp: $.kd.bos.metadata.form.container.TabPageAp_C;
export declare type WizardAp = $.kd.bos.metadata.form.container.WizardAp;
export declare const WizardAp: $.kd.bos.metadata.form.container.WizardAp_C;
export declare type WizardPageAp = $.kd.bos.metadata.form.container.WizardPageAp;
export declare const WizardPageAp: $.kd.bos.metadata.form.container.WizardPageAp_C;
