export declare type BarItemAp = $.kd.bos.metadata.form.control.BarItemAp;
export declare const BarItemAp: $.kd.bos.metadata.form.control.BarItemAp_C;
export declare type ButtonAp = $.kd.bos.metadata.form.control.ButtonAp;
export declare const ButtonAp: $.kd.bos.metadata.form.control.ButtonAp_C;
export declare type CarouselFigureAp = $.kd.bos.metadata.form.control.CarouselFigureAp;
export declare const CarouselFigureAp: $.kd.bos.metadata.form.control.CarouselFigureAp_C;
export declare type CodeEditAp = $.kd.bos.metadata.form.control.CodeEditAp;
export declare const CodeEditAp: $.kd.bos.metadata.form.control.CodeEditAp_C;
export declare type DateSelectPanelAp = $.kd.bos.metadata.form.control.DateSelectPanelAp;
export declare const DateSelectPanelAp: $.kd.bos.metadata.form.control.DateSelectPanelAp_C;
export declare type EntryAp = $.kd.bos.metadata.form.control.EntryAp;
export declare const EntryAp: $.kd.bos.metadata.form.control.EntryAp_C;
export declare type EntryFieldAp = $.kd.bos.metadata.form.control.EntryFieldAp;
export declare const EntryFieldAp: $.kd.bos.metadata.form.control.EntryFieldAp_C;
export declare type EntryFieldContainerAp = $.kd.bos.metadata.form.control.EntryFieldContainerAp;
export declare const EntryFieldContainerAp: $.kd.bos.metadata.form.control.EntryFieldContainerAp_C;
export declare type EntryFieldGroupAp = $.kd.bos.metadata.form.control.EntryFieldGroupAp;
export declare const EntryFieldGroupAp: $.kd.bos.metadata.form.control.EntryFieldGroupAp_C;
export declare type ExchangeRateGroupCheckUtil = $.kd.bos.metadata.form.control.ExchangeRateGroupCheckUtil;
export declare const ExchangeRateGroupCheckUtil: $.kd.bos.metadata.form.control.ExchangeRateGroupCheckUtil_C;
export declare type FieldAp = $.kd.bos.metadata.form.control.FieldAp;
export declare const FieldAp: $.kd.bos.metadata.form.control.FieldAp_C;
export declare type FilterGridAp = $.kd.bos.metadata.form.control.FilterGridAp;
export declare const FilterGridAp: $.kd.bos.metadata.form.control.FilterGridAp_C;
export declare type FlatFieldAp = $.kd.bos.metadata.form.control.FlatFieldAp;
export declare const FlatFieldAp: $.kd.bos.metadata.form.control.FlatFieldAp_C;
export declare type FloatButtonAp = $.kd.bos.metadata.form.control.FloatButtonAp;
export declare const FloatButtonAp: $.kd.bos.metadata.form.control.FloatButtonAp_C;
export declare type FloatMenuAp = $.kd.bos.metadata.form.control.FloatMenuAp;
export declare const FloatMenuAp: $.kd.bos.metadata.form.control.FloatMenuAp_C;
export declare type FloatMenuItemAp = $.kd.bos.metadata.form.control.FloatMenuItemAp;
export declare const FloatMenuItemAp: $.kd.bos.metadata.form.control.FloatMenuItemAp_C;
export declare type FloatMenuPanelAp = $.kd.bos.metadata.form.control.FloatMenuPanelAp;
export declare const FloatMenuPanelAp: $.kd.bos.metadata.form.control.FloatMenuPanelAp_C;
export declare type HtmlAp = $.kd.bos.metadata.form.control.HtmlAp;
export declare const HtmlAp: $.kd.bos.metadata.form.control.HtmlAp_C;
export declare type HyperlinkAp = $.kd.bos.metadata.form.control.HyperlinkAp;
export declare const HyperlinkAp: $.kd.bos.metadata.form.control.HyperlinkAp_C;
export declare type IFrameAp = $.kd.bos.metadata.form.control.IFrameAp;
export declare const IFrameAp: $.kd.bos.metadata.form.control.IFrameAp_C;
export declare type LabelAp = $.kd.bos.metadata.form.control.LabelAp;
export declare const LabelAp: $.kd.bos.metadata.form.control.LabelAp_C;
export declare type OCRAp = $.kd.bos.metadata.form.control.OCRAp;
export declare const OCRAp: $.kd.bos.metadata.form.control.OCRAp_C;
export declare type OperationColumnAp = $.kd.bos.metadata.form.control.OperationColumnAp;
export declare const OperationColumnAp: $.kd.bos.metadata.form.control.OperationColumnAp_C;
export declare type ProgressBarAp = $.kd.bos.metadata.form.control.ProgressBarAp;
export declare const ProgressBarAp: $.kd.bos.metadata.form.control.ProgressBarAp_C;
export declare type QRCodeAp = $.kd.bos.metadata.form.control.QRCodeAp;
export declare const QRCodeAp: $.kd.bos.metadata.form.control.QRCodeAp_C;
export declare type RateAp = $.kd.bos.metadata.form.control.RateAp;
export declare const RateAp: $.kd.bos.metadata.form.control.RateAp_C;
export declare type RichTextEditorAp = $.kd.bos.metadata.form.control.RichTextEditorAp;
export declare const RichTextEditorAp: $.kd.bos.metadata.form.control.RichTextEditorAp_C;
export declare type SegmentOption = $.kd.bos.metadata.form.control.SegmentOption;
export declare const SegmentOption: $.kd.bos.metadata.form.control.SegmentOption_C;
export declare type SegmentedControlAp = $.kd.bos.metadata.form.control.SegmentedControlAp;
export declare const SegmentedControlAp: $.kd.bos.metadata.form.control.SegmentedControlAp_C;
export declare type SliderAp = $.kd.bos.metadata.form.control.SliderAp;
export declare const SliderAp: $.kd.bos.metadata.form.control.SliderAp_C;
export declare type StepsAp = $.kd.bos.metadata.form.control.StepsAp;
export declare const StepsAp: $.kd.bos.metadata.form.control.StepsAp_C;
export declare type StepsOption = $.kd.bos.metadata.form.control.StepsOption;
export declare const StepsOption: $.kd.bos.metadata.form.control.StepsOption_C;
export declare type TimelineAp = $.kd.bos.metadata.form.control.TimelineAp;
export declare const TimelineAp: $.kd.bos.metadata.form.control.TimelineAp_C;
export declare type TimelineContentOption = $.kd.bos.metadata.form.control.TimelineContentOption;
export declare const TimelineContentOption: $.kd.bos.metadata.form.control.TimelineContentOption_C;
export declare type TimelineLabelOption = $.kd.bos.metadata.form.control.TimelineLabelOption;
export declare const TimelineLabelOption: $.kd.bos.metadata.form.control.TimelineLabelOption_C;
export declare type TimelineOption = $.kd.bos.metadata.form.control.TimelineOption;
export declare const TimelineOption: $.kd.bos.metadata.form.control.TimelineOption_C;
export declare type ToolbarAp = $.kd.bos.metadata.form.control.ToolbarAp;
export declare const ToolbarAp: $.kd.bos.metadata.form.control.ToolbarAp_C;
export declare type TransferContainerAp = $.kd.bos.metadata.form.control.TransferContainerAp;
export declare const TransferContainerAp: $.kd.bos.metadata.form.control.TransferContainerAp_C;
export declare type TreeMenuAp = $.kd.bos.metadata.form.control.TreeMenuAp;
export declare const TreeMenuAp: $.kd.bos.metadata.form.control.TreeMenuAp_C;
export declare type TreeViewAp = $.kd.bos.metadata.form.control.TreeViewAp;
export declare const TreeViewAp: $.kd.bos.metadata.form.control.TreeViewAp_C;
export declare type VectorAp = $.kd.bos.metadata.form.control.VectorAp;
export declare const VectorAp: $.kd.bos.metadata.form.control.VectorAp_C;
export declare type VectorListAp = $.kd.bos.metadata.form.control.VectorListAp;
export declare const VectorListAp: $.kd.bos.metadata.form.control.VectorListAp_C;
export declare type WorkCalendarAp = $.kd.bos.metadata.form.control.WorkCalendarAp;
export declare const WorkCalendarAp: $.kd.bos.metadata.form.control.WorkCalendarAp_C;
export declare type AttachmentPanelAp = $.kd.bos.metadata.form.control.AttachmentPanelAp;
export declare const AttachmentPanelAp: $.kd.bos.metadata.form.control.AttachmentPanelAp_C;
export declare type ImageAp = $.kd.bos.metadata.form.control.ImageAp;
export declare const ImageAp: $.kd.bos.metadata.form.control.ImageAp_C;
