export declare type MobAdvFilterPanelAp = $.kd.bos.metadata.form.mcontrol.MobAdvFilterPanelAp;
export declare const MobAdvFilterPanelAp: $.kd.bos.metadata.form.mcontrol.MobAdvFilterPanelAp_C;
export declare type MobCommonBaseDataFilterColumnAp = $.kd.bos.metadata.form.mcontrol.MobCommonBaseDataFilterColumnAp;
export declare const MobCommonBaseDataFilterColumnAp: $.kd.bos.metadata.form.mcontrol.MobCommonBaseDataFilterColumnAp_C;
export declare type MobCommonCheckBoxFilterColumnAp = $.kd.bos.metadata.form.mcontrol.MobCommonCheckBoxFilterColumnAp;
export declare const MobCommonCheckBoxFilterColumnAp: $.kd.bos.metadata.form.mcontrol.MobCommonCheckBoxFilterColumnAp_C;
export declare type MobCommonDateFilterColumnAp = $.kd.bos.metadata.form.mcontrol.MobCommonDateFilterColumnAp;
export declare const MobCommonDateFilterColumnAp: $.kd.bos.metadata.form.mcontrol.MobCommonDateFilterColumnAp_C;
export declare type MobCommonFilterColumnAp = $.kd.bos.metadata.form.mcontrol.MobCommonFilterColumnAp;
export declare const MobCommonFilterColumnAp: $.kd.bos.metadata.form.mcontrol.MobCommonFilterColumnAp_C;
export declare type MobFilterPanelAp = $.kd.bos.metadata.form.mcontrol.MobFilterPanelAp;
export declare const MobFilterPanelAp: $.kd.bos.metadata.form.mcontrol.MobFilterPanelAp_C;
export declare type MobFilterSortAp = $.kd.bos.metadata.form.mcontrol.MobFilterSortAp;
export declare const MobFilterSortAp: $.kd.bos.metadata.form.mcontrol.MobFilterSortAp_C;
export declare type MobSortColumnAp = $.kd.bos.metadata.form.mcontrol.MobSortColumnAp;
export declare const MobSortColumnAp: $.kd.bos.metadata.form.mcontrol.MobSortColumnAp_C;
export declare type MobSortPanelAp = $.kd.bos.metadata.form.mcontrol.MobSortPanelAp;
export declare const MobSortPanelAp: $.kd.bos.metadata.form.mcontrol.MobSortPanelAp_C;
export declare type MobileSearchAp = $.kd.bos.metadata.form.mcontrol.MobileSearchAp;
export declare const MobileSearchAp: $.kd.bos.metadata.form.mcontrol.MobileSearchAp_C;
export declare type MBarItemAp = $.kd.bos.metadata.form.mcontrol.MBarItemAp;
export declare const MBarItemAp: $.kd.bos.metadata.form.mcontrol.MBarItemAp_C;
export declare type MBlockMenuAp = $.kd.bos.metadata.form.mcontrol.MBlockMenuAp;
export declare const MBlockMenuAp: $.kd.bos.metadata.form.mcontrol.MBlockMenuAp_C;
export declare type MBlockMenuItemAp = $.kd.bos.metadata.form.mcontrol.MBlockMenuItemAp;
export declare const MBlockMenuItemAp: $.kd.bos.metadata.form.mcontrol.MBlockMenuItemAp_C;
export declare type MTabBarAp = $.kd.bos.metadata.form.mcontrol.MTabBarAp;
export declare const MTabBarAp: $.kd.bos.metadata.form.mcontrol.MTabBarAp_C;
export declare type MTabBarFormAp = $.kd.bos.metadata.form.mcontrol.MTabBarFormAp;
export declare const MTabBarFormAp: $.kd.bos.metadata.form.mcontrol.MTabBarFormAp_C;
export declare type MTabBarItemAp = $.kd.bos.metadata.form.mcontrol.MTabBarItemAp;
export declare const MTabBarItemAp: $.kd.bos.metadata.form.mcontrol.MTabBarItemAp_C;
export declare type MToolbarAp = $.kd.bos.metadata.form.mcontrol.MToolbarAp;
export declare const MToolbarAp: $.kd.bos.metadata.form.mcontrol.MToolbarAp_C;
export declare type SearchAp = $.kd.bos.metadata.form.mcontrol.SearchAp;
export declare const SearchAp: $.kd.bos.metadata.form.mcontrol.SearchAp_C;
