export declare type AbstractListView = $.kd.bos.mvc.list.AbstractListView;
export declare const AbstractListView: $.kd.bos.mvc.list.AbstractListView_C;
export declare type ListDataProvider = $.kd.bos.mvc.list.ListDataProvider;
export declare const ListDataProvider: $.kd.bos.mvc.list.ListDataProvider_C;
export declare type ListModel = $.kd.bos.mvc.list.ListModel;
export declare const ListModel: $.kd.bos.mvc.list.ListModel_C;
export declare type ListUserConfig = $.kd.bos.mvc.list.ListUserConfig;
export declare const ListUserConfig: $.kd.bos.mvc.list.ListUserConfig_C;
export declare type ListView = $.kd.bos.mvc.list.ListView;
export declare const ListView: $.kd.bos.mvc.list.ListView_C;
export declare type MobileListView = $.kd.bos.mvc.list.MobileListView;
export declare const MobileListView: $.kd.bos.mvc.list.MobileListView_C;
export declare type QueryBuilderFactory = $.kd.bos.mvc.list.QueryBuilderFactory;
export declare const QueryBuilderFactory: $.kd.bos.mvc.list.QueryBuilderFactory_C;
export declare type TreeListModel = $.kd.bos.mvc.list.TreeListModel;
export declare const TreeListModel: $.kd.bos.mvc.list.TreeListModel_C;
export declare type TreeListView = $.kd.bos.mvc.list.TreeListView;
export declare const TreeListView: $.kd.bos.mvc.list.TreeListView_C;
