export declare type IAfterSettleProcess = $.kd.sdk.fi.ap.extpoint.settle.IAfterSettleProcess;
export declare const IAfterSettleProcess: $.kd.sdk.fi.ap.extpoint.settle.IAfterSettleProcess;
export declare type IManualSettleCheck = $.kd.sdk.fi.ap.extpoint.settle.IManualSettleCheck;
export declare const IManualSettleCheck: $.kd.sdk.fi.ap.extpoint.settle.IManualSettleCheck;
export declare type IPaySettleWarnFilter = $.kd.sdk.fi.ap.extpoint.settle.IPaySettleWarnFilter;
export declare const IPaySettleWarnFilter: $.kd.sdk.fi.ap.extpoint.settle.IPaySettleWarnFilter;
export declare type IPreSettleFilter = $.kd.sdk.fi.ap.extpoint.settle.IPreSettleFilter;
export declare const IPreSettleFilter: $.kd.sdk.fi.ap.extpoint.settle.IPreSettleFilter;
export declare type ISettleMatchExt = $.kd.sdk.fi.ap.extpoint.settle.ISettleMatchExt;
export declare const ISettleMatchExt: $.kd.sdk.fi.ap.extpoint.settle.ISettleMatchExt;
