export declare type AlgoX = $.kd.bos.algox.AlgoX;
export declare const AlgoX: $.kd.bos.algox.AlgoX_C;
export declare type AlgoXCallBack = $.kd.bos.algox.AlgoXCallBack;
export declare const AlgoXCallBack: $.kd.bos.algox.AlgoXCallBack;
export declare type AlgoXModule = $.kd.bos.algox.AlgoXModule;
export declare const AlgoXModule: $.kd.bos.algox.AlgoXModule_C;
export declare type CancelTimeoutException = $.kd.bos.algox.CancelTimeoutException;
export declare const CancelTimeoutException: $.kd.bos.algox.CancelTimeoutException_C;
export declare type CoGroupDataSetX = $.kd.bos.algox.CoGroupDataSetX;
export declare const CoGroupDataSetX: $.kd.bos.algox.CoGroupDataSetX_C;
export declare type CoGroupFunction = $.kd.bos.algox.CoGroupFunction;
export declare const CoGroupFunction: $.kd.bos.algox.CoGroupFunction_C;
export declare type Collector = $.kd.bos.algox.Collector;
export declare const Collector: $.kd.bos.algox.Collector;
export declare type CommitTimeoutException = $.kd.bos.algox.CommitTimeoutException;
export declare const CommitTimeoutException: $.kd.bos.algox.CommitTimeoutException_C;
export declare type DataSetX = $.kd.bos.algox.DataSetX;
export declare const DataSetX: $.kd.bos.algox.DataSetX;
export declare type FilterFunction = $.kd.bos.algox.FilterFunction;
export declare const FilterFunction: $.kd.bos.algox.FilterFunction_C;
export declare type FlatMapFunction = $.kd.bos.algox.FlatMapFunction;
export declare const FlatMapFunction: $.kd.bos.algox.FlatMapFunction_C;
export declare type GroupCombineFunction = $.kd.bos.algox.GroupCombineFunction;
export declare const GroupCombineFunction: $.kd.bos.algox.GroupCombineFunction_C;
export declare type GroupCombineReduceFunction = $.kd.bos.algox.GroupCombineReduceFunction;
export declare const GroupCombineReduceFunction: $.kd.bos.algox.GroupCombineReduceFunction_C;
export declare type GroupReduceFunction = $.kd.bos.algox.GroupReduceFunction;
export declare const GroupReduceFunction: $.kd.bos.algox.GroupReduceFunction_C;
export declare type Grouper = $.kd.bos.algox.Grouper;
export declare const Grouper: $.kd.bos.algox.Grouper_C;
export declare type JobSession = $.kd.bos.algox.JobSession;
export declare const JobSession: $.kd.bos.algox.JobSession_C;
export declare type JoinDataSetX = $.kd.bos.algox.JoinDataSetX;
export declare const JoinDataSetX: $.kd.bos.algox.JoinDataSetX_C;
export declare type JoinFunction = $.kd.bos.algox.JoinFunction;
export declare const JoinFunction: $.kd.bos.algox.JoinFunction_C;
export declare type MapFunction = $.kd.bos.algox.MapFunction;
export declare const MapFunction: $.kd.bos.algox.MapFunction_C;
export declare type ResultAwarable = $.kd.bos.algox.ResultAwarable;
export declare const ResultAwarable: $.kd.bos.algox.ResultAwarable;
export declare type RowX = $.kd.bos.algox.RowX;
export declare const RowX: $.kd.bos.algox.RowX_C;
export declare type RunningTimeoutException = $.kd.bos.algox.RunningTimeoutException;
export declare const RunningTimeoutException: $.kd.bos.algox.RunningTimeoutException_C;
