export declare type Algo = $.kd.bos.algo.Algo;
export declare const Algo: $.kd.bos.algo.Algo_C;
export declare type AlgoContext = $.kd.bos.algo.AlgoContext;
export declare const AlgoContext: $.kd.bos.algo.AlgoContext;
export declare type AlgoException = $.kd.bos.algo.AlgoException;
export declare const AlgoException: $.kd.bos.algo.AlgoException_C;
export declare type AlgoModule = $.kd.bos.algo.AlgoModule;
export declare const AlgoModule: $.kd.bos.algo.AlgoModule_C;
export declare type CacheHint = $.kd.bos.algo.CacheHint;
export declare const CacheHint: $.kd.bos.algo.CacheHint_C;
export declare type CachedDataSet = $.kd.bos.algo.CachedDataSet;
export declare const CachedDataSet: $.kd.bos.algo.CachedDataSet;
export declare type CachedDataSet$Builder = $.kd.bos.algo.CachedDataSet$Builder;
export declare const CachedDataSet$Builder: $.kd.bos.algo.CachedDataSet$Builder;
export declare type Collector = $.kd.bos.algo.Collector;
export declare const Collector: $.kd.bos.algo.Collector;
export declare type CustomAggFunction = $.kd.bos.algo.CustomAggFunction;
export declare const CustomAggFunction: $.kd.bos.algo.CustomAggFunction_C;
export declare type CustomizedInput = $.kd.bos.algo.CustomizedInput;
export declare const CustomizedInput: $.kd.bos.algo.CustomizedInput;
export declare type CustomizedOutput = $.kd.bos.algo.CustomizedOutput;
export declare const CustomizedOutput: $.kd.bos.algo.CustomizedOutput;
export declare type DataSet = $.kd.bos.algo.DataSet;
export declare const DataSet: $.kd.bos.algo.DataSet;
export declare type DataSet$Listener = $.kd.bos.algo.DataSet$Listener;
export declare const DataSet$Listener: $.kd.bos.algo.DataSet$Listener;
export declare type DataSetBuilder = $.kd.bos.algo.DataSetBuilder;
export declare const DataSetBuilder: $.kd.bos.algo.DataSetBuilder;
export declare type DataType = $.kd.bos.algo.DataType;
export declare const DataType: $.kd.bos.algo.DataType_C;
export declare type Field = $.kd.bos.algo.Field;
export declare const Field: $.kd.bos.algo.Field_C;
export declare type FilterFunction = $.kd.bos.algo.FilterFunction;
export declare const FilterFunction: $.kd.bos.algo.FilterFunction_C;
export declare type GroupbyDataSet = $.kd.bos.algo.GroupbyDataSet;
export declare const GroupbyDataSet: $.kd.bos.algo.GroupbyDataSet;
export declare type HashJoinDataSet = $.kd.bos.algo.HashJoinDataSet;
export declare const HashJoinDataSet: $.kd.bos.algo.HashJoinDataSet;
export declare type HashTable = $.kd.bos.algo.HashTable;
export declare const HashTable: $.kd.bos.algo.HashTable;
export declare type Input = $.kd.bos.algo.Input;
export declare const Input: $.kd.bos.algo.Input;
export declare type JoinDataSet = $.kd.bos.algo.JoinDataSet;
export declare const JoinDataSet: $.kd.bos.algo.JoinDataSet;
export declare type JoinHint = $.kd.bos.algo.JoinHint;
export declare const JoinHint: $.kd.bos.algo.JoinHint_C;
export declare type JoinType = $.kd.bos.algo.JoinType;
export declare const JoinType: typeof $.kd.bos.algo.JoinType;
export declare type MapFunction = $.kd.bos.algo.MapFunction;
export declare const MapFunction: $.kd.bos.algo.MapFunction_C;
export declare type Output = $.kd.bos.algo.Output;
export declare const Output: $.kd.bos.algo.Output;
export declare type ReduceGroupFunction = $.kd.bos.algo.ReduceGroupFunction;
export declare const ReduceGroupFunction: $.kd.bos.algo.ReduceGroupFunction_C;
export declare type ReduceGroupFunctionWithCollector = $.kd.bos.algo.ReduceGroupFunctionWithCollector;
export declare const ReduceGroupFunctionWithCollector: $.kd.bos.algo.ReduceGroupFunctionWithCollector_C;
export declare type Row = $.kd.bos.algo.Row;
export declare const Row: $.kd.bos.algo.Row;
export declare type RowFeature = $.kd.bos.algo.RowFeature;
export declare const RowFeature: $.kd.bos.algo.RowFeature;
export declare type RowMeta = $.kd.bos.algo.RowMeta;
export declare const RowMeta: $.kd.bos.algo.RowMeta_C;
export declare type RowMetaFactory = $.kd.bos.algo.RowMetaFactory;
export declare const RowMetaFactory: $.kd.bos.algo.RowMetaFactory_C;
export declare type RowUtil = $.kd.bos.algo.RowUtil;
export declare const RowUtil: $.kd.bos.algo.RowUtil_C;
export declare type SqlHint = $.kd.bos.algo.SqlHint;
export declare const SqlHint: $.kd.bos.algo.SqlHint_C;
