export declare type AbstractBillPlugIn = $.kd.bos.bill.AbstractBillPlugIn;
export declare const AbstractBillPlugIn: $.kd.bos.bill.AbstractBillPlugIn_C;
export declare type AbstractBillWebApiPlugin = $.kd.bos.bill.AbstractBillWebApiPlugin;
export declare const AbstractBillWebApiPlugin: $.kd.bos.bill.AbstractBillWebApiPlugin_C;
export declare type AbstractMobBillPlugIn = $.kd.bos.bill.AbstractMobBillPlugIn;
export declare const AbstractMobBillPlugIn: $.kd.bos.bill.AbstractMobBillPlugIn_C;
export declare type IBillPlugin = $.kd.bos.bill.IBillPlugin;
export declare const IBillPlugin: $.kd.bos.bill.IBillPlugin;
export declare type IBillWebApiPlugin = $.kd.bos.bill.IBillWebApiPlugin;
export declare const IBillWebApiPlugin: $.kd.bos.bill.IBillWebApiPlugin;
export declare type IMobileBillView = $.kd.bos.bill.IMobileBillView;
export declare const IMobileBillView: $.kd.bos.bill.IMobileBillView;
export declare type BillOperationStatus = $.kd.bos.bill.BillOperationStatus;
export declare const BillOperationStatus: typeof $.kd.bos.bill.BillOperationStatus;
export declare type BillShowParameter = $.kd.bos.bill.BillShowParameter;
export declare const BillShowParameter: $.kd.bos.bill.BillShowParameter_C;
export declare type CtsyBillShowParameter = $.kd.bos.bill.CtsyBillShowParameter;
export declare const CtsyBillShowParameter: $.kd.bos.bill.CtsyBillShowParameter_C;
export declare type IBillView = $.kd.bos.bill.IBillView;
export declare const IBillView: $.kd.bos.bill.IBillView;
export declare type MobileBillShowParameter = $.kd.bos.bill.MobileBillShowParameter;
export declare const MobileBillShowParameter: $.kd.bos.bill.MobileBillShowParameter_C;
export declare type MobileFormPosition = $.kd.bos.bill.MobileFormPosition;
export declare const MobileFormPosition: typeof $.kd.bos.bill.MobileFormPosition;
export declare type OperationStatus = $.kd.bos.bill.OperationStatus;
export declare const OperationStatus: typeof $.kd.bos.bill.OperationStatus;
