export declare type Consumer = $.kd.bos.dataentity.Consumer;
export declare const Consumer: $.kd.bos.dataentity.Consumer;
export declare type DataEntityModule = $.kd.bos.dataentity.DataEntityModule;
export declare const DataEntityModule: $.kd.bos.dataentity.DataEntityModule_C;
export declare type FourTuple = $.kd.bos.dataentity.FourTuple;
export declare const FourTuple: $.kd.bos.dataentity.FourTuple_C;
export declare type OperateOption = $.kd.bos.dataentity.OperateOption;
export declare const OperateOption: $.kd.bos.dataentity.OperateOption_C;
export declare type OperateOptionPrivate = $.kd.bos.dataentity.OperateOptionPrivate;
export declare const OperateOptionPrivate: $.kd.bos.dataentity.OperateOptionPrivate_C;
export declare type RefObject = $.kd.bos.dataentity.RefObject;
export declare const RefObject: $.kd.bos.dataentity.RefObject_C;
export declare type SqlParameter = $.kd.bos.dataentity.SqlParameter;
export declare const SqlParameter: $.kd.bos.dataentity.SqlParameter_C;
export declare type ThreeTuple = $.kd.bos.dataentity.ThreeTuple;
export declare const ThreeTuple: $.kd.bos.dataentity.ThreeTuple_C;
export declare type Tuple = $.kd.bos.dataentity.Tuple;
export declare const Tuple: $.kd.bos.dataentity.Tuple_C;
export declare type TypesContainer = $.kd.bos.dataentity.TypesContainer;
export declare const TypesContainer: $.kd.bos.dataentity.TypesContainer_C;
