export declare type AnchorItems = $.kd.bos.entity.AnchorItems;
export declare const AnchorItems: $.kd.bos.entity.AnchorItems_C;
export declare type DBVersion = $.kd.bos.entity.DBVersion;
export declare const DBVersion: $.kd.bos.entity.DBVersion_C;
export declare type KDDMModule = $.kd.bos.entity.KDDMModule;
export declare const KDDMModule: $.kd.bos.entity.KDDMModule_C;
export declare type ListboxItem = $.kd.bos.entity.ListboxItem;
export declare const ListboxItem: $.kd.bos.entity.ListboxItem_C;
export declare type MarkdownLinkData = $.kd.bos.entity.MarkdownLinkData;
export declare const MarkdownLinkData: $.kd.bos.entity.MarkdownLinkData_C;
export declare type TileItem = $.kd.bos.entity.TileItem;
export declare const TileItem: $.kd.bos.entity.TileItem_C;
export declare type ValueTextItem = $.kd.bos.entity.ValueTextItem;
export declare const ValueTextItem: $.kd.bos.entity.ValueTextItem_C;
export declare type AbstractQueryBuilder = $.kd.bos.entity.AbstractQueryBuilder;
export declare const AbstractQueryBuilder: $.kd.bos.entity.AbstractQueryBuilder_C;
export declare type AppInfo = $.kd.bos.entity.AppInfo;
export declare const AppInfo: $.kd.bos.entity.AppInfo_C;
export declare type AppMenuInfo = $.kd.bos.entity.AppMenuInfo;
export declare const AppMenuInfo: $.kd.bos.entity.AppMenuInfo_C;
export declare type AppMetadataCache = $.kd.bos.entity.AppMetadataCache;
export declare const AppMetadataCache: $.kd.bos.entity.AppMetadataCache_C;
export declare type BOSRuntime = $.kd.bos.entity.BOSRuntime;
export declare const BOSRuntime: $.kd.bos.entity.BOSRuntime_C;
export declare type BadgeInfo = $.kd.bos.entity.BadgeInfo;
export declare const BadgeInfo: $.kd.bos.entity.BadgeInfo_C;
export declare type BasedataEntityType = $.kd.bos.entity.BasedataEntityType;
export declare const BasedataEntityType: $.kd.bos.entity.BasedataEntityType_C;
export declare type BillEntityType = $.kd.bos.entity.BillEntityType;
export declare const BillEntityType: $.kd.bos.entity.BillEntityType_C;
export declare type BillTypeControlInfo = $.kd.bos.entity.BillTypeControlInfo;
export declare const BillTypeControlInfo: $.kd.bos.entity.BillTypeControlInfo_C;
export declare type ComboPropShowStyle = $.kd.bos.entity.ComboPropShowStyle;
export declare const ComboPropShowStyle: typeof $.kd.bos.entity.ComboPropShowStyle;
export declare type CompareTypeConfig = $.kd.bos.entity.CompareTypeConfig;
export declare const CompareTypeConfig: $.kd.bos.entity.CompareTypeConfig_C;
export declare type CompareTypeField = $.kd.bos.entity.CompareTypeField;
export declare const CompareTypeField: $.kd.bos.entity.CompareTypeField_C;
export declare type CtLinkEntryType = $.kd.bos.entity.CtLinkEntryType;
export declare const CtLinkEntryType: $.kd.bos.entity.CtLinkEntryType_C;
export declare type CtlSchemaInfo = $.kd.bos.entity.CtlSchemaInfo;
export declare const CtlSchemaInfo: $.kd.bos.entity.CtlSchemaInfo_C;
export declare type EntityItemTypes = $.kd.bos.entity.EntityItemTypes;
export declare const EntityItemTypes: $.kd.bos.entity.EntityItemTypes_C;
export declare type EntityMetadataCache = $.kd.bos.entity.EntityMetadataCache;
export declare const EntityMetadataCache: $.kd.bos.entity.EntityMetadataCache_C;
export declare type EntityType = $.kd.bos.entity.EntityType;
export declare const EntityType: $.kd.bos.entity.EntityType_C;
export declare type EntityTypeUtil = $.kd.bos.entity.EntityTypeUtil;
export declare const EntityTypeUtil: $.kd.bos.entity.EntityTypeUtil_C;
export declare type EntryEntityDto = $.kd.bos.entity.EntryEntityDto;
export declare const EntryEntityDto: $.kd.bos.entity.EntryEntityDto_C;
export declare type EntryType = $.kd.bos.entity.EntryType;
export declare const EntryType: $.kd.bos.entity.EntryType_C;
export declare type ExtendedDataEntity = $.kd.bos.entity.ExtendedDataEntity;
export declare const ExtendedDataEntity: $.kd.bos.entity.ExtendedDataEntity_C;
export declare type ExtendedDataEntitySet = $.kd.bos.entity.ExtendedDataEntitySet;
export declare const ExtendedDataEntitySet: $.kd.bos.entity.ExtendedDataEntitySet_C;
export declare type FeatureOption = $.kd.bos.entity.FeatureOption;
export declare const FeatureOption: typeof $.kd.bos.entity.FeatureOption;
export declare type Features = $.kd.bos.entity.Features;
export declare const Features: $.kd.bos.entity.Features_C;
export declare type FlexEntityType = $.kd.bos.entity.FlexEntityType;
export declare const FlexEntityType: $.kd.bos.entity.FlexEntityType_C;
export declare type GetFilterFieldsParameter = $.kd.bos.entity.GetFilterFieldsParameter;
export declare const GetFilterFieldsParameter: $.kd.bos.entity.GetFilterFieldsParameter_C;
export declare type IBaseColumn = $.kd.bos.entity.IBaseColumn;
export declare const IBaseColumn: $.kd.bos.entity.IBaseColumn;
export declare type IColumn = $.kd.bos.entity.IColumn;
export declare const IColumn: $.kd.bos.entity.IColumn;
export declare type IFrameMessage = $.kd.bos.entity.IFrameMessage;
export declare const IFrameMessage: $.kd.bos.entity.IFrameMessage_C;
export declare type ISVInfo = $.kd.bos.entity.ISVInfo;
export declare const ISVInfo: $.kd.bos.entity.ISVInfo_C;
export declare type LinkEntryType = $.kd.bos.entity.LinkEntryType;
export declare const LinkEntryType: $.kd.bos.entity.LinkEntryType_C;
export declare type LinkSetElement = $.kd.bos.entity.LinkSetElement;
export declare const LinkSetElement: $.kd.bos.entity.LinkSetElement_C;
export declare type LinkSetItemElement = $.kd.bos.entity.LinkSetItemElement;
export declare const LinkSetItemElement: $.kd.bos.entity.LinkSetItemElement_C;
export declare type MainEntityType = $.kd.bos.entity.MainEntityType;
export declare const MainEntityType: $.kd.bos.entity.MainEntityType_C;
export declare type MobLocation = $.kd.bos.entity.MobLocation;
export declare const MobLocation: $.kd.bos.entity.MobLocation_C;
export declare type NumberFormatProvider = $.kd.bos.entity.NumberFormatProvider;
export declare const NumberFormatProvider: $.kd.bos.entity.NumberFormatProvider_C;
export declare type PermissionControlType = $.kd.bos.entity.PermissionControlType;
export declare const PermissionControlType: $.kd.bos.entity.PermissionControlType_C;
export declare type QueryEntityType = $.kd.bos.entity.QueryEntityType;
export declare const QueryEntityType: $.kd.bos.entity.QueryEntityType_C;
export declare type RefEntityType = $.kd.bos.entity.RefEntityType;
export declare const RefEntityType: $.kd.bos.entity.RefEntityType_C;
export declare type RefEntityTypeCache = $.kd.bos.entity.RefEntityTypeCache;
export declare const RefEntityTypeCache: $.kd.bos.entity.RefEntityTypeCache_C;
export declare type RefPropType = $.kd.bos.entity.RefPropType;
export declare const RefPropType: $.kd.bos.entity.RefPropType_C;
export declare type ReportQueryEntityType = $.kd.bos.entity.ReportQueryEntityType;
export declare const ReportQueryEntityType: $.kd.bos.entity.ReportQueryEntityType_C;
export declare type SelectedDisplayField = $.kd.bos.entity.SelectedDisplayField;
export declare const SelectedDisplayField: $.kd.bos.entity.SelectedDisplayField_C;
export declare type SingleOrgContextHelper = $.kd.bos.entity.SingleOrgContextHelper;
export declare const SingleOrgContextHelper: $.kd.bos.entity.SingleOrgContextHelper_C;
export declare type SubEntryType = $.kd.bos.entity.SubEntryType;
export declare const SubEntryType: $.kd.bos.entity.SubEntryType_C;
export declare type SummaryToField = $.kd.bos.entity.SummaryToField;
export declare const SummaryToField: $.kd.bos.entity.SummaryToField_C;
export declare type Tips = $.kd.bos.entity.Tips;
export declare const Tips: $.kd.bos.entity.Tips_C;
export declare type TipsLink = $.kd.bos.entity.TipsLink;
export declare const TipsLink: $.kd.bos.entity.TipsLink_C;
export declare type TreeEntryType = $.kd.bos.entity.TreeEntryType;
export declare const TreeEntryType: $.kd.bos.entity.TreeEntryType_C;
export declare type ValueMapItem = $.kd.bos.entity.ValueMapItem;
export declare const ValueMapItem: $.kd.bos.entity.ValueMapItem_C;
