export declare type AbstractStdExtPlugin = $.kd.bos.extplugin.AbstractStdExtPlugin;
export declare const AbstractStdExtPlugin: $.kd.bos.extplugin.AbstractStdExtPlugin_C;
export declare type ExtEvent = $.kd.bos.extplugin.ExtEvent;
export declare const ExtEvent: $.kd.bos.extplugin.ExtEvent_C;
export declare type PluginCall = $.kd.bos.extplugin.PluginCall;
export declare const PluginCall: $.kd.bos.extplugin.PluginCall;
export declare type PluginFilter = $.kd.bos.extplugin.PluginFilter;
export declare const PluginFilter: $.kd.bos.extplugin.PluginFilter;
export declare type PluginModule = $.kd.bos.extplugin.PluginModule;
export declare const PluginModule: $.kd.bos.extplugin.PluginModule_C;
export declare type PluginProvider = $.kd.bos.extplugin.PluginProvider;
export declare const PluginProvider: $.kd.bos.extplugin.PluginProvider;
export declare type PluginProxy = $.kd.bos.extplugin.PluginProxy;
export declare const PluginProxy: $.kd.bos.extplugin.PluginProxy;
export declare type ScriptExtensionManager = $.kd.bos.extplugin.ScriptExtensionManager;
export declare const ScriptExtensionManager: $.kd.bos.extplugin.ScriptExtensionManager_C;
export declare type StdExtPlugin = $.kd.bos.extplugin.StdExtPlugin;
export declare const StdExtPlugin: $.kd.bos.extplugin.StdExtPlugin;
export declare type StdExtPluginProxy = $.kd.bos.extplugin.StdExtPluginProxy;
export declare const StdExtPluginProxy: $.kd.bos.extplugin.StdExtPluginProxy_C;
