export declare type BatchDownloadRequest = $.kd.bos.fileservice.BatchDownloadRequest;
export declare const BatchDownloadRequest: $.kd.bos.fileservice.BatchDownloadRequest_C;
export declare type BatchDownloadRequest$Dir = $.kd.bos.fileservice.BatchDownloadRequest$Dir;
export declare const BatchDownloadRequest$Dir: $.kd.bos.fileservice.BatchDownloadRequest$Dir_C;
export declare type BatchDownloadRequest$File = $.kd.bos.fileservice.BatchDownloadRequest$File;
export declare const BatchDownloadRequest$File: $.kd.bos.fileservice.BatchDownloadRequest$File_C;
export declare type FileItem = $.kd.bos.fileservice.FileItem;
export declare const FileItem: $.kd.bos.fileservice.FileItem_C;
export declare type FileService = $.kd.bos.fileservice.FileService;
export declare const FileService: $.kd.bos.fileservice.FileService;
export declare type FileServiceFactory = $.kd.bos.fileservice.FileServiceFactory;
export declare const FileServiceFactory: $.kd.bos.fileservice.FileServiceFactory_C;
export declare type FileServiceModule = $.kd.bos.fileservice.FileServiceModule;
export declare const FileServiceModule: $.kd.bos.fileservice.FileServiceModule_C;
