export declare type AbstractFilterGridView = $.kd.bos.filter.AbstractFilterGridView;
export declare const AbstractFilterGridView: $.kd.bos.filter.AbstractFilterGridView_C;
export declare type CommonBaseDataFilterColumn = $.kd.bos.filter.CommonBaseDataFilterColumn;
export declare const CommonBaseDataFilterColumn: $.kd.bos.filter.CommonBaseDataFilterColumn_C;
export declare type CommonCheckBoxFilterColumn = $.kd.bos.filter.CommonCheckBoxFilterColumn;
export declare const CommonCheckBoxFilterColumn: $.kd.bos.filter.CommonCheckBoxFilterColumn_C;
export declare type CommonCheckBoxGroupFilterColumn = $.kd.bos.filter.CommonCheckBoxGroupFilterColumn;
export declare const CommonCheckBoxGroupFilterColumn: $.kd.bos.filter.CommonCheckBoxGroupFilterColumn_C;
export declare type CommonDateFilterColumn = $.kd.bos.filter.CommonDateFilterColumn;
export declare const CommonDateFilterColumn: $.kd.bos.filter.CommonDateFilterColumn_C;
export declare type CommonFilterColumn = $.kd.bos.filter.CommonFilterColumn;
export declare const CommonFilterColumn: $.kd.bos.filter.CommonFilterColumn_C;
export declare type CustomBaseDataFilterColumn = $.kd.bos.filter.CustomBaseDataFilterColumn;
export declare const CustomBaseDataFilterColumn: $.kd.bos.filter.CustomBaseDataFilterColumn_C;
export declare type CustomBaseDataSchemeFilterColumn = $.kd.bos.filter.CustomBaseDataSchemeFilterColumn;
export declare const CustomBaseDataSchemeFilterColumn: $.kd.bos.filter.CustomBaseDataSchemeFilterColumn_C;
export declare type CustomNumberFilterColumn = $.kd.bos.filter.CustomNumberFilterColumn;
export declare const CustomNumberFilterColumn: $.kd.bos.filter.CustomNumberFilterColumn_C;
export declare type CustomOrgFilterColumn = $.kd.bos.filter.CustomOrgFilterColumn;
export declare const CustomOrgFilterColumn: $.kd.bos.filter.CustomOrgFilterColumn_C;
export declare type CustomOrgSchemeFilterColumn = $.kd.bos.filter.CustomOrgSchemeFilterColumn;
export declare const CustomOrgSchemeFilterColumn: $.kd.bos.filter.CustomOrgSchemeFilterColumn_C;
export declare type DependField = $.kd.bos.filter.DependField;
export declare const DependField: $.kd.bos.filter.DependField_C;
export declare type FastSearchGridView = $.kd.bos.filter.FastSearchGridView;
export declare const FastSearchGridView: $.kd.bos.filter.FastSearchGridView_C;
export declare type FilterColumn = $.kd.bos.filter.FilterColumn;
export declare const FilterColumn: $.kd.bos.filter.FilterColumn_C;
export declare type FilterContainer = $.kd.bos.filter.FilterContainer;
export declare const FilterContainer: $.kd.bos.filter.FilterContainer_C;
export declare type FilterGridView = $.kd.bos.filter.FilterGridView;
export declare const FilterGridView: $.kd.bos.filter.FilterGridView_C;
export declare type FilterModel = $.kd.bos.filter.FilterModel;
export declare const FilterModel: $.kd.bos.filter.FilterModel_C;
export declare type SchemeBaseDataFilterColumn = $.kd.bos.filter.SchemeBaseDataFilterColumn;
export declare const SchemeBaseDataFilterColumn: $.kd.bos.filter.SchemeBaseDataFilterColumn_C;
export declare type SchemeFilterColumn = $.kd.bos.filter.SchemeFilterColumn;
export declare const SchemeFilterColumn: $.kd.bos.filter.SchemeFilterColumn_C;
export declare type SchemeFilterView = $.kd.bos.filter.SchemeFilterView;
export declare const SchemeFilterView: $.kd.bos.filter.SchemeFilterView_C;
export declare type FilterContainerFilterValues = $.kd.bos.filter.FilterContainerFilterValues;
export declare const FilterContainerFilterValues: $.kd.bos.filter.FilterContainerFilterValues_C;
export declare type FilterSchemeService = $.kd.bos.filter.FilterSchemeService;
export declare const FilterSchemeService: $.kd.bos.filter.FilterSchemeService_C;
export declare type FilterSchemeUIProxy = $.kd.bos.filter.FilterSchemeUIProxy;
export declare const FilterSchemeUIProxy: $.kd.bos.filter.FilterSchemeUIProxy_C;
export declare type ICustomController = $.kd.bos.filter.ICustomController;
export declare const ICustomController: $.kd.bos.filter.ICustomController;
export declare type PinnedCondition = $.kd.bos.filter.PinnedCondition;
export declare const PinnedCondition: $.kd.bos.filter.PinnedCondition_C;
export declare type PinnedConditionCollection = $.kd.bos.filter.PinnedConditionCollection;
export declare const PinnedConditionCollection: $.kd.bos.filter.PinnedConditionCollection_C;
