export declare type ShowFormHelper = $.kd.bos.form.ShowFormHelper;
export declare const ShowFormHelper: $.kd.bos.form.ShowFormHelper_C;
export declare type SingleOrgContextHelper = $.kd.bos.form.SingleOrgContextHelper;
export declare const SingleOrgContextHelper: $.kd.bos.form.SingleOrgContextHelper_C;
export declare type AbstractFormView = $.kd.bos.form.AbstractFormView;
export declare const AbstractFormView: $.kd.bos.form.AbstractFormView_C;
export declare type AnimationType = $.kd.bos.form.AnimationType;
export declare const AnimationType: typeof $.kd.bos.form.AnimationType;
export declare type BindingContext = $.kd.bos.form.BindingContext;
export declare const BindingContext: $.kd.bos.form.BindingContext_C;
export declare type ClientActions = $.kd.bos.form.ClientActions;
export declare const ClientActions: $.kd.bos.form.ClientActions_C;
export declare type ClientMethod = $.kd.bos.form.ClientMethod;
export declare const ClientMethod: typeof $.kd.bos.form.ClientMethod;
export declare type ClientMethodResult = $.kd.bos.form.ClientMethodResult;
export declare const ClientMethodResult: $.kd.bos.form.ClientMethodResult_C;
export declare type CloseCallBack = $.kd.bos.form.CloseCallBack;
export declare const CloseCallBack: $.kd.bos.form.CloseCallBack_C;
export declare type CloseCallBackWraper = $.kd.bos.form.CloseCallBackWraper;
export declare const CloseCallBackWraper: $.kd.bos.form.CloseCallBackWraper_C;
export declare type ColorUtils = $.kd.bos.form.ColorUtils;
export declare const ColorUtils: $.kd.bos.form.ColorUtils_C;
export declare type ConfirmCallBackListener = $.kd.bos.form.ConfirmCallBackListener;
export declare const ConfirmCallBackListener: $.kd.bos.form.ConfirmCallBackListener_C;
export declare type ConfirmTypes = $.kd.bos.form.ConfirmTypes;
export declare const ConfirmTypes: typeof $.kd.bos.form.ConfirmTypes;
export declare type ControlTypes = $.kd.bos.form.ControlTypes;
export declare const ControlTypes: $.kd.bos.form.ControlTypes_C;
export declare type CoreShowFormHelper = $.kd.bos.form.CoreShowFormHelper;
export declare const CoreShowFormHelper: $.kd.bos.form.CoreShowFormHelper_C;
export declare type CtsyFormShowParameter = $.kd.bos.form.CtsyFormShowParameter;
export declare const CtsyFormShowParameter: $.kd.bos.form.CtsyFormShowParameter_C;
export declare type FieldTip = $.kd.bos.form.FieldTip;
export declare const FieldTip: $.kd.bos.form.FieldTip_C;
export declare type FloatingDirection = $.kd.bos.form.FloatingDirection;
export declare const FloatingDirection: typeof $.kd.bos.form.FloatingDirection;
export declare type FormConfig = $.kd.bos.form.FormConfig;
export declare const FormConfig: $.kd.bos.form.FormConfig_C;
export declare type FormMetadataCache = $.kd.bos.form.FormMetadataCache;
export declare const FormMetadataCache: $.kd.bos.form.FormMetadataCache_C;
export declare type FormShowParameter = $.kd.bos.form.FormShowParameter;
export declare const FormShowParameter: $.kd.bos.form.FormShowParameter_C;
export declare type FormShowParameterNames = $.kd.bos.form.FormShowParameterNames;
export declare const FormShowParameterNames: $.kd.bos.form.FormShowParameterNames_C;
export declare type IClientViewProxy = $.kd.bos.form.IClientViewProxy;
export declare const IClientViewProxy: $.kd.bos.form.IClientViewProxy;
export declare type ICloseCallBack = $.kd.bos.form.ICloseCallBack;
export declare const ICloseCallBack: $.kd.bos.form.ICloseCallBack;
export declare type IConfirmCallBack = $.kd.bos.form.IConfirmCallBack;
export declare const IConfirmCallBack: $.kd.bos.form.IConfirmCallBack;
export declare type ICtsyShowParameter = $.kd.bos.form.ICtsyShowParameter;
export declare const ICtsyShowParameter: $.kd.bos.form.ICtsyShowParameter;
export declare type IFormUserConfig = $.kd.bos.form.IFormUserConfig;
export declare const IFormUserConfig: $.kd.bos.form.IFormUserConfig;
export declare type IFormView = $.kd.bos.form.IFormView;
export declare const IFormView: $.kd.bos.form.IFormView;
export declare type IMobileView = $.kd.bos.form.IMobileView;
export declare const IMobileView: $.kd.bos.form.IMobileView;
export declare type IPageCache = $.kd.bos.form.IPageCache;
export declare const IPageCache: $.kd.bos.form.IPageCache;
export declare type ITipsSupport = $.kd.bos.form.ITipsSupport;
export declare const ITipsSupport: $.kd.bos.form.ITipsSupport;
export declare type ListVisible = $.kd.bos.form.ListVisible;
export declare const ListVisible: typeof $.kd.bos.form.ListVisible;
export declare type MessageBoxLink = $.kd.bos.form.MessageBoxLink;
export declare const MessageBoxLink: $.kd.bos.form.MessageBoxLink_C;
export declare type MessageBoxOptions = $.kd.bos.form.MessageBoxOptions;
export declare const MessageBoxOptions: typeof $.kd.bos.form.MessageBoxOptions;
export declare type MessageBoxResult = $.kd.bos.form.MessageBoxResult;
export declare const MessageBoxResult: typeof $.kd.bos.form.MessageBoxResult;
export declare type MessageTypes = $.kd.bos.form.MessageTypes;
export declare const MessageTypes: typeof $.kd.bos.form.MessageTypes;
export declare type MobileFormShowParameter = $.kd.bos.form.MobileFormShowParameter;
export declare const MobileFormShowParameter: $.kd.bos.form.MobileFormShowParameter_C;
export declare type OpenStyle = $.kd.bos.form.OpenStyle;
export declare const OpenStyle: $.kd.bos.form.OpenStyle_C;
export declare type OperateParameter = $.kd.bos.form.OperateParameter;
export declare const OperateParameter: $.kd.bos.form.OperateParameter_C;
export declare type ShowType = $.kd.bos.form.ShowType;
export declare const ShowType: typeof $.kd.bos.form.ShowType;
export declare type SignCallbackLisenter = $.kd.bos.form.SignCallbackLisenter;
export declare const SignCallbackLisenter: $.kd.bos.form.SignCallbackLisenter;
export declare type StyleCss = $.kd.bos.form.StyleCss;
export declare const StyleCss: $.kd.bos.form.StyleCss_C;
export declare type TipsSupport = $.kd.bos.form.TipsSupport;
export declare const TipsSupport: $.kd.bos.form.TipsSupport_C;
