export declare type AbstractList = $.kd.bos.list.AbstractList;
export declare const AbstractList: $.kd.bos.list.AbstractList_C;
export declare type AbstractListContainerColumn = $.kd.bos.list.AbstractListContainerColumn;
export declare const AbstractListContainerColumn: $.kd.bos.list.AbstractListContainerColumn_C;
export declare type AbstractTreeListView = $.kd.bos.list.AbstractTreeListView;
export declare const AbstractTreeListView: $.kd.bos.list.AbstractTreeListView_C;
export declare type BillList = $.kd.bos.list.BillList;
export declare const BillList: $.kd.bos.list.BillList_C;
export declare type CardListColumn = $.kd.bos.list.CardListColumn;
export declare const CardListColumn: $.kd.bos.list.CardListColumn_C;
export declare type CheckBoxListColumn = $.kd.bos.list.CheckBoxListColumn;
export declare const CheckBoxListColumn: $.kd.bos.list.CheckBoxListColumn_C;
export declare type CityList = $.kd.bos.list.CityList;
export declare const CityList: $.kd.bos.list.CityList_C;
export declare type ComboListColumn = $.kd.bos.list.ComboListColumn;
export declare const ComboListColumn: $.kd.bos.list.ComboListColumn_C;
export declare type DateListColumn = $.kd.bos.list.DateListColumn;
export declare const DateListColumn: $.kd.bos.list.DateListColumn_C;
export declare type DecimalListColumn = $.kd.bos.list.DecimalListColumn;
export declare const DecimalListColumn: $.kd.bos.list.DecimalListColumn_C;
export declare type DynamicTextListColumn = $.kd.bos.list.DynamicTextListColumn;
export declare const DynamicTextListColumn: $.kd.bos.list.DynamicTextListColumn_C;
export declare type F7SelectedList = $.kd.bos.list.F7SelectedList;
export declare const F7SelectedList: $.kd.bos.list.F7SelectedList_C;
export declare type ListCardView = $.kd.bos.list.ListCardView;
export declare const ListCardView: $.kd.bos.list.ListCardView_C;
export declare type ListColumn = $.kd.bos.list.ListColumn;
export declare const ListColumn: $.kd.bos.list.ListColumn_C;
export declare type ListColumnGroup = $.kd.bos.list.ListColumnGroup;
export declare const ListColumnGroup: $.kd.bos.list.ListColumnGroup_C;
export declare type ListGridView = $.kd.bos.list.ListGridView;
export declare const ListGridView: $.kd.bos.list.ListGridView_C;
export declare type ListOperationColumn = $.kd.bos.list.ListOperationColumn;
export declare const ListOperationColumn: $.kd.bos.list.ListOperationColumn_C;
export declare type MergeListColumn = $.kd.bos.list.MergeListColumn;
export declare const MergeListColumn: $.kd.bos.list.MergeListColumn_C;
export declare type MobControlContext = $.kd.bos.list.MobControlContext;
export declare const MobControlContext: $.kd.bos.list.MobControlContext_C;
export declare type MobF7SelectedList = $.kd.bos.list.MobF7SelectedList;
export declare const MobF7SelectedList: $.kd.bos.list.MobF7SelectedList_C;
export declare type MobileSearch = $.kd.bos.list.MobileSearch;
export declare const MobileSearch: $.kd.bos.list.MobileSearch_C;
export declare type MobileTreeList = $.kd.bos.list.MobileTreeList;
export declare const MobileTreeList: $.kd.bos.list.MobileTreeList_C;
export declare type OrgList = $.kd.bos.list.OrgList;
export declare const OrgList: $.kd.bos.list.OrgList_C;
export declare type TemplateTextListColumn = $.kd.bos.list.TemplateTextListColumn;
export declare const TemplateTextListColumn: $.kd.bos.list.TemplateTextListColumn_C;
export declare type TimeListColumn = $.kd.bos.list.TimeListColumn;
export declare const TimeListColumn: $.kd.bos.list.TimeListColumn_C;
export declare type UserList = $.kd.bos.list.UserList;
export declare const UserList: $.kd.bos.list.UserList_C;
export declare type ViewCommonUtil = $.kd.bos.list.ViewCommonUtil;
export declare const ViewCommonUtil: $.kd.bos.list.ViewCommonUtil_C;
export declare type VoucherNoListColumn = $.kd.bos.list.VoucherNoListColumn;
export declare const VoucherNoListColumn: $.kd.bos.list.VoucherNoListColumn_C;
export declare type AbstractListColumn = $.kd.bos.list.AbstractListColumn;
export declare const AbstractListColumn: $.kd.bos.list.AbstractListColumn_C;
export declare type CtsyListShowParameter = $.kd.bos.list.CtsyListShowParameter;
export declare const CtsyListShowParameter: $.kd.bos.list.CtsyListShowParameter_C;
export declare type IListColumn = $.kd.bos.list.IListColumn;
export declare const IListColumn: $.kd.bos.list.IListColumn;
export declare type IListView = $.kd.bos.list.IListView;
export declare const IListView: $.kd.bos.list.IListView;
export declare type IMobileListView = $.kd.bos.list.IMobileListView;
export declare const IMobileListView: $.kd.bos.list.IMobileListView;
export declare type ITreeListView = $.kd.bos.list.ITreeListView;
export declare const ITreeListView: $.kd.bos.list.ITreeListView;
export declare type LinkQueryPkIdCollection = $.kd.bos.list.LinkQueryPkIdCollection;
export declare const LinkQueryPkIdCollection: $.kd.bos.list.LinkQueryPkIdCollection_C;
export declare type ListColumnCompareType = $.kd.bos.list.ListColumnCompareType;
export declare const ListColumnCompareType: $.kd.bos.list.ListColumnCompareType_C;
export declare type ListColumnType = $.kd.bos.list.ListColumnType;
export declare const ListColumnType: typeof $.kd.bos.list.ListColumnType;
export declare type ListFieldMeta = $.kd.bos.list.ListFieldMeta;
export declare const ListFieldMeta: $.kd.bos.list.ListFieldMeta_C;
export declare type ListFilterParameter = $.kd.bos.list.ListFilterParameter;
export declare const ListFilterParameter: $.kd.bos.list.ListFilterParameter_C;
export declare type ListShowParameter = $.kd.bos.list.ListShowParameter;
export declare const ListShowParameter: $.kd.bos.list.ListShowParameter_C;
export declare type MobileListShowParameter = $.kd.bos.list.MobileListShowParameter;
export declare const MobileListShowParameter: $.kd.bos.list.MobileListShowParameter_C;
export declare type PageMode = $.kd.bos.list.PageMode;
export declare const PageMode: typeof $.kd.bos.list.PageMode;
export declare type SeqColumnType = $.kd.bos.list.SeqColumnType;
export declare const SeqColumnType: typeof $.kd.bos.list.SeqColumnType;
