export declare type MQFactory = $.kd.bos.mq.MQFactory;
export declare const MQFactory: $.kd.bos.mq.MQFactory_C;
export declare type MessageAcker = $.kd.bos.mq.MessageAcker;
export declare const MessageAcker: $.kd.bos.mq.MessageAcker;
export declare type MessageConsumer = $.kd.bos.mq.MessageConsumer;
export declare const MessageConsumer: $.kd.bos.mq.MessageConsumer;
export declare type MessagePublisher = $.kd.bos.mq.MessagePublisher;
export declare const MessagePublisher: $.kd.bos.mq.MessagePublisher;
export declare type MessageServiceModule = $.kd.bos.mq.MessageServiceModule;
export declare const MessageServiceModule: $.kd.bos.mq.MessageServiceModule_C;
