export declare type CtBillTrackerServiceHelper = $.kd.bos.servicehelper.CtBillTrackerServiceHelper;
export declare const CtBillTrackerServiceHelper: $.kd.bos.servicehelper.CtBillTrackerServiceHelper_C;
export declare type CtConvertMetaServiceHelper = $.kd.bos.servicehelper.CtConvertMetaServiceHelper;
export declare const CtConvertMetaServiceHelper: $.kd.bos.servicehelper.CtConvertMetaServiceHelper_C;
export declare type CtConvertServiceHelper = $.kd.bos.servicehelper.CtConvertServiceHelper;
export declare const CtConvertServiceHelper: $.kd.bos.servicehelper.CtConvertServiceHelper_C;
export declare type CtSaveServiceHelper = $.kd.bos.servicehelper.CtSaveServiceHelper;
export declare const CtSaveServiceHelper: $.kd.bos.servicehelper.CtSaveServiceHelper_C;
export declare type CtSyncLogServiceHelper = $.kd.bos.servicehelper.CtSyncLogServiceHelper;
export declare const CtSyncLogServiceHelper: $.kd.bos.servicehelper.CtSyncLogServiceHelper_C;
export declare type CtSyncServiceHelper = $.kd.bos.servicehelper.CtSyncServiceHelper;
export declare const CtSyncServiceHelper: $.kd.bos.servicehelper.CtSyncServiceHelper_C;
export declare type CoreBusinessDataServiceHelper = $.kd.bos.servicehelper.CoreBusinessDataServiceHelper;
export declare const CoreBusinessDataServiceHelper: $.kd.bos.servicehelper.CoreBusinessDataServiceHelper_C;
export declare type PrintServiceHelper = $.kd.bos.servicehelper.PrintServiceHelper;
export declare const PrintServiceHelper: $.kd.bos.servicehelper.PrintServiceHelper_C;
export declare type AttDto = $.kd.bos.servicehelper.AttDto;
export declare const AttDto: $.kd.bos.servicehelper.AttDto_C;
export declare type BillTypeDifferentialHelper = $.kd.bos.servicehelper.BillTypeDifferentialHelper;
export declare const BillTypeDifferentialHelper: $.kd.bos.servicehelper.BillTypeDifferentialHelper_C;
export declare type BusinessDataServiceHelper = $.kd.bos.servicehelper.BusinessDataServiceHelper;
export declare const BusinessDataServiceHelper: $.kd.bos.servicehelper.BusinessDataServiceHelper_C;
export declare type ConfigServiceHelper = $.kd.bos.servicehelper.ConfigServiceHelper;
export declare const ConfigServiceHelper: $.kd.bos.servicehelper.ConfigServiceHelper_C;
export declare type DBServiceHelper = $.kd.bos.servicehelper.DBServiceHelper;
export declare const DBServiceHelper: $.kd.bos.servicehelper.DBServiceHelper_C;
export declare type DispatchServiceHelper = $.kd.bos.servicehelper.DispatchServiceHelper;
export declare const DispatchServiceHelper: $.kd.bos.servicehelper.DispatchServiceHelper_C;
export declare type ISVServiceHelper = $.kd.bos.servicehelper.ISVServiceHelper;
export declare const ISVServiceHelper: $.kd.bos.servicehelper.ISVServiceHelper_C;
export declare type MetadataServiceHelper = $.kd.bos.servicehelper.MetadataServiceHelper;
export declare const MetadataServiceHelper: $.kd.bos.servicehelper.MetadataServiceHelper_C;
export declare type OpBizRuleSetServiceHelper = $.kd.bos.servicehelper.OpBizRuleSetServiceHelper;
export declare const OpBizRuleSetServiceHelper: $.kd.bos.servicehelper.OpBizRuleSetServiceHelper_C;
export declare type QueryServiceHelper = $.kd.bos.servicehelper.QueryServiceHelper;
export declare const QueryServiceHelper: $.kd.bos.servicehelper.QueryServiceHelper_C;
export declare type ServiceHelperModule = $.kd.bos.servicehelper.ServiceHelperModule;
export declare const ServiceHelperModule: $.kd.bos.servicehelper.ServiceHelperModule_C;
export declare type TimeServiceHelper = $.kd.bos.servicehelper.TimeServiceHelper;
export declare const TimeServiceHelper: $.kd.bos.servicehelper.TimeServiceHelper_C;
export declare type UnitConvertHelper = $.kd.bos.servicehelper.UnitConvertHelper;
export declare const UnitConvertHelper: $.kd.bos.servicehelper.UnitConvertHelper_C;
export declare type AttachmentDto = $.kd.bos.servicehelper.AttachmentDto;
export declare const AttachmentDto: $.kd.bos.servicehelper.AttachmentDto_C;
export declare type AttachmentModule = $.kd.bos.servicehelper.AttachmentModule;
export declare const AttachmentModule: $.kd.bos.servicehelper.AttachmentModule_C;
export declare type AttachmentServiceHelper = $.kd.bos.servicehelper.AttachmentServiceHelper;
export declare const AttachmentServiceHelper: $.kd.bos.servicehelper.AttachmentServiceHelper_C;
