export declare type ApprovalConstants = $.kd.sdk.hr.hspm.common.constants.ApprovalConstants;
export declare const ApprovalConstants: $.kd.sdk.hr.hspm.common.constants.ApprovalConstants;
export declare type AttachConstants = $.kd.sdk.hr.hspm.common.constants.AttachConstants;
export declare const AttachConstants: $.kd.sdk.hr.hspm.common.constants.AttachConstants;
export declare type DynConfigConstants = $.kd.sdk.hr.hspm.common.constants.DynConfigConstants;
export declare const DynConfigConstants: $.kd.sdk.hr.hspm.common.constants.DynConfigConstants;
export declare type HSPMFieldConstants = $.kd.sdk.hr.hspm.common.constants.HSPMFieldConstants;
export declare const HSPMFieldConstants: $.kd.sdk.hr.hspm.common.constants.HSPMFieldConstants;
export declare type HspmCommonConstants = $.kd.sdk.hr.hspm.common.constants.HspmCommonConstants;
export declare const HspmCommonConstants: $.kd.sdk.hr.hspm.common.constants.HspmCommonConstants;
export declare type ImportTypeConstant = $.kd.sdk.hr.hspm.common.constants.ImportTypeConstant;
export declare const ImportTypeConstant: $.kd.sdk.hr.hspm.common.constants.ImportTypeConstant;
export declare type InfoClassifyCommonConstant = $.kd.sdk.hr.hspm.common.constants.InfoClassifyCommonConstant;
export declare const InfoClassifyCommonConstant: $.kd.sdk.hr.hspm.common.constants.InfoClassifyCommonConstant;
export declare type MobileDrawConstants = $.kd.sdk.hr.hspm.common.constants.MobileDrawConstants;
export declare const MobileDrawConstants: $.kd.sdk.hr.hspm.common.constants.MobileDrawConstants;
export declare type MultiViewConfigConstants = $.kd.sdk.hr.hspm.common.constants.MultiViewConfigConstants;
export declare const MultiViewConfigConstants: $.kd.sdk.hr.hspm.common.constants.MultiViewConfigConstants;
export declare type MyErManFileConstants = $.kd.sdk.hr.hspm.common.constants.MyErManFileConstants;
export declare const MyErManFileConstants: $.kd.sdk.hr.hspm.common.constants.MyErManFileConstants;
export declare type ReportDisplayPageConstants = $.kd.sdk.hr.hspm.common.constants.ReportDisplayPageConstants;
export declare const ReportDisplayPageConstants: $.kd.sdk.hr.hspm.common.constants.ReportDisplayPageConstants;
export declare type ScheduleDrawConstants = $.kd.sdk.hr.hspm.common.constants.ScheduleDrawConstants;
export declare const ScheduleDrawConstants: $.kd.sdk.hr.hspm.common.constants.ScheduleDrawConstants;
