export declare type ApprovalEntityUtils = $.kd.sdk.hr.hspm.common.utils.ApprovalEntityUtils;
export declare const ApprovalEntityUtils: $.kd.sdk.hr.hspm.common.utils.ApprovalEntityUtils_C;
export declare type BusinessUtils = $.kd.sdk.hr.hspm.common.utils.BusinessUtils;
export declare const BusinessUtils: $.kd.sdk.hr.hspm.common.utils.BusinessUtils_C;
export declare type ComboItemUtil = $.kd.sdk.hr.hspm.common.utils.ComboItemUtil;
export declare const ComboItemUtil: $.kd.sdk.hr.hspm.common.utils.ComboItemUtil_C;
export declare type CommonUtil = $.kd.sdk.hr.hspm.common.utils.CommonUtil;
export declare const CommonUtil: $.kd.sdk.hr.hspm.common.utils.CommonUtil_C;
export declare type DynamicPropUtil = $.kd.sdk.hr.hspm.common.utils.DynamicPropUtil;
export declare const DynamicPropUtil: $.kd.sdk.hr.hspm.common.utils.DynamicPropUtil_C;
export declare type DynamicPropValidateUtil = $.kd.sdk.hr.hspm.common.utils.DynamicPropValidateUtil;
export declare const DynamicPropValidateUtil: $.kd.sdk.hr.hspm.common.utils.DynamicPropValidateUtil_C;
export declare type DynamicTransformUtil = $.kd.sdk.hr.hspm.common.utils.DynamicTransformUtil;
export declare const DynamicTransformUtil: $.kd.sdk.hr.hspm.common.utils.DynamicTransformUtil_C;
export declare type HrpiServiceOperateParam = $.kd.sdk.hr.hspm.common.utils.HrpiServiceOperateParam;
export declare const HrpiServiceOperateParam: $.kd.sdk.hr.hspm.common.utils.HrpiServiceOperateParam_C;
export declare type HspmDateUtils = $.kd.sdk.hr.hspm.common.utils.HspmDateUtils;
export declare const HspmDateUtils: $.kd.sdk.hr.hspm.common.utils.HspmDateUtils_C;
export declare type IDCardUtils = $.kd.sdk.hr.hspm.common.utils.IDCardUtils;
export declare const IDCardUtils: $.kd.sdk.hr.hspm.common.utils.IDCardUtils_C;
export declare type InfoClassifyOpenWindowUtil = $.kd.sdk.hr.hspm.common.utils.InfoClassifyOpenWindowUtil;
export declare const InfoClassifyOpenWindowUtil: $.kd.sdk.hr.hspm.common.utils.InfoClassifyOpenWindowUtil_C;
export declare type InfoClassifyPercreFieldUtil = $.kd.sdk.hr.hspm.common.utils.InfoClassifyPercreFieldUtil;
export declare const InfoClassifyPercreFieldUtil: $.kd.sdk.hr.hspm.common.utils.InfoClassifyPercreFieldUtil_C;
export declare type InfoGroupApprovalUtil = $.kd.sdk.hr.hspm.common.utils.InfoGroupApprovalUtil;
export declare const InfoGroupApprovalUtil: $.kd.sdk.hr.hspm.common.utils.InfoGroupApprovalUtil_C;
export declare type PageCacheUtils = $.kd.sdk.hr.hspm.common.utils.PageCacheUtils;
export declare const PageCacheUtils: $.kd.sdk.hr.hspm.common.utils.PageCacheUtils_C;
export declare type ParamAnalysisUtil = $.kd.sdk.hr.hspm.common.utils.ParamAnalysisUtil;
export declare const ParamAnalysisUtil: $.kd.sdk.hr.hspm.common.utils.ParamAnalysisUtil_C;
export declare type PermUtil = $.kd.sdk.hr.hspm.common.utils.PermUtil;
export declare const PermUtil: $.kd.sdk.hr.hspm.common.utils.PermUtil_C;
export declare type PersonModelUtil = $.kd.sdk.hr.hspm.common.utils.PersonModelUtil;
export declare const PersonModelUtil: $.kd.sdk.hr.hspm.common.utils.PersonModelUtil_C;
export declare type PropertyHelper = $.kd.sdk.hr.hspm.common.utils.PropertyHelper;
export declare const PropertyHelper: $.kd.sdk.hr.hspm.common.utils.PropertyHelper_C;
