export declare type AfterCreatVo = $.kd.sdk.hr.hspm.common.vo.AfterCreatVo;
export declare const AfterCreatVo: $.kd.sdk.hr.hspm.common.vo.AfterCreatVo_C;
export declare type BeforeCreatVo = $.kd.sdk.hr.hspm.common.vo.BeforeCreatVo;
export declare const BeforeCreatVo: $.kd.sdk.hr.hspm.common.vo.BeforeCreatVo_C;
export declare type CardViewCompareVo = $.kd.sdk.hr.hspm.common.vo.CardViewCompareVo;
export declare const CardViewCompareVo: $.kd.sdk.hr.hspm.common.vo.CardViewCompareVo_C;
export declare type CardViewVo = $.kd.sdk.hr.hspm.common.vo.CardViewVo;
export declare const CardViewVo: $.kd.sdk.hr.hspm.common.vo.CardViewVo_C;
export declare type ContentApVo = $.kd.sdk.hr.hspm.common.vo.ContentApVo;
export declare const ContentApVo: $.kd.sdk.hr.hspm.common.vo.ContentApVo_C;
export declare type DefineSpecialVo = $.kd.sdk.hr.hspm.common.vo.DefineSpecialVo;
export declare const DefineSpecialVo: $.kd.sdk.hr.hspm.common.vo.DefineSpecialVo_C;
export declare type FieldTransVo = $.kd.sdk.hr.hspm.common.vo.FieldTransVo;
export declare const FieldTransVo: $.kd.sdk.hr.hspm.common.vo.FieldTransVo_C;
export declare type PreBindDataVo = $.kd.sdk.hr.hspm.common.vo.PreBindDataVo;
export declare const PreBindDataVo: $.kd.sdk.hr.hspm.common.vo.PreBindDataVo_C;
export declare type QueryDbVo = $.kd.sdk.hr.hspm.common.vo.QueryDbVo;
export declare const QueryDbVo: $.kd.sdk.hr.hspm.common.vo.QueryDbVo_C;
export declare type TextColorVo = $.kd.sdk.hr.hspm.common.vo.TextColorVo;
export declare const TextColorVo: $.kd.sdk.hr.hspm.common.vo.TextColorVo_C;
export declare type TimeApVo = $.kd.sdk.hr.hspm.common.vo.TimeApVo;
export declare const TimeApVo: $.kd.sdk.hr.hspm.common.vo.TimeApVo_C;
