export declare type AbstractCtConvertServiceArgs = $.kd.bos.entity.ctbotp.runtime.AbstractCtConvertServiceArgs;
export declare const AbstractCtConvertServiceArgs: $.kd.bos.entity.ctbotp.runtime.AbstractCtConvertServiceArgs_C;
export declare type CtBFEntryTable = $.kd.bos.entity.ctbotp.runtime.CtBFEntryTable;
export declare const CtBFEntryTable: $.kd.bos.entity.ctbotp.runtime.CtBFEntryTable_C;
export declare type CtBFRow = $.kd.bos.entity.ctbotp.runtime.CtBFRow;
export declare const CtBFRow: $.kd.bos.entity.ctbotp.runtime.CtBFRow_C;
export declare type CtBFRowId = $.kd.bos.entity.ctbotp.runtime.CtBFRowId;
export declare const CtBFRowId: $.kd.bos.entity.ctbotp.runtime.CtBFRowId_C;
export declare type CtBFRowLinkDownNode = $.kd.bos.entity.ctbotp.runtime.CtBFRowLinkDownNode;
export declare const CtBFRowLinkDownNode: $.kd.bos.entity.ctbotp.runtime.CtBFRowLinkDownNode_C;
export declare type CtBFRowLinkUpNode = $.kd.bos.entity.ctbotp.runtime.CtBFRowLinkUpNode;
export declare const CtBFRowLinkUpNode: $.kd.bos.entity.ctbotp.runtime.CtBFRowLinkUpNode_C;
export declare type CtBFTable = $.kd.bos.entity.ctbotp.runtime.CtBFTable;
export declare const CtBFTable: $.kd.bos.entity.ctbotp.runtime.CtBFTable_C;
export declare type CtBillEntryInfo = $.kd.bos.entity.ctbotp.runtime.CtBillEntryInfo;
export declare const CtBillEntryInfo: $.kd.bos.entity.ctbotp.runtime.CtBillEntryInfo_C;
export declare type CtCRBizRuleElement = $.kd.bos.entity.ctbotp.runtime.CtCRBizRuleElement;
export declare const CtCRBizRuleElement: $.kd.bos.entity.ctbotp.runtime.CtCRBizRuleElement_C;
export declare type CtConvertConst = $.kd.bos.entity.ctbotp.runtime.CtConvertConst;
export declare const CtConvertConst: $.kd.bos.entity.ctbotp.runtime.CtConvertConst_C;
export declare type CtConvertOpRule = $.kd.bos.entity.ctbotp.runtime.CtConvertOpRule;
export declare const CtConvertOpRule: $.kd.bos.entity.ctbotp.runtime.CtConvertOpRule_C;
export declare type CtConvertOperationResult = $.kd.bos.entity.ctbotp.runtime.CtConvertOperationResult;
export declare const CtConvertOperationResult: $.kd.bos.entity.ctbotp.runtime.CtConvertOperationResult_C;
export declare type CtDrawArgs = $.kd.bos.entity.ctbotp.runtime.CtDrawArgs;
export declare const CtDrawArgs: $.kd.bos.entity.ctbotp.runtime.CtDrawArgs_C;
export declare type CtGetTargetOptionalOrgsArgs = $.kd.bos.entity.ctbotp.runtime.CtGetTargetOptionalOrgsArgs;
export declare const CtGetTargetOptionalOrgsArgs: $.kd.bos.entity.ctbotp.runtime.CtGetTargetOptionalOrgsArgs_C;
export declare type CtGetTargetOptionalOrgsResult = $.kd.bos.entity.ctbotp.runtime.CtGetTargetOptionalOrgsResult;
export declare const CtGetTargetOptionalOrgsResult: $.kd.bos.entity.ctbotp.runtime.CtGetTargetOptionalOrgsResult_C;
export declare type CtPushArgs = $.kd.bos.entity.ctbotp.runtime.CtPushArgs;
export declare const CtPushArgs: $.kd.bos.entity.ctbotp.runtime.CtPushArgs_C;
export declare type CtSaveArgs = $.kd.bos.entity.ctbotp.runtime.CtSaveArgs;
export declare const CtSaveArgs: $.kd.bos.entity.ctbotp.runtime.CtSaveArgs_C;
export declare type CtSaveOperationResult = $.kd.bos.entity.ctbotp.runtime.CtSaveOperationResult;
export declare const CtSaveOperationResult: $.kd.bos.entity.ctbotp.runtime.CtSaveOperationResult_C;
export declare type CtSourceBillReport = $.kd.bos.entity.ctbotp.runtime.CtSourceBillReport;
export declare const CtSourceBillReport: $.kd.bos.entity.ctbotp.runtime.CtSourceBillReport_C;
export declare type CtSourceRowReport = $.kd.bos.entity.ctbotp.runtime.CtSourceRowReport;
export declare const CtSourceRowReport: $.kd.bos.entity.ctbotp.runtime.CtSourceRowReport_C;
export declare type CtSyncArgs = $.kd.bos.entity.ctbotp.runtime.CtSyncArgs;
export declare const CtSyncArgs: $.kd.bos.entity.ctbotp.runtime.CtSyncArgs_C;
export declare type CtSyncResult = $.kd.bos.entity.ctbotp.runtime.CtSyncResult;
export declare const CtSyncResult: $.kd.bos.entity.ctbotp.runtime.CtSyncResult_C;
export declare type CtTenantAccount = $.kd.bos.entity.ctbotp.runtime.CtTenantAccount;
export declare const CtTenantAccount: $.kd.bos.entity.ctbotp.runtime.CtTenantAccount_C;
export declare type CtTenantTable = $.kd.bos.entity.ctbotp.runtime.CtTenantTable;
export declare const CtTenantTable: $.kd.bos.entity.ctbotp.runtime.CtTenantTable_C;
export declare type CtWriteBackBizRule = $.kd.bos.entity.ctbotp.runtime.CtWriteBackBizRule;
export declare const CtWriteBackBizRule: $.kd.bos.entity.ctbotp.runtime.CtWriteBackBizRule_C;
export declare type CtWriteBackFormula = $.kd.bos.entity.ctbotp.runtime.CtWriteBackFormula;
export declare const CtWriteBackFormula: $.kd.bos.entity.ctbotp.runtime.CtWriteBackFormula_C;
export declare type CtWriteBackOpType = $.kd.bos.entity.ctbotp.runtime.CtWriteBackOpType;
export declare const CtWriteBackOpType: typeof $.kd.bos.entity.ctbotp.runtime.CtWriteBackOpType;
export declare type CtWriteBackRuleElement = $.kd.bos.entity.ctbotp.runtime.CtWriteBackRuleElement;
export declare const CtWriteBackRuleElement: $.kd.bos.entity.ctbotp.runtime.CtWriteBackRuleElement_C;
export declare type CtWriteBackType = $.kd.bos.entity.ctbotp.runtime.CtWriteBackType;
export declare const CtWriteBackType: typeof $.kd.bos.entity.ctbotp.runtime.CtWriteBackType;
