export declare type AttendPersonExt = $.kd.sdk.wtc.wtes.business.tie.model.attenperson.AttendPersonExt;
export declare const AttendPersonExt: $.kd.sdk.wtc.wtes.business.tie.model.attenperson.AttendPersonExt;
export declare type CmpEmpExt = $.kd.sdk.wtc.wtes.business.tie.model.attenperson.CmpEmpExt;
export declare const CmpEmpExt: $.kd.sdk.wtc.wtes.business.tie.model.attenperson.CmpEmpExt;
export declare type ContrWorkLocExt = $.kd.sdk.wtc.wtes.business.tie.model.attenperson.ContrWorkLocExt;
export declare const ContrWorkLocExt: $.kd.sdk.wtc.wtes.business.tie.model.attenperson.ContrWorkLocExt;
export declare type EmpEntRelExt = $.kd.sdk.wtc.wtes.business.tie.model.attenperson.EmpEntRelExt;
export declare const EmpEntRelExt: $.kd.sdk.wtc.wtes.business.tie.model.attenperson.EmpEntRelExt;
export declare type EmpJobRelExt = $.kd.sdk.wtc.wtes.business.tie.model.attenperson.EmpJobRelExt;
export declare const EmpJobRelExt: $.kd.sdk.wtc.wtes.business.tie.model.attenperson.EmpJobRelExt;
export declare type EmpPosOrgRelExt = $.kd.sdk.wtc.wtes.business.tie.model.attenperson.EmpPosOrgRelExt;
export declare const EmpPosOrgRelExt: $.kd.sdk.wtc.wtes.business.tie.model.attenperson.EmpPosOrgRelExt;
export declare type EmployeeExt = $.kd.sdk.wtc.wtes.business.tie.model.attenperson.EmployeeExt;
export declare const EmployeeExt: $.kd.sdk.wtc.wtes.business.tie.model.attenperson.EmployeeExt;
export declare type PerNonTsPropExt = $.kd.sdk.wtc.wtes.business.tie.model.attenperson.PerNonTsPropExt;
export declare const PerNonTsPropExt: $.kd.sdk.wtc.wtes.business.tie.model.attenperson.PerNonTsPropExt;
export declare type PersonExt = $.kd.sdk.wtc.wtes.business.tie.model.attenperson.PersonExt;
export declare const PersonExt: $.kd.sdk.wtc.wtes.business.tie.model.attenperson.PersonExt;
export declare type TrialPeriodExt = $.kd.sdk.wtc.wtes.business.tie.model.attenperson.TrialPeriodExt;
export declare const TrialPeriodExt: $.kd.sdk.wtc.wtes.business.tie.model.attenperson.TrialPeriodExt;
