export declare type IMobBotpResultHandlerPlugin = $.kd.sdk.mpscmm.msmob.expoint.IMobBotpResultHandlerPlugin;
export declare const IMobBotpResultHandlerPlugin: $.kd.sdk.mpscmm.msmob.expoint.IMobBotpResultHandlerPlugin;
export declare type IMobHomePageCustomDataPlugin = $.kd.sdk.mpscmm.msmob.expoint.IMobHomePageCustomDataPlugin;
export declare const IMobHomePageCustomDataPlugin: $.kd.sdk.mpscmm.msmob.expoint.IMobHomePageCustomDataPlugin;
export declare type IMobOpenApiUrlMapping = $.kd.sdk.mpscmm.msmob.expoint.IMobOpenApiUrlMapping;
export declare const IMobOpenApiUrlMapping: $.kd.sdk.mpscmm.msmob.expoint.IMobOpenApiUrlMapping;
export declare type IMobOperationDataTransferPlugin = $.kd.sdk.mpscmm.msmob.expoint.IMobOperationDataTransferPlugin;
export declare const IMobOperationDataTransferPlugin: $.kd.sdk.mpscmm.msmob.expoint.IMobOperationDataTransferPlugin;
export declare type MsmobExpandCaseCodes = $.kd.sdk.mpscmm.msmob.expoint.MsmobExpandCaseCodes;
export declare const MsmobExpandCaseCodes: $.kd.sdk.mpscmm.msmob.expoint.MsmobExpandCaseCodes_C;
