export declare type MatcherResult = $.kd.bos.print.matchtpl.MatcherResult;
export declare const MatcherResult: $.kd.bos.print.matchtpl.MatcherResult_C;
export declare type MatcherTpl = $.kd.bos.print.matchtpl.MatcherTpl;
export declare const MatcherTpl: $.kd.bos.print.matchtpl.MatcherTpl_C;
export declare type TplMatcherContext = $.kd.bos.print.matchtpl.TplMatcherContext;
export declare const TplMatcherContext: $.kd.bos.print.matchtpl.TplMatcherContext_C;
export declare type TplMatcherParam = $.kd.bos.print.matchtpl.TplMatcherParam;
export declare const TplMatcherParam: $.kd.bos.print.matchtpl.TplMatcherParam_C;
export declare type TplMatcherResult = $.kd.bos.print.matchtpl.TplMatcherResult;
export declare const TplMatcherResult: $.kd.bos.print.matchtpl.TplMatcherResult_C;
export declare type TplMatcherUtil = $.kd.bos.print.matchtpl.TplMatcherUtil;
export declare const TplMatcherUtil: $.kd.bos.print.matchtpl.TplMatcherUtil_C;
export declare type ViewType = $.kd.bos.print.matchtpl.ViewType;
export declare const ViewType: typeof $.kd.bos.print.matchtpl.ViewType;
