export declare type CloneUtils = $.kd.bos.dataentity.entity.CloneUtils;
export declare const CloneUtils: $.kd.bos.dataentity.entity.CloneUtils_C;
export declare type CollectionPropertyAttribute = $.kd.bos.dataentity.entity.CollectionPropertyAttribute;
export declare const CollectionPropertyAttribute: $.kd.bos.dataentity.entity.CollectionPropertyAttribute;
export declare type ComplexPropertyAttribute = $.kd.bos.dataentity.entity.ComplexPropertyAttribute;
export declare const ComplexPropertyAttribute: $.kd.bos.dataentity.entity.ComplexPropertyAttribute;
export declare type DataEntityBase = $.kd.bos.dataentity.entity.DataEntityBase;
export declare const DataEntityBase: $.kd.bos.dataentity.entity.DataEntityBase_C;
export declare type DataEntityCollection = $.kd.bos.dataentity.entity.DataEntityCollection;
export declare const DataEntityCollection: $.kd.bos.dataentity.entity.DataEntityCollection_C;
export declare type DataEntityState = $.kd.bos.dataentity.entity.DataEntityState;
export declare const DataEntityState: $.kd.bos.dataentity.entity.DataEntityState_C;
export declare type DataEntityTypeAttribute = $.kd.bos.dataentity.entity.DataEntityTypeAttribute;
export declare const DataEntityTypeAttribute: $.kd.bos.dataentity.entity.DataEntityTypeAttribute;
export declare type DbIgnoreAttribute = $.kd.bos.dataentity.entity.DbIgnoreAttribute;
export declare const DbIgnoreAttribute: $.kd.bos.dataentity.entity.DbIgnoreAttribute;
export declare type DefaultValueAttribute = $.kd.bos.dataentity.entity.DefaultValueAttribute;
export declare const DefaultValueAttribute: $.kd.bos.dataentity.entity.DefaultValueAttribute;
export declare type DynamicObject = $.kd.bos.dataentity.entity.DynamicObject;
export declare const DynamicObject: $.kd.bos.dataentity.entity.DynamicObject_C;
export declare type DynamicObjectCollection = $.kd.bos.dataentity.entity.DynamicObjectCollection;
export declare const DynamicObjectCollection: $.kd.bos.dataentity.entity.DynamicObjectCollection_C;
export declare type EntryInfo = $.kd.bos.dataentity.entity.EntryInfo;
export declare const EntryInfo: $.kd.bos.dataentity.entity.EntryInfo_C;
export declare type IBillEntityType = $.kd.bos.dataentity.entity.IBillEntityType;
export declare const IBillEntityType: $.kd.bos.dataentity.entity.IBillEntityType;
export declare type IDataEntityBase = $.kd.bos.dataentity.entity.IDataEntityBase;
export declare const IDataEntityBase: $.kd.bos.dataentity.entity.IDataEntityBase;
export declare type IDataStorage = $.kd.bos.dataentity.entity.IDataStorage;
export declare const IDataStorage: $.kd.bos.dataentity.entity.IDataStorage;
export declare type ILocaleString = $.kd.bos.dataentity.entity.ILocaleString;
export declare const ILocaleString: $.kd.bos.dataentity.entity.ILocaleString;
export declare type ILocaleValue = $.kd.bos.dataentity.entity.ILocaleValue;
export declare const ILocaleValue: $.kd.bos.dataentity.entity.ILocaleValue;
export declare type IObjectWithParent = $.kd.bos.dataentity.entity.IObjectWithParent;
export declare const IObjectWithParent: $.kd.bos.dataentity.entity.IObjectWithParent;
export declare type ISupportInitialize = $.kd.bos.dataentity.entity.ISupportInitialize;
export declare const ISupportInitialize: $.kd.bos.dataentity.entity.ISupportInitialize;
export declare type LocaleDynamicObjectCollection = $.kd.bos.dataentity.entity.LocaleDynamicObjectCollection;
export declare const LocaleDynamicObjectCollection: $.kd.bos.dataentity.entity.LocaleDynamicObjectCollection_C;
export declare type LocaleString = $.kd.bos.dataentity.entity.LocaleString;
export declare const LocaleString: $.kd.bos.dataentity.entity.LocaleString_C;
export declare type LocaleValue = $.kd.bos.dataentity.entity.LocaleValue;
export declare const LocaleValue: $.kd.bos.dataentity.entity.LocaleValue_C;
export declare type LocaleValueItem = $.kd.bos.dataentity.entity.LocaleValueItem;
export declare const LocaleValueItem: $.kd.bos.dataentity.entity.LocaleValueItem_C;
export declare type MulBasedataDynamicObjectCollection = $.kd.bos.dataentity.entity.MulBasedataDynamicObjectCollection;
export declare const MulBasedataDynamicObjectCollection: $.kd.bos.dataentity.entity.MulBasedataDynamicObjectCollection_C;
export declare type ObjectConverter = $.kd.bos.dataentity.entity.ObjectConverter;
export declare const ObjectConverter: $.kd.bos.dataentity.entity.ObjectConverter_C;
export declare type OrmLocaleValue = $.kd.bos.dataentity.entity.OrmLocaleValue;
export declare const OrmLocaleValue: $.kd.bos.dataentity.entity.OrmLocaleValue_C;
export declare type PkSnapshot = $.kd.bos.dataentity.entity.PkSnapshot;
export declare const PkSnapshot: $.kd.bos.dataentity.entity.PkSnapshot_C;
export declare type PkSnapshotSet = $.kd.bos.dataentity.entity.PkSnapshotSet;
export declare const PkSnapshotSet: $.kd.bos.dataentity.entity.PkSnapshotSet_C;
export declare type SimplePropertyAttribute = $.kd.bos.dataentity.entity.SimplePropertyAttribute;
export declare const SimplePropertyAttribute: $.kd.bos.dataentity.entity.SimplePropertyAttribute;
