export declare type DataEntityCacheType = $.kd.bos.dataentity.metadata.DataEntityCacheType;
export declare const DataEntityCacheType: typeof $.kd.bos.dataentity.metadata.DataEntityCacheType;
export declare type DataEntityTypeFlag = $.kd.bos.dataentity.metadata.DataEntityTypeFlag;
export declare const DataEntityTypeFlag: typeof $.kd.bos.dataentity.metadata.DataEntityTypeFlag;
export declare type IBillNoProperty = $.kd.bos.dataentity.metadata.IBillNoProperty;
export declare const IBillNoProperty: $.kd.bos.dataentity.metadata.IBillNoProperty;
export declare type ICollectionProperty = $.kd.bos.dataentity.metadata.ICollectionProperty;
export declare const ICollectionProperty: $.kd.bos.dataentity.metadata.ICollectionProperty;
export declare type IColumnValuePair = $.kd.bos.dataentity.metadata.IColumnValuePair;
export declare const IColumnValuePair: $.kd.bos.dataentity.metadata.IColumnValuePair;
export declare type IComplexProperty = $.kd.bos.dataentity.metadata.IComplexProperty;
export declare const IComplexProperty: $.kd.bos.dataentity.metadata.IComplexProperty;
export declare type ICreateTimeProperty = $.kd.bos.dataentity.metadata.ICreateTimeProperty;
export declare const ICreateTimeProperty: $.kd.bos.dataentity.metadata.ICreateTimeProperty;
export declare type ICreatedByProperty = $.kd.bos.dataentity.metadata.ICreatedByProperty;
export declare const ICreatedByProperty: $.kd.bos.dataentity.metadata.ICreatedByProperty;
export declare type IDataEntityProperty = $.kd.bos.dataentity.metadata.IDataEntityProperty;
export declare const IDataEntityProperty: $.kd.bos.dataentity.metadata.IDataEntityProperty;
export declare type IDataEntityPropertyCollection = $.kd.bos.dataentity.metadata.IDataEntityPropertyCollection;
export declare const IDataEntityPropertyCollection: $.kd.bos.dataentity.metadata.IDataEntityPropertyCollection;
export declare type IDataEntityType = $.kd.bos.dataentity.metadata.IDataEntityType;
export declare const IDataEntityType: $.kd.bos.dataentity.metadata.IDataEntityType;
export declare type IDataEntityTypeCollection = $.kd.bos.dataentity.metadata.IDataEntityTypeCollection;
export declare const IDataEntityTypeCollection: $.kd.bos.dataentity.metadata.IDataEntityTypeCollection;
export declare type IDeleteMetaRow = $.kd.bos.dataentity.metadata.IDeleteMetaRow;
export declare const IDeleteMetaRow: $.kd.bos.dataentity.metadata.IDeleteMetaRow;
export declare type IDirtyProperty = $.kd.bos.dataentity.metadata.IDirtyProperty;
export declare const IDirtyProperty: $.kd.bos.dataentity.metadata.IDirtyProperty;
export declare type IEntryType = $.kd.bos.dataentity.metadata.IEntryType;
export declare const IEntryType: $.kd.bos.dataentity.metadata.IEntryType;
export declare type IGeoPointProperty = $.kd.bos.dataentity.metadata.IGeoPointProperty;
export declare const IGeoPointProperty: $.kd.bos.dataentity.metadata.IGeoPointProperty;
export declare type IJoinProperty = $.kd.bos.dataentity.metadata.IJoinProperty;
export declare const IJoinProperty: $.kd.bos.dataentity.metadata.IJoinProperty;
export declare type ILocaleProperty = $.kd.bos.dataentity.metadata.ILocaleProperty;
export declare const ILocaleProperty: $.kd.bos.dataentity.metadata.ILocaleProperty;
export declare type ILongDataProperty = $.kd.bos.dataentity.metadata.ILongDataProperty;
export declare const ILongDataProperty: $.kd.bos.dataentity.metadata.ILongDataProperty;
export declare type IMetadata = $.kd.bos.dataentity.metadata.IMetadata;
export declare const IMetadata: $.kd.bos.dataentity.metadata.IMetadata;
export declare type IModifierProperty = $.kd.bos.dataentity.metadata.IModifierProperty;
export declare const IModifierProperty: $.kd.bos.dataentity.metadata.IModifierProperty;
export declare type IModifyTimeProperty = $.kd.bos.dataentity.metadata.IModifyTimeProperty;
export declare const IModifyTimeProperty: $.kd.bos.dataentity.metadata.IModifyTimeProperty;
export declare type ISaveDataSet = $.kd.bos.dataentity.metadata.ISaveDataSet;
export declare const ISaveDataSet: $.kd.bos.dataentity.metadata.ISaveDataSet;
export declare type ISaveDataTable = $.kd.bos.dataentity.metadata.ISaveDataTable;
export declare const ISaveDataTable: $.kd.bos.dataentity.metadata.ISaveDataTable;
export declare type ISaveMetaRow = $.kd.bos.dataentity.metadata.ISaveMetaRow;
export declare const ISaveMetaRow: $.kd.bos.dataentity.metadata.ISaveMetaRow;
export declare type ISimpleProperty = $.kd.bos.dataentity.metadata.ISimpleProperty;
export declare const ISimpleProperty: $.kd.bos.dataentity.metadata.ISimpleProperty;
export declare type RowOperateType = $.kd.bos.dataentity.metadata.RowOperateType;
export declare const RowOperateType: typeof $.kd.bos.dataentity.metadata.RowOperateType;
