export declare type DataEntityDeserializerOption = $.kd.bos.dataentity.serialization.DataEntityDeserializerOption;
export declare const DataEntityDeserializerOption: $.kd.bos.dataentity.serialization.DataEntityDeserializerOption_C;
export declare type DataEntitySerializer = $.kd.bos.dataentity.serialization.DataEntitySerializer;
export declare const DataEntitySerializer: $.kd.bos.dataentity.serialization.DataEntitySerializer_C;
export declare type DataEntitySerializerOption = $.kd.bos.dataentity.serialization.DataEntitySerializerOption;
export declare const DataEntitySerializerOption: $.kd.bos.dataentity.serialization.DataEntitySerializerOption_C;
export declare type DcBinder = $.kd.bos.dataentity.serialization.DcBinder;
export declare const DcBinder: $.kd.bos.dataentity.serialization.DcBinder_C;
export declare type DcJsonSerializer = $.kd.bos.dataentity.serialization.DcJsonSerializer;
export declare const DcJsonSerializer: $.kd.bos.dataentity.serialization.DcJsonSerializer_C;
export declare type DcSerializer = $.kd.bos.dataentity.serialization.DcSerializer;
export declare const DcSerializer: $.kd.bos.dataentity.serialization.DcSerializer_C;
export declare type DcxmlSerializer = $.kd.bos.dataentity.serialization.DcxmlSerializer;
export declare const DcxmlSerializer: $.kd.bos.dataentity.serialization.DcxmlSerializer_C;
export declare type DynamicObjectSerializationBinder = $.kd.bos.dataentity.serialization.DynamicObjectSerializationBinder;
export declare const DynamicObjectSerializationBinder: $.kd.bos.dataentity.serialization.DynamicObjectSerializationBinder_C;
export declare type IDataEntityBinder = $.kd.bos.dataentity.serialization.IDataEntityBinder;
export declare const IDataEntityBinder: $.kd.bos.dataentity.serialization.IDataEntityBinder;
export declare type ListDcxmlBinder = $.kd.bos.dataentity.serialization.ListDcxmlBinder;
export declare const ListDcxmlBinder: $.kd.bos.dataentity.serialization.ListDcxmlBinder_C;
export declare type SerializationUtils = $.kd.bos.dataentity.serialization.SerializationUtils;
export declare const SerializationUtils: $.kd.bos.dataentity.serialization.SerializationUtils_C;
