export declare type ArrayUtils = $.kd.bos.dataentity.utils.ArrayUtils;
export declare const ArrayUtils: $.kd.bos.dataentity.utils.ArrayUtils_C;
export declare type CharSequenceUtils = $.kd.bos.dataentity.utils.CharSequenceUtils;
export declare const CharSequenceUtils: $.kd.bos.dataentity.utils.CharSequenceUtils_C;
export declare type CharUtils = $.kd.bos.dataentity.utils.CharUtils;
export declare const CharUtils: $.kd.bos.dataentity.utils.CharUtils_C;
export declare type ObjectUtils = $.kd.bos.dataentity.utils.ObjectUtils;
export declare const ObjectUtils: $.kd.bos.dataentity.utils.ObjectUtils_C;
export declare type OrmUtils = $.kd.bos.dataentity.utils.OrmUtils;
export declare const OrmUtils: $.kd.bos.dataentity.utils.OrmUtils_C;
export declare type StringUtils = $.kd.bos.dataentity.utils.StringUtils;
export declare const StringUtils: $.kd.bos.dataentity.utils.StringUtils_C;
export declare type Uuid16 = $.kd.bos.dataentity.utils.Uuid16;
export declare const Uuid16: $.kd.bos.dataentity.utils.Uuid16_C;
export declare type Uuid8 = $.kd.bos.dataentity.utils.Uuid8;
export declare const Uuid8: $.kd.bos.dataentity.utils.Uuid8_C;
export declare type Validate = $.kd.bos.dataentity.utils.Validate;
export declare const Validate: $.kd.bos.dataentity.utils.Validate_C;
