export declare type BatchVersionChangeRespData = $.kd.hr.hbp.business.domain.model.newhismodel.BatchVersionChangeRespData;
export declare const BatchVersionChangeRespData: $.kd.hr.hbp.business.domain.model.newhismodel.BatchVersionChangeRespData_C;
export declare type HisBaseBo = $.kd.hr.hbp.business.domain.model.newhismodel.HisBaseBo;
export declare const HisBaseBo: $.kd.hr.hbp.business.domain.model.newhismodel.HisBaseBo_C;
export declare type HisImportBo = $.kd.hr.hbp.business.domain.model.newhismodel.HisImportBo;
export declare const HisImportBo: $.kd.hr.hbp.business.domain.model.newhismodel.HisImportBo_C;
export declare type HisInitReturnBo = $.kd.hr.hbp.business.domain.model.newhismodel.HisInitReturnBo;
export declare const HisInitReturnBo: $.kd.hr.hbp.business.domain.model.newhismodel.HisInitReturnBo_C;
export declare type HisResponse = $.kd.hr.hbp.business.domain.model.newhismodel.HisResponse;
export declare const HisResponse: $.kd.hr.hbp.business.domain.model.newhismodel.HisResponse_C;
export declare type HisTransRevocationBo = $.kd.hr.hbp.business.domain.model.newhismodel.HisTransRevocationBo;
export declare const HisTransRevocationBo: $.kd.hr.hbp.business.domain.model.newhismodel.HisTransRevocationBo_C;
export declare type HisTransRevocationListBo = $.kd.hr.hbp.business.domain.model.newhismodel.HisTransRevocationListBo;
export declare const HisTransRevocationListBo: $.kd.hr.hbp.business.domain.model.newhismodel.HisTransRevocationListBo_C;
export declare type HisVersionParamBo = $.kd.hr.hbp.business.domain.model.newhismodel.HisVersionParamBo;
export declare const HisVersionParamBo: $.kd.hr.hbp.business.domain.model.newhismodel.HisVersionParamBo_C;
export declare type HisVersionParamListBo = $.kd.hr.hbp.business.domain.model.newhismodel.HisVersionParamListBo;
export declare const HisVersionParamListBo: $.kd.hr.hbp.business.domain.model.newhismodel.HisVersionParamListBo_C;
export declare type HisVersionReviseParamBo = $.kd.hr.hbp.business.domain.model.newhismodel.HisVersionReviseParamBo;
export declare const HisVersionReviseParamBo: $.kd.hr.hbp.business.domain.model.newhismodel.HisVersionReviseParamBo_C;
export declare type HisVersionReviseReturnDataBo = $.kd.hr.hbp.business.domain.model.newhismodel.HisVersionReviseReturnDataBo;
export declare const HisVersionReviseReturnDataBo: $.kd.hr.hbp.business.domain.model.newhismodel.HisVersionReviseReturnDataBo_C;
export declare type ImportRespData = $.kd.hr.hbp.business.domain.model.newhismodel.ImportRespData;
export declare const ImportRespData: $.kd.hr.hbp.business.domain.model.newhismodel.ImportRespData_C;
export declare type VersionChangeRespData = $.kd.hr.hbp.business.domain.model.newhismodel.VersionChangeRespData;
export declare const VersionChangeRespData: $.kd.hr.hbp.business.domain.model.newhismodel.VersionChangeRespData_C;
