export declare type AbstractColumnDesc = $.kd.bos.entity.list.column.AbstractColumnDesc;
export declare const AbstractColumnDesc: $.kd.bos.entity.list.column.AbstractColumnDesc_C;
export declare type AdminDivisionColumnDesc = $.kd.bos.entity.list.column.AdminDivisionColumnDesc;
export declare const AdminDivisionColumnDesc: $.kd.bos.entity.list.column.AdminDivisionColumnDesc_C;
export declare type AmountColumnDesc = $.kd.bos.entity.list.column.AmountColumnDesc;
export declare const AmountColumnDesc: $.kd.bos.entity.list.column.AmountColumnDesc_C;
export declare type ApproverColumnDesc = $.kd.bos.entity.list.column.ApproverColumnDesc;
export declare const ApproverColumnDesc: $.kd.bos.entity.list.column.ApproverColumnDesc_C;
export declare type BaseDataColumnDesc = $.kd.bos.entity.list.column.BaseDataColumnDesc;
export declare const BaseDataColumnDesc: $.kd.bos.entity.list.column.BaseDataColumnDesc_C;
export declare type BaseDataRefColumnDesc = $.kd.bos.entity.list.column.BaseDataRefColumnDesc;
export declare const BaseDataRefColumnDesc: $.kd.bos.entity.list.column.BaseDataRefColumnDesc_C;
export declare type BigIntColumnDesc = $.kd.bos.entity.list.column.BigIntColumnDesc;
export declare const BigIntColumnDesc: $.kd.bos.entity.list.column.BigIntColumnDesc_C;
export declare type BooleanColumnDesc = $.kd.bos.entity.list.column.BooleanColumnDesc;
export declare const BooleanColumnDesc: $.kd.bos.entity.list.column.BooleanColumnDesc_C;
export declare type ColumnDesc = $.kd.bos.entity.list.column.ColumnDesc;
export declare const ColumnDesc: $.kd.bos.entity.list.column.ColumnDesc_C;
export declare type ComboColumnDesc = $.kd.bos.entity.list.column.ComboColumnDesc;
export declare const ComboColumnDesc: $.kd.bos.entity.list.column.ComboColumnDesc_C;
export declare type ControlColumnDesc = $.kd.bos.entity.list.column.ControlColumnDesc;
export declare const ControlColumnDesc: $.kd.bos.entity.list.column.ControlColumnDesc_C;
export declare type DateColumnDesc = $.kd.bos.entity.list.column.DateColumnDesc;
export declare const DateColumnDesc: $.kd.bos.entity.list.column.DateColumnDesc_C;
export declare type DateTimeColumnDesc = $.kd.bos.entity.list.column.DateTimeColumnDesc;
export declare const DateTimeColumnDesc: $.kd.bos.entity.list.column.DateTimeColumnDesc_C;
export declare type DecimalColumnDesc = $.kd.bos.entity.list.column.DecimalColumnDesc;
export declare const DecimalColumnDesc: $.kd.bos.entity.list.column.DecimalColumnDesc_C;
export declare type DynamicTextColumnDesc = $.kd.bos.entity.list.column.DynamicTextColumnDesc;
export declare const DynamicTextColumnDesc: $.kd.bos.entity.list.column.DynamicTextColumnDesc_C;
export declare type ExchangeRateColumnDesc = $.kd.bos.entity.list.column.ExchangeRateColumnDesc;
export declare const ExchangeRateColumnDesc: $.kd.bos.entity.list.column.ExchangeRateColumnDesc_C;
export declare type FlexColumnDesc = $.kd.bos.entity.list.column.FlexColumnDesc;
export declare const FlexColumnDesc: $.kd.bos.entity.list.column.FlexColumnDesc_C;
export declare type IntegerColumnDesc = $.kd.bos.entity.list.column.IntegerColumnDesc;
export declare const IntegerColumnDesc: $.kd.bos.entity.list.column.IntegerColumnDesc_C;
export declare type ItemClassColumnDesc = $.kd.bos.entity.list.column.ItemClassColumnDesc;
export declare const ItemClassColumnDesc: $.kd.bos.entity.list.column.ItemClassColumnDesc_C;
export declare type MulBaseDataColumnDesc = $.kd.bos.entity.list.column.MulBaseDataColumnDesc;
export declare const MulBaseDataColumnDesc: $.kd.bos.entity.list.column.MulBaseDataColumnDesc_C;
export declare type MuliLangTextColumnDesc = $.kd.bos.entity.list.column.MuliLangTextColumnDesc;
export declare const MuliLangTextColumnDesc: $.kd.bos.entity.list.column.MuliLangTextColumnDesc_C;
export declare type NumberColumnDesc = $.kd.bos.entity.list.column.NumberColumnDesc;
export declare const NumberColumnDesc: $.kd.bos.entity.list.column.NumberColumnDesc_C;
export declare type PKColumnDesc = $.kd.bos.entity.list.column.PKColumnDesc;
export declare const PKColumnDesc: $.kd.bos.entity.list.column.PKColumnDesc_C;
export declare type QtyColumnDesc = $.kd.bos.entity.list.column.QtyColumnDesc;
export declare const QtyColumnDesc: $.kd.bos.entity.list.column.QtyColumnDesc_C;
export declare type RefBillColumnDesc = $.kd.bos.entity.list.column.RefBillColumnDesc;
export declare const RefBillColumnDesc: $.kd.bos.entity.list.column.RefBillColumnDesc_C;
export declare type TextColumnDesc = $.kd.bos.entity.list.column.TextColumnDesc;
export declare const TextColumnDesc: $.kd.bos.entity.list.column.TextColumnDesc_C;
export declare type TimeColumnDesc = $.kd.bos.entity.list.column.TimeColumnDesc;
export declare const TimeColumnDesc: $.kd.bos.entity.list.column.TimeColumnDesc_C;
export declare type VoucherNoColumnDesc = $.kd.bos.entity.list.column.VoucherNoColumnDesc;
export declare const VoucherNoColumnDesc: $.kd.bos.entity.list.column.VoucherNoColumnDesc_C;
