export declare type BinaryExpr = $.kd.bos.formula.excel.BinaryExpr;
export declare const BinaryExpr: $.kd.bos.formula.excel.BinaryExpr_C;
export declare type CompoundId = $.kd.bos.formula.excel.CompoundId;
export declare const CompoundId: $.kd.bos.formula.excel.CompoundId_C;
export declare type ExecuteContext = $.kd.bos.formula.excel.ExecuteContext;
export declare const ExecuteContext: $.kd.bos.formula.excel.ExecuteContext;
export declare type Expr = $.kd.bos.formula.excel.Expr;
export declare const Expr: $.kd.bos.formula.excel.Expr;
export declare type ExprBase = $.kd.bos.formula.excel.ExprBase;
export declare const ExprBase: $.kd.bos.formula.excel.ExprBase_C;
export declare type ExprList = $.kd.bos.formula.excel.ExprList;
export declare const ExprList: $.kd.bos.formula.excel.ExprList_C;
export declare type ExprParser = $.kd.bos.formula.excel.ExprParser;
export declare const ExprParser: $.kd.bos.formula.excel.ExprParser_C;
export declare type FormulaException = $.kd.bos.formula.excel.FormulaException;
export declare const FormulaException: $.kd.bos.formula.excel.FormulaException_C;
export declare type FunCall = $.kd.bos.formula.excel.FunCall;
export declare const FunCall: $.kd.bos.formula.excel.FunCall_C;
export declare type FunDef = $.kd.bos.formula.excel.FunDef;
export declare const FunDef: $.kd.bos.formula.excel.FunDef_C;
export declare type Literal = $.kd.bos.formula.excel.Literal;
export declare const Literal: $.kd.bos.formula.excel.Literal_C;
export declare type MapExecuteContext = $.kd.bos.formula.excel.MapExecuteContext;
export declare const MapExecuteContext: $.kd.bos.formula.excel.MapExecuteContext_C;
export declare type NamedExpr = $.kd.bos.formula.excel.NamedExpr;
export declare const NamedExpr: $.kd.bos.formula.excel.NamedExpr_C;
export declare type Operator = $.kd.bos.formula.excel.Operator;
export declare const Operator: $.kd.bos.formula.excel.Operator_C;
export declare type Paren = $.kd.bos.formula.excel.Paren;
export declare const Paren: $.kd.bos.formula.excel.Paren_C;
export declare type UDFunction = $.kd.bos.formula.excel.UDFunction;
export declare const UDFunction: $.kd.bos.formula.excel.UDFunction;
export declare type VerifyVisitor = $.kd.bos.formula.excel.VerifyVisitor;
export declare const VerifyVisitor: $.kd.bos.formula.excel.VerifyVisitor_C;
export declare type Visitor = $.kd.bos.formula.excel.Visitor;
export declare const Visitor: $.kd.bos.formula.excel.Visitor;
