export declare type AmountMobTableColumn = $.kd.bos.form.mcontrol.mobtable.tablecolumn.AmountMobTableColumn;
export declare const AmountMobTableColumn: $.kd.bos.form.mcontrol.mobtable.tablecolumn.AmountMobTableColumn_C;
export declare type DateMobTableColumn = $.kd.bos.form.mcontrol.mobtable.tablecolumn.DateMobTableColumn;
export declare const DateMobTableColumn: $.kd.bos.form.mcontrol.mobtable.tablecolumn.DateMobTableColumn_C;
export declare type DecimalMobTableColumn = $.kd.bos.form.mcontrol.mobtable.tablecolumn.DecimalMobTableColumn;
export declare const DecimalMobTableColumn: $.kd.bos.form.mcontrol.mobtable.tablecolumn.DecimalMobTableColumn_C;
export declare type IMobTableColumn = $.kd.bos.form.mcontrol.mobtable.tablecolumn.IMobTableColumn;
export declare const IMobTableColumn: $.kd.bos.form.mcontrol.mobtable.tablecolumn.IMobTableColumn;
export declare type IntegerMobTableColumn = $.kd.bos.form.mcontrol.mobtable.tablecolumn.IntegerMobTableColumn;
export declare const IntegerMobTableColumn: $.kd.bos.form.mcontrol.mobtable.tablecolumn.IntegerMobTableColumn_C;
export declare type MobTableColumn = $.kd.bos.form.mcontrol.mobtable.tablecolumn.MobTableColumn;
export declare const MobTableColumn: $.kd.bos.form.mcontrol.mobtable.tablecolumn.MobTableColumn_C;
export declare type PictureMobTableColumn = $.kd.bos.form.mcontrol.mobtable.tablecolumn.PictureMobTableColumn;
export declare const PictureMobTableColumn: $.kd.bos.form.mcontrol.mobtable.tablecolumn.PictureMobTableColumn_C;
export declare type TextMobTableColumn = $.kd.bos.form.mcontrol.mobtable.tablecolumn.TextMobTableColumn;
export declare const TextMobTableColumn: $.kd.bos.form.mcontrol.mobtable.tablecolumn.TextMobTableColumn_C;
export declare type TimeMobTableColumn = $.kd.bos.form.mcontrol.mobtable.tablecolumn.TimeMobTableColumn;
export declare const TimeMobTableColumn: $.kd.bos.form.mcontrol.mobtable.tablecolumn.TimeMobTableColumn_C;
export declare type AttachmentMobTableColumn = $.kd.bos.form.mcontrol.mobtable.tablecolumn.AttachmentMobTableColumn;
export declare const AttachmentMobTableColumn: $.kd.bos.form.mcontrol.mobtable.tablecolumn.AttachmentMobTableColumn_C;
