export declare type AnyType = $.kd.bos.algo.datatype.AnyType;
export declare const AnyType: $.kd.bos.algo.datatype.AnyType_C;
export declare type BigDecimalType = $.kd.bos.algo.datatype.BigDecimalType;
export declare const BigDecimalType: $.kd.bos.algo.datatype.BigDecimalType_C;
export declare type BooleanType = $.kd.bos.algo.datatype.BooleanType;
export declare const BooleanType: $.kd.bos.algo.datatype.BooleanType_C;
export declare type DateType = $.kd.bos.algo.datatype.DateType;
export declare const DateType: $.kd.bos.algo.datatype.DateType_C;
export declare type FractionalType = $.kd.bos.algo.datatype.FractionalType;
export declare const FractionalType: $.kd.bos.algo.datatype.FractionalType_C;
export declare type IntegerType = $.kd.bos.algo.datatype.IntegerType;
export declare const IntegerType: $.kd.bos.algo.datatype.IntegerType_C;
export declare type IntegralType = $.kd.bos.algo.datatype.IntegralType;
export declare const IntegralType: $.kd.bos.algo.datatype.IntegralType_C;
export declare type LongType = $.kd.bos.algo.datatype.LongType;
export declare const LongType: $.kd.bos.algo.datatype.LongType_C;
export declare type NullType = $.kd.bos.algo.datatype.NullType;
export declare const NullType: $.kd.bos.algo.datatype.NullType_C;
export declare type NumericType = $.kd.bos.algo.datatype.NumericType;
export declare const NumericType: $.kd.bos.algo.datatype.NumericType_C;
export declare type StringType = $.kd.bos.algo.datatype.StringType;
export declare const StringType: $.kd.bos.algo.datatype.StringType_C;
export declare type TimestampType = $.kd.bos.algo.datatype.TimestampType;
export declare const TimestampType: $.kd.bos.algo.datatype.TimestampType_C;
