export declare type AlgoExceedAllowMaxDataSetsException = $.kd.bos.algo.exception.AlgoExceedAllowMaxDataSetsException;
export declare const AlgoExceedAllowMaxDataSetsException: $.kd.bos.algo.exception.AlgoExceedAllowMaxDataSetsException_C;
export declare type AlgoExceedAllowMaxRows4SortException = $.kd.bos.algo.exception.AlgoExceedAllowMaxRows4SortException;
export declare const AlgoExceedAllowMaxRows4SortException: $.kd.bos.algo.exception.AlgoExceedAllowMaxRows4SortException_C;
export declare type AlgoExceedAllowMaxRowsException = $.kd.bos.algo.exception.AlgoExceedAllowMaxRowsException;
export declare const AlgoExceedAllowMaxRowsException: $.kd.bos.algo.exception.AlgoExceedAllowMaxRowsException_C;
export declare type AlgoExceedAllowMaxRowsToDiskException = $.kd.bos.algo.exception.AlgoExceedAllowMaxRowsToDiskException;
export declare const AlgoExceedAllowMaxRowsToDiskException: $.kd.bos.algo.exception.AlgoExceedAllowMaxRowsToDiskException_C;
export declare type AlgoTimeOutException = $.kd.bos.algo.exception.AlgoTimeOutException;
export declare const AlgoTimeOutException: $.kd.bos.algo.exception.AlgoTimeOutException_C;
