export declare type CollectionPropertyMap = $.kd.bos.dataentity.metadata.database.CollectionPropertyMap;
export declare const CollectionPropertyMap: $.kd.bos.dataentity.metadata.database.CollectionPropertyMap_C;
export declare type ComplexPropertyMap = $.kd.bos.dataentity.metadata.database.ComplexPropertyMap;
export declare const ComplexPropertyMap: $.kd.bos.dataentity.metadata.database.ComplexPropertyMap_C;
export declare type DataEntityMetadataMapBase = $.kd.bos.dataentity.metadata.database.DataEntityMetadataMapBase;
export declare const DataEntityMetadataMapBase: $.kd.bos.dataentity.metadata.database.DataEntityMetadataMapBase_C;
export declare type DataEntityTypeMap = $.kd.bos.dataentity.metadata.database.DataEntityTypeMap;
export declare const DataEntityTypeMap: $.kd.bos.dataentity.metadata.database.DataEntityTypeMap_C;
export declare type DbMetadataBase = $.kd.bos.dataentity.metadata.database.DbMetadataBase;
export declare const DbMetadataBase: $.kd.bos.dataentity.metadata.database.DbMetadataBase_C;
export declare type DbMetadataCollection = $.kd.bos.dataentity.metadata.database.DbMetadataCollection;
export declare const DbMetadataCollection: $.kd.bos.dataentity.metadata.database.DbMetadataCollection_C;
export declare type DbMetadataColumn = $.kd.bos.dataentity.metadata.database.DbMetadataColumn;
export declare const DbMetadataColumn: $.kd.bos.dataentity.metadata.database.DbMetadataColumn_C;
export declare type DbMetadataColumnCollection = $.kd.bos.dataentity.metadata.database.DbMetadataColumnCollection;
export declare const DbMetadataColumnCollection: $.kd.bos.dataentity.metadata.database.DbMetadataColumnCollection_C;
export declare type DbMetadataDatabase = $.kd.bos.dataentity.metadata.database.DbMetadataDatabase;
export declare const DbMetadataDatabase: $.kd.bos.dataentity.metadata.database.DbMetadataDatabase_C;
export declare type DbMetadataGeoColumn = $.kd.bos.dataentity.metadata.database.DbMetadataGeoColumn;
export declare const DbMetadataGeoColumn: $.kd.bos.dataentity.metadata.database.DbMetadataGeoColumn_C;
export declare type DbMetadataRelation = $.kd.bos.dataentity.metadata.database.DbMetadataRelation;
export declare const DbMetadataRelation: $.kd.bos.dataentity.metadata.database.DbMetadataRelation_C;
export declare type DbMetadataRelationCollection = $.kd.bos.dataentity.metadata.database.DbMetadataRelationCollection;
export declare const DbMetadataRelationCollection: $.kd.bos.dataentity.metadata.database.DbMetadataRelationCollection_C;
export declare type DbMetadataTable = $.kd.bos.dataentity.metadata.database.DbMetadataTable;
export declare const DbMetadataTable: $.kd.bos.dataentity.metadata.database.DbMetadataTable_C;
export declare type DbMetadataTableCollection = $.kd.bos.dataentity.metadata.database.DbMetadataTableCollection;
export declare const DbMetadataTableCollection: $.kd.bos.dataentity.metadata.database.DbMetadataTableCollection_C;
export declare type PropertyMap = $.kd.bos.dataentity.metadata.database.PropertyMap;
export declare const PropertyMap: $.kd.bos.dataentity.metadata.database.PropertyMap_C;
export declare type SimplePropertyMap = $.kd.bos.dataentity.metadata.database.SimplePropertyMap;
export declare const SimplePropertyMap: $.kd.bos.dataentity.metadata.database.SimplePropertyMap_C;
