export declare type AfterOperationArgs = $.kd.bos.entity.plugin.args.AfterOperationArgs;
export declare const AfterOperationArgs: $.kd.bos.entity.plugin.args.AfterOperationArgs_C;
export declare type BeforeOperationArgs = $.kd.bos.entity.plugin.args.BeforeOperationArgs;
export declare const BeforeOperationArgs: $.kd.bos.entity.plugin.args.BeforeOperationArgs_C;
export declare type BeforeSaveAuditLogArg = $.kd.bos.entity.plugin.args.BeforeSaveAuditLogArg;
export declare const BeforeSaveAuditLogArg: $.kd.bos.entity.plugin.args.BeforeSaveAuditLogArg_C;
export declare type BeginOperationTransactionArgs = $.kd.bos.entity.plugin.args.BeginOperationTransactionArgs;
export declare const BeginOperationTransactionArgs: $.kd.bos.entity.plugin.args.BeginOperationTransactionArgs_C;
export declare type EndOperationTransactionArgs = $.kd.bos.entity.plugin.args.EndOperationTransactionArgs;
export declare const EndOperationTransactionArgs: $.kd.bos.entity.plugin.args.EndOperationTransactionArgs_C;
export declare type InitOperationArgs = $.kd.bos.entity.plugin.args.InitOperationArgs;
export declare const InitOperationArgs: $.kd.bos.entity.plugin.args.InitOperationArgs_C;
export declare type OperationArgs = $.kd.bos.entity.plugin.args.OperationArgs;
export declare const OperationArgs: $.kd.bos.entity.plugin.args.OperationArgs_C;
export declare type ReturnOperationArgs = $.kd.bos.entity.plugin.args.ReturnOperationArgs;
export declare const ReturnOperationArgs: $.kd.bos.entity.plugin.args.ReturnOperationArgs_C;
export declare type RollbackOperationArgs = $.kd.bos.entity.plugin.args.RollbackOperationArgs;
export declare const RollbackOperationArgs: $.kd.bos.entity.plugin.args.RollbackOperationArgs_C;
export declare type SensitiveArgs = $.kd.bos.entity.plugin.args.SensitiveArgs;
export declare const SensitiveArgs: $.kd.bos.entity.plugin.args.SensitiveArgs_C;
export declare type ValidatePrefixArgs = $.kd.bos.entity.plugin.args.ValidatePrefixArgs;
export declare const ValidatePrefixArgs: $.kd.bos.entity.plugin.args.ValidatePrefixArgs_C;
export declare type BeforeLoadDataArgs = $.kd.bos.entity.plugin.args.BeforeLoadDataArgs;
export declare const BeforeLoadDataArgs: $.kd.bos.entity.plugin.args.BeforeLoadDataArgs_C;
export declare type CustomPrintDataEntitiesArgs = $.kd.bos.entity.plugin.args.CustomPrintDataEntitiesArgs;
export declare const CustomPrintDataEntitiesArgs: $.kd.bos.entity.plugin.args.CustomPrintDataEntitiesArgs_C;
export declare type DynamicColumnArgs = $.kd.bos.entity.plugin.args.DynamicColumnArgs;
export declare const DynamicColumnArgs: $.kd.bos.entity.plugin.args.DynamicColumnArgs_C;
export declare type OutputElementArgs = $.kd.bos.entity.plugin.args.OutputElementArgs;
export declare const OutputElementArgs: $.kd.bos.entity.plugin.args.OutputElementArgs_C;
